### ISSUE TITLE
Tensorflow exception triggered while loading model.

### ISSUE THREAD

**Issue by selwyn1958** [dotnet/machinelearning-modelbuilder#1000]
**Model Builder Version**: _In which Model Builder version was the bug encountered?_
**Visual Studion Version**: _In which Visual Studio version was the bug encountered?_

**Bug description**
_A clear and concise description of what the bug is._

**Steps to Reproduce**
1. _List the minimal steps required to reproduce the bug._
2. _Thanks for reporting!_

**Expected Experience**
_A description of what you expected to happen. If applicable, add screenshots or "Machine Learning" Output Logs to help explain what you expected._

**Actual Experience**
_A description of what actually happens. If applicable, add screenshots or "Machine Learning" Output Logs to help explain what actually happened._

**Additional Context**
_Add any other context about the problem here, such as unusual system configurations, network restrictions, etc._

**Comment by zewditu** [comment]
Thanks for reporting the issue, could you tell us your ML.Net  Model Builder version and the steps to reproduce the issue?

**Comment by selwyn1958** [comment]
Model Builder version number is  16.2.0.2046002
Visual Studio version 2019
Windows 10 Pro

Step 1: Created new project .NET CORE  C# : ConsoleAPP .
Step 2: Right Click and added Machine Learning 
Step 3: Selected Scenario as "Immage Classification" and Environment as "Local CPU"
Step 4 Selected Data Set <assets> folder has two sub folders <cat> and <dog> image size < 50 K
Step 5: While Training, after a few seconds of Execution we had this error message.

**Comment by selwyn1958** [comment]
Here is the full Error Message Received

Tensorflow exception triggered while loading model.


 at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ML.ModelBuilder.AutoMLService.Experiments.AutoMLExperiment`3.<ExecuteAsync>d__21.MoveNext() in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/Experiments/AutoMLExperiment.cs:line 112
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ML.ModelBuilder.AutoMLEngine.<StartTrainingAsync>d__26.MoveNext() in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/AutoMLEngineService/AutoMLEngine.cs:line 134


Kindly help me to Resolve this issue

**Comment by selwyn1958** [comment]
Here is the Log Report
[Log170920.txt](https://github.com/dotnet/machinelearning-modelbuilder/files/5239259/Log170920.txt)

**Comment by selwyn1958** [comment]
Here is another log report

2020-09-17 20:04:08.3031 INFO [Source=ImageClassificationTrainer; Ensuring meta files are present., Kind=Trace] Channel disposed (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2020-09-17 20:04:08.3031 INFO [Source=ImageClassificationTrainer; Ensuring meta files are present., Kind=Trace] Channel finished. Elapsed 00:00:00.0007885. (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2020-09-17 20:04:22.8842 INFO [Source=AutoML, Kind=Error] Pipeline crashed: xf=ValueToKeyMapping{ col=Label:Label} xf=RawByteImageLoading{ col=ImageSource_featurized:ImageSource imageFolder=} xf=ColumnCopying{ col=Features:ImageSource_featurized} tr=ImageClassification{} xf=KeyToValueMapping{ col=PredictedLabel:PredictedLabel} cache=- . Exception: System.FormatException: Tensorflow exception triggered while loading model. ---> System.DllNotFoundException: Unable to load DLL 'tensorflow': A dynamic link library (DLL) initialization routine failed. (Exception from HRESULT: 0x8007045A)
   at Tensorflow.c_api.TF_NewGraph()
   at Tensorflow.Graph..ctor()
   at Microsoft.ML.TensorFlow.TensorFlowUtils.LoadMetaGraph(String path)
   at Microsoft.ML.TensorFlow.TensorFlowUtils.LoadTFSessionByModelFilePath(IExceptionContext ectx, String modelFile, Boolean metaGraph)
   --- End of inner exception stack trace ---
   at Microsoft.ML.TensorFlow.TensorFlowUtils.LoadTFSessionByModelFilePath(IExceptionContext ectx, String modelFile, Boolean metaGraph)
   at Microsoft.ML.Vision.ImageClassificationTrainer.LoadTensorFlowSessionFromMetaGraph(IHostEnvironment env, Architecture arch)
   at Microsoft.ML.Vision.ImageClassificationTrainer.InitializeTrainingGraph(IDataView input)
   at Microsoft.ML.Vision.ImageClassificationTrainer.TrainModelCore(TrainContext trainContext)
   at Microsoft.ML.Trainers.TrainerEstimatorBase`2.TrainTransformer(IDataView trainSet, IDataView validationSet, IPredictor initPredictor)
   at Microsoft.ML.Data.EstimatorChain`1.Fit(IDataView input)
   at Microsoft.ML.Data.EstimatorChain`1.Fit(IDataView input)
   at Microsoft.ML.AutoML.RunnerUtil.TrainAndScorePipeline[TMetrics](MLContext context, SuggestedPipeline pipeline, IDataView trainData, IDataView validData, String groupId, String labelColumn, IMetricsAgent`1 metricsAgent, ITransformer preprocessorTransform, FileInfo modelFileInfo, DataViewSchema modelInputSchema, IChannel logger) (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2020-09-17 20:04:22.8842 INFO [Source=ImageClassificationTrainer; ImageClassificationTrainer, Kind=Trace] Channel started (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2020-09-17 20:04:22.8842 INFO Tensorflow exception triggered while loading model. (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2020-09-17 20:04:22.8842 DEBUG Disposing AutoMLService Client (Microsoft.ML.ModelBuilder.Utils.Logger.Debug)
2020-09-17 20:04:22.8972 DEBUG Tensorflow exception triggered while loading model.
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ML.ModelBuilder.AutoMLService.Experiments.AutoMLExperiment`3.<ExecuteAsync>d__21.MoveNext() in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/Experiments/AutoMLExperiment.cs:line 112
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ML.ModelBuilder.AutoMLEngine.<StartTrainingAsync>d__26.MoveNext() in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/AutoMLEngineService/AutoMLEngine.cs:line 134 (Microsoft.ML.ModelBuilder.Utils.Logger.Debug)
2020-09-17 20:05:08.6154 DEBUG Open Log FileC:\Users\SELWYN\AppData\Local\Temp\MLVSTools\logs\9bb04b44-477e-49ec-a77f-2c40aedee277.txt (Microsoft.ML.ModelBuilder.Utils.Logger.Debug)

**Comment by zewditu** [comment]
Sorry for the late reply!

Could you update ML.Net Model Builder to the latest version?

**Comment by zewditu** [comment]
if you still hit the issue let us know.
