### ISSUE TITLE
Model builder Error - Unable to find method 'PredictMultiClassClassificationAsync/3' on Microsoft.ML.ModelBuilder.AutoMLEngine

### ISSUE THREAD

**Issue by forReason** [dotnet/machinelearning-modelbuilder#1001]
**System Information (please complete the following information):**
 - Model Builder Version: Current
 - Visual Studio Version 

**Describe the bug**
I cannot predict from models. Training works fine.  
The following error arises:
![image](https://user-images.githubusercontent.com/12736950/93219479-b8127480-f76b-11ea-917b-fcc934702f2b.png)
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at StreamJsonRpc.JsonRpc.<InvokeCoreAsync>d__94`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ML.ModelBuilder.AutoMLServiceFactory.AutoMLServiceProxy.<PredictMultiClassClassificationAsync>d__16.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ML.ModelBuilder.TrainSession.<PredictMultiClassClassificationAsync>d__51.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.ML.ModelBuilder.ToolWindows.EvaluateTabDataContext.<MulticlassficationAsync>d__93.MoveNext()

**To Reproduce**
1. Go to Solution
2. Richtclick -> Add -> MachineLearning
2. Click on Image Classification, select train data and start trainng
3. Once Training is finished, go to the evaluate section
![image](https://user-images.githubusercontent.com/12736950/93219696-eabc6d00-f76b-11ea-82bb-2e7aca9c253f.png)
4. Select an image to evaluate -> Error

**Expected behavior**
Select an image for evaluation or prediction and get a prediction

**Additional context**
Log File:
http://julianbechtold.de/media/ce9cf982-687e-4fab-8b9d-f202af8d484a.txt

**Comment by forReason** [comment]
new project resolved the issue... but its really annoying.

**Comment by forReason** [comment]
nevermind. when I rebuild the Solution the error reappears at the following line.

``` C#
public string ClassifyImage(string imagePath)
{
        // Add input data
        var modelInput = new ModelInput();
        modelInput.ImageSource = imagePath;
        // Load model and predict output of sample data
        ModelOutput result = ConsumeModel.Predict(modelInput); // <-- Issue here
        return result.Prediction;
}
```
System.AggregateException: 'One or more errors occurred.'  
Inner Exception
TensorflowException: 2 root error(s) found.
0) Unknown: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
	 [[{{node resnet_v2_50/conv1/Conv2D}}]]
	 [[Score/_7]]
  (1) Unknown: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
	 [[{{node resnet_v2_50/conv1/Conv2D}}]]
0 successful operations.
0 derived errors ignored.

This exception was originally thrown at this call stack:
    [External Code]
    DatasetValidationToolML.Model.ConsumeModel.Predict(DatasetValidationToolML.Model.ModelInput) in ConsumeModel.cs
    DatasetValidationTool.Predict.ClassifyImage(string) in Predict.cs
    DatasetValidationTool.AITasks.FindWronglyCategorizedImages(System.IO.FileInfo[]) in AITasks.cs

**Comment by zewditu** [comment]
@forReason thanks for reporting the issue, we will look into it why it happens

**Comment by zewditu** [comment]
@LittleLittleCloud,  could you have anything for the reason of this?

**Comment by LittleLittleCloud** [comment]
Hi @forReason

It looks like your model is trained by scisharp.tensorflow.windows-gpu, but in .csproj you are referring scisharp.tensorflow (CPU). Could you replace the `SciSharp.TensorFlow.Redist` with `SciSharp.TensorFlow.Redist-Windows-GPU`, rebuilt and try again?

Regards

**Comment by forReason** [comment]
I have changed the Package reference in all .csproj file in the Solution, restarted Visual studio
![image](https://user-images.githubusercontent.com/12736950/93334706-a8effd00-f825-11ea-89dc-78f272e0bafc.png)

I still can not evaluate my model. The issue is a different one now:
Error 1:

![image](https://user-images.githubusercontent.com/12736950/93339806-4d753d80-f82c-11ea-9bcc-67ea257c8f00.png)
Model Builder Error
Value cannot be null.
Parameter name: Source
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   at Microsoft.ML.ModelBuilder.ToolWindows.EvaluateTabControl.<BrowseImage_Click>d__6.MoveNext()

Error 2:
Unable to find method 'PredictMultiClassClassificationAsync/3' on Microsoft.ML.ModelBuilder.AutoMLEngine for the following reasons: 
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at StreamJsonRpc.JsonRpc.<InvokeCoreAsync>d__94`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ML.ModelBuilder.AutoMLServiceFactory.AutoMLServiceProxy.<PredictMultiClassClassificationAsync>d__16.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ML.ModelBuilder.TrainSession.<PredictMultiClassClassificationAsync>d__51.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.ML.ModelBuilder.ToolWindows.EvaluateTabDataContext.<MulticlassficationAsync>d__93.MoveNext()


Logfile:
http://julianbechtold.de/media/b3520ec5-7840-488b-b7bf-8c719b5a2fcb.txt

**Comment by zewditu** [comment]
Sorry for hitting another error!
Did you solve the first issue ?
Could you update your **ML.Net Model Builder** to the latest version. The issue might abe solved in latest version

**Comment by forReason** [comment]
Yes the first issue is resolved. How would I go about updating ML.Net Model Builder? I have installed it with the Visual Studio installer

**Comment by zewditu** [comment]
Hello,

Sorry for the late reply !

To update to the latest version in Vs go to Extensions --> Manage Extensions. In Manage Extensions window go to Updates tab then if there is an updated version of ML.Net Model Builder you will see ML.Net Model Builder and update.

![image.png](https://images.zenhubusercontent.com/5d014b8c2b5aa11c6166d13d/395f584b-4a97-4e2a-90c1-b4e317949ade)

**Comment by zewditu** [comment]
@forReason I hope you solved your issue!  If you still hit the issue you can reopen it. Thanks

**Comment by Claytonious** [comment]
I had this error, too. Removing the ML.NET Model Builder GPU preview extension solved it for me.
