### ISSUE TITLE
Model Builder Error in when Training

### ISSUE THREAD

**Issue by 8** [dotnet/machinelearning-modelbuilder#1002]
**System Information (please complete the following information):**
 - Model Builder Version: 16.1.0.2027905
 - Visual Studio Version 16.7.3

**Describe the bug**
Model Builder fails in the "Train" phase with the error message:
```
Specified argument was out of the range of valid values.
Parameter name: index
  at System.Linq.Enumerable.ElementAt[TSource](IEnumerable`1 source, Int32 index)
   at Microsoft.ML.ModelBuilder.AutoMLService.Experiments.AutoMLExperiment`3.<ExecuteAsync>d__21.MoveNext() in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/Experiments/AutoMLExperiment.cs:line 136
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ML.ModelBuilder.AutoMLEngine.<StartTrainingAsync>d__30.MoveNext() in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/AutoMLEngineService/AutoMLEngine.cs:line 147
```

**To Reproduce**
1. Start Model Builder
2. Choose scenario Value prediction
3. Continue to Data tab.
4. Pick a file, select the result column and click train.
5. Wait until several Trainer are explored and notice the exception happening.

**Expected behavior**
Taining step completes without error popups.

**Comment by zewditu** [comment]
Thanks for reporting this issue. In order to help,  could you provide the dataset you used?

**Comment by 8** [comment]
Hi,

I saw that there was a new version of the model builder available and updated it - now training works, I guess it was fixed in the newer version.

Take care,
Martin
