### ISSUE TITLE
Train Image Clasification Model in Azure: Iteration Timeout

### ISSUE THREAD

**Issue by elbruno** [dotnet/machinelearning-modelbuilder#1005]
**System Information (please complete the following information):**
 - Model Builder Version: 16.2.0.2027905
 - Visual Studio Version: 4.8.04161

**Describe the bug**
- On which step of the process did you run into an issue:
When the Image Recognition Scenario is training on Azure
- Clear description of the problem:
After +90 minutes of training the IDE shows the error below. I'm also attaching the full log.
[77341910-1b12-40ce-a75b-ba4802ee1a37.txt](https://github.com/dotnet/machinelearning-modelbuilder/files/5250839/77341910-1b12-40ce-a75b-ba4802ee1a37.txt)

**To Reproduce**
1. Create a new Image Clasification scenario
2. Select an Azure Environment
3. Uses local images to train the model. ~1GB of images from the Distracted Driver Detection Challenge from Kaggle. https://www.kaggle.com/c/state-farm-distracted-driver-detection

Completed a training run
Downloading best model to C:\Users\bruno\AppData\Local\Temp\MLVSTools\MLNet ModelBuilderML\MLNet ModelBuilderML.Model\bestModel.onnx..
Object reference not set to an instance of an object.

   at AzureML.AutoMLRunnerImages.<RunAutoMLAsync>d__27.MoveNext() in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/RemoteAutoML/AutoMLRunnerImages.cs:line 237
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ML.ModelBuilder.AutoMLService.Experiments.AzureImageClassificationExperiment.<ExecuteAsync>d__13.MoveNext() in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/Experiments/AzureImageClassificationExperiment.cs:line 69
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ML.ModelBuilder.AutoMLEngine.<StartTrainingAsync>d__26.MoveNext() in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/AutoMLEngineService/AutoMLEngine.cs:line 134

**Screenshots**
On the Azure Portal the run shows the following iteration timeout error

![image](https://user-images.githubusercontent.com/3533489/93691140-63defb80-faaf-11ea-8ef0-86b850c6dbf4.png)

Reference Id: AutoML_0affc79b-87bd-421b-a213-73e46f9a02f7

**Additional context**

**Comment by nandomaro** [comment]
Is there a new update on this? It's pretty common and reproducable with all data sets above 2k images.
