### ISSUE TITLE
I'm using ml.net built-in model for Recommendation  . When I select the table in from the database this error comes" A delimiter cannot be Nothing or an empty String. Parameter name: Delimiters""

### ISSUE THREAD

**Issue by ahmedishtiaq9777** [dotnet/machinelearning-modelbuilder#1022]
I have an eccomerce application for which I want to make a recommendation system with AI . I am using ml.net for that purpose to recommend product based on rating .When I select the product table   within the  database this error comes" A delimiter cannot be Nothing or an empty String. Parameter name: Delimiters""'
at Microsoft.VisualBasic.FileIO.TextFieldParser.ValidateDelimiters(String[] delimiterArray)
   at Microsoft.VisualBasic.FileIO.TextFieldParser.set_Delimiters(String[] value)
   at Microsoft.VisualBasic.FileIO.TextFieldParser.SetDelimiters(String[] delimiters)
   at Microsoft.ML.ModelBuilder.DataSources.FileDataSource.<>c__DisplayClass8_0.<GetAllDataAsync>b__0()

 - Model Builder Version: current version
 - Visual Studio Version:  2019

**Comment by beccamc** [comment]
@ahmedishtiaq9777 Sorry you ran into this problem. Just to double confirm, you're using a SQL connection correct?

**Comment by beccamc** [comment]
Closing this due to inactivity. @ahmedishtiaq9777 if this is still a problem please ping me and we can reopen
