### ISSUE TITLE
Local GPU training for image classification fails due to a failure to load tensorflow

### ISSUE THREAD

**Issue by kasthack** [dotnet/machinelearning-modelbuilder#1081]
**System Information**
 - Model Builder Version: 16.2.0.2047901
 - Model Builder GPU support Version: 16.2.0.2047901
 - Visual Studio Version: Microsoft Visual Studio Community 2019 Preview / Version 16.8.0 Preview 6.0
 - Windows: 10 Pro Version 20H2  build 19042.572
 - CUDA: 10.0
 - cuDNN: 7.6.4 for 10.10
 - Nvidia GeForce GTX 1060

**Describe the bug**
- Model builder fails to load TensorFlow when attempting to train an image classification model using GPU locally. CPU training works fine on the same machine.

Stacktrace:

````
[Source=ImageClassificationTrainer; ImageClassificationTrainer, Kind=Trace] Channel started
[Source=ImageClassificationTrainer; ImageClassificationTrainer, Kind=Trace] Channel started
[Source=ImageClassificationTrainer; Ensuring meta files are present., Kind=Trace] Channel started
[Source=ImageClassificationTrainer; Ensuring meta files are present., Kind=Trace] Channel finished. Elapsed 00:00:00.0036866.
[Source=ImageClassificationTrainer; Ensuring meta files are present., Kind=Trace] Channel disposed
[Source=AutoML, Kind=Error] Pipeline crashed: xf=ValueToKeyMapping{ col=Label:Label} xf=RawByteImageLoading{ col=ImageSource_featurized:ImageSource imageFolder=} xf=ColumnCopying{ col=Features:ImageSource_featurized} tr=ImageClassification{} xf=KeyToValueMapping{ col=PredictedLabel:PredictedLabel} cache=- . Exception: System.FormatException: Tensorflow exception triggered while loading model. ---> System.DllNotFoundException: Unable to load DLL 'tensorflow': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
   at Tensorflow.c_api.TF_NewGraph()
   at Tensorflow.Graph..ctor()
   at Microsoft.ML.TensorFlow.TensorFlowUtils.LoadMetaGraph(String path)
   at Microsoft.ML.TensorFlow.TensorFlowUtils.LoadTFSessionByModelFilePath(IExceptionContext ectx, String modelFile, Boolean metaGraph)
   --- End of inner exception stack trace ---
   at Microsoft.ML.TensorFlow.TensorFlowUtils.LoadTFSessionByModelFilePath(IExceptionContext ectx, String modelFile, Boolean metaGraph)
   at Microsoft.ML.Vision.ImageClassificationTrainer.LoadTensorFlowSessionFromMetaGraph(IHostEnvironment env, Architecture arch)
   at Microsoft.ML.Vision.ImageClassificationTrainer.InitializeTrainingGraph(IDataView input)
   at Microsoft.ML.Vision.ImageClassificationTrainer.TrainModelCore(TrainContext trainContext)
   at Microsoft.ML.Trainers.TrainerEstimatorBase`2.TrainTransformer(IDataView trainSet, IDataView validationSet, IPredictor initPredictor)
   at Microsoft.ML.Data.EstimatorChain`1.Fit(IDataView input)
   at Microsoft.ML.Data.EstimatorChain`1.Fit(IDataView input)
   at Microsoft.ML.AutoML.RunnerUtil.TrainAndScorePipeline[TMetrics](MLContext context, SuggestedPipeline pipeline, IDataView trainData, IDataView validData, String groupId, String labelColumn, IMetricsAgent`1 metricsAgent, ITransformer preprocessorTransform, FileInfo modelFileInfo, DataViewSchema modelInputSchema, IChannel logger)
````

````
Tensorflow exception triggered while loading model.
````

**To Reproduce**
1. Create a console .net core application.
2. Click 'Add -> Add Machine Learning' for the project in the solution view.
3. Select 'Image classification scenario'
4. Select 'Local(GPU)' training environment.
5. Configure any image dataset(I used 20 pictures of my cat but this seems to be irrelevant).
6. Press 'Train' on the 'Train' step
7. Get an error message within a few seconds.
8. Errors in the output window usually keep printing for some time.

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/1292818/97791059-aa824400-1b8b-11eb-9004-0c8ffb60188e.png)

**Additional context**

[full_log.txt](https://github.com/dotnet/machinelearning-modelbuilder/files/5469916/full_log.txt)

**Comment by tamaskaroly** [comment]
I ran into the same error just now.

**Comment by LittleLittleCloud** [comment]
Hi @tamaskaroly  @kasthack 
Thanks for the reporting, we are looking into that issue now.
Could you do me a favor and try GPU training using ML.Net directly so that we can determine if the error is on ModelBuilder side or not? I will publish a dotnet sample image classification project using GPU training later

**Comment by LittleLittleCloud** [comment]
Hi @tamaskaroly  @kasthack 
Can you download this [example](https://github.com/LittleLittleCloud/ImageClassification/blob/main/README.md) and run to see if it launch an image classification training or not?

If the training fails with the same error, can you also change the redist-gpu's version from 1.14.1 to 2.3.0, re-launch the training and see if the error goes?

**Comment by LittleLittleCloud** [comment]
@tamaskaroly  @kasthack 
One more thing, could you check the cuda version on your system? You can get it by `nvcc --version`. Gently remind that GPU training only works with cuda 10.0. Cuda with later version is not compatible with tf binary used by model builder for now

**Comment by tamaskaroly** [comment]
Hi @LittleLittleCloud 
I can confirm that the example project does NOT work with 1.14.1. However, changing to 2.3.0 DOES solve the problem. Regarding CUDA version, I'm on 10.1

**Comment by kasthack** [comment]
I've reinstalled CUDA and it fails with a new message now.

nvcc:
```
 nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2018 NVIDIA Corporation
Built on Sat_Aug_25_21:08:04_Central_Daylight_Time_2018
Cuda compilation tools, release 10.0, V10.0.130
```

example output(1.14.1):

```
PS E:\files\kasthack\Own\Source\github\littlelittlecloud\ImageClassification> dotnet run --project .\ImageClassification.Train\\ImageClassification.Train.csproj
[Source=ImageClassificationTrainer; ImageClassificationTrainer, Kind=Trace] Channel started
*** Training the image classification model with DNN Transfer Learning on top of the selected pre-trained model/architecture ***
[Source=ImageClassificationTrainer; Ensuring meta files are present., Kind=Trace] Channel started
[Source=ImageClassificationTrainer; Ensuring meta files are present., Kind=Trace] Channel finished. Elapsed 00:00:00.0050438.
[Source=ImageClassificationTrainer; Ensuring meta files are present., Kind=Trace] Channel disposed
2020-11-28 16:29:47.617248: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
2020-11-28 16:29:47.623050: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library nvcuda.dll
2020-11-28 16:29:47.726361: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1640] Found device 0 with properties:
name: GeForce GTX 1060 6GB major: 6 minor: 1 memoryClockRate(GHz): 1.759
pciBusID: 0000:41:00.0
2020-11-28 16:29:47.726528: I tensorflow/stream_executor/platform/default/dlopen_checker_stub.cc:25] GPU libraries are statically linked, skip dlopen check.
2020-11-28 16:29:47.727234: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1763] Adding visible gpu devices: 0
2020-11-28 16:31:38.940301: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1181] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-11-28 16:31:38.940407: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1187]      0
2020-11-28 16:31:38.940737: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1200] 0:   N
2020-11-28 16:31:38.941418: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1326] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 4453 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1060 6GB, pci bus id: 0000:41:00.0, compute capability: 6.1)
Saver not created because there are no variables in the graph to restore
2020-11-28 16:31:39.808630: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1640] Found device 0 with properties:
name: GeForce GTX 1060 6GB major: 6 minor: 1 memoryClockRate(GHz): 1.759
pciBusID: 0000:41:00.0
2020-11-28 16:31:39.808726: I tensorflow/stream_executor/platform/default/dlopen_checker_stub.cc:25] GPU libraries are statically linked, skip dlopen check.
2020-11-28 16:31:39.809071: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1763] Adding visible gpu devices: 0
2020-11-28 16:31:39.809166: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1181] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-11-28 16:31:39.809215: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1187]      0
2020-11-28 16:31:39.809257: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1200] 0:   N
2020-11-28 16:31:39.809617: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1326] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 4453 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1060 6GB, pci bus id: 0000:41:00.0, compute capability: 6.1)
2020-11-28 16:31:45.599192: E tensorflow/stream_executor/cuda/cuda_dnn.cc:329] Could not create cudnn handle: CUDNN_STATUS_ALLOC_FAILED
2020-11-28 16:31:45.599720: E tensorflow/stream_executor/cuda/cuda_dnn.cc:329] Could not create cudnn handle: CUDNN_STATUS_ALLOC_FAILED
2 root error(s) found.
  (0) Unknown: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
         [[{{node resnet_v2_50/conv1/Conv2D}}]]
  (1) Unknown: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
         [[{{node resnet_v2_50/conv1/Conv2D}}]]
         [[resnet_v2_50/SpatialSqueeze/_7]]
0 successful operations.
0 derived errors ignored.
Unhandled exception. Tensorflow.TensorflowException: 2 root error(s) found.
  (0) Unknown: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
         [[{{node resnet_v2_50/conv1/Conv2D}}]]
  (1) Unknown: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
         [[{{node resnet_v2_50/conv1/Conv2D}}]]
         [[resnet_v2_50/SpatialSqueeze/_7]]
0 successful operations.
0 derived errors ignored.
   at Microsoft.ML.TensorFlow.TensorFlowUtils.Runner.Run()
   at Microsoft.ML.Vision.ImageClassificationTrainer.CacheFeaturizedImagesToDisk(IDataView input, String labelColumnName, String imageColumnName, ImageProcessor imageProcessor, String inputTensorName, String outputTensorName, String cacheFilePath, Dataset dataset, Action`1 metricsCallback, Nullable`1 validationFraction)
   at Microsoft.ML.Vision.ImageClassificationTrainer.TrainModelCore(TrainContext trainContext)
   at Microsoft.ML.Trainers.TrainerEstimatorBase`2.TrainTransformer(IDataView trainSet, IDataView validationSet, IPredictor initPredictor)
   at Microsoft.ML.Trainers.TrainerEstimatorBase`2.Fit(IDataView input)
   at Microsoft.ML.Data.EstimatorChain`1.Fit(IDataView input)
   at ImageClassification.Train.Program.Main() in E:\files\kasthack\Own\Source\github\littlelittlecloud\ImageClassification\ImageClassification.Train\Program.cs:line 94
```

example output(2.3.0):

```
dotnet run --project .\ImageClassification.Train\\ImageClassification.Train.csproj
[Source=ImageClassificationTrainer; ImageClassificationTrainer, Kind=Trace] Channel started
*** Training the image classification model with DNN Transfer Learning on top of the selected pre-trained model/architecture ***
[Source=ImageClassificationTrainer; Ensuring meta files are present., Kind=Trace] Channel started
[Source=ImageClassificationTrainer; Ensuring meta files are present., Kind=Trace] Channel finished. Elapsed 00:00:00.0052014.
[Source=ImageClassificationTrainer; Ensuring meta files are present., Kind=Trace] Channel disposed
2020-11-28 16:35:41.752706: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'cudart64_101.dll'; dlerror: cudart64_101.dll not found
2020-11-28 16:35:41.753310: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2020-11-28 16:35:41.850418: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN)to use the following CPU instructions in performance-critical operations:  AVX2
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2020-11-28 16:35:41.859792: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x2087e2b5460 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-11-28 16:35:41.859864: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2020-11-28 16:35:41.861927: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library nvcuda.dll
2020-11-28 16:35:41.961601: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1716] Found device 0 with properties:
pciBusID: 0000:41:00.0 name: GeForce GTX 1060 6GB computeCapability: 6.1
coreClock: 1.759GHz coreCount: 10 deviceMemorySize: 6.00GiB deviceMemoryBandwidth: 178.99GiB/s
2020-11-28 16:35:41.962514: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'cudart64_101.dll'; dlerror: cudart64_101.dll not found
2020-11-28 16:35:41.963065: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'cublas64_10.dll'; dlerror: cublas64_10.dll not found
2020-11-28 16:35:41.963593: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'cufft64_10.dll'; dlerror: cufft64_10.dll not found
2020-11-28 16:35:41.964088: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'curand64_10.dll'; dlerror: curand64_10.dll not found
2020-11-28 16:35:41.964700: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'cusolver64_10.dll'; dlerror: cusolver64_10.dll not found
2020-11-28 16:35:41.965281: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'cusparse64_10.dll'; dlerror: cusparse64_10.dll not found
2020-11-28 16:35:41.970210: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library cudnn64_7.dll
2020-11-28 16:35:41.970290: W tensorflow/core/common_runtime/gpu/gpu_device.cc:1753] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
Skipping registering GPU devices...
2020-11-28 16:35:42.072342: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1257] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-11-28 16:35:42.072579: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1263]      0
2020-11-28 16:35:42.072883: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1276] 0:   N
2020-11-28 16:35:42.075669: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x2087e2b58e0 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:
2020-11-28 16:35:42.075735: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): GeForce GTX 1060 6GB, Compute Capability 6.1
Saver not created because there are no variables in the graph to restore
2020-11-28 16:35:45.387168: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1716] Found device 0 with properties:
pciBusID: 0000:41:00.0 name: GeForce GTX 1060 6GB computeCapability: 6.1
coreClock: 1.759GHz coreCount: 10 deviceMemorySize: 6.00GiB deviceMemoryBandwidth: 178.99GiB/s
2020-11-28 16:35:45.387961: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'cudart64_101.dll'; dlerror: cudart64_101.dll not found
2020-11-28 16:35:45.388530: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'cublas64_10.dll'; dlerror: cublas64_10.dll not found
2020-11-28 16:35:45.389044: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'cufft64_10.dll'; dlerror: cufft64_10.dll not found
2020-11-28 16:35:45.389573: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'curand64_10.dll'; dlerror: curand64_10.dll not found
2020-11-28 16:35:45.390144: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'cusolver64_10.dll'; dlerror: cusolver64_10.dll not found
2020-11-28 16:35:45.390697: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'cusparse64_10.dll'; dlerror: cusparse64_10.dll not found
2020-11-28 16:35:45.390756: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library cudnn64_7.dll
2020-11-28 16:35:45.390805: W tensorflow/core/common_runtime/gpu/gpu_device.cc:1753] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
Skipping registering GPU devices...
2020-11-28 16:35:45.390904: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1257] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-11-28 16:35:45.391750: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1263]      0
2020-11-28 16:35:45.392439: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1276] 0:   N

< starts training on CPU instead and gives the usual output here >
```

**Comment by kasthack** [comment]
It finally worked one complete reinstall later.

Good driver versions for those who stumble upon the same issue:

* Nvidia 457.30 / win 10 x64
* CUDA 10.0.130_411.31_win10
* cuDNN 7.6.4.38
