### ISSUE TITLE
Creating Azure AI Workspace fails, (Azure resources are created)

### ISSUE THREAD

**Issue by frankhaugen** [dotnet/machinelearning-modelbuilder#1104]
**System Information (please complete the following information):**
 - Model Builder Version: 
16.3.2056001
 - Visual Studio Version:
Microsoft Visual Studio Enterprise 2019 Preview
Version 16.9.0 Preview 1.0

**Describe the bug**
Creating a Object Detection workspace

**To Reproduce**
1. Start the model builder
2. Choose "Object Detection"
3, Click Add new workspace
4. Set a name, select region, and resource group
5. Click Create
6. After approx. 90 seconds, error is shown

**Expected behavior**
To complete without error

**Screenshots**
Results in Azure portal after two attempts
![image](https://user-images.githubusercontent.com/13543585/99186020-c2da8d00-274d-11eb-8af3-7e40080b1991.png)

Error message:
![image](https://user-images.githubusercontent.com/13543585/99185685-c0773380-274b-11eb-8594-9c888eafd635.png)

**Additional context**
```
   at Microsoft.Rest.ClientRuntime.Azure.LRO.AzureLRO`2.CheckForErrors()
   at Microsoft.Rest.ClientRuntime.Azure.LRO.PutLRO`2.CheckForErrors()
   at Microsoft.Rest.ClientRuntime.Azure.LRO.AzureLRO`2.<StartPollingAsync>d__20.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Rest.ClientRuntime.Azure.LRO.AzureLRO`2.<BeginLROAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Rest.Azure.AzureClientExtensions.<GetLongRunningOperationResultAsync>d__1`2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Rest.Azure.AzureClientExtensions.<GetLongRunningOperationResultAsync>d__0`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Rest.Azure.AzureClientExtensions.<GetPutOrPatchOperationResultAsync>d__5`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.Azure.Management.ResourceManager.Fluent.DeploymentsOperations.<CreateOrUpdateWithHttpMessagesAsync>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.Azure.Management.ResourceManager.Fluent.DeploymentsOperationsExtensions.<CreateOrUpdateAsync>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.Azure.Management.ResourceManager.Fluent.DeploymentImpl.<CreateResourceAsync>d__60.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.Azure.Management.ResourceManager.Fluent.DeploymentImpl.<CreateAsync>d__59.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Azure.MachineLearning.Services.Workspaces.WorkspaceOperations.<CreateAsync>d__10.MoveNext() in /_/src/Microsoft.ML.AzureMLClient/Workspaces/WorkspaceOperations.cs:line 193
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Azure.MachineLearning.Services.AMLRest.AzureAttachManager.<PutCreateWorkspaceAsync>d__10.MoveNext() in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/AMLRest/AzureAttachManager.cs:line 127
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ML.ModelBuilder.AutoMLEngine.<PutCreateWorkspaceAsync>d__40.MoveNext() in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/AutoMLEngineService/AutoMLEngine.cs:line 251
```

**Comment by lridgard** [comment]
Same problem. I have attached a little more info from my attempt.

![image](https://user-images.githubusercontent.com/11907052/99319082-c9383a00-281d-11eb-95a0-9ee466471ca7.png)

![image](https://user-images.githubusercontent.com/11907052/99319226-01d81380-281e-11eb-82b7-8699083a5e24.png)

**Comment by LittleLittleCloud** [comment]
Hi @frankhaugen @lridgard  sorry for the trouble. Could you try creating workspace in azure portal instead and let us know if it works or not. It can be a temporary work around plus helping us locate the bug. 

Regards

**Comment by LittleLittleCloud** [comment]
Hi @frankhaugen @lridgard , we reproduced the error and are working on a fix for that, in the meantime, one work around is to go to azure portal to create workspace.

Regards

**Comment by lridgard** [comment]
I tried two things.

1. I deleted the 4 successful resources and then tried the redeploy option from the portal. This created 4 of the 5 resources and failed on the 5th with the same error. as above.

2. Using the marketplace, I selected the Machine Learning resource, configured it to use the 4 resources successfully created in the earlier step, selected the resource group etc. matching the successful deployments, all other values were left at default, and deployed it. This also failed with the same error as above.

The resource is: Microsoft.MachineLearningServices/workspaces
The error is: "An invalid value was provided for 'accessPolicies'."

**Comment by beccamc** [comment]
This seems to be a problem for new subscriptions or subscriptions with no existing key vaults. You should be able to unblock yourself by creating a brand new workspace in the poral at https://ms.portal.azure.com/#create/Microsoft.MachineLearningServices. 

We're working on a fix on our side.

**Comment by beccamc** [comment]
This is fixed! Please download the new build from the VS Marketplace.
