### ISSUE TITLE
When Azure ML training fails the model builder throws a null ref exception

### ISSUE THREAD

**Issue by frankhaugen** [dotnet/machinelearning-modelbuilder#1111]
**System Information**
- Model Builder Version:
16.3.2056001
- Visual Studio Version:
Microsoft Visual Studio Enterprise 2019 Preview
Version 16.9.0 Preview 1.0
- Scenario:
Object detection (Azure)

**Describe the bug**
In the event that the training in the cloud fails, the model builder appears to interpret this as a "complete" and tries to download a file that does not exist and so the builder throws a null reference exception. 

This occurs when there is a failure to train a model in Azure 

**To Reproduce**
1. Have a set of Vott-tagged images
  Images: [https://github.com/freedoom/freedoom/tree/master/sprites](https://github.com/freedoom/freedoom/tree/master/sprites)
   Vott-model: [Model.json.txt](https://github.com/dotnet/machinelearning-modelbuilder/files/5565005/Model.json.txt)
   (paths needs to be replaced unless you use this format: `C:\tensorflow\sprites\*.png`)
2. Start ML Model Builder and select Object Detection
3. Select all workspace-stuff and the files etc.
4. Start training
5. Wait ~2 Hours for the process to throw

**Expected behavior**
One or more of these is the behaviour I would expect:
1. The process shouldn't hard-fail on this, but a message that the process failed and what error message
2. It shouldn't fail, (In the web-UI it's re-runnable)
3. The process should fail, but the message should inform the user to go to the web UI and rerun the failed run, at which point the model builder process should continue and not fail, so that the resultant model can be used to generate a project
4. The error message in this specific case should link to the documentation where it's described how to remedy this, (Googling and Binging didn't give me any result for how I could increase the "iteration timeout"

**Screenshots**
Error message
![image](https://user-images.githubusercontent.com/13543585/99634575-06c8dd00-2a41-11eb-96b7-f34b7ad84455.png)

Error in the Azure training
![image](https://user-images.githubusercontent.com/13543585/99632937-65408c00-2a3e-11eb-972f-0cf2c0e653d7.png)

**Additional context**
Run Id: 
```
AutoML_4e5a3d77-7733-4af7-9c38-2ba115c62e0e?wsid=/subscriptions/f534f692-eda4-455a-bc23-e6793b49e2d3/resourceGroups/Haugen/providers/Microsoft.MachineLearningServices/workspaces/Hackathon2020
```

Stacktrace:
```
   at AzureML.AutoMLRunnerImages.<RunAutoMLAsync>d__27.MoveNext() in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/RemoteAutoML/AutoMLRunnerImages.cs:line 237
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ML.ModelBuilder.AutoMLService.Experiments.AzureImageClassificationExperiment.<ExecuteAsync>d__13.MoveNext() in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/Experiments/AzureImageClassificationExperiment.cs:line 69
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ML.ModelBuilder.AutoMLEngine.<StartTrainingAsync>d__26.MoveNext() in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/AutoMLEngineService/AutoMLEngine.cs:line 150
```
Log (the entire thing, probably not useful):
[d1e9ec13-86cb-4885-b721-3312a4959a9b.txt](https://github.com/dotnet/machinelearning-modelbuilder/files/5564964/d1e9ec13-86cb-4885-b721-3312a4959a9b.txt)

**Comment by JakeRadMSFT** [comment]
Thanks for reporting and sorry you're hitting this issue.

How many images were you using to train? It looks like it's timing out ... you can try a smaller subset and we'll investigate a fix on our side.

**Comment by frankhaugen** [comment]
@JakeRadMSFT Thank you for answering me this quickly! 😺 

I included a link to the ~1400 images in the text, you could have counted them 😉 
(It's low resolution .png images)

The error message explicitly says "Iteration Timeout", so timeout is a sensible guess. When I shaved off the dataset by about 30 percent and tried again with no failures, (though that model was mis-trained as I had just removed all but one class of images, giving it an accuracy of ~0.99998, which felt wrong and gave really bad results). It was possible to complete the original run, (or rather my retry of the entire experiment resulted in the same), and I tried to resubmit the failed run, which succeeded. Having already finished it once I could just download the .onnx -file and run the ModelBuilder.cs with the new file, and all was well.

The Model Builder is, (as I understand/see it), a gateway for someone to just dip their toes into ML, and so making it super user-friendly and with a lot of error mitigation is probably not a priority, but in this case it's really important that the user gets something meaningful back, because, (assuming the other bug I reported this week gets fixed), there is the appearance of Visual Studio being the primary UI for the training.

Tangentially:
I tried to get more powerful computing going, but there is some limit I'm unable to pay to increase, (unless I setup a dedicated VM that'll cost a fortune and I'll use for a few hours per week, max). My logic was that if it's slow, pay it to go faster.

And where do I increase the "iteration timeout"?? The error in Azure says I should consider it, I've considered it, and think it's a splendid idea, but I can't really find where to do it! 😆

**Comment by beccamc** [comment]
@v-Hailishi Can you see if this still reproduces on large datasets (above 2k images)? Let me know if you need help finding a dataset.

**Comment by v-Hailishi** [comment]
@beccamc Tried on the on the latest main branch: 16.13.5.2222101, I met the network issue when using the datasets frankhaugen provided:
Images: https://github.com/freedoom/freedoom/tree/master/sprites
Vott-model: [Model.json.txt](https://github.com/dotnet/machinelearning-modelbuilder/files/5565005/Model.json.txt)
![image](https://user-images.githubusercontent.com/99375895/165474703-6b83417b-98dd-4b33-afd9-81019e7548cd.png)
![image](https://user-images.githubusercontent.com/99375895/165505158-c5c25002-966f-4a47-8aa7-f489cebe8b9c.png)
![image](https://user-images.githubusercontent.com/99375895/165505358-d6b086ba-0ace-4b35-8f9b-b5cd7e10b5a0.png)
Log file: 
[MLModel1-GM2Z7C.txt](https://github.com/dotnet/machinelearning-modelbuilder/files/8571490/MLModel1-GM2Z7C.txt)

Run link in Azure portal:
https://ml.azure.com/experiments/id/8ad34cd8-0b2e-445b-a3a7-5760c3306ece/runs/AutoML_c12004bd-dd51-408c-9907-0de3e9350218?wsid=/subscriptions/83635e26-687a-4333-a2a0-33e3cd1f573a/resourceGroups/FullTestPass/providers/Microsoft.MachineLearningServices/workspaces/FullTestPass&tid=72f988bf-86f1-41af-91ab-2d7cd011db47#details

**Comment by nillmaker** [comment]
My friends, 

I has same error. 

Even using NC6 / NC24 virtual machines with approximately 750 images, after some training time the same problem occurs (sometimes faster).
In the case of the NC24, the Model Builder is "eternally" in "provisioning computation" until this same error occurs.
It has also occurred in other old trainings that the strangeness lasts for 2 hours. When this time arrives, the interactions error occurs.

**Comment by nillmaker** [comment]
Hey @beccamc! How are you?
Almost a year later, I'm just recording what happened in this case.
I spent several days trying to make it work and strangely, after I restarted the machine, Visual Studio was able to finish training using the Azure machine that I mentioned earlier.
As a lot of time has passed since this issue, some processes may have been improved and corrected in this regard.
