### ISSUE TITLE
Fix on Could not find file '/Users/########/myMLApp/consumeModelApp/MLModel.zip'

### ISSUE THREAD

**Issue by fabracht** [dotnet/machinelearning-modelbuilder#1142]
**System Information (please complete the following information):**
dotnet 5.0.100
mlnet 16.2.0
MacOS Catalina 10.15.7

**Describe the bug**
https://dotnet.microsoft.com/learn/ml-dotnet/get-started-tutorial/consume
- Clear description of the problem:
I ran the commands exactly as described in the tutorial, but when it comes to do dotnet run, the thing crashes with the following error.

```
Unhandled exception. System.IO.FileNotFoundException: Could not find file '/Users/###########/myMLApp/consumeModelApp/MLModel.zip'.
File name: '/Users//###########//myMLApp/consumeModelApp/MLModel.zip'
   at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
   at System.IO.FileStream.OpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at System.IO.File.OpenRead(String path)
   at Microsoft.ML.ModelOperationsCatalog.Load(String filePath, DataViewSchema& inputSchema)
   at SampleClassification.Model.ConsumeModel.CreatePredictionEngine() in /Users//###########//myMLApp/SampleClassification/SampleClassification.Model/ConsumeModel.cs:line 37
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.get_Value()
   at SampleClassification.Model.ConsumeModel.Predict(ModelInput input) in /Users//###########//myMLApp/SampleClassification/SampleClassification.Model/ConsumeModel.cs:line 27
   at consumeModelApp.Program.Main(String[] args) in /Users//###########//myMLApp/consumeModelApp/Program.cs:line 15
```

**To Reproduce**
1. Go to https://dotnet.microsoft.com/learn/ml-dotnet/get-started-tutorial/intro MacOS version
2. Follow the tutorial until Download and add Data -> type wget https://raw.githubusercontent.com/dotnet/machinelearning/master/test/data/wikipedia-detox-250-line-data.ts to download the file
3. Continue until you reach the Consume the app phase. 
4. Once I run the command dotnet run, I the the error described above

**Expected behavior**

**Comment by LittleLittleCloud** [comment]
Hi @fabracht 
We are working on a fix for this bug, in the meanwhile, a quick work around is go to consume.cs and replace this line
`public static string MLNetModelPath = Path.GetFullPath("MLModel.zip");`

with this

`public static string MLNetModelPath = Path.Combine(System.AppContext.BaseDirectory, "MLModel.zip");`

**Comment by LittleLittleCloud** [comment]
dup of #1137

**Comment by fabracht** [comment]
Thanks,
That solved it.
