### ISSUE TITLE
Model Builder training fails on classification dataset

### ISSUE THREAD

**Issue by LittleLittleCloud** [dotnet/machinelearning-modelbuilder#1160]
**System Information (please complete the following information):**
 - Model Builder Version:  16.3.0.2056001
 - Visual Studio Version 16.7

**To Reproduce**
- download this dataset
- pick classification
- training

**Screenshots**

![image](https://user-images.githubusercontent.com/16876986/101832904-13df6600-3aed-11eb-9f00-ca1a669d46b3.png)

**Additional context**
dataset: 

[wikipedia-detox-250-line-data.txt](https://github.com/dotnet/machinelearning-modelbuilder/files/5675751/wikipedia-detox-250-line-data.txt)

**Comment by okarpov** [comment]
all DB value types are real in SQL 2019 Express


Specified cast is not valid.
   
at System.Data.SqlClient.SqlBuffer.get_Single()
   at Microsoft.ML.Data.DatabaseLoader.Cursor.<>c__DisplayClass37_0.<CreateSingleGetterDelegate>b__0(Single& value)
   at Microsoft.ML.AutoML.DatasetDimensionsUtil.HasMissingNumericSingleValue(IDataView data, Column column)
   at Microsoft.ML.AutoML.DatasetDimensionsApi.CalcColumnDimensions(MLContext context, IDataView data, Column[] purposes)
   at Microsoft.ML.AutoML.DatasetColumnInfoUtil.GetDatasetColumnInfo(MLContext context, IDataView data, ColumnInformation columnInfo)
   at Microsoft.ML.AutoML.ExperimentBase`2.ExecuteTrainValidate(IDataView trainData, ColumnInformation columnInfo, IDataView validationData, IEstimator`1 preFeaturizer, IProgress`1 progressHandler)
   at Microsoft.ML.AutoML.ExperimentBase`2.Execute(IDataView trainData, ColumnInformation columnInformation, IEstimator`1 preFeaturizer, IProgress`1 progressHandler)
   at Microsoft.ML.ModelBuilder.AutoMLService.Experiments.AutoMLExperiment`3.<>c__DisplayClass21_0.<ExecuteAsync>b__5() in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/Experiments/AutoMLExperiment.cs:line 80
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ML.ModelBuilder.AutoMLService.Experiments.AutoMLExperiment`3.<ExecuteAsync>d__21.MoveNext() in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/Experiments/AutoMLExperiment.cs:line 107
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ML.ModelBuilder.AutoMLEngine.<StartTrainingAsync>d__26.MoveNext() in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/AutoMLEngineService/AutoMLEngine.cs:line 150

**Comment by LittleLittleCloud** [comment]
Hi @okarpov 
Thanks for the feedback, we will take a look at this issue.

In the meanwhile, your case will be traced under this one. As the error from your case is different from this original one.

**Comment by vzhuqin** [comment]
This issue can't be repro on：
- Windows 10 Enterprise, Version 20H2
- ML.Net Model Builder (Preview): 16.5.21.2122301
- Microsoft Visual Studio Enterprise 2019: 16.9.4
- .Net: 5.0.202

Main branch:
https://privategallery.blob.core.windows.net/gallery/refs/heads/main/atom.xml

Steps：
1. Create new C# console app with .Net 5.0;
2. Add model builder by right click on the project;
3. Select "Text classification";
4. Select "Local (CPU)" on Environment page;
5. Input data and set "Sentiment" to Label;
6. Set train time to 60s and training complete without any error.
![image.png](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/8b21515d-ea3c-46ed-bb0a-ccd93bbfae33)

Dataset:
https://testpass.blob.core.windows.net/test-pass-data/wikipedia-detox-250-line-data.tsv
