### ISSUE TITLE
Specified label column 'sentiment' was not found. in ML.NET Model Builder 1 example

### ISSUE THREAD

**Issue by cecchettia** [dotnet/machinelearning-modelbuilder#1168]
**System Information (please complete the following information):**
 - Model Builder Version: 16.3.0.205601
 - Visual Studio Version: 16.8.3

**Describe the bug** Error when first example in dotnet.microsoft.com/learn/ml-dotnet/get-started-tutorial/create
error was Specified label column 'sentiment' was not found. 

- On which step of the process did you run into an issue: "start training"
- Clear description of the problem:'
- In this version 16.8.3 - the "Pick a scenario" page differs- text classification is missing
I tried both Sentiment Analysis and Custom Scenario.
I tried reinstalling ML_NET Model Builder preview under extensions. Made sure ML.NET preview was enabled under "Preview Features"

I tried the suggestions above and a few found in other forums, created a new file with only 19 lines, removed the tabs and replace with commas, Made sure the header column names contained no spaces.
Still getting the error: "Specified label column 'Sentiment' was not found."

error log
   at Microsoft.ML.AutoML.ColumnTypeInference.GetAndValidateLabelColumn(Arguments args, IntermediateColumn[] cols)
   at Microsoft.ML.AutoML.ColumnTypeInference.InferTextFileColumnTypesCore(MLContext context, IMultiStreamSource fileSource, Arguments args)
   at Microsoft.ML.AutoML.ColumnInferenceApi.InferColumnTypes(MLContext context, TextFileSample sample, ColumnSplitResult splitInference, Boolean hasHeader, Nullable`1 labelColumnIndex, String label)
   at Microsoft.ML.AutoML.ColumnInferenceApi.InferColumns(MLContext context, String path, ColumnInformation columnInfo, Nullable`1 separatorChar, Nullable`1 allowQuotedStrings, Nullable`1 supportSparse, Boolean trimWhitespace, Boolean groupColumns, Boolean hasHeader)
   at Microsoft.ML.ModelBuilder.AutoMLEngine.InferColumns(MLContext context, AutoMLServiceParameter config) in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/AutoMLEngineService/AutoMLEngine.cs:line 271
   at Microsoft.ML.ModelBuilder.AutoMLEngine.<StartTrainingAsync>d__26.MoveNext() in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/AutoMLEngineService/AutoMLEngine.cs:line 114

**To Reproduce**
This is what is contained in the simplified data file

sentiment,text
1,RUDE  Dude. you are rude upload
1,OK!   IM GOING TO VANDALIZE WILD ONES WIKI THEN!!!  
1,Stop trolling. zapatancas. 
1,You're cool  You seem like a 
1,Why are you threatening me? 
1,hey waz up?   hey ummm..
0,I'm not sure either. I think it 
0,Your POV and propaganda pushing is 
0,FileHildebrandt-Greg and Tim.jpg listed for deletion
0,This is a gross exaggeration. Nobody is setting a k
1,No. I won't unrevert your edits!   sounds more like 
1,I heard Mark Kermode say today that Turbo was rubbish. 
1,I am a sock puppet? THAT is my ban reason? This is my 
1,You twit. read the article before you revert edits. 
0,A tag has been placed on Jerome leung kam. 
1,READ THIS  This is Wikipedia. It is a place 
0,Administrator Complaint Filed Against You I requested 
1,It is a shame what people are here. I am disgusting of you.

2. run this under sentiment analysis ( or custom)
3. See error

"Specified label column 'Sentiment' was not found."

error log
   at Microsoft.ML.AutoML.ColumnTypeInference.GetAndValidateLabelColumn(Arguments args, IntermediateColumn[] cols)
   at Microsoft.ML.AutoML.ColumnTypeInference.InferTextFileColumnTypesCore(MLContext context, IMultiStreamSource fileSource, Arguments args)
   at Microsoft.ML.AutoML.ColumnInferenceApi.InferColumnTypes(MLContext context, TextFileSample sample, ColumnSplitResult splitInference, Boolean hasHeader, Nullable`1 labelColumnIndex, String label)
   at Microsoft.ML.AutoML.ColumnInferenceApi.InferColumns(MLContext context, String path, ColumnInformation columnInfo, Nullable`1 separatorChar, Nullable`1 allowQuotedStrings, Nullable`1 supportSparse, Boolean trimWhitespace, Boolean groupColumns, Boolean hasHeader)
   at Microsoft.ML.ModelBuilder.AutoMLEngine.InferColumns(MLContext context, AutoMLServiceParameter config) in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/AutoMLEngineService/AutoMLEngine.cs:line 271
   at Microsoft.ML.ModelBuilder.AutoMLEngine.<StartTrainingAsync>d__26.MoveNext() in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/AutoMLEngineService/AutoMLEngine.cs:line 114

**Screenshots**
![image](https://user-images.githubusercontent.com/16923116/103180963-6351c000-4869-11eb-823f-8dc72069ce5b.png)

**Additional context**
Tried variations of the file. Tried loading and uploadoing ML.NET Model Buider 1. 

Thank you

**Comment by LittleLittleCloud** [comment]
Greeting @cecchettia 

I just tried your dataset on latest model builder and it works well. Could you double-check if your model builder is the latest one? The scenario page should look like this, and we remove custom scenario long long time ago.

![image](https://user-images.githubusercontent.com/16876986/103238655-343a5d80-4900-11eb-83d1-cb3d0c1d4985.png)

**Comment by cecchettia** [comment]
Dear LittleLittleCloud,

Thank you, that was my problem. I had added machine learning the old way using visual studio installer. Once I removed machine learning and reinstalled the current version of machine learning using the extension method, everything worked. 
Thank you
