### ISSUE TITLE
Database Loader error in AutoML

### ISSUE THREAD

**Issue by LittleLittleCloud** [dotnet/machinelearning-modelbuilder#1170]
`all DB value types are real in SQL 2019 Express

Specified cast is not valid.
   
```
at System.Data.SqlClient.SqlBuffer.get_Single()
   at Microsoft.ML.Data.DatabaseLoader.Cursor.<>c__DisplayClass37_0.<CreateSingleGetterDelegate>b__0(Single& value)
   at Microsoft.ML.AutoML.DatasetDimensionsUtil.HasMissingNumericSingleValue(IDataView data, Column column)
   at Microsoft.ML.AutoML.DatasetDimensionsApi.CalcColumnDimensions(MLContext context, IDataView data, Column[] purposes)
   at Microsoft.ML.AutoML.DatasetColumnInfoUtil.GetDatasetColumnInfo(MLContext context, IDataView data, ColumnInformation columnInfo)
   at Microsoft.ML.AutoML.ExperimentBase`2.ExecuteTrainValidate(IDataView trainData, ColumnInformation columnInfo, IDataView validationData, IEstimator`1 preFeaturizer, IProgress`1 progressHandler)
   at Microsoft.ML.AutoML.ExperimentBase`2.Execute(IDataView trainData, ColumnInformation columnInformation, IEstimator`1 preFeaturizer, IProgress`1 progressHandler)
   at Microsoft.ML.ModelBuilder.AutoMLService.Experiments.AutoMLExperiment`3.<>c__DisplayClass21_0.<ExecuteAsync>b__5() in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/Experiments/AutoMLExperiment.cs:line 80
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ML.ModelBuilder.AutoMLService.Experiments.AutoMLExperiment`3.<ExecuteAsync>d__21.MoveNext() in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/Experiments/AutoMLExperiment.cs:line 107
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ML.ModelBuilder.AutoMLEngine.<StartTrainingAsync>d__26.MoveNext() in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/AutoMLEngineService/AutoMLEngine.cs:line 150
````

**Comment by okarpov** [comment]
same for me, any solution?

**Comment by nvaghari** [comment]
same for me, just I tried to fetch two columns. one text and another one a number

**Comment by daniesa** [comment]
Same here

**Comment by beccamc** [comment]
Hi everyone, we just shipped a new version of Model Builder. Can you upgrade and try again? https://marketplace.visualstudio.com/items?itemName=MLNET.07

**Comment by beccamc** [comment]
Any update here? Is the problem fixed with the upgrade?

**Comment by daniesa** [comment]
Hey,
Thank you for the follow up.
Yes, the problem was with the number of data on the sample sheet. I just
tried to double them and it's all ok now.

**Comment by beccamc** [comment]
So is anyone else still experiencing his problem? Or was it resolved in our latest build https://marketplace.visualstudio.com/items?itemName=MLNET.07

**Comment by LittleLittleCloud** [comment]
Going to close this issue because of no response,  feel free to reopen it if you have any questions.
