### ISSUE TITLE
Exception thrown when using Model Builder to train Image classification

### ISSUE THREAD

**Issue by efonsecab** [dotnet/machinelearning-modelbuilder#1176]
**System Information (please complete the following information):**
 - Model Builder Version: 16.3.0
 - Visual Studio Version: Community 16.8.3

**Describe the bug**
- On which step of the process did you run into an issue: 
When clicking Train after selecting Image Classification and being able to view the images in the Data Preview
- Clear description of the problem:
Every single time I try to train an Image Classification using the Visual Studio integrated UI, I get the following exception

   at Microsoft.ML.AutoML.ColumnTypeInference.GetAndValidateLabelColumn(Arguments args, IntermediateColumn[] cols)
   at Microsoft.ML.AutoML.ColumnTypeInference.InferTextFileColumnTypesCore(MLContext context, IMultiStreamSource fileSource, Arguments args)
   at Microsoft.ML.AutoML.ColumnInferenceApi.InferColumnTypes(MLContext context, TextFileSample sample, ColumnSplitResult splitInference, Boolean hasHeader, Nullable`1 labelColumnIndex, String label)
   at Microsoft.ML.AutoML.ColumnInferenceApi.InferColumns(MLContext context, String path, ColumnInformation columnInfo, Nullable`1 separatorChar, Nullable`1 allowQuotedStrings, Nullable`1 supportSparse, Boolean trimWhitespace, Boolean groupColumns, Boolean hasHeader)
   at Microsoft.ML.ModelBuilder.AutoMLEngine.InferColumns(MLContext context, AutoMLServiceParameter config) in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/AutoMLEngineService/AutoMLEngine.cs:line 271
   at Microsoft.ML.ModelBuilder.AutoMLEngine.<StartTrainingAsync>d__26.MoveNext() in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/AutoMLEngineService/AutoMLEngine.cs:line 114

**To Reproduce**
1. Create a Directory with the following structure

- Images
- - Tag1
- -- Image1.png
- - Tag2
- -- Image2.png 

2. Check the preview works
3. Click Train
4. See exception happening

**Expected behavior**
Train action working correctly and giving more detailed message
Abilty to debug what is going on

**Screenshots**

**Additional context**

**Comment by zewditu** [comment]
@efonsecab, thanks for reporting the issues. to investigate the issues in more detail could you give us more information? like how large is your image?

**Comment by efonsecab** [comment]
> @efonsecab, thanks for reporting the issues. to investigate the issues in more detail could you give us more information? like how large is your image?

Hello, sure, they are between 80kbs and 1MB

**Comment by efonsecab** [comment]
Is there any source code for Model Builder that I could download and debug out the VS Tooling?

**Comment by zewditu** [comment]
@JakeRadMSFT or  @LittleLittleCloud,  any thought on this?

**Comment by JakeRadMSFT** [comment]
@efonsecab - I've never seen that issue before. 

How many images do you have in your dataset and how many different labels/folders? Would you be able to share a screenshot of the Data Preview?

**Comment by efonsecab** [comment]
This is fixed in the latest versions of Visual Studio
