### ISSUE TITLE
Failure on SQL Recommendation

### ISSUE THREAD

**Issue by beccamc** [dotnet/machinelearning-modelbuilder#1236]
1. Choose Recommendation -> SQL
2. Choose Rating, User, there is an error on Item column 

at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlCommand.RunExecuteNonQueryTds(String methodName, Boolean async, Int32 timeout, Boolean asyncWrite)
   at System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, String methodName, Boolean sendToPipe, Int32 timeout, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)
   at System.Data.SqlClient.SqlCommand.ExecuteNonQuery()
   at Microsoft.ML.ModelBuilder.DataProviders.SQLDataProvider.GetTableSize(String connectionString, String tableName)
   at Microsoft.ML.ModelBuilder.Utils.Utilities.GetTrainTime(IDataSource datasource)
   at Microsoft.ML.ModelBuilder.ToolWindows.ModelBuilderDataContext.GetTrainViewModel()
   at Microsoft.ML.ModelBuilder.ToolWindows.ModelBuilderDataContext.<<-ctor>b__3_5>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ML.ModelBuilder.Observable.ObservableModel.<ExecuteUpdateHandlerAsync>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ML.ModelBuilder.Observable.ObservableModel.<HandlePropertyUpdateAsync>d__18.MoveNext()

**Comment by beccamc** [comment]
We have an issue with SQL tables containing "-"

![image.png](https://images.zenhubusercontent.com/5d55c3d68fac840001314eaa/0f4e8571-514f-4907-9911-544172f7a8ed)
