### ISSUE TITLE
A delimiter cannot be Nothing or an empty String.

### ISSUE THREAD

**Issue by phillipmunn** [dotnet/machinelearning-modelbuilder#1332]
**System Information (please complete the following information):**
 - Model Builder Version:  16.3.0.2056001
 - Visual Studio Version 16.9.2

**Describe the bug**
- In the ML.NET Model Builder, I selected SQL Server as a data source.
- I picked a table from my SQL Server database.
- An exception is then thrown.

2021-03-16 23:01:17.3237 DEBUG Set log file path to C:\Users\phill\AppData\Local\Temp\MLVSTools\logs\70cbb47c-a22c-4bf2-a525-b3016bf002fd.txt (Microsoft.ML.ModelBuilder.Utils.Logger.Debug)
2021-03-16 23:11:26.5269 TRACE Disposing AutoMLService Client (Microsoft.ML.ModelBuilder.AutoMLServiceFactory+AutoMLServiceProxy.Dispose)
2021-03-16 23:11:26.5269 DEBUG A delimiter cannot be Nothing or an empty String.
Parameter name: Delimiters
   at Microsoft.VisualBasic.FileIO.TextFieldParser.ValidateDelimiters(String[] delimiterArray)
   at Microsoft.VisualBasic.FileIO.TextFieldParser.set_Delimiters(String[] value)
   at Microsoft.ML.ModelBuilder.AutoMLService.DataProcessingEngine.GetRichDataTypes(String fileName, Boolean hasHeader, String[] delimiter, List`1 columnNames, Char& decimalSeparator) in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/DataProcessingEngine.cs:line 60
   at Microsoft.ML.ModelBuilder.AutoMLService.DataProcessingEngine.GetFileAttributes(String fileName) in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/DataProcessingEngine.cs:line 35
   at Microsoft.ML.ModelBuilder.AutoMLEngine.GetFileAttributesAsync(String fileName) in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/AutoMLEngineService/AutoMLEngine.cs:line 195 (Microsoft.ML.ModelBuilder.Utils.Logger.Debug)
2021-03-16 23:11:44.6301 TRACE Disposing AutoMLService Client (Microsoft.ML.ModelBuilder.AutoMLServiceFactory+AutoMLServiceProxy.Dispose)
2021-03-16 23:11:57.2321 TRACE Disposing AutoMLService Client (Microsoft.ML.ModelBuilder.AutoMLServiceFactory+AutoMLServiceProxy.Dispose)
2021-03-16 23:11:57.2321 DEBUG A delimiter cannot be Nothing or an empty String.
Parameter name: Delimiters
   at Microsoft.VisualBasic.FileIO.TextFieldParser.ValidateDelimiters(String[] delimiterArray)
   at Microsoft.VisualBasic.FileIO.TextFieldParser.set_Delimiters(String[] value)
   at Microsoft.ML.ModelBuilder.AutoMLService.DataProcessingEngine.GetRichDataTypes(String fileName, Boolean hasHeader, String[] delimiter, List`1 columnNames, Char& decimalSeparator) in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/DataProcessingEngine.cs:line 60
   at Microsoft.ML.ModelBuilder.AutoMLService.DataProcessingEngine.GetFileAttributes(String fileName) in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/DataProcessingEngine.cs:line 35
   at Microsoft.ML.ModelBuilder.AutoMLEngine.GetFileAttributesAsync(String fileName) in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/AutoMLEngineService/AutoMLEngine.cs:line 195 (Microsoft.ML.ModelBuilder.Utils.Logger.Debug)
2021-03-16 23:12:19.0873 DEBUG Open Log FileC:\Users\phill\AppData\Local\Temp\MLVSTools\logs\70cbb47c-a22c-4bf2-a525-b3016bf002fd.txt (Microsoft.ML.ModelBuilder.Utils.Logger.Debug)

**Comment by beccamc** [comment]
@phillipmunn sorry you've run into this problem. My guess is your SQL data contains commas?

When you use a SQL datasource we read in a portion of your data (200 lines) and save it to a .csv file. We then use that .csv file for column type prediction, getting sample data, and the data preview. If your SQL data has commas, it could be that our parser is reading it incorrectly. 

Can you get me a copy of that .csv file? Open Model Builder and open your SQL file again, and pick the table. Then go to the %temp% folder. There should be a recently created file <guid>.csv.  Can you open it and see if it looks correct? If you don't have sensitive data can you share it with me? Thanks! 

![image.png](https://images.zenhubusercontent.com/5d55c3d68fac840001314eaa/5ffca258-c917-41b6-b1dc-88a30abd578f)

**Comment by beccamc** [comment]
Hi @phillipmunn! Any update here? Would love to see the generated .cvs file to help you out with this problem. Thanks!

**Comment by phillipmunn** [comment]
Hello @beccamc 

The information is sensitive - it's actually Invoice data, but so I can hopefully make the product better I've included a single row from the CSV file and manually redacted anything which I believe I cannot share.

One of the columns in our SQL database is named "SerializedObject" and is actually XML data stored in a text column.
It will therefore include comma's and other symbols which is where I suspect the issue is.

Appologies for not being able to share more of the data - but perhaps this is enough information you need to see if you can improve the parser?

[24018c95-914a-409e-9897-5f05e57538b1.zip](https://github.com/dotnet/machinelearning-modelbuilder/files/6280233/24018c95-914a-409e-9897-5f05e57538b1.zip)

**Comment by beccamc** [comment]
@phillipmunn Yes I think you're exactly right! The problem is likely the XML data. In this sample it appears Model Builder can load it, but if there are commas in other rows it would break. Are you able to try this again without the "SeralizedObject" column?

**Comment by beccamc** [comment]
Did this work without the SerlizedObject column?

**Comment by phillipmunn** [comment]
@beccamc yes, excluding the column containing XML data (stored as VARCHAR) within the database solves the issue.

**Comment by beccamc** [comment]
Great! Is that an acceptable solution?

**Comment by phillipmunn** [comment]
Yes thanks.
