### ISSUE TITLE
Cannot run sample program

### ISSUE THREAD

**Issue by adamantinum** [dotnet/machinelearning-modelbuilder#1345]
**System Information (please complete the following information):**
 - Model Builder or CLI Version:  CLI version installed with `dotnet tool install -g mlnet`
 - Visual Studio Version (if applicable): No Visual Studio

**Describe the bug**
- On which page of the tutorial did you run into an issue (URL): https://dotnet.microsoft.com/learn/ml-dotnet/get-started-tutorial/consume
- Clear description of the problem: The sample program doesn't run because it searches MLModel.zip in its own folder instead that in the referenced one.

**To Reproduce**
1. `cd consumeModelApp`
2. `dotnet add reference "../SampleClassification/SampleClassification.Model/SampleClassification.Model.csproj"`
3.  Edit Program.cs as explained
4. The error occurs when the command `dotnet run` is used
5. See error:
`Unhandled exception. System.IO.FileNotFoundException: Could not find file 'C:\Users\Alessandro\Desktop\myMLApp\consumeModelApp\MLModel.zip'.
File name: 'C:\Users\Alessandro\Desktop\myMLApp\consumeModelApp\MLModel.zip'
   at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle)
   at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at System.IO.File.OpenRead(String path)
   at Microsoft.ML.ModelOperationsCatalog.Load(String filePath, DataViewSchema& inputSchema)
   at SampleClassification.Model.ConsumeModel.CreatePredictionEngine() in C:\Users\Alessandro\Desktop\myMLApp\SampleClassification\SampleClassification.Model\ConsumeModel.cs:line 37
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.get_Value()
   at SampleClassification.Model.ConsumeModel.Predict(ModelInput input) in C:\Users\Alessandro\Desktop\myMLApp\SampleClassification\SampleClassification.Model\ConsumeModel.cs:line 27
   at consumeModelApp.Program.Main(String[] args) in C:\Users\Alessandro\Desktop\myMLApp\consumeModelApp\Program.cs:line 18`

**Expected behavior**
Program should run.

Thank you in advance.

**Comment by beccamc** [comment]
@adamantinum Sorry for the delay here. Did you copy the generated MLModel.zip file from the SampleClassification.Model folder to the consumeModelApp folder?

**Comment by adamantinum** [comment]
Thank you for your reply. Yes, I was able to run the program copying MLModel.zip, but there isn't written in the tutorial, so I suppose it should work without doing it, also because SampleClassification.Model.csproj is referenced in the consumeModelApp project file.

**Comment by beccamc** [comment]
Glad you got it working @adamantinum!  I want to make sure our docs are clear. We do have a note about copying the zip, but it seems it isn't noticeable. 

![image](https://user-images.githubusercontent.com/9122518/115090843-9339d780-9edb-11eb-8059-599ae24853cd.png)

Sorry, I'm not trying to call you out! I want to hear if you have feedback on how we make this more clear and understandable.

**Comment by adamantinum** [comment]
Oh my fault, it has escaped me.
Sorry and thank you for your patience.

**Comment by beccamc** [comment]
No problem! Please let us know if you run into any more issues
