### ISSUE TITLE
Trouble with Model Builder -- cannot download resnet from https://aka.ms/mlnet-resources/meta/resnet_v2_50_299.meta

### ISSUE THREAD

**Issue by f-quintero** [dotnet/machinelearning-modelbuilder#1376]
**System Information (please complete the following information):**
 - Model Builder Version: 16.3.0.2056001
 - Visual Studio Version Microsoft Visual Studio Community 2019 Version 16.9.3

**Describe the bug**
- On which step of the process did you run into an issue: training
- Clear description of the problem: the training process fail because can not download the resnet file: resnet_v2_50_299.meta from https://aka.ms/mlnet-resources/meta/resnet_v2_50_299.meta

aka.ms resolve to mlnetresources.blob.core.windows.net. But this address not exists.

**To Reproduce**
First: be sure you do not have already downloaded the resnet_v2_50_299.meta file(s) (maybe at %USERPROFILE%\AppData\Local\Temp\MLNET)
1. Select Image classification scenario
2. Select Local CPU 
3. Select label organized folder
4. Start training
5. Fail.

**Expected behavior**
Model trained

**Screenshots**
Same trouble occurs if you try to train a image classification model using mlnet using command line:
mlnet image-classification --dataset peces
in such case the error message is similar:

[Source=AutoML, Kind=Error] Pipeline crashed: xf=ValueToKeyMapping{ col=Label:Label} xf=RawByteImageLoading{ col=ImageSource_featurized:ImageSource imageFolder=} xf=ColumnCopying{ col=Features:ImageSource_featurized} tr=ImageClassification{} xf=KeyToValueMapping{ col=PredictedLabel:PredictedLabel} cache=- . Exception: System.InvalidOperationException: Error downloading resource from 'https://aka.ms/mlnet-resources/meta/resnet_v2_50_299.meta': Host desconocido. Host desconocido.\nHost desconocido. Host desconocido.\nHost desconocido. Host desconocido.\nHost desconocido. Host desconocido.\nHost desconocido. Host desconocido.\n
Meta file could not be downloaded! Please copy the model file 'resnet_v2_50_299.meta' from 'meta\resnet_v2_50_299.meta' to 'C:\Users\fabian.quintero\AppData\Local\Temp\MLNET'.
   at Microsoft.ML.TensorFlow.TensorFlowUtils.DownloadIfNeeded(IHostEnvironment env, String url, String dir, String fileName, Int32 timeout)
   at Microsoft.ML.Vision.ImageClassificationTrainer.LoadTensorFlowSessionFromMetaGraph(IHostEnvironment env, Architecture arch)
   at Microsoft.ML.Vision.ImageClassificationTrainer.InitializeTrainingGraph(IDataView input)
   at Microsoft.ML.Vision.ImageClassificationTrainer.TrainModelCore(TrainContext trainContext)
   at Microsoft.ML.Trainers.TrainerEstimatorBase`2.TrainTransformer(IDataView trainSet, IDataView validationSet, IPredictor initPredictor)
   at Microsoft.ML.Trainers.TrainerEstimatorBase`2.Fit(IDataView input)
   at Microsoft.ML.Data.EstimatorChain`1.Fit(IDataView input)
   at Microsoft.ML.Data.EstimatorChain`1.Fit(IDataView input)
   at Microsoft.ML.AutoML.RunnerUtil.TrainAndScorePipeline[TMetrics](MLContext context, SuggestedPipeline pipeline, IDataView trainData, IDataView validData, String groupId, String labelColumn, IMetricsAgent`1 metricsAgent, ITransformer preprocessorTransform, FileInfo modelFileInfo, DataViewSchema modelInputSchema, IChannel logger)
[Source=ImageClassificationTrainer; ImageClassificationTrainer, Kind=Trace] Channel started
Error downloading resource from 'https://aka.ms/mlnet-resources/meta/resnet_v2_50_299.meta': Host desconocido. Host desconocido.\nHost desconocido. Host desconocido.\nHost desconocido. Host desconocido.\nHost desconocido. Host desconocido.\nHost desconocido. Host desconocido.\n
Meta file could not be downloaded! Please copy the model file 'resnet_v2_50_299.meta' from 'meta\resnet_v2_50_299.meta' to 'C:\Users\fabian.quintero\AppData\Local\Temp\MLNET'.
One or more errors occurred. (Value cannot be null. (Parameter 'source'))

**Additional context**
rror downloading resource from 'https://aka.ms/mlnet-resources/meta/resnet_v2_50_299.meta': No se puede resolver el nombre remoto: 'mlnetresources.blob.core.windows.net'\nNo se puede resolver el nombre remoto: 'mlnetresources.blob.core.windows.net'\nNo se puede resolver el nombre remoto: 'mlnetresources.blob.core.windows.net'\nNo se puede resolver el nombre remoto: 'mlnetresources.blob.core.windows.net'\nNo se puede resolver el nombre remoto: 'mlnetresources.blob.core.windows.net'\n
Meta file could not be downloaded! Please copy the model file 'resnet_v2_50_299.meta' from 'meta\resnet_v2_50_299.meta' to 'C:\Users\nueva\AppData\Local\Temp\MLNET'.

en Microsoft.ML.ModelBuilder.AutoMLService.Experiments.AutoMLExperiment`3.<ExecuteAsync>d__21.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en Microsoft.ML.ModelBuilder.AutoMLEngine.<StartTrainingAsync>d__26.MoveNext() en /_/src/Microsoft.ML.ModelBuilder.AutoMLService/AutoMLEngineService/AutoMLEngine.cs:línea 150

Extract from log file:

2021-04-11 13:09:46.6099 INFO [Source=AutoML, Kind=Error] Pipeline crashed: xf=ValueToKeyMapping{ col=Label:Label} xf=RawByteImageLoading{ col=ImageSource_featurized:ImageSource imageFolder=} xf=ColumnCopying{ col=Features:ImageSource_featurized} tr=ImageClassification{} xf=KeyToValueMapping{ col=PredictedLabel:PredictedLabel} cache=- . Exception: System.InvalidOperationException: Error downloading resource from 'https://aka.ms/mlnet-resources/meta/resnet_v2_50_299.meta': No se puede resolver el nombre remoto: 'mlnetresources.blob.core.windows.net'\nNo se puede resolver el nombre remoto: 'mlnetresources.blob.core.windows.net'\nNo se puede resolver el nombre remoto: 'mlnetresources.blob.core.windows.net'\nNo se puede resolver el nombre remoto: 'mlnetresources.blob.core.windows.net'\nNo se puede resolver el nombre remoto: 'mlnetresources.blob.core.windows.net'\n
Meta file could not be downloaded! Please copy the model file 'resnet_v2_50_299.meta' from 'meta\resnet_v2_50_299.meta' to 'C:\Users\nueva\AppData\Local\Temp\MLNET'.
   en Microsoft.ML.TensorFlow.TensorFlowUtils.DownloadIfNeeded(IHostEnvironment env, String url, String dir, String fileName, Int32 timeout)
   en Microsoft.ML.Vision.ImageClassificationTrainer.LoadTensorFlowSessionFromMetaGraph(IHostEnvironment env, Architecture arch)
   en Microsoft.ML.Vision.ImageClassificationTrainer.InitializeTrainingGraph(IDataView input)
   en Microsoft.ML.Vision.ImageClassificationTrainer.TrainModelCore(TrainContext trainContext)
   en Microsoft.ML.Trainers.TrainerEstimatorBase`2.TrainTransformer(IDataView trainSet, IDataView validationSet, IPredictor initPredictor)
   en Microsoft.ML.Data.EstimatorChain`1.Fit(IDataView input)
   en Microsoft.ML.Data.EstimatorChain`1.Fit(IDataView input)
   en Microsoft.ML.AutoML.RunnerUtil.TrainAndScorePipeline[TMetrics](MLContext context, SuggestedPipeline pipeline, IDataView trainData, IDataView validData, String groupId, String labelColumn, IMetricsAgent`1 metricsAgent, ITransformer preprocessorTransform, FileInfo modelFileInfo, DataViewSchema modelInputSchema, IChannel logger) (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2021-04-11 13:09:46.6099 INFO [Source=ImageClassificationTrainer; Ensuring meta files are present., Kind=Trace] Channel finished. Elapsed 00:00:50.7023486. (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2021-04-11 13:09:46.6099 INFO [Source=ImageClassificationTrainer; ImageClassificationTrainer, Kind=Trace] Channel started (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2021-04-11 13:09:46.6309 INFO Error downloading resource from 'https://aka.ms/mlnet-resources/meta/resnet_v2_50_299.meta': No se puede resolver el nombre remoto: 'mlnetresources.blob.core.windows.net'\nNo se puede resolver el nombre remoto: 'mlnetresources.blob.core.windows.net'\nNo se puede resolver el nombre remoto: 'mlnetresources.blob.core.windows.net'\nNo se puede resolver el nombre remoto: 'mlnetresources.blob.core.windows.net'\nNo se puede resolver el nombre remoto: 'mlnetresources.blob.core.windows.net'\n
Meta file could not be downloaded! Please copy the model file 'resnet_v2_50_299.meta' from 'meta\resnet_v2_50_299.meta' to 'C:\Users\nueva\AppData\Local\Temp\MLNET'. (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2021-04-11 13:09:46.7279 TRACE Disposing AutoMLService Client (Microsoft.ML.ModelBuilder.AutoMLServiceFactory+AutoMLServiceProxy.Dispose)
2021-04-11 13:09:46.7349 DEBUG Error downloading resource from 'https://aka.ms/mlnet-resources/meta/resnet_v2_50_299.meta': No se puede resolver el nombre remoto: 'mlnetresources.blob.core.windows.net'\nNo se puede resolver el nombre remoto: 'mlnetresources.blob.core.windows.net'\nNo se puede resolver el nombre remoto: 'mlnetresources.blob.core.windows.net'\nNo se puede resolver el nombre remoto: 'mlnetresources.blob.core.windows.net'\nNo se puede resolver el nombre remoto: 'mlnetresources.blob.core.windows.net'\n
Meta file could not be downloaded! Please copy the model file 'resnet_v2_50_299.meta' from 'meta\resnet_v2_50_299.meta' to 'C:\Users\nueva\AppData\Local\Temp\MLNET'.
   en Microsoft.ML.ModelBuilder.AutoMLService.Experiments.AutoMLExperiment`3.<ExecuteAsync>d__21.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en Microsoft.ML.ModelBuilder.AutoMLEngine.<StartTrainingAsync>d__26.MoveNext() en /_/src/Microsoft.ML.ModelBuilder.AutoMLService/AutoMLEngineService/AutoMLEngine.cs:línea 150 (Microsoft.ML.ModelBuilder.Utils.Logger.Debug)
2021-04-11 13:22:24.2489 DEBUG Open Log FileC:\Users\nueva\AppData\Local\Temp\MLVSTools\logs\49c63063-c8b3-4d8a-97bc-ab96a4a676a3.txt (Microsoft.ML.ModelBuilder.Utils.Logger.Debug)

**Comment by Christopher600** [comment]
Same

**Comment by fuomag9** [comment]
#1375 Is a related issue as well

**Comment by rahulgorai** [comment]
Same Issue, do we have any solution to this Issue ?

**Comment by fuomag9** [comment]
We'd need a mirror for the files so we can download them manually on disk, but until microsoft sorts out their DNS issues we can't do anything

**Comment by sudiptaBGorai** [comment]
I'm stuck in production environment as unable to train my model

**Comment by sgbuddy** [comment]
Experiencing Same Problem with the Model Builder, the URL is unable to Resolve. Do Someone have alternate FTP to resnet ???

**Comment by beccamc** [comment]
Hi all - sorry for this issue. We're looking into it. Based on time reported I'm guessing many of you are in Europe, is that correct?

**Comment by fuomag9** [comment]
Yep, I'm from europe

**Comment by rahulgorai** [comment]
> 
> 
> Hi all - sorry for this issue. We're looking into it. Based on time reported I'm guessing many of you are in Europe, is that correct?

I am from INDIA

**Comment by f-quintero** [comment]
> Hi all - sorry for this issue. We're looking into it. Based on time reported I'm guessing many of you are in Europe, is that correct?

I am from Colombia, South America

**Comment by beccamc** [comment]
This should be fixed now. Please check and let me know!

**Comment by fuomag9** [comment]
> This should be fixed now. Please check and let me know!

Fixed for me, thanks!

**Comment by f-quintero** [comment]
> This should be fixed now. Please check and let me know!

Yes, file downloaded. Thank you, Becca.

**Comment by f-quintero** [comment]
File downloaded.

**Comment by Linh-Bau** [comment]
Hi Becca. I'm from Viet Nam and get the same issue, please help. Thank you!

**Comment by hannespreishuber** [comment]
today
owload resnet_v2_50_299.meta from https://aka.ms/mlnet-resources/meta/resnet_v2_50_299.meta fail with exception One or more errors occurred.

**Comment by dedaap72** [comment]
Same here. Looking into the code of ResourceManagerUtils, there is a timeout set of 600000 ms (if not overridden by an environment variable) to wait for the download. However, the download uses a HttpClient instance, with its default timeout, being 100 seconds. I am not sure what that 600000 ms is supposed to do, but it will never hit because the HttpClient timeout will be hit first. 100 seconds does not seem a lot when the connection is a bit slow.

**Comment by torronen** [comment]
Not this specific but a onnx file... my problem was my firewall was blocking the CDN location in India. Using VPN bypassed firewall, then finally adding the CDN location to the whitelist in firewal
