### ISSUE TITLE
Error on CSV-Parsing at Amazon Review Dataset (although , or ; converted)

### ISSUE THREAD

**Issue by 42Entwickler** [dotnet/machinelearning-modelbuilder#1380]
**System Information (please complete the following information):**
 - Model Builder Version: 16.5.0.2115505
 - Visual Studio Version: 16.9.4

**Describe the bug**
- On which step of the process did you run into an issue:
- Clear description of the problem:

**To Reproduce**
1. Download the trainings file from kaggle [https://www.kaggle.com/bittlingmayer/amazonreviews?select=train.ft.txt.bz2](https://www.kaggle.com/bittlingmayer/amazonreviews?select=train.ft.txt.bz2) which acutally IS fixed length.
2. use this c# code for doing conversion to semi-colon
`static void Main(string[] args)
{
    Console.WriteLine("Converting...");
    using (System.IO.StreamWriter writer = new System.IO.StreamWriter(TARGET))
    {
        foreach (string line in System.IO.File.ReadLines(SOURCE))
        {
            string repl = String.Concat(line[..11], ";\"", line[11..], "\"");
            writer.WriteLine(repl);
        }
    }
    Console.WriteLine("Done");
}
`
3. Add a new mbconfig-File to a blank project.
4. Use Szenario "text Classification"
5. Local CPU - Next
6. At the Data-Section use the file with semi-colon and you get the error bellow.

**Expected behavior**
I expected that this will work but I get the error message although I did convert the fixed length to comma sepparated values, but also i tried with semi-colon.

**Screenshots**
![image](https://user-images.githubusercontent.com/68561197/114717532-69df4700-9d35-11eb-8f81-73eaf1d82fc0.png)
Here as Text:
`   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at StreamJsonRpc.JsonRpc.<InvokeCoreAsync>d__94`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ML.ModelBuilder.AutoMLServiceFactory.AutoMLServiceProxy.<GetFileAttributesAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ML.ModelBuilder.Actions.DataTextActions.<GetCsvDataProgramAsync>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ML.ModelBuilder.Actions.DataTextActions.<SetFileNameAsync>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ML.ModelBuilder.ToolWindows.DataTextViewModel.<SetFileNameAsync>d__87.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ML.ModelBuilder.ToolWindows.TextDataControl.<<BrowseFileButton_Click>b__7_0>d.MoveNext()`

**Comment by beccamc** [comment]
@42Entwickler Thanks for the detailed report here! The generated file also failed for me. I was able to get a working file by having Excel do the translation for me (New workbook -> Data -> From Text/CSV -> Load -> Save as .csv). 

It produced results like this: 
```
Column1,Column2
__label__2 ,Stuning even for the non-gamer: This sound track was beautiful! It paints the senery in your mind so well I would recomend it even to people who hate vid. game music! I have played the game Chrono Cross but out of all of the games I have ever played it has the best music! It backs away from crude keyboarding and takes a fresher step with grate guitars and soulful orchestras. It would impress anyone who cares to listen! ^_^
__label__2 ,"The best soundtrack ever to anything.: I'm reading a lot of reviews saying that this is the best 'game soundtrack' and I figured that I'd write a review to disagree a bit. This in my opinino is Yasunori Mitsuda's ultimate masterpiece. The music is timeless and I'm been listening to it for years now and its beauty simply refuses to fade.The price tag on this is pretty staggering I must say, but if you are going to buy any cd for this much money, this is the only one that I feel would be worth every penny."
```

It looks very similar to your file, but it works properly and can be loaded/trained. I've reached out to our partner team that predicts the file type to explain the difference. 

In the mean time, you could use excel to convert or I could share the converted file. Thanks!

**Comment by 42Entwickler** [comment]
@beccamc thank you very much So I added the " " to the second column to avoid troubles in csv if the delimiter is part of the string and i didn't have a column name.
Excel convert wasn't possible because the file has 1.5GB and too many rows for excel. I try conversion with this format again and will see how it works otherwise I say thank you for ping back for conversion ;)

**Comment by beccamc** [comment]
@42Entwickler I got a response from our partner team (PROSE) that handles the file parsing:

> The CSV file produced from the code snippet is invalid, as there are unescaped quotes and delimiters. For example, take a look at line 181 in “train.ft.tsv” (at the end of the line there is another unescaped semicolon). Therefore, PROSE does not learn delimited file, because this would lead to loss of data. I have also tried to load this file using Excel and it ignores this problem and looses data. For example, on line 181 all the data after semicolon at the end is lost in Excel. 
> 
> On the other hand, on the file “amazon-reviews.csv” _(produced by excel)_ the comma delimiter is only accidentally learned, because there is exactly one comma on the prefix of rows. However, if you take a look, for example, at lines 27-49 – the commas are definitively at wrong places, and the file will not be loaded correctly (as the original structure is lost). 

Ivan, our partner, helpfully fixed the code to correctly escape quotes:

> The correct conversion code (fixed from github issue – I have added quoting escape):

```
            Console.WriteLine("Converting...");
            using (StreamWriter writer = new StreamWriter(TARGET))
            {
                foreach (string line in File.ReadLines(SOURCE))
                {
                    string repl = string.Concat(line[..11], ";\"", line[11..].Replace("\"", "\"\""), "\"");
                    writer.WriteLine(repl);
                }
            }
            Console.WriteLine("Done");
```

**Comment by beccamc** [comment]
Any luck with the above code?
