### ISSUE TITLE
Invalid login throws Azure reload exception

### ISSUE THREAD

**Issue by beccamc** [dotnet/machinelearning-modelbuilder#1412]
My personal account was in an invalid state in VS. This caused an error in the User Authorization manager. 

Expected Behavior: We shouldn't throw an error if one identity doesn't work. In this case the problem identity wasn't needed to access Azure and we should just ignore it. 

```
System.Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at async Task<AuthenticationInfo> Microsoft.Developer.IdentityService.AccountProvider.MsalNetworkServicesImpl.AcquireTokenSilentAsync(string resource, string tenant, UserIdentifier userId, CancellationToken cancellationToken)
   at async Task<AuthenticationInfo> Microsoft.Developer.IdentityService.AccountProvider.MsalNetworkServicesImpl.AcquireTokenSilentAsync(string resource, string tenant, UserIdentifier userId, CancellationToken cancellationToken)
   at void Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
   at async Task<AuthenticationInfo> Microsoft.Developer.IdentityService.AccountProvider.AadAccountProviderService.AcquireAuthenticationInfoSilentAsync(string resource, string tenantId, Account account, CancellationToken cancellationToken)
   at async Task<AccessTokenResult> Microsoft.Developer.IdentityService.AccountProvider.AadAccountProviderService.AcquireTokenAsync(string resource, string tenantId, Account account)
   at Microsoft.ML.ModelBuilder.AzureAttach.UserAuthorizationManager.<GetUserTokenAsync>d__6.MoveNext() in C:\Repos\machinelearning-tools\src\Microsoft.ML.ModelBuilder\AzureAttach\UserAuthorizationManager.cs:line 103
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.ML.ModelBuilder.AzureAttach.UserAuthorizationManager.<TryReloadAzureUserAsync>d__5.MoveNext() in C:\Repos\machinelearning-tools\src\Microsoft.ML.ModelBuilder\AzureAttach\UserAuthorizationManager.cs:line 70
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.ML.ModelBuilder.ViewModels.EnvironmentViewModel.<<TryReloadAzure>b__76_0>d.MoveNext() in C:\Repos\machinelearning-tools\src\Microsoft.ML.ModelBuilder\ViewModels\EnvironmentViewModel.cs:line 404
Set log file path to C:\Users\beccam\AppData\Local\Temp\MLVSTools\logs\1e859850-8f4f-41c7-a623-c5d8aa774543.txt
System.Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at async Task<AuthenticationInfo> Microsoft.Developer.IdentityService.AccountProvider.MsalNetworkServicesImpl.AcquireTokenSilentAsync(string resource, string tenant, UserIdentifier userId, CancellationToken cancellationToken)
   at async Task<AuthenticationInfo> Microsoft.Developer.IdentityService.AccountProvider.MsalNetworkServicesImpl.AcquireTokenSilentAsync(string resource, string tenant, UserIdentifier userId, CancellationToken cancellationToken)
   at void Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
   at async Task<AuthenticationInfo> Microsoft.Developer.IdentityService.AccountProvider.AadAccountProviderService.AcquireAuthenticationInfoSilentAsync(string resource, string tenantId, Account account, CancellationToken cancellationToken)
   at async Task<AccessTokenResult> Microsoft.Developer.IdentityService.AccountProvider.AadAccountProviderService.AcquireTokenAsync(string resource, string tenantId, Account account)
   at Microsoft.ML.ModelBuilder.AzureAttach.UserAuthorizationManager.<GetUserTokenAsync>d__6.MoveNext() in C:\Repos\machinelearning-tools\src\Microsoft.ML.ModelBuilder\AzureAttach\UserAuthorizationManager.cs:line 103
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.ML.ModelBuilder.AzureAttach.UserAuthorizationManager.<TryReloadAzureUserAsync>d__5.MoveNext() in C:\Repos\machinelearning-tools\src\Microsoft.ML.ModelBuilder\AzureAttach\UserAuthorizationManager.cs:line 70
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.ML.ModelBuilder.ViewModels.EnvironmentViewModel.<<TryReloadAzure>b__76_0>d.MoveNext() in C:\Repos\machinelearning-tools\src\Microsoft.ML.ModelBuilder\ViewModels\EnvironmentViewModel.cs:line 404
Set log file path to C:\Users\beccam\AppData\Local\Temp\MLVSTools\logs\fbaded98-7ab4-47dd-a129-8620c2aeb369.txt
System.Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at async Task<AuthenticationInfo> Microsoft.Developer.IdentityService.AccountProvider.MsalNetworkServicesImpl.AcquireTokenSilentAsync(string resource, string tenant, UserIdentifier userId, CancellationToken cancellationToken)
   at async Task<AuthenticationInfo> Microsoft.Developer.IdentityService.AccountProvider.MsalNetworkServicesImpl.AcquireTokenSilentAsync(string resource, string tenant, UserIdentifier userId, CancellationToken cancellationToken)
   at void Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
   at async Task<AuthenticationInfo> Microsoft.Developer.IdentityService.AccountProvider.AadAccountProviderService.AcquireAuthenticationInfoSilentAsync(string resource, string tenantId, Account account, CancellationToken cancellationToken)
   at async Task<AccessTokenResult> Microsoft.Developer.IdentityService.AccountProvider.AadAccountProviderService.AcquireTokenAsync(string resource, string tenantId, Account account)
   at Microsoft.ML.ModelBuilder.AzureAttach.UserAuthorizationManager.<GetUserTokenAsync>d__6.MoveNext() in C:\Repos\machinelearning-tools\src\Microsoft.ML.ModelBuilder\AzureAttach\UserAuthorizationManager.cs:line 103
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.ML.ModelBuilder.AzureAttach.UserAuthorizationManager.<TryReloadAzureUserAsync>d__5.MoveNext() in C:\Repos\machinelearning-tools\src\Microsoft.ML.ModelBuilder\AzureAttach\UserAuthorizationManager.cs:line 70
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.ML.ModelBuilder.ViewModels.EnvironmentViewModel.<<TryReloadAzure>b__76_0>d.MoveNext() in C:\Repos\machinelearning-tools\src\Microsoft.ML.ModelBuilder\ViewModels\EnvironmentViewModel.cs:line 404
Set log file path to C:\Users\beccam\AppData\Local\Temp\MLVSTools\logs\a22475e6-19f1-406b-a7b7-9f108e59ebf5.txt
System.Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at async Task<AuthenticationInfo> Microsoft.Developer.IdentityService.AccountProvider.MsalNetworkServicesImpl.AcquireTokenSilentAsync(string resource, string tenant, UserIdentifier userId, CancellationToken cancellationToken)
   at async Task<AuthenticationInfo> Microsoft.Developer.IdentityService.AccountProvider.MsalNetworkServicesImpl.AcquireTokenSilentAsync(string resource, string tenant, UserIdentifier userId, CancellationToken cancellationToken)
   at void Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
   at async Task<AuthenticationInfo> Microsoft.Developer.IdentityService.AccountProvider.AadAccountProviderService.AcquireAuthenticationInfoSilentAsync(string resource, string tenantId, Account account, CancellationToken cancellationToken)
   at async Task<AccessTokenResult> Microsoft.Developer.IdentityService.AccountProvider.AadAccountProviderService.AcquireTokenAsync(string resource, string tenantId, Account account)
   at Microsoft.ML.ModelBuilder.AzureAttach.UserAuthorizationManager.<GetUserTokenAsync>d__6.MoveNext() in C:\Repos\machinelearning-tools\src\Microsoft.ML.ModelBuilder\AzureAttach\UserAuthorizationManager.cs:line 103
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.ML.ModelBuilder.AzureAttach.UserAuthorizationManager.<TryReloadAzureUserAsync>d__5.MoveNext() in C:\Repos\machinelearning-tools\src\Microsoft.ML.ModelBuilder\AzureAttach\UserAuthorizationManager.cs:line 70
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.ML.ModelBuilder.ViewModels.EnvironmentViewModel.<<TryReloadAzure>b__76_0>d.MoveNext() in C:\Repos\machinelearning-tools\src\Microsoft.ML.ModelBuilder\ViewModels\EnvironmentViewModel.cs:line 404
```

**Comment by vzhuqin** [comment]
Verify this issue on main branch: 16.5.25.2127102
After clicked Object detection scenario, pop up below Model Builder Error window: Object reference not set to an instance of an object. @beccamc Could you help to take a look whether they are related?
![image.png](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/26807edb-3611-4806-8f40-d1a4aea1adf4)

**Comment by beccamc** [comment]
Nope, this one is unrelated! This is fallout from Jake's changes.

**Comment by vzhuqin** [comment]
Thanks for your confirmation, had added that issue on PR#1057 for tracking. This issue has been fixed: no pop up System.Exception error when access azure environment or reentrancy the azure model builder.
![#1412.gif](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/567f2a66-5322-4e0f-a1a5-a424fe13ac53)
