### ISSUE TITLE
CodeGen Relative Path Issue 

### ISSUE THREAD

**Issue by JakeRadMSFT** [dotnet/machinelearning-modelbuilder#1420]
https://github.com/dotnet/machinelearning-tools/pull/1012  introduced an issues with CodeGen

```
Could not find file 'C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\common7\ServiceHub\Hosts\ServiceHub.Host.CLR.x64\Classification.zip'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at Microsoft.ML.ModelOperationsCatalog.Load(String filePath, DataViewSchema& inputSchema)
   at Microsoft.ML.ModelBuilder.AutoMLService.ServiceFactory.CodeGeneratorService.GetColumns(Dictionary`2 sampleData, String modelPath) in C:\dev\machinelearning-tools\src\Microsoft.ML.ModelBuilder.AutoMLService\ServiceFactory\CodeGeneratorService.cs:line 144
   at Microsoft.ML.ModelBuilder.AutoMLService.ServiceFactory.CodeGeneratorService.CreateConsoleAppProjectCodesAsync(Dictionary`2 sampleData, String sampleProjectName, String className, String modelPath, String pipeline, TaskType task, String[] labels, ColumnDataKind labelColumnDataKind, String targetFramework, ScenarioType scenarioName, String labelName, Boolean isAzureArtifact, CancellationToken ct) in C:\dev\machinelearning-tools\src\Microsoft.ML.ModelBuilder.AutoMLService\ServiceFactory\CodeGeneratorService.cs:line 42
```

It's looking next to the Host ... we need make relative paths absolute before using them.

**Comment by LittleLittleCloud** [comment]
This issue no longer exists and no need to validate after we remove artifact from .mbconfig.
