### ISSUE TITLE
How to view the output in VS Debug Console?

### ISSUE THREAD

**Issue by PeanutYC** [dotnet/machinelearning-modelbuilder#1435]
**System Information (please complete the following information):**
 - Model Builder or CLI Version: 16.3.0.2056001
 - Visual Studio Version (if applicable): VS 2019 16.9.4

**Describe the bug**
- On which page of the tutorial did you run into an issue (URL): https://dotnet.microsoft.com/learn/ml-dotnet/get-started-tutorial/consume
- Clear description of the problem:
I am new to VS and .NET, may I know how to get the exact output given on the page? I can only see build successful message after selecting Ctrl+F5.

**To Reproduce**

**Expected behavior**
![image](https://user-images.githubusercontent.com/72436355/117161746-c4c80380-adf4-11eb-9a64-232011a8bf5e.png)

**Screenshots**
![image](https://user-images.githubusercontent.com/72436355/117161535-921e0b00-adf4-11eb-860d-fc4e11f19eba.png)
![image](https://user-images.githubusercontent.com/72436355/117161713-bda0f580-adf4-11eb-96e1-4dab98951224.png)

**Additional context**

**Comment by PeanutYC** [comment]
> @PeanutYC Thanks for getting started with us, and sorry you've run into a problem. Were any errors produced? Can you put a breakpoint on line 20 and see what result was produced? Thanks!

@beccamc 
Recently I tried to run the program again, there's an error produced.

![image](https://user-images.githubusercontent.com/72436355/117580207-75057700-b129-11eb-9d8b-afacd537f0ad.png)

Below is the details of the error shown when I debug at line 20. May I know how should I solve this problem? Thanks!

System.TypeInitializationException
  HResult=0x80131534
  Message=The type initializer for 'MyMLAppML.Model.ConsumeModel' threw an exception.
  Source=myMLAppML.Model
  StackTrace:
   at MyMLAppML.Model.ConsumeModel.Predict(ModelInput input) in C:\Users\Asus\source\repos\myMLApp\myMLAppML.Model\ConsumeModel.cs:line 22
   at myMLApp.Program.Main(String[] args) in C:\Users\Asus\source\repos\myMLApp\myMLApp\Program.cs:line 17

Inner Exception 1:
FileNotFoundException: Could not load file or assembly 'Microsoft.ML.Data, Version=1.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The system cannot find the file specified.

**Comment by PeanutYC** [comment]
After reinstalling VS and rebuilding the solution, I am able to get the desired output already. Thanks for your help!! @beccamc
