### ISSUE TITLE
Regression model impossible to train a model

### ISSUE THREAD

**Issue by apacifico** [dotnet/machinelearning-modelbuilder#1442]
**System Information (please complete the following information):**
 - Model Builder Version: 16.5.0.2115505
 - Visual Studio Version : 16.9.4

**Describe the bug**
This happen during the training for a regression model, the system is not able to parse correctly data on columns and throw errors

2021-05-06 16:01:51.7496 DEBUG Parsing failed with an exception: Could not parse value P in line 99, column PavedDrive
   at Microsoft.ML.Data.TextLoader.Cursor.<ParseParallel>d__33.MoveNext()
   at Microsoft.ML.Data.TextLoader.Cursor.MoveNextCore()
   at Microsoft.ML.Data.RootCursorBase.MoveNext()
   at Microsoft.ML.Data.IO.BinarySaver.RowsPerBlockHeuristic(IDataView data, ColumnCodec[] actives)
   at Microsoft.ML.Data.IO.BinarySaver.SaveData(Stream stream, IDataView data, Int32[] colIndices)
   at Microsoft.ML.Data.DataSaverUtils.SaveDataView(IChannel ch, IDataSaver saver, IDataView view, Stream stream, Boolean keepHidden)
   at Microsoft.ML.BinaryLoaderSaverCatalog.SaveAsBinary(DataOperationsCatalog catalog, IDataView data, Stream stream, Boolean keepHidden)
   at Microsoft.ML.ModelBuilder.AutoMLService.Experiments.LocalAutoMLExperiment.<ExecuteAsync>d__21.MoveNext() in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/Experiments/LocalAutoMLExperiment.cs:line 120
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ML.ModelBuilder.AutoMLEngine.<StartTrainingAsync>d__23.MoveNext() in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/AutoMLEngineService/AutoMLEngine.cs:line 155 (Mic

**To Reproduce**
I use this csv file : https://github.com/mdfarragher/DSC/blob/master/Regression/HousePricePrediction/data.csv
The column to predict is SalePrice and the train time is 10s
I Start the train and I obtain the exception I extracted the trace here above.

**Expected behavior**
I expect the tool is able to parse the column without raising exception , or is it normal? Do we expect the dataset is clean and usable for the prediction?

**Comment by beccamc** [comment]
Thanks for reporting with details @apacifico. The problem here is that we've predicted that the PavedDrive is a boolean, with Y/N values. It turns out this column is actually a categorical string value ("Y", "N" or "P"). 

You should be on a version that contains an "Advanced data options" experience on the data page. Open that dialog, and change the "Paved Driveway" data type to "string". Thanks!

**Comment by apacifico** [comment]
Hi Becca. If I understand well Auto-ML try to guess the content exploring the content and here it guess as a boolean type because it discovered Y an N, does it mean the exploratin doesn't observe the all line in the dataset. In this case it's a categorical column. It means we have to check all the column type identified by Auto-ML, it means it could be a long process if the number of coulumn is big.  The dark theme in visual studio produces a strange effect when you try to select the type, it's not readable
![AutoMLIm1](https://user-images.githubusercontent.com/824095/117511096-7ac65580-af8d-11eb-9fb1-480da9127f9b.jpg)
able

**Comment by apacifico** [comment]
Auto-ML select automatically the features it will use to build the model. But in case we have a column type error and after the column type is fixed by the user, does Auto-ML re evaluate the feature it will use to build the model? 
Inform the user about the type of the feature must be correct before a training I think it's an important point to indicate in the user interface. 
Re-evaluate the feature Auto-ML will use in case the user change the column type is important too.
Because you agree the algorithm used inside to select the features is dependent of the column type in the dataset. So a change on the type must trigger a re-evaluation of the features selected for training the model. Is my understanding correct?

**Comment by beccamc** [comment]
On the data page we process your data, and that includes predicting what the data looks like.  Using 200 rows of your dataset we predict the data type of the all columns (we also predict if the dataset has a header, and for text datasets what the column delimiter is). This happens before training, and is independent of training.  Yes you may need to look over the data to ensure it is correct, although many combinations of data just work (if it classified a Boolean as a string for example, this would still build a successful model). 

When you click "Start training" auto-ml loads the data based on the column information supplied, trains, and optimizes the resulting model. At this point it may choose to minimize features that are not relevant. If you have changed the column types auto-ml will build a new model based on the data provided. After changing a column type to more accurately reflect the data you should re-train so auto-ml can build a new model. 

I will report this feedback to our PM/designer:

> Inform the user about the type of the feature must be correct before a training I think it's an important point to indicate in the user interface.

Thanks for reporting the dark theme error. It's fixed and is shipping in the next release. 

Did that help address your questions?

**Comment by apacifico** [comment]
Yes Becca this address my question , yes doing this will enforce the process.
This means to evaluate the column that AutoML selects to build the model, 
1) The column type  must be checked before
2) In case the user change the column type, AutoML must re-evaluate the column used for the model.
3) inform the user it's important to have checked the good type of the column because based on the logic in place , it's possible the type auto-selected by the tool could be wrong and will impact the quality of the model obtained.

**Comment by beccamc** [comment]
I agree with you @apacifico. Thanks for the feedback!
