### ISSUE TITLE
Model Builder Error during the "Create New Workspace" wizard

### ISSUE THREAD

**Issue by BenjaminCharlton** [dotnet/machinelearning-modelbuilder#1492]
**System Information (please complete the following information):**
 - Model Builder Version: 16.3.0.2056001
 - Visual Studio Version 16.10.0

**Describe the bug**

Right Click on the Project > _Add_ > _Machine Learning_

Click _Object Detection_
Click _Set Up Workspace_
Fill in the form and click _Create_

It hangs a while, appearing to make a remote call or a long IO operation or something like that.
Then it displays this error message:

Long running operation failed with status 'Failed'. Additional Info:'At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.'
   at Microsoft.Rest.ClientRuntime.Azure.LRO.AzureLRO`2.CheckForErrors()
   at Microsoft.Rest.ClientRuntime.Azure.LRO.PutLRO`2.CheckForErrors()
   at Microsoft.Rest.ClientRuntime.Azure.LRO.AzureLRO`2.<StartPollingAsync>d__20.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Rest.ClientRuntime.Azure.LRO.AzureLRO`2.<BeginLROAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Rest.Azure.AzureClientExtensions.<GetLongRunningOperationResultAsync>d__1`2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Rest.Azure.AzureClientExtensions.<GetLongRunningOperationResultAsync>d__0`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Rest.Azure.AzureClientExtensions.<GetPutOrPatchOperationResultAsync>d__5`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.Azure.Management.ResourceManager.Fluent.DeploymentsOperations.<CreateOrUpdateWithHttpMessagesAsync>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.Azure.Management.ResourceManager.Fluent.DeploymentsOperationsExtensions.<CreateOrUpdateAsync>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.Azure.Management.ResourceManager.Fluent.DeploymentImpl.<CreateResourceAsync>d__60.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.Azure.Management.ResourceManager.Fluent.DeploymentImpl.<CreateAsync>d__59.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Azure.MachineLearning.Services.Workspaces.WorkspaceOperations.<CreateAsync>d__10.MoveNext() in /_/src/Microsoft.ML.AzureMLClient/Workspaces/WorkspaceOperations.cs:line 193
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Azure.MachineLearning.Services.AMLRest.AzureAttachManager.<PutCreateWorkspaceAsync>d__10.MoveNext() in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/AMLRest/AzureAttachManager.cs:line 127
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ML.ModelBuilder.AutoMLEngine.<PutCreateWorkspaceAsync>d__40.MoveNext() in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/AutoMLEngineService/AutoMLEngine.cs:line 251

**Expected behavior**
I'm sorry, I've never done it before so I didn't know what to expect.

**Screenshots**
![Screenshot 2021-06-03 151615](https://user-images.githubusercontent.com/28094599/120637165-984ce900-c47f-11eb-9aaa-0f618472636e.png)
![Screenshot 2021-06-03 161317](https://user-images.githubusercontent.com/28094599/120643014-a7836500-c486-11eb-8261-ec52df3b0282.png)

**Additional context**
None

**Comment by beccamc** [comment]
Sorry you ran into this problem @BenjaminCharlton, and thanks for reporting!

We've had several customers report problems creating their first workspace for a subscription. I'm guessing your issue is the same. Can you go to the portal to check? You can find information in the activities log on portal.azure.com

![image](https://user-images.githubusercontent.com/9122518/121239359-c30fb680-c85e-11eb-8b76-62903da3463a.png)

Can you find the call to make the new workspace? I'm guessing it will say it failed "An invalid value was provided for access policies".

**Comment by BenjaminCharlton** [comment]
Hi @beccamc! Yes, it says that in the _statusMessage_ of the JSON.

**Comment by beccamc** [comment]
Thanks! I'm going to try to pull in the Azure team to help.

**Comment by beccamc** [comment]
We have fixed this issue, and will ship it with our next release. Expect to see it in September. Thanks for your patience!

**Comment by BenjaminCharlton** [comment]
Well done! Thanks for the update
