### ISSUE TITLE
Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by jv-er** [dotnet/machinelearning-modelbuilder#1560]
at StreamJsonRpc.JsonRpc.<InvokeCoreAsync>d__139`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.ML.ModelBuilder.ViewModels.TrainViewModel.<GenerateCodeBehindFilesAsync>d__108.MoveNext()

**Comment by beccamc** [comment]
@jv-er Sorry you ran into this problem and thanks for reporting. What version of Model Builder are you on? You can find this info in the Manage Extension dialog

**Comment by jv-er** [comment]
![Most Recent](https://user-images.githubusercontent.com/86890117/124800955-1c750f00-df0b-11eb-8640-1abe338b503e.PNG)

**Comment by beccamc** [comment]
Was this with the same dataset you shared [here](https://github.com/dotnet/machinelearning-modelbuilder/issues/1563)?

**Comment by jv-er** [comment]
> 
> 
> Was this with the same dataset you shared [here](https://github.com/dotnet/machinelearning-modelbuilder/issues/1563)?

Yes, it was the same at that time.

**Comment by beccamc** [comment]
@jv-er We just released a new version. Can you update and try again? https://marketplace.visualstudio.com/items?itemName=MLNET.07
