### ISSUE TITLE
Model Builder Error: Index was outside the bounds of the array.

### ISSUE THREAD

**Issue by vzhuqin** [dotnet/machinelearning-modelbuilder#1602]
**System Information (please complete the following information):**
- Windows OS: Windows-10-Enterprise-21H1
- ML.Net Model Builder (Preview): 16.6.2.2136201 (Main Branch)
- Microsoft Visual Studio Enterprise 2019: 16.10.2
- .Net: 5.0.301

**Dataset:**
https://testpass.blob.core.windows.net/test-pass-data/issues.tsv.txt

**To Reproduce**
1. Select Create a new project from the Visual Studio 2019 start window.
2. Choose the C# Console App (.NET Core) project template with .Net 5.0;
3. Add model builder by right click on the project;
4. Select "Text classification" scenario and Local "CPU" environment;
5. Navigate to Data page and input the data source; 
6. Open "Advanced data options dialog to do "Advanced Data Test Pass";
7. Pop up Model Builder Error: Index was outside the bounds of the array if do below settings:
a. change the "Label" column "Area" from String to Single.
![image](https://user-images.githubusercontent.com/81727020/125576914-b18aaff1-262d-43ec-9156-bf6e7e212313.png)

b. change Label column from "Area" to another one (ID, Title, Description) with correct data type. 
![image](https://user-images.githubusercontent.com/81727020/125576957-25bcdde7-afb5-4aab-81b7-0731a9391915.png)

**Expected behavior**
Hope to add more explanation about the error.

- For a: I guess the error is caused by the incorrect data type for label column, "Area" only has strings, but set to "Single". if so, it is recommended to add more descriptions to help users judge. 
- For b: I don't understand the meaning of the error message because all columns have correct data type, or are the other 3 columns unsuitable for "label" purpose?

**Screenshots**
![image](https://user-images.githubusercontent.com/81727020/125573388-8110fff8-3ef0-4ae6-922b-ca2866fff59c.png)

**Additional context**

**Comment by LittleLittleCloud** [comment]
Thanks for finding that, this error happens as long as one of trial metric is `NaN`, I'll fix that

**Comment by vzhuqin** [comment]
Verified this issue on latest main build: 16.7.0.2137701, encounter other 2 error, could you please take a look?
a. change the "Label" column "Area" from String to Single.
![image.png](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/1a881c19-65dc-44e8-a1c6-e2bdbd07f8a7)
b. change Label column from "Area" to another one (ID, Title, Description) with correct data type.
![image.png](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/11abd570-745a-4702-ab38-8f8538c9f8cf)

Error Log:
[https://app.zenhub.com/files/186917455/255111d6-658a-40f5-a792-73e69018d651/download](https://app.zenhub.com/files/186917455/255111d6-658a-40f5-a792-73e69018d651/download)

**Comment by LittleLittleCloud** [comment]
@vzhuqin 
Thanks for the finding, I'll take a look again

**Comment by LittleLittleCloud** [comment]
The first error "Training set has 0 instances" is expected. Because the data type of training label is actually string type and can't be parsed as single, so the training set is actually empty. In this situation, throwing a parse error might be better, but in most of the cases, parsing error is inevitable, and simply ignoring the rows with parsing error or replacing them with NaN or other default value is generally more friendly. Which means the error "Training set has 0 instances" correctly reflects the error reason, although the error is caused by user error strictly speaking.

I prefer keeping this error message for the Sep release. And in the future, a separate data validation step should be added to solve this issue thoroughly.

**Comment by vzhuqin** [comment]
Thanks @LittleLittleCloud , But I can repro the second error on latest main build: 16.7.4.2145201, please take a look when you have time.
Dataset: [link](https://testpass.blob.core.windows.net/test-pass-data/issues.tsv.txt)
Label Column: Title
![image.png](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/db4f578c-ced5-4087-92bf-5c1a9d7247ba)
![image.png](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/bd6cce13-e633-4668-bbae-ce4bda48de38)

**Comment by LittleLittleCloud** [comment]
The second error is unrelated to the `index was outside the bounds of array`, I'll create another issue to track down that.

**Comment by beccamc** [comment]
@LittleLittleCloud Can you take a look if this is the same error?  We are still getting Index was outside the bounds of the array at `PipelineProposer.Propose(TrialParameter trialParameter)` (slightly diferent due to TrailParamater). 

```
at Microsoft.ML.ModelBuilder.AutoMLService.Proposer.PipelineProposer.Propose(TrialParameter trialParameter) in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/Proposer/PipelineProposer.cs:line 99
   at Microsoft.ML.ModelBuilder.AutoMLService.Proposer.Controller.Propose() in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/Proposer/Controller.cs:line 60
   at Microsoft.ML.ModelBuilder.AutoMLService.Experiments.LocalAutoMLExperiment.<ExecuteAsync>d__15.MoveNext() in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/Experiments/LocalAutoMLExperiment.cs:line 137
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ML.ModelBuilder.AutoMLEngine.<StartTrainingAsync>d__21.MoveNext() in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/AutoMLEngineService/AutoMLEngine.cs:line 163   at StreamJsonRpc.JsonRpc.<I...
```
Is this the same (or similar) root cause? Happy to create a new issue if not.

**Comment by LittleLittleCloud** [comment]
I'm not sure about that, but let's reuse this issue first and see if there's more coming
