### ISSUE TITLE
Model Build Error - The type initializer for 'Tensorflow.Binding' threw an exception.

### ISSUE THREAD

**Issue by Ronimjan** [dotnet/machinelearning-modelbuilder#1620]
**System Information (please complete the following information):**
 - Model Builder: Visual Studio Extension v16.6.1.2131904
 - Visual Studio Version: Visual Studio Community 2019 v16.10.3

**Describe the bug**
- When trying to train a new Image Classification model an exception gets thrown.
- Clear description of the problem: The following exception gets thrown:

>    at Microsoft.ML.Vision.ImageClassificationTrainer..ctor(IHostEnvironment env, Options options)
   at Microsoft.ML.AutoML.ImageClassificationExtension.CreateInstance(MLContext mlContext, IEnumerable`1 sweepParams, ColumnInformation columnInfo, IDataView validationSet)
   at Microsoft.ML.AutoML.SuggestedTrainer.BuildTrainer(IDataView validationSet)
   at Microsoft.ML.AutoML.SuggestedPipelineBuilder.Build(MLContext context, ICollection`1 transforms, ICollection`1 transformsPostTrainer, SuggestedTrainer trainer, CacheBeforeTrainer cacheBeforeTrainerSettings)
   at Microsoft.ML.AutoML.PipelineSuggester.GetNextInferredPipeline(MLContext context, IEnumerable`1 history, DatasetColumnInfo[] columns, TaskKind task, Boolean isMaximizingMetric, CacheBeforeTrainer cacheBeforeTrainer, IChannel logger, IEnumerable`1 trainerAllowList)
   at Microsoft.ML.AutoML.Experiment`2.Execute()
   at Microsoft.ML.AutoML.ExperimentBase`2.Execute(ColumnInformation columnInfo, DatasetColumnInfo[] columns, IEstimator`1 preFeaturizer, IProgress`1 progressHandler, IRunner`1 runner)
   at Microsoft.ML.AutoML.ExperimentBase`2.ExecuteCrossValSummary(IDataView[] trainDatasets, ColumnInformation columnInfo, IDataView[] validationDatasets, IEstimator`1 preFeaturizer, IProgress`1 progressHandler)
   at Microsoft.ML.AutoML.ExperimentBase`2.Execute(IDataView trainData, ColumnInformation columnInformation, IEstimator`1 preFeaturizer, IProgress`1 progressHandler)
   at Microsoft.ML.ModelBuilder.AutoMLService.Experiments.AutoMLExperiment`3.<>c__DisplayClass22_0.<ExecuteAsync>b__6() in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/Experiments/AutoMLExperiment.cs:line 85
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ML.ModelBuilder.AutoMLService.Experiments.AutoMLExperiment`3.<ExecuteAsync>d__22.MoveNext() in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/Experiments/AutoMLExperiment.cs:line 100
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ML.ModelBuilder.AutoMLEngine.<StartTrainingAsync>d__23.MoveNext() in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/AutoMLEngineService/AutoMLEngine.cs:line 153

**To Reproduce**
1. Add a new "Machine Learning Model" using the "Add" Button of your solution.
2. Select "Image Classification" as scenario
3. Select "Local CPU" as enviroment
4. Use [this](https://drive.google.com/drive/folders/1eUZ8V90Wgz_s6IHUQgRFU_JT_QoKIuI-?usp=sharing) dataset organized as given with "MLdata" as the root-folder.
5. Click "next step" and hit "train"

**Expected behavior**
I expected the "Wizard" to start training the model and checking through different algorithms, as shown in a variety of videos around the internet.

**Additional context**
In the "testrun" that produced the given exception I didn't have any packages installed.
**But** I tried it with following packages installed and it still threw an exception: Microsoft.ML v1.6.0, Microsoft.ML.Vision v1.6.0, Microsoft.ML.ImageAnalytics v1.6.0, SciSharp.TensorFlow.Redist v2.5.0

And btw, sorry if this is some super easy, silly, noobie thing that I am missing but I tried fixing it for 4 hours now and nothing worked yet so here I am 😃

**Comment by zewditu** [comment]
@LittleLittleCloud  for visibility.

**Comment by Ronimjan** [comment]
Hey guys,
I can 100% understand that you are busy and got more important stuff to do than helping an private, non-comercial user, but I'd love to get some support! 

If you need any additional information, let me know!

**Comment by LittleLittleCloud** [comment]
Hi @Ronimjan, sorry for the late response, community users are what we valued most as the entire ML.Net eco-system is open-source and community-driven, and we are trying our best to track and resolve all user issues. It's not easy especially when the number of open issues grows while we getting more users from ML.Net and model builder, and apologize again if we fail to respond to your thread in time. Trust me, it's not on purpose.

Back to the point, **Tensorflow.Binding** exception usually indicates that model builder fails to load tensorflow.dll because model builder can't find it or the tf binary is in a format that is not supported (if your CPU is arm, for example).

**Comment by Ronimjan** [comment]
Okay, so:

CPU: Intel Core I7 950 (Bloomfield)

The Logfile is attached.

[48b743b4-54ca-4774-a208-ee9eedcda782 - LOGFILE ML.NET.txt](https://github.com/dotnet/machinelearning-modelbuilder/files/6881601/48b743b4-54ca-4774-a208-ee9eedcda782.-.LOGFILE.ML.NET.txt)

In case of a not working CPU, would selecting the azure enviroment help?

Anyway, thanks for your answer :D

**Comment by LittleLittleCloud** [comment]
@Ronimjan 
> In case of a not working CPU, would selecting the azure enviroment help?
Yes, it will, but you need to create an AML workspace

Your CPU looks fine, it's not that new, but it supports avx instructions. 

Can you try if you can run TF.Net directly? TF.Net is the .net binding to TF and is what ML.Net and model builder uses for image classification training. If you can train with TF.Net directly, we can rule out the TF binary incompatible problem.

You can find bunch of TF.Net example here, just pick one and let us know if the run is successful

https://github.com/SciSharp/SciSharp-Stack-Examples

**Comment by Ronimjan** [comment]
Hey,
glad to hear!

Sadly, I am not used to git hub a lot, so.... How do I clone these specific samples?
I don't want to download the whole samples repository.

**Comment by LittleLittleCloud** [comment]
@Ronimjan 

Unfortunately, I don't think github supports clone "part" of repo,, you'll need to download the entire codebase.

**Comment by Ronimjan** [comment]
ah okay.

Gonna do that then I guess and will report back!

**Comment by lucent-sea** [comment]
I'm having the same issue on one of my computers.  My main dev laptop is fine, though.  Both are running the same version of Visual Studio 2019 and .NET SDK.  I tried repairing the VS installation.  Here's what I'm getting when running the SciSharp-Stack-Examples project:

```
PS C:\Users\trans\Desktop\SciSharp-Stack-Examples> dotnet run --project .\src\TensorFlowNET.Examples\ -ex "Linear Regression (Graph)"
Microsoft Windows NT 10.0.19043.0
64Bit Operating System: True
.NET CLR: 5.0.10
Unhandled exception. System.TypeInitializationException: The type initializer for 'Tensorflow.Binding' threw an exception.
 ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.DllNotFoundException: Unable to load DLL 'tensorflow' or one of its dependencies: A dynamic link library (DLL) initialization routine failed. (0x8007045A)
   at Tensorflow.c_api.TF_NewStatus()
   at Tensorflow.Status..ctor()
   at Tensorflow.tensorflow..ctor()
   --- End of inner exception stack trace ---
   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean wrapExceptions, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& hasNoDefaultCtor)
   at System.RuntimeType.CreateInstanceDefaultCtorSlow(Boolean publicOnly, Boolean wrapExceptions, Boolean fillCache)
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, Boolean wrapExceptions)
   at System.Activator.CreateInstance[T]()
   at Tensorflow.Binding.New[T]()
   at Tensorflow.Binding..cctor()
   --- End of inner exception stack trace ---
   at Tensorflow.Binding.get_tf()
   at TensorFlowNET.Examples.Program.Main(String[] args) in C:\Users\trans\Desktop\SciSharp-Stack-Examples\src\TensorFlowNET.Examples\Program.cs:line 50
PS C:\Users\trans\Desktop\SciSharp-Stack-Examples>
```

**Comment by LittleLittleCloud** [comment]
@lucent-sea 

The error is usually because system can't load binaries. We have a known error for loading dlls when your CPU is too old and don't support avx.

Can I have your TF version and CPU mode, Thanks!

**Comment by lucent-sea** [comment]
@LittleLittleCloud 

That explains it.  It's an old PC I use for hosting services on my LAN.  CPU is Intel Core i5 660.

How do I check TF version?  I'm new to ML.  I'm just using this extension: https://marketplace.visualstudio.com/items?itemName=MLNET.07.

**Comment by LittleLittleCloud** [comment]
@lucent-sea 
If you are using ModelBuilder, your TF version should be 2.3.1, which is compiled with avx instructions.

I just googled i5 660 was launched in 2010, while most of CPU with avx support comes out after 2011. So it's probably that your CPU doesn't support avx.

**Comment by lucent-sea** [comment]
@LittleLittleCloud 

Okay.  Thanks for looking into it.  :)

It works fine on my primary machine, and I've been having a lot of fun playing with datasets.  Thank you for helping to make ML so easy for beginners to get started!

**Comment by phatht** [comment]
@lucent-sea  how did you fix it? can you let me know 
thanks u.

**Comment by lucent-sea** [comment]
@phatht As LittleLittleCloud said, the i5 660 isn't supported, so I used my primary machine that has a newer CPU.

**Comment by luisquintanilla** [comment]
Thanks for reporting this issue. It appears it's been resolved. If there are additional questions or problems, please feel free to open a new issue.
