### ISSUE TITLE
Model Builder Error

### ISSUE THREAD

**Issue by peho-ea** [dotnet/machinelearning-modelbuilder#1797]
**System Information (please complete the following information):**
 - Model Builder or CLI Version: 16.7.3.2143002
 - Visual Studio Version (if applicable): 16.11.3

**Describe the bug**
- On which page of the tutorial did you run into an issue (URL): https://docs.microsoft.com/en-us/dotnet/machine-learning/tutorials/object-detection-model-builder#set-up-an-azure-ml-workspace
- Clear description of the problem: When I create a new Machine Learning Workspace, a Model Builder Error pops up.

**To Reproduce**
1. Select the "Set up workspace" button in "Select training environment"
2. Click "New" in Workspace
3. Enter "BasicMLWorkspace" in "Machine Learning Workspace name"
4. Select "West US 2" in Regions
4. Click "New" in Resource Groups and enter "BasicMLWorkspaceResourceGroup" name.
5. Got the error.

**Expected behavior**
It should create the Resource Groups and workspace successfully.

**Screenshots**
![image](https://user-images.githubusercontent.com/90938689/133861568-0b94edc0-3e5a-4eed-8f75-31851d0fd8c9.png)

**Additional context**
2021-09-17 15:04:25.8673 INFO Set log file path to C:\Users\peho\AppData\Local\Temp\2\MLVSTools\logs\StopSignDetectionMLModel-C6D7AY.txt (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2021-09-17 15:26:00.2791 TRACE Current user is null (Microsoft.ML.ModelBuilder.Utils.Logger.Trace)
2021-09-17 15:26:01.0605 TRACE Current user is not null (Microsoft.ML.ModelBuilder.Utils.Logger.Trace)
2021-09-17 15:30:35.4412 DEBUG Long running operation failed with status 'Failed'. Additional Info:'At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.'
   at Microsoft.Rest.ClientRuntime.Azure.LRO.AzureLRO`2.CheckForErrors()
   at Microsoft.Rest.ClientRuntime.Azure.LRO.PutLRO`2.CheckForErrors()
   at Microsoft.Rest.ClientRuntime.Azure.LRO.AzureLRO`2.<StartPollingAsync>d__20.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Rest.ClientRuntime.Azure.LRO.AzureLRO`2.<BeginLROAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Rest.Azure.AzureClientExtensions.<GetLongRunningOperationResultAsync>d__1`2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Rest.Azure.AzureClientExtensions.<GetLongRunningOperationResultAsync>d__0`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Rest.Azure.AzureClientExtensions.<GetPutOrPatchOperationResultAsync>d__5`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.Azure.Management.ResourceManager.Fluent.DeploymentsOperations.<CreateOrUpdateWithHttpMessagesAsync>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.Azure.Management.ResourceManager.Fluent.DeploymentsOperationsExtensions.<CreateOrUpdateAsync>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.Azure.Management.ResourceManager.Fluent.DeploymentImpl.<CreateResourceAsync>d__60.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.Azure.Management.ResourceManager.Fluent.DeploymentImpl.<CreateAsync>d__59.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ML.ModelBuilder.AutoMLService.WorkspaceCreator.WorkspaceCreateOperations.<CreateAsync>d__6.MoveNext() in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/WorkspaceCreator/WorkspaceCreateOperations.cs:line 141
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Azure.MachineLearning.Services.AMLRest.AzureAttachManager.<PutCreateWorkspaceAsync>d__10.MoveNext() in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/AMLRest/AzureAttachManager.cs:line 130
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ML.ModelBuilder.AutoMLEngine.<PutCreateWorkspaceAsync>d__34.MoveNext() in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/AutoMLEngineService/AutoMLEngine.cs:line 259   at StreamJsonRpc.JsonRpc.<InvokeCoreAsync>d__139`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ML.ModelBuilder.AzureAttach.NewWorkspaceDataContext.<CreateWorkspaceAsync>d__36.MoveNext() (Microsoft.ML.ModelBuilder.Utils.Logger.Debug)

**Comment by beccamc** [comment]
Sorry you ran into this problem @peho-ea.  Does it look like the workspace was successfully created in the portal? You can check at ml.azure.com. If you can't access the ml portal, go to portal.azure.com -> "Azure services" at the top of the page -> Machine Learning

Based on this... 
- If there is a workspace, it should be visible in Model Builder. Is the Azure dialog now loading things correctly?
- If not, can you go to portal.azure.com and check Notifications in the top right. Does it show any messages about why this failed?

**Comment by beccamc** [comment]
Were you able to check the portal for this issue?
