### ISSUE TITLE
Object Instance not set to an instance of an object on training image classification on CPU

### ISSUE THREAD

**Issue by AmritanshuAVerma** [dotnet/machinelearning-modelbuilder#1801]
**System Information (please complete the following information):**
 - Model Builder Version (available in Manage Extensions dialog): 16.7.3.2143002
 - Visual Studio Version 16.11.3

**Describe the bug**
- On which step of the process did you run into an issue: Training
- Clear description of the problem: Object instance not set to an instance of an object

**To Reproduce**
1. Add a mbconfig file
2. select image classification
3. click on train

**Expected behavior**
Model starts training

**Screenshots**
![image](https://user-images.githubusercontent.com/40417442/134461080-d5a9480d-facf-4dcc-8b17-301229829b70.png)

![image](https://user-images.githubusercontent.com/40417442/134461331-01525d4d-ca5e-465b-99ae-45bef77a8dbf.png)

![image](https://user-images.githubusercontent.com/40417442/134461476-54aa4e38-876b-46cc-b76a-5ce3fe4bc330.png)

**Additional context**
2021-09-23 11:18:46.0155 INFO Set log file path to C:\Users\LENOVO\AppData\Local\Temp\MLVSTools\logs\MLModel1-D7YI1P.txt (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2021-09-23 11:19:20.5755 DEBUG AutoMLType: Octopus (Microsoft.ML.ModelBuilder.Utils.Logger.Debug)
2021-09-23 11:19:20.6525 DEBUG Object reference not set to an instance of an object.
   at Microsoft.ML.ModelBuilder.AutoMLEngine.<StartTrainingAsync>d__21.MoveNext() in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/AutoMLEngineService/AutoMLEngine.cs:line 121   at StreamJsonRpc.JsonRpc.<InvokeCoreAsync>d__139`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.ML.ModelBuilder.ViewModels.TrainViewModel.<<StartTrainingAsync>b__109_0>d.MoveNext() (Microsoft.ML.ModelBuilder.Utils.Logger.Debug)
2021-09-23 11:31:34.2354 DEBUG AutoMLType: Octopus (Microsoft.ML.ModelBuilder.Utils.Logger.Debug)
2021-09-23 11:31:34.2571 DEBUG Object reference not set to an instance of an object.
   at Microsoft.ML.ModelBuilder.AutoMLEngine.<StartTrainingAsync>d__21.MoveNext() in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/AutoMLEngineService/AutoMLEngine.cs:line 121   at StreamJsonRpc.JsonRpc.<InvokeCoreAsync>d__139`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.ML.ModelBuilder.ViewModels.TrainViewModel.<<StartTrainingAsync>b__109_0>d.MoveNext() (Microsoft.ML.ModelBuilder.Utils.Logger.Debug)
2021-09-23 11:31:50.3567 DEBUG AutoMLType: Octopus (Microsoft.ML.ModelBuilder.Utils.Logger.Debug)
2021-09-23 11:31:50.3745 DEBUG Object reference not set to an instance of an object.
   at Microsoft.ML.ModelBuilder.AutoMLEngine.<StartTrainingAsync>d__21.MoveNext() in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/AutoMLEngineService/AutoMLEngine.cs:line 121   at StreamJsonRpc.JsonRpc.<InvokeCoreAsync>d__139`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.ML.ModelBuilder.ViewModels.TrainViewModel.<<StartTrainingAsync>b__109_0>d.MoveNext() (Microsoft.ML.ModelBuilder.Utils.Logger.Debug)
2021-09-23 11:32:23.0555 DEBUG AutoMLType: Octopus (Microsoft.ML.ModelBuilder.Utils.Logger.Debug)
2021-09-23 11:32:23.0710 DEBUG Object reference not set to an instance of an object.
   at Microsoft.ML.ModelBuilder.AutoMLEngine.<StartTrainingAsync>d__21.MoveNext() in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/AutoMLEngineService/AutoMLEngine.cs:line 121   at StreamJsonRpc.JsonRpc.<InvokeCoreAsync>d__139`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.ML.ModelBuilder.ViewModels.TrainViewModel.<<StartTrainingAsync>b__109_0>d.MoveNext() (Microsoft.ML.ModelBuilder.Utils.Logger.Debug)

**Comment by beccamc** [comment]
Thanks for reporting! I'll take a look.

**Comment by beccamc** [comment]
@AmritanshuAVerma It looks like there is a problem with your DataSource. Can you save your model builder file and open it in notepad? It should look something like this...

```
  "DataSource": {
    "Type": "Folder",
    "Version": 1,
    "FolderPath": "C:\\Users\\...."
```
If it looks like that, can you re-open model builder and try to run again?  If that doesn't work, can you please upload your .mbconfig file here. Thanks!
