### ISSUE TITLE
Training time finished without any models trained.

### ISSUE THREAD

**Issue by KasperPi** [dotnet/machinelearning-modelbuilder#1817]
Greetings,
I'm new to using this tool as well as Machine Learning. I figured I would try out the ML.NET on some data I have. I did try searching for fragments of the error message I encountered online as well as here but could not find anything relevant.

The scenario data is a book synopsis and correctly identified corresponding genre codes. (Note: there may be some meaningless synopsis in the data set but these are far and few between) The goal is: based on a synopsis of a book, suggest genre codes for a cataloguer.

System Info:
ML.NET Model Builder 2019 Version: 16.7.6.2150501 
Visual Studio Version: Microsoft Visual Studio Professional 2019 Version 16.11.2

1. Right click on project
2. Go to Add->Machine Learning Model then click 'Add'
3. Select Data classification
4. Click Next step
5. Choose File
Data-set is a tsv file with three columns and over 5000 rows of data:
ID (ignore)
Synopsis (Feature / String)
Genre Code (Label / String) [Categorical selected]
6. Train for 10s or 60s.
7. Either way the following error shows up when the timer runs out:

 ```
  at Microsoft.ML.ModelBuilder.AutoMLService.Experiments.LocalAutoMLExperiment.<ExecuteAsync>d__15.MoveNext() in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/Experiments/LocalAutoMLExperiment.cs:line 171
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ML.ModelBuilder.AutoMLEngine.<StartTrainingAsync>d__21.MoveNext() in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/AutoMLEngineService/AutoMLEngine.cs:line 163   at StreamJsonRpc.JsonRpc.<InvokeCoreAsync>d__139`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.ML.ModelBuilder.ViewModels.TrainViewModel.<<StartTrainingAsync>b__109_0>d.MoveNext()
```

Questions:
What does this error message mean?
Am I doing something incorrectly? 
Should I be using a different Scenario?
Note the data-set may have multiple identical synopsis that match to different genre codes (eg synopsis A -> 'Mysteries and crime stories' and another row has synopsis A -> 'Spy stories')

**Comment by JakeRadMSFT** [comment]
@KasperPi can you share the dataset you're trying to use?

**Comment by beccamc** [comment]
Sorry @KasperPi we don't have enough info to investigate... 

It sounds like you have chosen the correct scenario (data classification; label to predict is genre). I would increase the runtime to several minutes and see if it succeeds. 

If you upload or link your dataset we can take a look. Ping me and we can reopen this issue. Thanks!
