### ISSUE TITLE
Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by fredrick72** [dotnet/machinelearning-modelbuilder#1838]
**System Information (please complete the following information):**
 - Model Builder Version (available in Manage Extensions dialog): 16.7.6.2150501
 - Visual Studio Version 16.11.3

**Describe the bug**
- On which step of the process did you run into an issue: Code Generation
- Clear description of the problem: After model training i get the exception just as the code behind is about to be created.

**To Reproduce**
1. Go to scenario value prediction
2. Load CSV dataset
3. Train model

**Expected behavior**
the system should have built the code behind to consume the trained model. 

**Screenshots**
Object reference not set to an instance of an object.

 at Microsoft.ML.ModelBuilder.AutoMLService.ServiceFactory.CodeGeneratorService.<>c__DisplayClass8_0.<GetColumns>b__1(Column col) in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/ServiceFactory/CodeGeneratorService.cs:line 205
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at Microsoft.ML.ModelBuilder.CodeGenerator.Template.CSharp.ModelInput.TransformText() in /_/src/Microsoft.ML.ModelBuilder.CodeGenerator/Template/CSharp/ModelInput.cs:line 47
   at Microsoft.ML.ModelBuilder.CodeGenerator.ConsumptionGenerator..ctor(Option option) in /_/src/Microsoft.ML.ModelBuilder.CodeGenerator/CSharp/ConsumptionGenerator.cs:line 39
   at Microsoft.ML.ModelBuilder.AutoMLService.ServiceFactory.CodeGeneratorService.GenerateConsumptionAsync(TrainingConfiguration configuration, Dictionary`2 sampleData, String nameSpace, String className, String modelPath, String pipeline, TargetType target, TaskType task, String[] labels, ColumnDataKind labelColumnDataKind, CancellationToken ct) in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/ServiceFactory/CodeGeneratorService.cs:line 84   at StreamJsonRpc.JsonRpc.<InvokeCoreAsync>d__139`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.ML.ModelBuilder.ViewModels.TrainViewModel.<GenerateCodeBehindFilesAsync>d__118.MoveNext()

   Value cannot be null.
Parameter name: source

at System.Linq.Enumerable.Where[TSource](IEnumerable`1 source, Func`2 predicate)
   at Microsoft.ML.ModelBuilder.ToolWindows.EvaluateViewModel.<CreateAsync>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ML.ModelBuilder.ToolWindows.ModelBuilderDataContext.<<-ctor>b__0_4>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ML.ModelBuilder.ToolWindows.ModelBuilderDataContext.<>c__DisplayClass1_0.<<RegisterTabUpdateHandler>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ML.ModelBuilder.Observable.ObservableModel.<ExecuteUpdateHandlerAsync>d__24.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ML.ModelBuilder.Observable.ObservableModel.<HandlePropertyUpdateAsync>d__28.MoveNext()

**Additional context**
see attached dataset 
[2745044.csv](https://github.com/dotnet/machinelearning-modelbuilder/files/7341267/2745044.csv)

**Comment by beccamc** [comment]
@vzhuqin Did you report both of these errors in another issue? I remember this month you had a bug where there were several errors coming up during code generation.

**Comment by beccamc** [comment]
Never mind! I found the issue I was thinking of and it's unrelated
