### ISSUE TITLE
Model Builder Error: "The method or operation is not implemented." during Azure training.

### ISSUE THREAD

**Issue by vzhuqin** [dotnet/machinelearning-modelbuilder#1841]
**System Information (please complete the following information):**
- Windows OS: Windows-10-Enterprise-21H1
- Microsoft Visual Studio Enterprise 2019: 16.11.5
- ML.Net Model Builder: 16.8.3.2151403 (Main Branch)

**Describe the bug**
- On which step of the process did you run into an issue: Azure training
- Clear description of the problem:

**To Reproduce**
1. Select Create a new project from the Visual Studio 2019 start window;
2. Choose the C# Console App (.NET Core) project template with .Net 5.0;
3. Add model builder by right click on the project;
4. Select Image classification or Object detection scenario and Set up Azure environment;
5. Click Start training, wait about 10s, prompt Model Builder Error: The method or operation is not implemented.

**Expected behavior**
No error during training.

**Screenshots**
![image](https://user-images.githubusercontent.com/81727020/137424410-c9eb739c-a123-4fc8-8c93-bb98d398e043.png)

**Additional context**
Error Message:
   at Microsoft.ML.ModelBuilder.AutoMLService.Experiments.ExperimentFactory.CreateOctopusExperiment(MLContext context, TrainingConfiguration config, AutoMLDependService services, PathConfiguration pathConfig) in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/Experiments/ExperimentFactory.cs:line 49
   at Microsoft.ML.ModelBuilder.AutoMLService.Experiments.ExperimentFactory.CreateExperiment(MLContext context, TrainingConfiguration config, AutoMLDependService services, PathConfiguration pathConfig) in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/Experiments/ExperimentFactory.cs:line 22
   at Microsoft.ML.ModelBuilder.AutoMLEngine.<StartTrainingAsync>d__21.MoveNext() in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/AutoMLEngineService/AutoMLEngine.cs:line 156   at StreamJsonRpc.JsonRpc.<InvokeCoreAsync>d__139`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.ML.ModelBuilder.ViewModels.TrainViewModel.<<StartTrainingAsync>b__109_0>d.MoveNext()

**Comment by beccamc** [comment]
No repro for me anymore, everything seems to be working.

**Comment by vzhuqin** [comment]
Not repro issue on latest main: 16.9.1.2155901
![image.png](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/ccc85ed3-7285-4227-b94b-7701e7f9af63)
![image.png](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/4ea466a0-c7db-4af9-97dd-47f78cc7b9f7)
