### ISSUE TITLE
Model Builder Error: can't find image in boxes after input the json file with image labeling.

### ISSUE THREAD

**Issue by vzhuqin** [dotnet/machinelearning-modelbuilder#1877]
**System Information (please complete the following information):**
 - Model Builder Version (available in Manage Extensions dialog): 16.9.1.2152703
 - Microsoft Visual Studio Enterprise 2019: 16.11.5

**Describe the bug**
- On which step of the process did you run into an issue: Object detection>Data page
- Clear description of the problem: after input the json file with image labeling, prompt Model Builder Error: can't find image in boxes, close the error dialog, can continue the next step and training completed.

**To Reproduce**
1. Select Create a new project from the Visual Studio 2019 start window;
2. Choose the C# Console App (.NET Core) project template with .Net 5.0;
3. Add model builder by right click on the project;
4. Select Object detection and Azure environment;
5. Input the Json file, prompt Model Builder Error: can't find image in boxes.

**Expected behavior**
No any error after input the data set.

**Screenshots**
![image](https://user-images.githubusercontent.com/81727020/139180837-1d1f5375-5ba3-4836-b606-6163135c173e.png)

**Error message:**
   at Microsoft.ML.ModelBuilder.ViewModels.ObjectDetectionDataPreviewViewModel..ctor(String imagePath, IEnumerable`1 tags, IEnumerable`1 boxes, Int32 imageMaxWidthAndHeight, Boolean isShowScore)
   at Microsoft.ML.ModelBuilder.ViewModels.ObjectDetectionDataViewModel.OnSelectedImageChange_SetPreviewViewModel()
   at Microsoft.ML.ModelBuilder.ViewModels.ObjectDetectionDataViewModel.<<-ctor>b__0_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ML.ModelBuilder.Observable.ObservableModel.<ExecuteUpdateHandlerAsync>d__24.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ML.ModelBuilder.Observable.ObservableModel.<HandlePropertyUpdateAsync>d__28.MoveNext()

**Comment by beccamc** [comment]
Problem happens when switching between datasets. This is low priority, adding to Data page p1/p2 bugs and then closing.
