### ISSUE TITLE
Image Classification: Model Builder Error - Value cannot be null. Parameter name: path

### ISSUE THREAD

**Issue by sahgilbert** [dotnet/machinelearning-modelbuilder#1886]
**System Information (please complete the following information):**
 - Model Builder Version: ML.Net Model Builder 2019 Version 16.7.6.2150501
 - Visual Studio Version: VS Community 2019 Version 16.11.5

**Describe the bug**
- Training stops after a few minutes, followed by a popup dialog box error message.
- The error message is pasted further down the page.

**To Reproduce**
1. Create new Console Application.
2. Add new Machine Learning Model.
3. Scenario: Choose Image Classification.
4. Environment: Choose to run training locally, via CPU.
5. Data: A folder that contains 2 sub-folders (sub-folder 1 is 6 photos of dogs, sub-folder 2 is 6 photos of cats).
6. Train: Click start.

**Expected behavior**
Training completes without receiving an error message, regardless of the training accuracy results.

**Screenshots**
![Visual Studio Machine Learning Error 1](https://user-images.githubusercontent.com/13452745/139588874-cbc71185-c974-40db-8ba2-6cf7382d0862.PNG)

**Error Message**
  at System.IO.DirectoryInfo..ctor(String path)
   at Microsoft.ML.ModelBuilder.ViewModels.TrainViewModel.<SendTrainingCompletedTelemetryEventAsync>d__116.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.ML.ModelBuilder.ViewModels.TrainViewModel.<<StartTrainingAsync>b__109_0>d.MoveNext()

**Last Few Lines of Log File (it's extremely large)**
2021-10-31 14:33:53.1811 TRACE [Source=AutoML, Kind=Trace] [Source=SchemaBindableWrapper; Bind, Kind=Trace] Channel disposed (Microsoft.ML.ModelBuilder.Utils.Logger.Trace)
2021-10-31 14:33:53.2031 TRACE Saving Model... (Microsoft.ML.ModelBuilder.Utils.Logger.Trace)
2021-10-31 14:33:58.5339 TRACE [Source=AutoML, Kind=Trace] [Source=MulticlassPredictionTransformer; Saving train schema, Kind=Trace] Channel started (Microsoft.ML.ModelBuilder.Utils.Logger.Trace)
2021-10-31 14:33:58.5339 TRACE [Source=AutoML, Kind=Trace] [Source=BinarySaver; Saving, Kind=Trace] Channel started (Microsoft.ML.ModelBuilder.Utils.Logger.Trace)
2021-10-31 14:33:58.5339 TRACE [Source=AutoML, Kind=Trace] [Source=EmptyDataView; Cursor, Kind=Trace] Channel started (Microsoft.ML.ModelBuilder.Utils.Logger.Trace)
2021-10-31 14:33:58.5339 TRACE [Source=AutoML, Kind=Trace] [Source=EmptyDataView; Cursor, Kind=Trace] Channel finished. Elapsed 00:00:00.0002421. (Microsoft.ML.ModelBuilder.Utils.Logger.Trace)
2021-10-31 14:33:58.5339 TRACE [Source=AutoML, Kind=Trace] [Source=EmptyDataView; Cursor, Kind=Trace] Channel disposed (Microsoft.ML.ModelBuilder.Utils.Logger.Trace)
2021-10-31 14:33:58.5339 TRACE [Source=AutoML, Kind=Trace] [Source=EmptyDataView; Cursor, Kind=Trace] Channel started (Microsoft.ML.ModelBuilder.Utils.Logger.Trace)
2021-10-31 14:33:58.5339 TRACE [Source=AutoML, Kind=Trace] [Source=BinarySaver; Write, Kind=Trace] Channel started (Microsoft.ML.ModelBuilder.Utils.Logger.Trace)
2021-10-31 14:33:58.5339 TRACE [Source=AutoML, Kind=Trace] [Source=EmptyDataView; Cursor, Kind=Trace] Channel finished. Elapsed 00:00:00.0001616. (Microsoft.ML.ModelBuilder.Utils.Logger.Trace)
2021-10-31 14:33:58.5339 TRACE [Source=AutoML, Kind=Trace] [Source=EmptyDataView; Cursor, Kind=Trace] Channel disposed (Microsoft.ML.ModelBuilder.Utils.Logger.Trace)
2021-10-31 14:33:58.5502 TRACE [Source=AutoML, Kind=Trace] [Source=BinarySaver; Write, Kind=Trace] Channel finished. Elapsed 00:00:00.0148455. (Microsoft.ML.ModelBuilder.Utils.Logger.Trace)
2021-10-31 14:33:58.5502 TRACE [Source=AutoML, Kind=Trace] [Source=BinarySaver; Write, Kind=Trace] Channel disposed (Microsoft.ML.ModelBuilder.Utils.Logger.Trace)
2021-10-31 14:33:58.5502 TRACE [Source=AutoML, Kind=Trace] [Source=BinarySaver; Saving, Kind=Trace] Channel finished. Elapsed 00:00:00.0166453. (Microsoft.ML.ModelBuilder.Utils.Logger.Trace)
2021-10-31 14:33:58.5502 TRACE [Source=AutoML, Kind=Trace] [Source=BinarySaver; Saving, Kind=Trace] Channel disposed (Microsoft.ML.ModelBuilder.Utils.Logger.Trace)
2021-10-31 14:33:58.5502 TRACE [Source=AutoML, Kind=Trace] [Source=MulticlassPredictionTransformer; Saving train schema, Kind=Trace] Channel finished. Elapsed 00:00:00.0169561. (Microsoft.ML.ModelBuilder.Utils.Logger.Trace)
2021-10-31 14:33:58.5502 TRACE [Source=AutoML, Kind=Trace] [Source=MulticlassPredictionTransformer; Saving train schema, Kind=Trace] Channel disposed (Microsoft.ML.ModelBuilder.Utils.Logger.Trace)
2021-10-31 14:33:58.5502 TRACE [Source=Saving Schema, Kind=Trace] Channel started (Microsoft.ML.ModelBuilder.Utils.Logger.Trace)
2021-10-31 14:33:58.5502 TRACE [Source=BinarySaver; Saving, Kind=Trace] Channel started (Microsoft.ML.ModelBuilder.Utils.Logger.Trace)
2021-10-31 14:33:58.5502 TRACE [Source=EmptyDataView; Cursor, Kind=Trace] Channel started (Microsoft.ML.ModelBuilder.Utils.Logger.Trace)
2021-10-31 14:33:58.5502 TRACE [Source=EmptyDataView; Cursor, Kind=Trace] Channel finished. Elapsed 00:00:00.0000577. (Microsoft.ML.ModelBuilder.Utils.Logger.Trace)
2021-10-31 14:33:58.5502 TRACE [Source=EmptyDataView; Cursor, Kind=Trace] Channel disposed (Microsoft.ML.ModelBuilder.Utils.Logger.Trace)
2021-10-31 14:33:58.5502 TRACE [Source=EmptyDataView; Cursor, Kind=Trace] Channel started (Microsoft.ML.ModelBuilder.Utils.Logger.Trace)
2021-10-31 14:33:58.5502 TRACE [Source=BinarySaver; Write, Kind=Trace] Channel started (Microsoft.ML.ModelBuilder.Utils.Logger.Trace)
2021-10-31 14:33:58.5502 TRACE [Source=EmptyDataView; Cursor, Kind=Trace] Channel finished. Elapsed 00:00:00.0001295. (Microsoft.ML.ModelBuilder.Utils.Logger.Trace)
2021-10-31 14:33:58.5562 TRACE [Source=EmptyDataView; Cursor, Kind=Trace] Channel disposed (Microsoft.ML.ModelBuilder.Utils.Logger.Trace)
2021-10-31 14:33:58.5562 TRACE [Source=BinarySaver; Write, Kind=Trace] Channel finished. Elapsed 00:00:00.0077158. (Microsoft.ML.ModelBuilder.Utils.Logger.Trace)
2021-10-31 14:33:58.5562 TRACE [Source=BinarySaver; Write, Kind=Trace] Channel disposed (Microsoft.ML.ModelBuilder.Utils.Logger.Trace)
2021-10-31 14:33:58.5562 TRACE [Source=BinarySaver; Saving, Kind=Trace] Channel finished. Elapsed 00:00:00.0081209. (Microsoft.ML.ModelBuilder.Utils.Logger.Trace)
2021-10-31 14:33:58.5562 TRACE [Source=BinarySaver; Saving, Kind=Trace] Channel disposed (Microsoft.ML.ModelBuilder.Utils.Logger.Trace)
2021-10-31 14:33:58.5562 TRACE [Source=Saving Schema, Kind=Trace] Channel finished. Elapsed 00:00:00.0090928. (Microsoft.ML.ModelBuilder.Utils.Logger.Trace)
2021-10-31 14:33:58.5562 TRACE [Source=Saving Schema, Kind=Trace] Channel disposed (Microsoft.ML.ModelBuilder.Utils.Logger.Trace)
2021-10-31 14:33:58.5943 DEBUG Value cannot be null.
Parameter name: path
   at System.IO.DirectoryInfo..ctor(String path)
   at Microsoft.ML.ModelBuilder.ViewModels.TrainViewModel.<SendTrainingCompletedTelemetryEventAsync>d__116.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.ML.ModelBuilder.ViewModels.TrainViewModel.<<StartTrainingAsync>b__109_0>d.MoveNext() (Microsoft.ML.ModelBuilder.Utils.Logger.Debug)

**Comment by pierre01** [comment]
I have the exact same  issue.

VS Studio 2022 - ML.NET Builder GPU 2022  16.7.6.2152701

I can't send the full log as it occurs at the end of the training with 34,000 images

The logs ends like this:

2021-11-01 16:58:40.1490 DEBUG Value cannot be null.
Parameter name: path
   at System.IO.DirectoryInfo..ctor(String path)
   at Microsoft.ML.ModelBuilder.ViewModels.TrainViewModel.<SendTrainingCompletedTelemetryEventAsync>d__116.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ML.ModelBuilder.ViewModels.TrainViewModel.<<StartTrainingAsync>b__109_0>d.MoveNext() (Microsoft.ML.ModelBuilder.Utils.Logger.Debug)

Visual studio Model output shows:

===============================================Experiment Results=================================================
------------------------------------------------------------------------------------------------------------------
|                                                     Summary                                                    |
------------------------------------------------------------------------------------------------------------------
|ML Task: ImageClassification                                                                                    |
|Dataset:                                                                                                        |
|Label : Label                                                                                                   |
|Total experiment time : 3765.7146917 Secs                                                                       |
|Total number of models explored: 1                                                                              |
------------------------------------------------------------------------------------------------------------------

|                                              Top 1 models explored                                             |
------------------------------------------------------------------------------------------------------------------
|     Trainer                              MicroAccuracy  MacroAccuracy  Duration #Iteration                     |
|1    ImageClassification                         0.9797         0.5426    3765.7          1                     |
------------------------------------------------------------------------------------------------------------------

The ZIP Model file is created.

**Comment by pierre01** [comment]
Although the Model is created and the experiment ended,
I am unable to go to the next step, because it is showing as failed,
I am able to open the Generated Model with Netron

**Comment by LittleLittleCloud** [comment]
Looks like the same issue with https://github.com/dotnet/machinelearning-modelbuilder/issues/1751#issuecomment-948794309

One solution can be check your .mbconfig file and make sure folder path is there, then start a new training with the same config. In the meanwhile, we will fix this in next release.

Thanks for reporting!

**Comment by LittleLittleCloud** [comment]
Looks like the error has already been fixed by @beccamc

**Comment by vzhuqin** [comment]
Not repro this issue on latest main: 16.9.1.2155301
![image.png](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/5b8e062b-fc0e-4a1c-9a4d-f085d5ab45cd)

**Comment by beccamc** [comment]
Yes, that error should be mitigated with PR 1298 (added try/catch around telemetry call). I don't know why Folder Path is empty for some customers at that point... it shouldn't be since we just trained with that info. 

If anyone has more details about when this happens (e.g. only on reload, only with GPU, etc.) that would be really helpful!

**Comment by sahgilbert** [comment]
Hello, I was able to reproduce the same folder path error today using the latest versions of Visual Studio 2022 and the Model Builder extension using a .Net 6.0 Console App and choosing "Image Classification".

- Windows 10.
- Microsoft Visual Studio Community 2022 Version 17.0.0.
- (VisualStudio.17.Release/17.0.0+31903.59).
- .NET Runtime 6.0.0.
- ML.Net Model Builder 2022 Version 16.7.6.2152701.

Please see [this source code repository](https://github.com/sahgilbert/DotNetSixConsoleApp) which was used to reproduce the Folder Path null error.

Thank you

**Comment by sahgilbert** [comment]
I've just moved the images folder from being at the solution level, to being at the project level, and started training again.

The result was a successful training completion of image classification.

I've updated the [source code repository I mentioned](https://github.com/sahgilbert/DotNetSixConsoleApp) with the folder change.

Thank you.

**Comment by beccamc** [comment]
Thank you for this Simon. The issue is that FolderPath is empty in the .mbconfig file!

![image](https://user-images.githubusercontent.com/9122518/141492507-dfa264c1-a8fb-42d6-8907-a2a736f07ace.png)

This means somehow we're setting your training parameters without saving the folder path (or erasing it at some point).  I need to dig through the code. Thank you again for the repro project!

**Comment by sahgilbert** [comment]
Understood, thanks for taking a look, it's much appreciated!

**Comment by beccamc** [comment]
@LittleLittleCloud Thoughts on this one? I think we're somehow resetting FolderPath after the .tsv training files have been generated. 

I tried a few things to set the path to null/empty. None worked. 
1. Delete the folder path from the text box in the data page
2. Open the folder path picker and don't select anything; try to select something invalid 
3. I considered it could be some failure to write the value to the json, but then we shouldn't see this problem on first training because the FolderPath value in Model Builder would be available. 

@sahgilbert Did you do anything memorable on the data page, especially after training had started? Did the data preview disappear at any point?

**Comment by sahgilbert** [comment]
@beccamc I've just created a fresh console app and started from the beginning, resulting in a successful completion of training. Unfortunately this isn't particularly helpful as it's difficult to assess why this time it completed training successfully, as oppose to the previous failures.

I've documented the exact steps I took below. I purposely did not navigate around any more than I needed to.

## Steps Taken

1. Right-click on project and select Machine Learning from "Add" menu.
2. Add ImageClassification.mbconfig.
3. **Scenario Page:** Choose "Image Classification".
4. **Environment Page:** Choose "Local (CPU)", click "Next step".
5. **Data Page:** Navigate to Solution folder > Project folder > TrainingImages folder. Folder input text box says "TrainingImages" as per the folders name within this project. Click "Select Folder".
6. Still on the **data page**, and all images are displayed in the "Data Preview" section. Worth noting that I do not click on anything on this page, and instead I just click "Next step"
7. **Train Page:** Click "Start Training".
8. Training begins and at this point it is worth noting that the .mbconfig file only contains the following code:
```json
{
  "TrainingConfigurationVersion": 0
}
```
9. Training completed successfully.
10. All files are generated including the trained model.

**Comment by beccamc** [comment]
Thanks! At this point I'm thinking race condition. Really appreciate the help and extra info here.
