### ISSUE TITLE
Model Builder Error "Could not find input column 'ImageSource' Parameter name: inputSchema" when adding WebAPI project to solution.

### ISSUE THREAD

**Issue by vzhuqin** [dotnet/machinelearning-modelbuilder#1887]
**System Information (please complete the following information):**
 - Model Builder Version (available in Manage Extensions dialog): 16.9.1.2152802
 - Microsoft Visual Studio Enterprise 2019: 16.11.5

**Describe the bug**
- On which step of the process did you run into an issue: Object detection>Consume page: Add WebAPI project to solution

**To Reproduce**
1. Select Create a new project from the Visual Studio 2019 start window;
2. Choose the C# Console App (.NET Core) project template with .Net 5.0;
3. Add model builder by right click on the project;
4. Select Object detection to complete training;
5. Navigate to Consume page, add WebAPI to solution, prompt Model Builder Error "Could not find input column 'ImageSource' Parameter name: inputSchema".

**Expected behavior**
No Error when adding projects to solution.

**Screenshots**
![image](https://user-images.githubusercontent.com/81727020/139633655-187b8d90-c664-42e0-9b15-381c0a7411f2.png)

**Error message**
   at Microsoft.ML.Data.OneToOneTransformerBase.CheckInput(DataViewSchema inputSchema, Int32 col, Int32& srcCol)
   at Microsoft.ML.Data.OneToOneTransformerBase.OneToOneMapperBase..ctor(IHost host, OneToOneTransformerBase parent, DataViewSchema inputSchema)
   at Microsoft.ML.Transforms.Image.ImageResizingTransformer.Mapper..ctor(ImageResizingTransformer parent, DataViewSchema inputSchema)
   at Microsoft.ML.Transforms.Image.ImageResizingTransformer.MakeRowMapper(DataViewSchema schema)
   at Microsoft.ML.Data.RowToRowTransformerBase.GetOutputSchema(DataViewSchema inputSchema)
   at Microsoft.ML.Data.TransformerChain`1.GetOutputSchema(DataViewSchema inputSchema)
   at Microsoft.ML.ModelBuilder.AutoMLService.ServiceFactory.CodeGeneratorService.CreateWebApiProjectCodesAsync(TrainingConfiguration configuration, Dictionary`2 sampleData, String sampleProjectName, String modelpath, String modelFileName, String className, ColumnDataKind labelColumnDataKind, String targetFramework, String[] labels, String pipeline, Boolean isAzureArtifact, Boolean isDEV17, CancellationToken ct) in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/ServiceFactory/CodeGeneratorService.cs:line 150   at StreamJsonRpc.JsonRpc.<InvokeCoreAsync>d__139`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.ML.ModelBuilder.ToolWindows.ConsumeViewModel.<AddProjectToSolutionAsync>d__77.MoveNext()

**Comment by vzhuqin** [comment]
This issue happens on Azure environment ( Image classification and Object detection),  and also see the error when predicting the model on Evaluate page of Image classification>Azure.
![image](https://user-images.githubusercontent.com/81727020/139637959-8cc26242-d3ca-44cc-b5ea-c5c1dff93c46.png)

**Comment by LittleLittleCloud** [comment]
The code gen is broken for all image scenarios, I'll fix that.

**Comment by vzhuqin** [comment]
@LittleLittleCloud this error still happens when trying the model on Evaluate page (Image classification + Azure). 
- ML.Net Model Builder: 16.9.1.2155801 ( Latest Main)
![image.png](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/5b23d3ad-f02e-4bc6-ba6f-4ebca47a2171)

Not happens when adding WebAPI project to solution.

**Comment by vzhuqin** [comment]
not repro this issue on latest main: 16.9.1.2156701
![image.png](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/9dcd304d-5a65-43e1-9048-b73e1513f5fc)
