### ISSUE TITLE
Top customer errors from 16.7.6.0

### ISSUE THREAD

**Issue by beccamc** [dotnet/machinelearning-modelbuilder#1900]
- [x] Value cannot be null. Parameter name: source at **EvaluateTabContext Update Handler**
at System.Linq.Enumerable.Where[TSource](IEnumerable`1 source, Func`2 predicate)
   at Microsoft.ML.ModelBuilder.ToolWindows.EvaluateViewModel.<CreateAsync>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ML.ModelBuilder.ToolWindows.ModelBuilderDataContext.<<-ctor>b__0_4>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ML.ModelBuilder.ToolWindows.ModelBuilderDataContext.<>c__DisplayClass1_0.<<RegisterTabUpdateHandler>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System...

**^ https://github.com/dotnet/machinelearning-tools/pull/1325**

- [x] Object reference not set to an instance of an object. at **GPUEnvironmentFailed**
at Microsoft.ML.ModelBuilder.ViewModels.EnvironmentViewModel.<CheckGPUCompatibilityAsync>d__86.MoveNext()

**^ Above exception in telemetry is expected. It's what's logged when there are failures setting up GPU. Reported to users in the GPU error area.**

- [ ] Index was outside the bounds of the array.at **StartTraining**
at Microsoft.ML.ModelBuilder.AutoMLService.Proposer.PipelineProposer.Propose(TrialParameter trialParameter) in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/Proposer/PipelineProposer.cs:line 99
   at Microsoft.ML.ModelBuilder.AutoMLService.Proposer.Controller.Propose() in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/Proposer/Controller.cs:line 60
   at Microsoft.ML.ModelBuilder.AutoMLService.Experiments.LocalAutoMLExperiment.<ExecuteAsync>d__15.MoveNext() in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/Experiments/LocalAutoMLExperiment.cs:line 137
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ML.ModelBuilder.AutoMLEngine.<StartTrainingAsync>d__21.MoveNext() in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/AutoMLEngineService/AutoMLEngine.cs:line 163   at StreamJsonRpc.JsonRpc.<I...

**^ Should be fixed by https://github.com/dotnet/machinelearning-modelbuilder/issues/1602.**

- [ ] Value cannot be null. Parameter name: project at **MoveNext**
at NuGet.VisualStudio.VsPackageInstallerServices.GetInstalledPackages(Project project)
   at Microsoft.ML.ModelBuilder.Utils.Utilities.<InstallNugetPackageAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ML.ModelBuilder.ViewModels.TrainViewModel.<UpdateNugetDependenciesAsync>d__119.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Microsoft.ML.ModelBuilder.ViewModels.TrainViewModel.<GenerateCodeBehindFilesAsync>d__118.MoveNext()

**^Added logging in https://github.com/dotnet/machinelearning-tools/pull/1325. It won't fix the problem, but we will now log the name of the problem project that wasn't found to our file. Next customer who reports should be able to give us the file for more info. Tracking https://github.com/dotnet/machinelearning-modelbuilder/issues/1903** 

- [x] Value cannot be null. Parameter name: path at **StartTraining**
at System.IO.DirectoryInfo..ctor(String path)
   at Microsoft.ML.ModelBuilder.ViewModels.TrainViewModel.<SendTrainingCompletedTelemetryEventAsync>d__116.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.ML.ModelBuilder.ViewModels.TrainViewModel.<<StartTrainingAsync>b__109_0>d.MoveNext()

**^ Above mitigated with https://github.com/dotnet/machinelearning-tools/pull/1298.  I'm not sure why the DataSource is empty in this case... customers are hitting it but I don't know how to get a repro.**

**Comment by beccamc** [comment]
Closing this. Can circle back after release is out for a few weeks.
