### ISSUE TITLE
 Value cannot be null. Parameter name: project

### ISSUE THREAD

**Issue by beccamc** [dotnet/machinelearning-modelbuilder#1903]
Problem happens after training completes. 

**Log file:** 
Updating nuget dependencies... (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2021-10-30 03:39:43.1003 INFO Installing nuget package, package ID: Microsoft.ML, package Version: 1.6.0 (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2021-10-30 03:39:43.1003 DEBUG Value cannot be null.
Parameter name: project
   at NuGet.VisualStudio.VsPackageInstallerServices.GetInstalledPackages(Project project)
   at Microsoft.ML.ModelBuilder.Utils.Utilities.<InstallNugetPackageAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.ML.ModelBuilder.ViewModels.TrainViewModel.<UpdateNugetDependenciesAsync>d__119.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Microsoft.ML.ModelBuilder.ViewModels.TrainViewModel.<GenerateCodeBehindFilesAsync>d__118.MoveNext() (Microsoft.ML.ModelBuilder.Utils.Logger.Debug)

**Comment by beccamc** [comment]
Root cause is that the Project we're trying to use to update the NuGets doesn't exist. I've added some additional logging (will come out in November release). If anyone runs into this problem please let me know we can gather some more info about your project!

**Comment by 21r8390** [comment]
Hello @beccamc,
As a side note about me, ML and ML Builder is brand new. This is the first time I am using it.
With that said let's get to my problem. After the training is finished I get the error message: `Value cannot be null.` `Parameter name: project`. This error occurred everytime I tried.

The error message said that it had to do with a NuGet package, which is why I installed Microsoft.ML, Microsoft.ML.AutoML & Microsoft.ML.ImageAnalytics additionally by hand. However, the same error message keeps popping up.

The project and the images used are only there for testing, so I would be happy to share my project.

---

<details>
    <summary>Model Info</summary>

## Model Info
- Scenario: Image Classification
- Environment: 
    - Local (CPU)
    - Intel Core i7-10510U CPU @ 1.80GHz
    - Memory 16 GB

- Data: 3 folders with each 16 PNG-images

</details>

<details>
    <summary>Training result</summary>

## Training result
Best accuracy: 100.00%
Best model: DDN + ResNet50
Training time: 193.40 seconds
Models explored (total): 1
Generated code-behind (MLtesting is the filename): MLtesting.consumption.cs, MLtesting.training.cs

</details>

<details>
    <summary>VS Error Window</summary>

## VS Error Window:
```markdown
   at NuGet.VisualStudio.VsPackageInstallerServices.GetInstalledPackages(Project project)
   at Microsoft.ML.ModelBuilder.Utils.Utilities.<InstallNugetPackageAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.ML.ModelBuilder.ViewModels.TrainViewModel.<UpdateNugetDependenciesAsync>d__119.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Microsoft.ML.ModelBuilder.ViewModels.TrainViewModel.<GenerateCodeBehindFilesAsync>d__118.MoveNext()
```
</details>

<details>
    <summary>Log file</summary>

## Log file
```markdown
2022-01-23 18:28:16.9187 INFO Set log file path to C:\Users\username\AppData\Local\Temp\MLVSTools\logs\MLTesting-K4JAV4.txt (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2022-01-23 18:28:24.4074 DEBUG Object reference not set to an instance of an object.
   at Microsoft.ML.ModelBuilder.Observable.ObservableModel.<ExecuteUpdateHandlerAsync>d__24.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ML.ModelBuilder.Observable.ObservableModel.<HandlePropertyUpdateAsync>d__28.MoveNext() (Microsoft.ML.ModelBuilder.Utils.Logger.Debug)
2022-01-23 18:29:00.6979 DEBUG AutoMLType: Octopus (Microsoft.ML.ModelBuilder.Utils.Logger.Debug)

2022-01-23 18:29:00.6979 TRACE [Source=TextLoader; Binding, Kind=Trace] Channel started (Microsoft.ML.ModelBuilder.ViewModels.TrainViewModel.AutoMLService_DiagnosticDataReceived)

=> // I left this part out because it's just stack trace....

===============================================Experiment Results=================================================
------------------------------------------------------------------------------------------------------------------
|                                                     Summary                                                    |
------------------------------------------------------------------------------------------------------------------
|ML Task: ImageClassification                                                                                    |
|Dataset:                                                                                                        |
|Label : Label                                                                                                   |
|Total experiment time : 193.4416412 Secs                                                                        |
|Total number of models explored: 1                                                                              |
------------------------------------------------------------------------------------------------------------------
 (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2022-01-23 18:32:14.2134 INFO |                                              Top 1 models explored                                             |
------------------------------------------------------------------------------------------------------------------
|     Trainer                              MicroAccuracy  MacroAccuracy  Duration #Iteration                     |
|1    ImageClassification                         1.0000         1.0000     193.4          1                     |
------------------------------------------------------------------------------------------------------------------
 (Microsoft.ML.ModelBuilder.Utils.Logger.Info)

=> // I left this part out because it's just stack trace....

Updating nuget dependencies... (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2022-01-23 18:32:22.4499 INFO Installing nuget package, package ID: Microsoft.ML, package Version: 1.6.0 (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2022-01-23 18:32:22.4499 DEBUG Value cannot be null.
Parameter name: project
   at NuGet.VisualStudio.VsPackageInstallerServices.GetInstalledPackages(Project project)
   at Microsoft.ML.ModelBuilder.Utils.Utilities.<InstallNugetPackageAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.ML.ModelBuilder.ViewModels.TrainViewModel.<UpdateNugetDependenciesAsync>d__119.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Microsoft.ML.ModelBuilder.ViewModels.TrainViewModel.<GenerateCodeBehindFilesAsync>d__118.MoveNext() (Microsoft.ML.ModelBuilder.Utils.Logger.Debug)
```

</details>

**Comment by beccamc** [comment]
@21r8390 Sorry for the delay here. Is one of the projects in your solution unloaded?

**Comment by 21r8390** [comment]
I haven't written back for a while because I was still testing. It's super fun! ☺

There were some updates, which I have not followed closely. I do not know why, but this error no longer occurs.
