### ISSUE TITLE
Training; Read only 0 bytes in file, expected header size of 256

### ISSUE THREAD

**Issue by blahblehblah** [dotnet/machinelearning-modelbuilder#1916]
**System Information (please complete the following information):**
 - Model Builder Version  16.7.6.2152701
 - VS 2022 17.1.0 Preview 1.0

**Describe the bug**
- Using model builder for a value prediction 

Sample Data: Label (Won)
Symbol	Speed	Above70	OffsetSpeed	Offset	Offset2	Offset3	Offset4	Offset5	Offset6	Height	Max	Low	Won
Shark	73.67	TRUE	78.81	0.001266298	0.001400573	0.000906639	0.001073805	0.000359659	0.000326768	Short	5.06605	-0.8052	True 
PN	71.33	TRUE	59.16	0.031982341	0.032521557	0.01273333	0.016690975	0.019249011	0.015830582	Long	5.1333	-2.3618	True 
KING	20.12	FALSE	9.16	-0.109006572	-0.191450055	-0.074476465	-0.161157437	-0.034530107	-0.030292618	Long	5.2578	0	True 
Lowa	73.66	TRUE	68.75	0.008844278	0.009287541	0.00681637	0.007310604	0.002027909	0.001976937	Short	5.1993	-3.0411	True 
Airport	76.05	TRUE	69.87	0.003620095	0.004400298	0.003043191	0.00362233	0.000576903	0.000777968	Short	6.4024	-0.5738	True 
Ninja	72.28	TRUE	67.41	4.81648E-05	6.17632E-05	4.23785E-05	5.26293E-05	5.7862E-06	9.1339E-06	Short	5.37838	-1.3118	True 

Console Logs:

Set log file path to C:\Users\SQ\AppData\Local\Temp\MLVSTools\logs\MLModel1-5NJ6ZT.txt
start nni training
Experiment output folder: C:\Users\SQ\AppData\Local\Temp\AutoML-NNI\Experiment-MRD7SI
|     Trainer                             RSquared Absolute-loss Squared-loss RMS-loss  Duration #Iteration      |
Trial 0 encounter error with message: Read only 0 bytes in file, expected header size of 256

Log file: 
2021-11-14 22:34:59.6691 INFO Set log file path to C:\Users\SQ\AppData\Local\Temp\MLVSTools\logs\MLModel1-5NJ6ZT.txt (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2021-11-14 22:35:24.9975 DEBUG AutoMLType: Octopus (Microsoft.ML.ModelBuilder.Utils.Logger.Debug)
2021-11-14 22:35:25.0884 TRACE [Source=TextLoader; Binding, Kind=Trace] Channel started (Microsoft.ML.ModelBuilder.ViewModels.TrainViewModel.AutoMLService_DiagnosticDataReceived)
2021-11-14 22:35:25.1104 TRACE [Source=TextLoader; Binding, Kind=Trace] Channel finished. Elapsed 00:00:00.0231751. (Microsoft.ML.ModelBuilder.ViewModels.TrainViewModel.AutoMLService_DiagnosticDataReceived)
2021-11-14 22:35:25.1104 TRACE [Source=TextLoader; Binding, Kind=Trace] Channel disposed (Microsoft.ML.ModelBuilder.ViewModels.TrainViewModel.AutoMLService_DiagnosticDataReceived)
2021-11-14 22:35:25.2833 INFO start nni training (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2021-11-14 22:35:25.3003 INFO Experiment output folder: C:\Users\SQ\AppData\Local\Temp\AutoML-NNI\Experiment-MRD7SI (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2021-11-14 22:35:25.3003 DEBUG row count is unknown, count it explicitly (Microsoft.ML.ModelBuilder.Utils.Logger.Debug)
2021-11-14 22:35:25.3003 TRACE [Source=TextLoader; ParseStats, Kind=Trace] Channel started (Microsoft.ML.ModelBuilder.ViewModels.TrainViewModel.AutoMLService_DiagnosticDataReceived)
2021-11-14 22:35:25.3003 TRACE [Source=TextLoader; Cursor, Kind=Trace] Channel started (Microsoft.ML.ModelBuilder.ViewModels.TrainViewModel.AutoMLService_DiagnosticDataReceived)
2021-11-14 22:35:25.3562 TRACE [Source=TextLoader; ParseStats, Kind=Trace] Channel finished. Elapsed 00:00:00.0495542. (Microsoft.ML.ModelBuilder.ViewModels.TrainViewModel.AutoMLService_DiagnosticDataReceived)
2021-11-14 22:35:25.3562 TRACE [Source=TextLoader; ParseStats, Kind=Trace] Channel disposed (Microsoft.ML.ModelBuilder.ViewModels.TrainViewModel.AutoMLService_DiagnosticDataReceived)
2021-11-14 22:35:25.3562 TRACE [Source=TextLoader; Cursor, Kind=Trace] Channel finished. Elapsed 00:00:00.0479777. (Microsoft.ML.ModelBuilder.ViewModels.TrainViewModel.AutoMLService_DiagnosticDataReceived)
2021-11-14 22:35:25.3562 TRACE [Source=TextLoader; Cursor, Kind=Trace] Channel disposed (Microsoft.ML.ModelBuilder.ViewModels.TrainViewModel.AutoMLService_DiagnosticDataReceived)
2021-11-14 22:35:25.3562 DEBUG count elapse 55ms (Microsoft.ML.ModelBuilder.Utils.Logger.Debug)
2021-11-14 22:35:25.3562 INFO |     Trainer                             RSquared Absolute-loss Squared-loss RMS-loss  Duration #Iteration      | (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2021-11-14 22:35:25.6031 DEBUG select pipeline e0 * e1 * e2 * e3 * e5 (Microsoft.ML.ModelBuilder.Utils.Logger.Debug)
2021-11-14 22:35:25.6261 DEBUG 4$NumberOfTrees:4,4$FeatureFraction:1 (Microsoft.ML.ModelBuilder.Utils.Logger.Debug)
2021-11-14 22:35:25.6401 DEBUG update train dataset C:\Users\SQ\AppData\Local\Temp\AutoML-NNI\Experiment-MRD7SI\cv.bin (Microsoft.ML.ModelBuilder.Utils.Logger.Debug)
2021-11-14 22:35:25.6671 INFO Trial 0 encounter error with message: Read only 0 bytes in file, expected header size of 256 (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2021-11-14 22:35:25.7380 DEBUG    at Microsoft.ML.Data.IO.BinaryLoader.InitHeader()
   at Microsoft.ML.Data.IO.BinaryLoader..ctor(Arguments args, IHost host, Stream stream, Boolean leaveOpen)
   at Microsoft.ML.BinaryLoaderSaverCatalog.LoadFromBinary(DataOperationsCatalog catalog, String path)
   at Microsoft.ML.ModelBuilder.AutoMLService.LocalDispatcher.Run() in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/Dispatcher/LocalDispatcher.cs:line 113
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ML.ModelBuilder.AutoMLService.LocalDispatcher.<RunAsync>d__19.MoveNext() in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/Dispatcher/LocalDispatcher.cs:line 151
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ML.ModelBuilder.AutoMLService.LocalDispatcher.<AddTrialAsync>d__16.MoveNext() in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/Dispatcher/LocalDispatcher.cs:line 49 (Microsoft.ML.ModelBuilder.Utils.Logger.Debug)
2021-11-14 22:35:25.7380 DEBUG create new thread 0 (Microsoft.ML.ModelBuilder.Utils.Logger.Debug)
2021-11-14 22:35:25.7630 DEBUG probability 0.149924251961547,0.0124884049202641,0.309267828653661,0.294614240762341,0.0249768098405283,0.208728463861658 (Microsoft.ML.ModelBuilder.Utils.Logger.Debug)
2021-11-14 22:35:25.7630 DEBUG select pipeline e0 * e1 * e2 * e3 * e7 * e8 (Microsoft.ML.ModelBuilder.Utils.Logger.Debug)
2021-11-14 22:35:25.7630 DEBUG 5$NumberOfLeaves:4,5$MinimumExampleCountPerLeaf:20,5$LearningRate:0.1,5$NumberOfTrees:4,5$MaximumBinCountPerFeature:256,5$FeatureFraction:1 (Microsoft.ML.ModelBuilder.Utils.Logger.Debug)
2021-11-14 22:35:25.7630 DEBUG update train dataset C:\Users\SQ\AppData\Local\Temp\AutoML-NNI\Experiment-MRD7SI\cv.bin (Microsoft.ML.ModelBuilder.Utils.Logger.Debug)
2021-11-14 22:35:25.7630 INFO Trial 1 encounter error with message: Read only 0 bytes in file, expected header size of 256 (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2021-11-14 22:35:25.7630 DEBUG    at Microsoft.ML.Data.IO.BinaryLoader.InitHeader()
   at Microsoft.ML.Data.IO.BinaryLoader..ctor(Arguments args, IHost host, Stream stream, Boolean leaveOpen)
   at Microsoft.ML.BinaryLoaderSaverCatalog.LoadFromBinary(DataOperationsCatalog catalog, String path)
   at Microsoft.ML.ModelBuilder.AutoMLService.LocalDispatcher.Run() in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/Dispatcher/LocalDispatcher.cs:line 113
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ML.ModelBuilder.AutoMLService.LocalDispatcher.<RunAsync>d__19.MoveNext() in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/Dispatcher/LocalDispatcher.cs:line 151
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ML.ModelBuilder.AutoMLService.LocalDispatcher.<AddTrialAsync>d__16.MoveNext() in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/Dispatcher/LocalDispatcher.cs:line 49 (Microsoft.ML.ModelBuilder.Utils.Logger.Debug)
2021-11-14 22:35:25.7630 DEBUG create new thread 0 (Microsoft.ML.ModelBuilder.Utils.Logger.Debug)
2021-11-14 22:35:25.7630 DEBUG probability 0.210677262103834,0.0175490150674229,0.434590791983824,0.00877450753371146,0.0350980301348458,0.293310393176362 (Microsoft.ML.ModelBuilder.Utils.Logger.Debug)
2021-11-14 22:35:25.7790 DEBUG select pipeline e0 * e1 * e2 * e3 * e4 (Microsoft.ML.ModelBuilder.Utils.Logger.Debug)
2021-11-14 22:35:25.7790 DEBUG 4$NumberOfLeaves:4,4$MinimumExampleCountPerLeaf:20,4$LearningRate:0.1,4$NumberOfIterations:4,4$SubsampleFraction:1,4$MaximumBinCountPerFeature:256,4$FeatureFraction:1,4$L1Regularization:2E-10,4$L2Regularization:0.999999999999999 (Microsoft.ML.ModelBuilder.Utils.Logger.Debug)
2021-11-14 22:35:25.7790 DEBUG update train dataset C:\Users\SQ\AppData\Local\Temp\AutoML-NNI\Experiment-MRD7SI\cv.bin (Microsoft.ML.ModelBuilder.Utils.Logger.Debug)
2021-11-14 22:35:25.7790 INFO Trial 2 encounter error with message: Read only 0 bytes in file, expected header size of 256 (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2021-11-14 22:35:25.7790 DEBUG    at Microsoft.ML.Data.IO.BinaryLoader.InitHeader()
   at Microsoft.ML.Data.IO.BinaryLoader..ctor(Arguments args, IHost host, Stream stream, Boolean leaveOpen)
   at Microsoft.ML.BinaryLoaderSaverCatalog.LoadFromBinary(DataOperationsCatalog catalog, String path)
   at Microsoft.ML.ModelBuilder.AutoMLService.LocalDispatcher.Run() in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/Dispatcher/LocalDispatcher.cs:line 113
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ML.ModelBuilder.AutoMLService.LocalDispatcher.<RunAsync>d__19.MoveNext() in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/Dispatcher/LocalDispatcher.cs:line 151
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ML.ModelBuilder.AutoMLService.LocalDispatcher.<AddTrialAsync>d__16.MoveNext() in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/Dispatcher/LocalDispatcher.cs:line 49 (Microsoft.ML.ModelBuilder.Utils.Logger.Debug)
2021-11-14 22:35:25.7790 DEBUG create new thread 0 (Microsoft.ML.ModelBuilder.Utils.Logger.Debug)
2021-11-14 22:35:25.7940 DEBUG probability 0.00552752745075482,0.0221101098030193,0.547543556901995,0.0110550549015096,0.0442202196060385,0.369543531336682 (Microsoft.ML.ModelBuilder.Utils.Logger.Debug)
2021-11-14 22:35:25.7940 DEBUG select pipeline e0 * e1 * e2 * e3 * e11 * e12 (Microsoft.ML.ModelBuilder.Utils.Logger.Debug)
2021-11-14 22:35:25.7940 DEBUG 5$L1Regularization:1,5$L2Regularization:1 (Microsoft.ML.ModelBuilder.Utils.Logger.Debug)
2021-11-14 22:35:25.7940 DEBUG update train dataset C:\Users\SQ\AppData\Local\Temp\AutoML-NNI\Experiment-MRD7SI\cv.bin (Microsoft.ML.ModelBuilder.Utils.Logger.Debug)
2021-11-14 22:35:25.7940 INFO Trial 3 encounter error with message: Read only 0 bytes in file, expected header size of 256 (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2021-11-14 22:35:25.7940 DEBUG    at Microsoft.ML.Data.IO.BinaryLoader.InitHeader()
   at Microsoft.ML.Data.IO.BinaryLoader..ctor(Arguments args, IHost host, Stream stream, Boolean leaveOpen)
   at Microsoft.ML.BinaryLoaderSaverCatalog.LoadFromBinary(DataOperationsCatalog catalog, String path)
   at Microsoft.ML.ModelBuilder.AutoMLService.LocalDispatcher.Run() in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/Dispatcher/LocalDispatcher.cs:line 113
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ML.ModelBuilder.AutoMLService.LocalDispatcher.<RunAsync>d__19.MoveNext() in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/Dispatcher/LocalDispatcher.cs:line 151
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ML.ModelBuilder.AutoMLService.LocalDispatcher.<AddTrialAsync>d__16.MoveNext() in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/Dispatcher/LocalDispatcher.cs:line 49 (Microsoft.ML.ModelBuilder.Utils.Logger.Debug)
2021-11-14 22:35:25.7940 DEBUG create new thread 0 (Microsoft.ML.ModelBuilder.Utils.Logger.Debug)
2021-11-14 22:35:25.7940 DEBUG probability 0.00872923379264642,0.0349169351705857,0.864696876213981,0.0174584675852928,0.0698338703411714,0.00436461689632321 (Microsoft.ML.ModelBuilder.Utils.Logger.Debug)
2021-11-14 22:35:25.8140 DEBUG select pipeline e0 * e1 * e2 * e3 * e6 (Microsoft.ML.ModelBuilder.Utils.Logger.Debug)
2021-11-14 22:35:25.8140 DEBUG 4$NumberOfLeaves:4,4$MinimumExampleCountPerLeaf:20,4$LearningRate:0.1,4$NumberOfTrees:4,4$MaximumBinCountPerFeature:256,4$FeatureFraction:1 (Microsoft.ML.ModelBuilder.Utils.Logger.Debug)
2021-11-14 22:35:25.8140 DEBUG update train dataset C:\Users\SQ\AppData\Local\Temp\AutoML-NNI\Experiment-MRD7SI\cv.bin (Microsoft.ML.ModelBuilder.Utils.Logger.Debug)
2021-11-14 22:35:25.8140 INFO Trial 4 encounter error with message: Read only 0 bytes in file, expected header size of 256 (Microsoft.ML.ModelBuilder.Utils.Logger.Info)

**Comment by beccamc** [comment]
@blahblehblah Sorry you're running into this problem. What is your file separator/delimiter? In the sample provided above it looks like spaces?

**Comment by blahblehblah** [comment]
> @blahblehblah Sorry you're running into this problem. What is your file separator/delimiter? In the sample provided above it looks like spaces?

Its actually comma delimiter

**Comment by blahblehblah** [comment]
[sTank.zip](https://github.com/dotnet/machinelearning-modelbuilder/files/7548580/sTank.zip)
@beccamc sure.

**Comment by vzhuqin** [comment]
@beccamc , i met the same error on Value predication with SQL server dataset: https://testpass.blob.core.windows.net/test-pass-data/iris.mdf

![image](https://user-images.githubusercontent.com/81727020/142108055-163a4a2d-536a-4986-8100-2d6fef9551bb.png)


Table: taxi
Advanced settings:
![image](https://user-images.githubusercontent.com/81727020/142101574-d25e324a-b781-441f-942b-851e53eefbee.png)
MBconfig file:
[ValueSQL-MLModel1.zip](https://github.com/dotnet/machinelearning-modelbuilder/files/7551250/ValueSQL-MLModel1.zip)

but can be trained successfully with the same column setting on .csv file.
![image](https://user-images.githubusercontent.com/81727020/142121490-738c5f55-85c4-4e88-9123-0b0cb729b4a6.png)

**Comment by blahblehblah** [comment]
@beccamc Would love to hear if there's an update regarding the data i've sent.

**Comment by dliedke** [comment]
I am facing the same issue here:

Trial 125 encounter error with message: Read only 0 bytes in file, expected header size of 256
Trial 126 encounter error with message: Read only 0 bytes in file, expected header size of 256
Trial 127 encounter error with message: Read only 0 bytes in file, expected header size of 256
Trial 128 encounter error with message: Read only 0 bytes in file, expected header size of 256
Trial 129 encounter error with message: Read only 0 bytes in file, expected header size of 256
Trial 130 encounter error with message: Read only 0 bytes in file, expected header size of 256

And keeps forever. It only happens with ML Model builder 2022 and not ML Model Builder 2019.

**Comment by luisquintanilla** [comment]
@v-Hailishi can you please confirm whether this is still an issue in the latest version of Model Builder.

Thanks!

**Comment by v-Hailishi** [comment]
@luisquintanilla Training customer's data [sTank.zip](https://github.com/dotnet/machinelearning-modelbuilder/files/7548580/sTank.zip) on the latest main build: 16.13.10.2251201, it is failed with error "Schema mismatch for label column 'Won': expected Single, got Boolean".
But I think this is expected.

![image](https://user-images.githubusercontent.com/99375895/195568014-fc0b0791-6bd2-4289-971d-d96515f5c537.png)
![image](https://user-images.githubusercontent.com/99375895/195568691-4a23cc4d-d3d2-4245-b911-533d036f4012.png)

**Comment by beccamc** [comment]
Does this work if you do classification?

**Comment by v-Hailishi** [comment]
@beccamc It is failed with error "**Splitter/consolidator worker encountered exception while consuming source data**".
![image](https://user-images.githubusercontent.com/99375895/195744339-e7af43c1-9859-422e-861f-63df97ab9fb2.png)
![image](https://user-images.githubusercontent.com/99375895/195744405-82a0432c-57bd-4df4-a022-b1b1c97cccd5.png)
