### ISSUE TITLE
Input string was not in a correct format

### ISSUE THREAD

**Issue by vborovikov** [dotnet/machinelearning-modelbuilder#1921]
**System Information (please complete the following information):**
 - Model Builder Version (available in Manage Extensions dialog): 16.7.6.2152701
 - Visual Studio Version 2022 Community

**Describe the bug**
- On which step of the process did you run into an issue: training the model for 2 hours, almost done
- Clear description of the problem: train a model on a CSV file of 16M rows

**Expected behavior**
No exceptions and successful completion of the training process.

**Additional context**

```
Input string was not in a correct format.
   at System.Number.ParseDouble(String value, NumberStyles options, NumberFormatInfo numfmt)
   at Microsoft.ML.ModelBuilder.AutoMLService.Proposer.HyperParameterProposer.Propose(TrialParameter trialParameter) in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/Proposer/HyperParameterProposer.cs:line 63
   at Microsoft.ML.ModelBuilder.AutoMLService.Proposer.Controller.Propose() in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/Proposer/Controller.cs:line 62
   at Microsoft.ML.ModelBuilder.AutoMLService.Experiments.LocalAutoMLExperiment.<ExecuteAsync>d__15.MoveNext() in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/Experiments/LocalAutoMLExperiment.cs:line 137
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ML.ModelBuilder.AutoMLEngine.<StartTrainingAsync>d__21.MoveNext() in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/AutoMLEngineService/AutoMLEngine.cs:line 163   at StreamJsonRpc.JsonRpc.<InvokeCoreAsync>d__139`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ML.ModelBuilder.ViewModels.TrainViewModel.<<StartTrainingAsync>b__109_0>d.MoveNext() (Microsoft.ML.ModelBuilder.Utils.Logger.Debug)

```

**Comment by beccamc** [comment]
@vborovikov Sorry you've run into this problem. We've had other customers report this from machines in non-english language, specifically a machine that uses `,` as the decimal separator value for numbers.  

Can you tell me... 
1. What language your machine is in
2. What language your VS is in 
3. What the expected decimal separator of your data set is (you can see what it is set to in the Data Advanced Options)

**Comment by vborovikov** [comment]
1. English, but Russian for date-time and numeric data
2. English
3. Decimal dot (it's a correct setting for my data)

I've found what the issue was. My CSV file contained several rows with improper quotation marks way below the row # 430000. I tried to make a small sample of data (100 rows) to reproduce the issue but ML.NET recognized the incorrect format immediately.

```
feature,label
" ### ",###
" ### ","### <- last quotation mark is unexpected
" ### ",###
```

**Comment by beccamc** [comment]
@LittleLittleCloud Any thoughts as to why this might fail if more training time is given? Is it possible there is another bad row further down that ML.NET only gets to with more time?

Long term, what do we need to do to skip these rows?

**Comment by LittleLittleCloud** [comment]
@vborovikov Can you share with us the log file. You can find the link to log file at the very top of output window. And is there any trial completed successfully other than the current failing trial?

I feel like it's still the number format problem. In [this line](https://github.com/dotnet/machinelearning-tools/blob/main/src/Microsoft.ML.ModelBuilder.AutoMLService/Proposer/HyperParameterProposer.cs#L67), model builder parses a string into a double with invariant culture. So it will fail if the string has ',' as decimal seperate.

**Comment by vborovikov** [comment]
[Food-14YUSR.txt](https://github.com/dotnet/machinelearning-modelbuilder/files/7558166/Food-14YUSR.txt)
This is the log file.

I can't open the code from the link provided but looking into Model Builder DLLs with ILSpy shows me this code that fails:
```csharp
// Microsoft.ML.ModelBuilder.AutoMLService.Proposer.HyperParameterProposer.Propose
double sampleSize = double.Parse(parameter["_SampleSize"]);
```
And, I believe, the value for the parameter is created using this code:
```csharp
// Microsoft.ML.ModelBuilder.AutoMLService.Tuner.CFO.GenerateParameters
double val = param[key];
// ...
res[key] = val.ToString(CultureInfo.InvariantCulture);
```
This combination of calls ToString/Parse will fail 100% on my machine.

**Comment by LittleLittleCloud** [comment]
Got it, so the error happens when sample size is not integer. The sample size will have an initial value of 10000 and that's why there're a few trials success at the begining but fails when tunner start optimizing sample size

**Comment by beccamc** [comment]
It looks like XiaoYun has already validated this.
