### ISSUE TITLE
Sometimes cannot detect Data path on Train page after data setting.

### ISSUE THREAD

**Issue by vzhuqin** [dotnet/machinelearning-modelbuilder#1923]
**System Information (please complete the following information):**
 - Model Builder Version (available in Manage Extensions dialog):  16.9.1.2156701 (Main)
 - Microsoft Visual Studio Enterprise 2019: 16.11.7

**Describe the bug**
- On which step of the process did you run into an issue: Data is empty on Train page
- Clear description of the problem: have already input the data source, and set the columns settings, but Data is empty on Train page. This problem does not occur frequently, but I met it on different scenarios currently.

**To Reproduce**
1. Select Create a new project from the Visual Studio 2019 start window;
2. Choose the C# Console App (.NET Core) project template with .Net 5.0;
3. Add model builder by right click on the project;
4. Select Recommendation scenario;
5. Input the data source, and set the columns settings;
6. Navigate to Train page, click Start training, prompt Model Builder Error said that: "Value cannot be nulll. Parameter name: fileName". 
7. Close the error dialog, expand the Training setup summary, find that: Data is empty.

**Expected behavior**
Can detect the Data path on Train page after Data setting.

**Screenshots**
![image](https://user-images.githubusercontent.com/81727020/142390071-ec5f086f-8443-4785-93fe-93514a20c6b6.png)

![image](https://user-images.githubusercontent.com/81727020/142389344-c7f2d2cf-255f-4628-9245-21ce711cc05a.png)

**Additional context**
Reload the mbconfig file, re-input the Data source, can detect the data path on Train page.

**Comment by mhectorgato** [comment]
This happened for me as well.

Log file:
>2021-12-25 12:57:50.0533 INFO Set log file path to C:\Users\marten\AppData\Local\Temp\MLVSTools\logs\TextClassificationModel-TWFIVU.txt (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2021-12-25 12:58:28.8825 DEBUG Value cannot be null.
Parameter name: fileName
   at System.IO.FileInfo..ctor(String fileName)
   at Microsoft.ML.ModelBuilder.Utils.Utilities.GetFileTrainTime(String filePath)
   at Microsoft.ML.ModelBuilder.ViewModels.TrainViewModel.<StartTrainingAsync>d__109.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.ML.ModelBuilder.ToolWindows.TrainTabControl.<<StartTraining_Click>b__3_0>d.MoveNext() (Microsoft.ML.ModelBuilder.Utils.Logger.Debug)
2021-12-25 12:58:42.4985 DEBUG Value cannot be null.
Parameter name: fileName
   at System.IO.FileInfo..ctor(String fileName)
   at Microsoft.ML.ModelBuilder.Utils.Utilities.GetFileTrainTime(String filePath)
   at Microsoft.ML.ModelBuilder.ViewModels.TrainViewModel.<StartTrainingAsync>d__109.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.ML.ModelBuilder.ToolWindows.TrainTabControl.<<StartTraining_Click>b__3_0>d.MoveNext() (Microsoft.ML.ModelBuilder.Utils.Logger.Debug)

VS Settings:   
Microsoft Visual Studio Community 2019
Version 16.10.4
VisualStudio.16.Release/16.10.4+31515.178
Microsoft .NET Framework
Version 4.8.04084

**Comment by v-Hailishi** [comment]
@beccamc I haven't seen this.

**Comment by beccamc** [comment]
Closing this for lack of repro.
