### ISSUE TITLE
Could not find a part of the path 'C:\Users\Admin\AppData\Local\Temp\ukvjzu3u.t2y\validationSetBottleneckFile.csv_features.bin'.

### ISSUE THREAD

**Issue by JerzyKruszewski** [dotnet/machinelearning-modelbuilder#1924]
**System Information (please complete the following information):**
 - Model Builder Version (available in Manage Extensions dialog): 16.7.6.2152701
 - Visual Studio Version: 2022 Community 17.0.0

**Describe the bug**
- On which step of the process did you run into an issue: About 40 min into training an Image Classification scenario with 2 labels and 1819 images. It happened to me twice.
- Clear description of the problem:
Scenario: Image Classification
Type: Local
On: CPU
CPU: Intel Core i7-7700HQ
RAM: 16GB 2400MHz
Labels: 2
Images: 1819
Training method: Using Model Builder
About 40 min into training I got an exception.
Earlier I successfully finished training with ~180 images and the same labels.

**To Reproduce**
0. Prepare data
1. Make ML model
2. Choose Image Classification scenario
3. Choose Local CPU Env
4. Start Training using Model Builder
5. Wait for an exception

**Expected behavior**
Successfully finished training.

**Additional context**
```
2021-11-19 10:03:46.4778 TRACE [Source=AutoML, Kind=Trace] [Source=ImageClassificationTrainer; ImageClassificationTrainer, Kind=Trace] Channel started (Microsoft.ML.ModelBuilder.ViewModels.TrainViewModel.AutoMLService_DiagnosticDataReceived)
2021-11-19 10:03:46.4778 TRACE [Source=AutoML, Kind=Trace] 1	NaN	00:50:34.4015545	xf=ValueToKeyMapping{ col=Label:Label} xf=RawByteImageLoading{ col=ImageSource_featurized:ImageSource imageFolder=} xf=ColumnCopying{ col=Features:ImageSource_featurized} tr=ImageClassification{} xf=KeyToValueMapping{ col=PredictedLabel:PredictedLabel} cache=- (Microsoft.ML.ModelBuilder.ViewModels.TrainViewModel.AutoMLService_DiagnosticDataReceived)
2021-11-19 10:03:46.4778 INFO Could not find a part of the path 'C:\Users\Admin\AppData\Local\Temp\ukvjzu3u.t2y\validationSetBottleneckFile.csv_features.bin'. (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2021-11-19 10:03:46.5442 TRACE [Source=AutoML, Kind=Error] Progress report callback reported exception System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.ML.ModelBuilder.AutoMLService.Telemetry.TrialCompleteEvent.TrackTrialCompleteEvent(AutoMLTelemetry telemetry, AlgorithmIterationEventArgs args) in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/Telemetry/TelemetryEvents/TrialCompleteEvent.cs:line 20
   at Microsoft.ML.ModelBuilder.ModelBuilderProgressHandler`3.Report(RunDetail`1 value) in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/AutoMLEngineService/ModelBuilderProgressHandler.cs:line 49
   at Microsoft.ML.AutoML.Experiment`2.ReportProgress(TRunDetail iterationResult) (Microsoft.ML.ModelBuilder.ViewModels.TrainViewModel.AutoMLService_DiagnosticDataReceived)
2021-11-19 10:03:46.5741 DEBUG Could not find a part of the path 'C:\Users\Admin\AppData\Local\Temp\ukvjzu3u.t2y\validationSetBottleneckFile.csv_features.bin'.
   at Microsoft.ML.ModelBuilder.AutoMLService.Experiments.AutoMLExperiment`3.<ExecuteAsync>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ML.ModelBuilder.AutoMLEngine.<StartTrainingAsync>d__21.MoveNext() in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/AutoMLEngineService/AutoMLEngine.cs:line 163   at StreamJsonRpc.JsonRpc.<InvokeCoreAsync>d__139`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ML.ModelBuilder.ViewModels.TrainViewModel.<<StartTrainingAsync>b__109_0>d.MoveNext() (Microsoft.ML.ModelBuilder.Utils.Logger.Debug)

```

**Comment by beccamc** [comment]
@LittleLittleCloud Any ideas here?

**Comment by LittleLittleCloud** [comment]
Looks like the file `validationSetBottlenectFile.csv_features.bin` is created from this [code](https://github.com/dotnet/machinelearning/blob/0577957256c296fdea2deb6b6e00e7be9b458167/src/Microsoft.ML.Vision/ImageClassificationTrainer.cs#L671)

It's probably a bug in AutoML.Net and might not be reproduced in the latest main since we implement our own image classification training. @JerzyKruszewski would you mind sharing dataset with us so we can see if this bug goes?

**Comment by beccamc** [comment]
@JerzyKruszewski Is this still happening? If it is, would you mind sharing your dataset?

**Comment by beccamc** [comment]
Closing this due to inactivity. Please ping me or reopen if the issue persists.
