### ISSUE TITLE
Model Builder Error: Index was outside the bounds of the array

### ISSUE THREAD

**Issue by HashemGo** [dotnet/machinelearning-modelbuilder#1929]
**System Information (please complete the following information):**
 - Model Builder Version: NET6: 
 - Visual Studio Version 2022

**Describe the bug**
- Clear description of the problem:
Just a simple test

   at Microsoft.ML.ModelBuilder.AutoMLService.Proposer.PipelineProposer.Propose(TrialParameter trialParameter) in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/Proposer/PipelineProposer.cs:line 97
   at Microsoft.ML.ModelBuilder.AutoMLService.Proposer.Controller.Propose() in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/Proposer/Controller.cs:line 59
   at Microsoft.ML.ModelBuilder.AutoMLService.Experiments.LocalAutoMLExperiment.<ExecuteAsync>d__15.MoveNext() in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/Experiments/LocalAutoMLExperiment.cs:line 136
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ML.ModelBuilder.AutoMLEngine.<StartTrainingAsync>d__21.MoveNext() in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/AutoMLEngineService/AutoMLEngine.cs:line 167   at StreamJsonRpc.JsonRpc.<InvokeCoreAsync>d__139`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ML.ModelBuilder.ViewModels.TrainViewModel.<<StartTrainingAsync>b__109_0>d.MoveNext()

**Screenshots**
![image](https://user-images.githubusercontent.com/42634137/143314517-a5d75632-2a4a-4414-a5db-33a515966d89.png)

**Comment by HashemGo** [comment]
Any updates here, please?

Visual Studio 2022: Version 17.1.0 Preview 1.1
Microsoft.ML : 1.7.0

![image](https://user-images.githubusercontent.com/42634137/143571445-b09946d7-4c0b-4c68-ae39-c7b36fa1f5c6.png)

**Comment by HashemGo** [comment]
And this message showing up in output after I make train time for 30 minutes for a very small dataset 850 raw only, I have all NuGet are updates to 1.7.0,

“Installing NuGet package, package ID: Microsoft.ML, package Version: 1.6.0”

this is another Dataset with 10 raw :(
![image](https://user-images.githubusercontent.com/42634137/143597999-191c2264-4cf2-42d6-a9df-ec9bc3039874.png)

**Comment by HashemGo** [comment]
I tried to repair the Visual Studio and make sure every thing updated, but I's going to very bad
the UI ML become like this,
I can't analyze any datasets
any help please? 2 days without any solutions!

![image](https://user-images.githubusercontent.com/42634137/143609518-e253c7d1-6082-45fa-94f5-e8a049bde76c.png)

**Comment by zewditu** [comment]
@HashemGo sorry for the delay to respond to the Issue "Index was outside the bounds of the array"  is a known issue I will be fixed in the future release and follow here https://app.zenhub.com/workspaces/mlnet-tools-5cde1c97e3106e39e8ae08fc/issues/dotnet/machinelearning-modelbuilder/1602
 For training time finished without any model trained could you share your dataset?
 For the Update package  issue, it is a known issue https://github.com/dotnet/machinelearning-modelbuilder/issues/1918.

**Comment by zewditu** [comment]
If you still hit the issue after our next release feel free to reopen it.

**Comment by HashemGo** [comment]
Sorry, the issue still not resolve
I updated all ml.net and vs preview 2
still have this alert after analyze the dataset
i can't to do work :(
![image](https://user-images.githubusercontent.com/42634137/148542545-7bb7bc70-bc27-4ed3-be41-2c23e11cb7ec.png)

![image](https://user-images.githubusercontent.com/42634137/148542867-cd0c52a5-08f8-4fdd-a563-feaed5e53f32.png)

![image](https://user-images.githubusercontent.com/42634137/148543949-af761f2d-db4e-4309-8139-9c4f66ae2981.png)

![image](https://user-images.githubusercontent.com/42634137/148544009-0eb311ba-63a5-4fd3-91b0-f732212d730c.png)

**Comment by HashemGo** [comment]
With new update resolve part of problem
I think this is a bug

if you have a solution with many projects for ML
if you  try training one of them the project copy namespace from another that's wired!, The projects not connected 
also if you have version 1.6 and another project have version 1.7 the problem showing up


I hope this help
Thanks

**Comment by rasmusrim** [comment]
Ran into this problem today. Turns out I had too few samples. I duplicated them a couple of times and the training went smoothly.
