### ISSUE TITLE
Error: capacity was less than the current size. Parameter name: requiredLength

### ISSUE THREAD

**Issue by torronen** [dotnet/machinelearning-modelbuilder#1936]
**System Information (please complete the following information):**
 - Model Builder Version (available in Manage Extensions dialog): 16-7-3-2143002
 - Visual Studio Version 2022 Current

**Describe the bug**
Opening, multi-datatype 59 Gb CSV data set for classification gives error in Advanced Data Options...

Visual Studio becomes unresponsive after clicking Close.
```
capacity was less than the current size.
Parameter name: requiredLength

   at System.Text.StringBuilder.ExpandByABlock(Int32 minBlockCharCount)
   at System.Text.StringBuilder.Append(Char* value, Int32 valueCount)
   at System.Text.StringBuilder.Append(Char[] value, Int32 startIndex, Int32 charCount)
   at System.IO.StreamReader.ReadLine()
   at Microsoft.ML.ModelBuilder.DataProviders.FileDataProvider.<>c__DisplayClass3_0.<<CountFileLinesAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ML.ModelBuilder.DataProviders.FileDataProvider.<CountFileLinesAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ML.ModelBuilder.DataProviders.FileDataProvider.<GetNumberOfRowsForFileAsync>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ML.ModelBuilder.ToolWindows.DataTextViewModel.<OnColumnPropertiesChange_RowColSummaryAsync>d__119.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ML.ModelBuilder.Observable.ObservableModel.<ExecuteUpdateHandlerAsync>d__24.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ML.ModelBuilder.Observable.ObservableModel.<HandlePropertyUpdateAsync>d__28.MoveNext()
```

![image](https://user-images.githubusercontent.com/26261427/144720309-3220d92f-2261-4efe-9096-3bb3384f9f62.png)

**To Reproduce**
Unknown at this time.

**Comment by torronen** [comment]
I had forgotten to update the extension :(

Works fine on latest version of the extension.
