### ISSUE TITLE
value prediction parse error in official sample => when too much data I get a pars error (about 50k data)

### ISSUE THREAD

**Issue by MightyNold** [dotnet/machinelearning-modelbuilder#1937]
official sample not working : https://docs.microsoft.com/fr-fr/dotnet/machine-learning/tutorials/predict-prices-with-model-builder

last version visual 2022/Ml builder as of 05 dec 2021

logs :

   at System.Number.ParseDouble(String value, NumberStyles options, NumberFormatInfo numfmt)
   at Microsoft.ML.ModelBuilder.AutoMLService.Proposer.HyperParameterProposer.Propose(TrialParameter trialParameter) in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/Proposer/HyperParameterProposer.cs:line 66
   at Microsoft.ML.ModelBuilder.AutoMLService.Proposer.Controller.Propose() in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/Proposer/Controller.cs:line 61
   at Microsoft.ML.ModelBuilder.AutoMLService.Experiments.LocalAutoMLExperiment.<ExecuteAsync>d__15.MoveNext() in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/Experiments/LocalAutoMLExperiment.cs:line 136
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ML.ModelBuilder.AutoMLEngine.<StartTrainingAsync>d__21.MoveNext() in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/AutoMLEngineService/AutoMLEngine.cs:line 167   at StreamJsonRpc.JsonRpc.<InvokeCoreAsync>d__139`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ML.ModelBuilder.ViewModels.TrainViewModel.<<StartTrainingAsync>b__109_0>d.MoveNext()

**System Information (please complete the following information):**
 - Model Builder Version (available in Manage Extensions dialog): 
 - Visual Studio Version

**Describe the bug**
- On which step of the process did you run into an issue:
- Clear description of the problem:

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by MightyNold** [comment]
if I keep all sample data (1048575 lines of the CSV) I get the error
If I keep only for exemple 1000 first lines sampe run is ok and I get a best quality 0.94 working fine

**Comment by zewditu** [comment]
@MightyNoldthis , this issue is not reproduced in our latest private build 
![image.png](https://images.zenhubusercontent.com/5d014b8c2b5aa11c6166d13d/1ef9ae8d-0944-4956-a4d6-0ffa36478f36).

**Comment by zewditu** [comment]
if you are still in our next release feel free to open it.

**Comment by MightyNold** [comment]
thx a lot :)

**Comment by MightyNold** [comment]
nugget 1.7 still same problem
![image](https://user-images.githubusercontent.com/61160121/144912553-bff79d8c-9358-43fd-a1a2-3940f638cbfc.png)

![image](https://user-images.githubusercontent.com/61160121/144912629-92076e02-99d5-41c4-b84f-46a4fce4397a.png)

![image](https://user-images.githubusercontent.com/61160121/144913517-ab14ce9f-99b6-4d4a-9c66-7e632ce81073.png)
