### ISSUE TITLE
JSON parsing issue creating notebooks

### ISSUE THREAD

**Issue by beccamc** [dotnet/machinelearning-modelbuilder#1938]
I've gotten several different JSON parsing issues while generating notebooks. I'm going to track all of them here. 

Local Image classification: 
![image.png](https://images.zenhubusercontent.com/5d55c3d68fac840001314eaa/6a800c2a-24de-43a6-9c03-36668f66e981)
[Azure(2).zip](https://app.zenhub.com/files/186917455/b8742347-c6da-4c28-8574-a5243f0cfa19/download)

Text classification 
![image.png](https://images.zenhubusercontent.com/5d55c3d68fac840001314eaa/6cf33bf5-d5b7-4ec2-b397-57d9536e0db0)
[Text Classification](https://app.zenhub.com/files/186917455/21d2af8c-8450-4134-bf4f-423ffec59d4e/download)

Full Trace: 
   at Microsoft.ML.ModelBuilder.SerializablePipeline.Converter.SingleModelPipelineConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer) in C:\Repos\ModelBuilder\src\Microsoft.ML.ModelBuilder.SerializablePipeline\Converter\SingleModelPipelineConverter.cs:line 35
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Microsoft.ML.ModelBuilder.CodeGenerator.CSharp.NotebookGenerator.ImageClassificationNotebookGenerator.GenerateSingleFile() in C:\Repos\ModelBuilder\src\Microsoft.ML.ModelBuilder.CodeGenerator\CSharp\NotebookGenerator\ImageClassificationNotebookGenerator.cs:line 59
   at Microsoft.ML.ModelBuilder.AutoMLService.ServiceFactory.CodeGeneratorService.<CreateNotebookCodesAsync>d__6.MoveNext() in C:\Repos\ModelBuilder\src\Microsoft.ML.ModelBuilder.AutoMLService\ServiceFactory\CodeGeneratorService.cs:line 193   at StreamJsonRpc.JsonRpc.<InvokeCoreAsync>d__139`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.ML.ModelBuilder.ToolWindows.ConsumeViewModel.<AddNotebookToSolutionAsync>d__76.MoveNext() in C:\Repos\ModelBuilder\src\Microsoft.ML.ModelBuilder\ViewModels\ConsumeViewModel.cs:line 311

**Comment by beccamc** [comment]
Looks like we can't create any notebook (not through all scenarios but it isn't working for classification or image...). Changing to Ship Blocker.

**Comment by beccamc** [comment]
Looks like the SingleModelPipelineConverter is expecting a single object, but instead it's passed this: 
```
@LittleLittleCloud Can you help here? Is there a problem in the SingleModelPipelineConverter, or is the problem that this isn't actually a SingleModelPipeline? 
[
  {
    "EstimatorType": "MapValueToKey",
    "Inputs": [
      "Label"
    ],
    "Outputs": [
      "Label"
    ]
  },
  {
    "OutputColumnName": "ImageSource_featurized",
    "ImageFolder": "",
    "InputColumnName": "ImageSource",
    "EstimatorType": "LoadRawImageBytes",
    "Inputs": [
      "ImageSource"
    ],
    "Outputs": [
      "ImageSource_featurized"
    ]
  },
  {
    "EstimatorType": "CopyColumns",
    "Inputs": [
      "ImageSource_featurized"
    ],
    "Outputs": [
      "Features"
    ]
  },
  {
    "LabelColumnName": "Label",
    "EstimatorType": "ImageClassificationMulti",
    "Inputs": [
      "Features"
    ],
    "Outputs": [
      "Score"
    ]
  },
  {
    "EstimatorType": "MapKeyToValue",
    "Inputs": [
      "PredictedLabel"
    ],
    "Outputs": [
      "PredictedLabel"
    ]
  }
]
```

**Comment by LittleLittleCloud** [comment]
The problem is the schema for singleModelPipeline is changed and we need to increase RunHistory version to trigger an update process. After that update user will loose their run history since the change in single model pipeline schema is a broken change

**Comment by vzhuqin** [comment]
Not repro this issue on latest main: 16.12.1.2206302
![1938_Fixed.gif](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/bf6c069a-40b9-4d04-928a-e6d900ab954f)
