### ISSUE TITLE
Update ML.Net package version doesn't work on VS2022 int preview

### ISSUE THREAD

**Issue by LittleLittleCloud** [dotnet/machinelearning-modelbuilder#1945]
Model Builder version: latest main
Visual Studio version: Version 17.1.0 Preview 2.0 [32001.329.main]

I'll reach out to vs discuss thread for solution

![image](https://user-images.githubusercontent.com/16876986/145311873-853139cd-cfa1-4866-98eb-eff6dbe74455.png)

## full log
```
Updating nuget dependencies...
Starting update NuGet dependencies async.
Installing nuget package, package ID: Microsoft.ML, package Version: 1.7.0
Specified method is not supported.
   at Microsoft.VisualStudio.ProjectSystem.ProjectSerialization.CachedProject.GetItemProvenance(String itemToMatch, String itemType, EvaluationContext evaluationContext)
   at Microsoft.VisualStudio.ProjectSystem.Items.MSBuildGlobUtilities.TryGetLatestExactMetadataElement(ProjectItem item, ProjectRootElement containingProjectXml)
   at Microsoft.VisualStudio.ProjectSystem.Properties.ItemProperties.ProjectMetadataElementCache.<GetValueAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.VisualStudio.ProjectSystem.Properties.ItemProperties.<GetProjectItemAndMetaElementAsync>d__25.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.ProjectSystem.Properties.ItemProperties.<SetPropertyValueAsync>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.ProjectSystem.Properties.ItemPropertiesWithCatalog.<SetPropertyValueAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.ProjectSystem.Properties.ProjectPropertiesBase.<>c__DisplayClass31_0.<<Microsoft-VisualStudio-ProjectSystem-Properties-IProjectProperties-SetPropertyValueAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Threading.JoinableTask.<JoinAsync>d__76.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.ProjectSystem.ProjectLockService.<ExecuteWithinLockAsync>d__129.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.VisualStudio.ProjectSystem.ProjectLockService.<ExecuteWithinLockAsync>d__129.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.PackageManagement.VisualStudio.CpsPackageReferenceProject.<InstallPackageAsync>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at NuGet.PackageManagement.NuGetPackageManager.<ExecuteBuildIntegratedProjectActionsAsync>d__82.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.PackageManagement.NuGetPackageManager.<ExecuteNuGetProjectActionsAsync>d__79.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.PackageManagement.NuGetPackageManager.<InstallPackageAsync>d__48.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.PackageManagement.NuGetPackageManager.<InstallPackageAsync>d__47.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.VisualStudio.VsPackageInstaller.<InstallInternalCoreAsync>d__25.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at NuGet.VisualStudio.VsPackageInstaller.<InstallInternalAsync>d__24.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at NuGet.VisualStudio.VsPackageInstaller.<InstallInternalAsync>d__24.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Threading.JoinableTask.CompleteOnCurrentThread()
   at NuGet.VisualStudio.VsPackageInstaller.InstallPackage(String source, Project project, String packageId, String version, Boolean ignoreDependencies)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at NuGet.VisualStudio.VsPackageInstaller.InstallPackage(String source, Project project, String packageId, String version, Boolean ignoreDependencies)
   at Microsoft.ML.ModelBuilder.Utils.Utilities.<InstallNugetPackageAsync>d__17.MoveNext() in C:\Users\xiaoyuz\source\repos\machinelearning-tools\src\Microsoft.ML.ModelBuilder\Utils\Utilities.cs:line 319
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Microsoft.ML.ModelBuilder.ViewModels.TrainViewModel.<UpdateNugetDependenciesAsync>d__123.MoveNext() in C:\Users\xiaoyuz\source\repos\machinelearning-tools\src\Microsoft.ML.ModelBuilder\ViewModels\TrainViewModel.cs:line 1037
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Microsoft.ML.ModelBuilder.ViewModels.TrainViewModel.<GenerateCodeBehindFilesAsync>d__122.MoveNext() in C:\Users\xiaoyuz\source\repos\machinelearning-tools\src\Microsoft.ML.ModelBuilder\ViewModels\TrainViewModel.cs:line 981
```

**Comment by LittleLittleCloud** [comment]
Related with https://github.com/NuGet/Home/issues/11427

**Comment by LittleLittleCloud** [comment]
fix: update to latest VS
![image](https://user-images.githubusercontent.com/16876986/148826514-af8b486d-0241-449b-b20b-3cf9ca20a62e.png)

**Comment by vzhuqin** [comment]
@LittleLittleCloud , I can update the Microsoft.ML to latest 1.7.0 from NuGet Package Manager without error, not sure whether have verified this issue? if not, could you help to provide me the repro steps?

My steps:
1. Install Microsoft Visual Studio Enterprise 2022 (64-bit) - Int Preview Version 17.1.0 Preview 4.0 [32119.435.d17.1];
2. Update ML.Net Model Builder VS2022 to latest main;
3. Open NuGet Package Manager and install Microsoft.ML to 1.6.0;
4. Update Microsoft.ML to 1.7.0
![1945Fixed2.gif](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/ce729a7c-df64-4268-953f-bcd5d790e600)
- ML.Net Model Builder VS2022: 16.12.1.2206901
- Microsoft Visual Studio Enterprise 2022 (64-bit) - Int Preview Version 17.1.0 Preview 4.0 [32119.435.d17.1]
![image.png](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/713378af-d7da-43ca-83e2-636509a47ae9)

**Comment by vzhuqin** [comment]
@LittleLittleCloud any update about my validation steps?

**Comment by LittleLittleCloud** [comment]
@vzhuqin 

Nope, the fix is on VS side so we don't have to validate anything at this time point
