### ISSUE TITLE
Schema mismatch for label column 'Won': expected Single, got Boolean Parameter name: labelCol

### ISSUE THREAD

**Issue by blahblehblah** [dotnet/machinelearning-modelbuilder#1947]
**System Information (please complete the following information):**
 - Model Builder Version  16.7.6.2152701
 - Visual Studio Version 17.1.0 Preview 1.1

**Describe the bug**
- On starting to train the model.

Error > Schema mismatch for label column 'Won': expected Single, got Boolean Parameter name: labelCol

The label to predict is a Boolean, switching it to Single from the data options raises another error > `Training set has 0 instances, aborting training.`

Log file: 
2021-12-10 19:46:22.5305 INFO Set log file path to C:\Users\SQ\AppData\Local\Temp\MLVSTools\logs\MLModel-R3TOJK.txt (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2021-12-10 19:47:01.6201 DEBUG AutoMLType: Octopus (Microsoft.ML.ModelBuilder.Utils.Logger.Debug)
2021-12-10 19:47:01.7170 TRACE [Source=TextLoader; Binding, Kind=Trace] Channel started (Microsoft.ML.ModelBuilder.ViewModels.TrainViewModel.AutoMLService_DiagnosticDataReceived)
2021-12-10 19:47:01.7380 TRACE [Source=TextLoader; Binding, Kind=Trace] Channel finished. Elapsed 00:00:00.0214074. (Microsoft.ML.ModelBuilder.ViewModels.TrainViewModel.AutoMLService_DiagnosticDataReceived)
2021-12-10 19:47:01.7380 TRACE [Source=TextLoader; Binding, Kind=Trace] Channel disposed (Microsoft.ML.ModelBuilder.ViewModels.TrainViewModel.AutoMLService_DiagnosticDataReceived)
2021-12-10 19:47:01.9259 INFO start nni training (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2021-12-10 19:47:01.9479 INFO Experiment output folder: C:\Users\SQ\AppData\Local\Temp\AutoML-NNI\Experiment-A6C00H (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2021-12-10 19:47:01.9479 DEBUG row count is unknown, count it explicitly (Microsoft.ML.ModelBuilder.Utils.Logger.Debug)
2021-12-10 19:47:01.9479 TRACE [Source=TextLoader; ParseStats, Kind=Trace] Channel started (Microsoft.ML.ModelBuilder.ViewModels.TrainViewModel.AutoMLService_DiagnosticDataReceived)
2021-12-10 19:47:01.9559 TRACE [Source=TextLoader; Cursor, Kind=Trace] Channel started (Microsoft.ML.ModelBuilder.ViewModels.TrainViewModel.AutoMLService_DiagnosticDataReceived)
2021-12-10 19:47:02.0018 TRACE [Source=TextLoader; ParseStats, Kind=Trace] Channel finished. Elapsed 00:00:00.0490832. (Microsoft.ML.ModelBuilder.ViewModels.TrainViewModel.AutoMLService_DiagnosticDataReceived)
2021-12-10 19:47:02.0038 TRACE [Source=TextLoader; ParseStats, Kind=Trace] Channel disposed (Microsoft.ML.ModelBuilder.ViewModels.TrainViewModel.AutoMLService_DiagnosticDataReceived)
2021-12-10 19:47:02.0038 TRACE [Source=TextLoader; Cursor, Kind=Trace] Channel finished. Elapsed 00:00:00.0467902. (Microsoft.ML.ModelBuilder.ViewModels.TrainViewModel.AutoMLService_DiagnosticDataReceived)
2021-12-10 19:47:02.0038 TRACE [Source=TextLoader; Cursor, Kind=Trace] Channel disposed (Microsoft.ML.ModelBuilder.ViewModels.TrainViewModel.AutoMLService_DiagnosticDataReceived)
2021-12-10 19:47:02.0038 DEBUG count elapse 53ms (Microsoft.ML.ModelBuilder.Utils.Logger.Debug)
2021-12-10 19:47:02.0038 INFO |     Trainer                             RSquared Absolute-loss Squared-loss RMS-loss  Duration #Iteration      | (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2021-12-10 19:47:02.2477 DEBUG select pipeline e0 * e1 * e2 * e3 * e5 (Microsoft.ML.ModelBuilder.Utils.Logger.Debug)
2021-12-10 19:47:02.2717 DEBUG 4$NumberOfTrees:4,4$FeatureFraction:1 (Microsoft.ML.ModelBuilder.Utils.Logger.Debug)
2021-12-10 19:47:02.2867 DEBUG update train dataset C:\Users\SQ\AppData\Local\Temp\AutoML-NNI\Experiment-A6C00H\train.bin (Microsoft.ML.ModelBuilder.Utils.Logger.Debug)
2021-12-10 19:47:02.3366 DEBUG update test dataset C:\Users\SQ\AppData\Local\Temp\AutoML-NNI\Experiment-A6C00H\test.bin (Microsoft.ML.ModelBuilder.Utils.Logger.Debug)
2021-12-10 19:47:02.5455 DEBUG Schema mismatch for label column 'Won': expected Single, got Boolean
Parameter name: labelCol
   at Microsoft.ML.ModelBuilder.AutoMLService.LocalDispatcher.<AddTrialAsync>d__16.MoveNext() in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/Dispatcher/LocalDispatcher.cs:line 60
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.ML.ModelBuilder.AutoMLService.Experiments.LocalAutoMLExperiment.<ExecuteAsync>d__15.MoveNext() in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/Experiments/LocalAutoMLExperiment.cs:line 142
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ML.ModelBuilder.AutoMLEngine.<StartTrainingAsync>d__21.MoveNext() in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/AutoMLEngineService/AutoMLEngine.cs:line 163   at StreamJsonRpc.JsonRpc.<InvokeCoreAsync>d__139`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ML.ModelBuilder.ViewModels.TrainViewModel.<<StartTrainingAsync>b__109_0>d.MoveNext() (Microsoft.ML.ModelBuilder.Utils.Logger.Debug)

**Comment by blahblehblah** [comment]
[sTank2.zip](https://github.com/dotnet/machinelearning-modelbuilder/files/7694594/sTank2.zip)

**Comment by beccamc** [comment]
@blahblehblah Sorry you've ran into this problem! Are you doing Value Prediction or Text Classification scenario?

**Comment by blahblehblah** [comment]
@beccamc Value prediction

**Comment by beccamc** [comment]
@blahblehblah For the problem you are trying to solve it looks like you should use Classification. Can you try that and see if it works?

**Comment by blahblehblah** [comment]
That did work, thank you
