### ISSUE TITLE
Model Builder Error: Column 'Probability' not found Parameter name: name when predicting model in Evaluate page.

### ISSUE THREAD

**Issue by vzhuqin** [dotnet/machinelearning-modelbuilder#1951]
**System Information (please complete the following information):**
 - Model Builder Version (available in Manage Extensions dialog): 16.9.1.2161701
 - Microsoft Visual Studio Enterprise 2019: 16.11.8

**Describe the bug**
- On which step of the process did you run into an issue: Evaluate page
- Clear description of the problem: This issue doesn't occur 100%, maybe it is not reproduced after retrained it. 

**To Reproduce**
1. Select Create a new project from the Visual Studio 2019 start window;
2. Choose the C# ASP.NET Core Web App  project template with .Net 5.0;
3. Add model builder by right click on the project;
4. Select Data classification + Sentiment dataset to complete the training (set "Sentiment" to label with "Boolean" type);
5. Navigate to Evaluate page after completed training;
6. Click "Predict" button, prompts Model Builder Error: Column 'Probability' not found Parameter name: name

**Expected behavior**
No error when predicting the model

**Screenshots**
**Settings of Dataset:**
![image](https://user-images.githubusercontent.com/81727020/146879455-80adc135-b103-4f81-8ce2-89b4a3c2b6b7.png)
**Error in Evaluate page:**
![image](https://user-images.githubusercontent.com/81727020/146896323-8bf14b29-faf8-4754-96e5-2945028b0cd1.png)

**Additional context**
MBConfig file: 
[Data-Binary.zip](https://github.com/dotnet/machinelearning-modelbuilder/files/7749912/Data-Binary.zip)

Error Message:
   at Microsoft.ML.DataViewSchema.get_Item(String name)
   at Microsoft.ML.Data.ColumnCursorExtensions.GetColumn[T](IDataView data, String columnName)
   at Microsoft.ML.ModelBuilder.AutoMLService.ModelInferenceEngine.<>c__DisplayClass5_0.<PredictClassificationAsync>b__0() in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/ModelInferenceEngine.cs:line 64
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ML.ModelBuilder.AutoMLService.ModelInferenceEngine.<PredictClassificationAsync>d__5.MoveNext() in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/ModelInferenceEngine.cs:line 59
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ML.ModelBuilder.AutoMLService.ModelInferenceEngine.<PredictClassificationAsync>d__3.MoveNext() in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/ModelInferenceEngine.cs:line 36   at StreamJsonRpc.JsonRpc.<InvokeCoreAsync>d__139`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.ML.ModelBuilder.ToolWindows.EvaluateViewModel.<MulticlassficationAsync>d__103.MoveNext()

**Comment by LittleLittleCloud** [comment]
@vzhuqin Did you retrain your model after changing label type? If not the error is somehow expected but maybe a more proper way is to mark train page as incomplete if column type get changed

**Comment by vzhuqin** [comment]
@LittleLittleCloud It was not discovered after retain.  I started the first training after setting up the columns,, and then I encountered the error when predicting. Then back to click "Train again" with the same settings, the error may not be able to be reproduced.

**Comment by beccamc** [comment]
Is there a consistent repro for this if you don't retrain? @vzhuqin Have you hit this again?

**Comment by LittleLittleCloud** [comment]
@beccamc 
It's probably because we didn't clear training result after reset column purpose in advanced data option (which we should). We probably needs to fix that.

**Comment by vzhuqin** [comment]
@beccamc , I encountered this issue on latest main: ML.Net Model Builder 2022: 16.12.2.2207101, but it was found after retrained, and the probability of recurrence is very small now. Attached the screenshot for your reference.
![image.png](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/dea64cf2-6e2d-4576-b453-a1fbcae6f592)
MBConfig file:
[https://app.zenhub.com/files/186917455/255507fa-f808-4187-b98b-36fc39ddae6b/download](https://app.zenhub.com/files/186917455/255507fa-f808-4187-b98b-36fc39ddae6b/download)

Error message:
   at Microsoft.ML.DataViewSchema.get_Item(String name)
   at Microsoft.ML.Data.ColumnCursorExtensions.GetColumn[T](IDataView data, String columnName)
   at Microsoft.ML.ModelBuilder.AutoMLService.ModelInferenceEngine.<>c__DisplayClass5_0.<PredictClassificationAsync>b__0() in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/ModelInferenceEngine.cs:line 64
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ML.ModelBuilder.AutoMLService.ModelInferenceEngine.<PredictClassificationAsync>d__5.MoveNext() in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/ModelInferenceEngine.cs:line 59
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ML.ModelBuilder.AutoMLService.ModelInferenceEngine.<PredictClassificationAsync>d__3.MoveNext() in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/ModelInferenceEngine.cs:line 36   at StreamJsonRpc.JsonRpc.<InvokeCoreAsync>d__139`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.ML.ModelBuilder.ToolWindows.EvaluateViewModel.<MulticlassficationAsync>d__69.MoveNext()

**Comment by beccamc** [comment]
On evaluate we check for probability. We look for it by name. https://github.com/dotnet/machinelearning-tools/blob/main/src/Microsoft.ML.ModelBuilder.AutoMLService/ModelInferenceEngine.cs#L67

**Comment by JakeRadMSFT** [comment]
@michaelgsharp this is kind of related to having the model tell us which column is the prediction. What did we determine was the best way to do that?

**Comment by v-Hailishi** [comment]
The bug is not repro on the latest main build 17.17.0.2346401.
![image](https://github.com/dotnet/machinelearning-modelbuilder/assets/99375895/da76c4e5-4b75-42b0-9646-f8ffbd4cad68)
