### ISSUE TITLE
Error on train image classification ( The type initializer for 'Tensorflow.Binding' threw an exception. )

### ISSUE THREAD

**Issue by behnamasaei** [dotnet/machinelearning-modelbuilder#1959]
at Microsoft.ML.Vision.ImageClassificationTrainer..ctor(IHostEnvironment env, Options options)
   at Microsoft.ML.AutoML.ImageClassificationExtension.CreateInstance(MLContext mlContext, IEnumerable`1 sweepParams, ColumnInformation columnInfo, IDataView validationSet)
   at Microsoft.ML.AutoML.SuggestedTrainer.BuildTrainer(IDataView validationSet)
   at Microsoft.ML.AutoML.SuggestedPipelineBuilder.Build(MLContext context, ICollection`1 transforms, ICollection`1 transformsPostTrainer, SuggestedTrainer trainer, CacheBeforeTrainer cacheBeforeTrainerSettings)
   at Microsoft.ML.AutoML.PipelineSuggester.GetNextInferredPipeline(MLContext context, IEnumerable`1 history, DatasetColumnInfo[] columns, TaskKind task, Boolean isMaximizingMetric, CacheBeforeTrainer cacheBeforeTrainer, IChannel logger, IEnumerable`1 trainerAllowList)
   at Microsoft.ML.AutoML.Experiment`2.Execute()
   at Microsoft.ML.AutoML.ExperimentBase`2.Execute(ColumnInformation columnInfo, DatasetColumnInfo[] columns, IEstimator`1 preFeaturizer, IProgress`1 progressHandler, IRunner`1 runner)
   at Microsoft.ML.AutoML.ExperimentBase`2.ExecuteCrossValSummary(IDataView[] trainDatasets, ColumnInformation columnInfo, IDataView[] validationDatasets, IEstimator`1 preFeaturizer, IProgress`1 progressHandler)
   at Microsoft.ML.AutoML.ExperimentBase`2.Execute(IDataView trainData, ColumnInformation columnInformation, IEstimator`1 preFeaturizer, IProgress`1 progressHandler)
   at Microsoft.ML.ModelBuilder.AutoMLService.Experiments.AutoMLExperiment`3.<>c__DisplayClass22_0.<ExecuteAsync>b__6() in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/Experiments/AutoMLExperiment.cs:line 85
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ML.ModelBuilder.AutoMLService.Experiments.AutoMLExperiment`3.<ExecuteAsync>d__22.MoveNext() in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/Experiments/AutoMLExperiment.cs:line 100
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ML.ModelBuilder.AutoMLEngine.<StartTrainingAsync>d__21.MoveNext() in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/AutoMLEngineService/AutoMLEngine.cs:line 167   at StreamJsonRpc.JsonRpc.<InvokeCoreAsync>d__139`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ML.ModelBuilder.ViewModels.TrainViewModel.<<StartTrainingAsync>b__109_0>d.MoveNext()

**Comment by LittleLittleCloud** [comment]
Looks like TF binary fail to initialize, it's probably because of CPU incompatible. Can you let us know which CPU you are using?

**Comment by phatht** [comment]
@behnamasaei  how did you fix it? can you let me know
@LittleLittleCloud[](https://user-images.githubusercontent.com/40348487/155050535-01f3f053-7d48-4e98-b66d-e427a3f04dba.png) Can you help me with this issue?
my info CPU
image

thanks all
Phat.

**Comment by Zimo** [comment]
Installing the latest version of "VC_redist.x64.exe" solved the issue for me.

I hope this will help others!
