### ISSUE TITLE
Training Error for Image classification>Local(CPU).

### ISSUE THREAD

**Issue by vzhuqin** [dotnet/machinelearning-modelbuilder#1980]
**System Information (please complete the following information):**
 - Model Builder Version (available in Manage Extensions dialog): 16.12.0.2206201
 - Microsoft Visual Studio Enterprise 2022 (64-bit) Version 17.0.4

**Describe the bug**
- If you select Forecasting, then back to select Image classification>Local (CPU), will encounter the model builder error while training the model. 
- Not occur this issue if switched to Image classification>Azure environment

**To Reproduce**

1. Select Create a new project from the Visual Studio 2022 start window;
2. Choose the C# Console App (.NET Core) project template with .Net 6.0;
3. Add model builder by right click on the project;
4. Open the model builder, select Forecasting scenario;
5. Back to Scenario page and select Image classification scenario;
6. Select Local (CPU) environment;
7. Input the Image folder and go Train page;
8. Click "Start training" button, prompts Model Builder Error: 
filePath cannot be null or empty
Parameter name: filePath

**Expected behavior**
No training error after switched different scenarios.

**Screenshots**
![image](https://user-images.githubusercontent.com/81727020/149278227-b4427c56-0983-4071-91bb-a885547cc8d2.png)

**Additional context**
mbconfig file:
![image](https://user-images.githubusercontent.com/81727020/149278612-982427ec-5d84-4907-953f-6c18dda8680d.png)

Error message:
   at Microsoft.ML.Runtime.Contracts.CheckNonEmpty(IExceptionContext ctx, String s, String paramName)
   at Microsoft.ML.ModelOperationsCatalog.Load(String filePath, DataViewSchema& inputSchema)
   at Microsoft.ML.ModelBuilder.AutoMLService.Experiments.LocalAutoMLExperiment.<ExecuteAsync>d__15.MoveNext() in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/Experiments/LocalAutoMLExperiment.cs:line 231
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ML.ModelBuilder.AutoMLEngine.<StartTrainingAsync>d__21.MoveNext() in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/AutoMLEngineService/AutoMLEngine.cs:line 164

**Comment by ymind** [comment]
I had a similar problem:


```txt
2022-01-19 09:45:30.1382 DEBUG AutoMLType: Octopus (Microsoft.ML.ModelBuilder.Utils.Logger.Debug)
2022-01-19 09:45:30.4052 INFO start nni training (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2022-01-19 09:45:30.4332 INFO Experiment output folder: C:\Users\ymind\AppData\Local\Temp\AutoML-NNI\Experiment-ZXY1QG (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2022-01-19 09:45:30.4332 DEBUG row count is unknown, count it explicitly (Microsoft.ML.ModelBuilder.Utils.Logger.Debug)
2022-01-19 09:45:30.4332 DEBUG count elapse 0ms (Microsoft.ML.ModelBuilder.Utils.Logger.Debug)
2022-01-19 09:45:30.4332 INFO |     Trainer                              MicroAccuracy  MacroAccuracy  Duration #Iteration                     | (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2022-01-19 09:45:30.6114 DEBUG update train dataset C:\Users\ymind\AppData\Local\Temp\AutoML-NNI\Experiment-ZXY1QG\train.bin (Microsoft.ML.ModelBuilder.Utils.Logger.Debug)
2022-01-19 09:45:30.6334 DEBUG update test dataset C:\Users\ymind\AppData\Local\Temp\AutoML-NNI\Experiment-ZXY1QG\test.bin (Microsoft.ML.ModelBuilder.Utils.Logger.Debug)
2022-01-19 09:45:32.2782 INFO Trial 0 encounter error with message: Splitter/consolidator worker encountered exception while consuming source data (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2022-01-19 09:45:32.3232 DEBUG    在 Microsoft.ML.Data.DataViewUtils.Splitter.Batch.SetAll(OutPipe[] pipes)
   在 Microsoft.ML.Data.DataViewUtils.Splitter.Cursor.MoveNextCore()
   在 Microsoft.ML.Data.RootCursorBase.MoveNext()
   在 Microsoft.ML.Vision.ImageClassificationTrainer.CacheFeaturizedImagesToDisk(IDataView input, String labelColumnName, String imageColumnName, ImageProcessor imageProcessor, String inputTensorName, String outputTensorName, String cacheFilePath, Dataset dataset, Action`1 metricsCallback, Nullable`1 validationFraction)
   在 Microsoft.ML.Vision.ImageClassificationTrainer.TrainModelCore(TrainContext trainContext)
   在 Microsoft.ML.Trainers.TrainerEstimatorBase`2.TrainTransformer(IDataView trainSet, IDataView validationSet, IPredictor initPredictor)
   在 Microsoft.ML.Data.EstimatorChain`1.Fit(IDataView input)
   在 Microsoft.ML.ModelBuilder.AutoMLService.MulticlassClassificationRunner.RunTrainTestSplit(TrialParameter parameter, TrainingConfiguration config, IDataView trainDatasetCache, IDataView testDatasetCache) 位置 /_/src/Microsoft.ML.ModelBuilder.AutoMLService/Runner/MulticlassClassificationRunner.cs:行号 70
   在 Microsoft.ML.ModelBuilder.AutoMLService.LocalDispatcher.Run() 位置 /_/src/Microsoft.ML.ModelBuilder.AutoMLService/Dispatcher/LocalDispatcher.cs:行号 155
   在 System.Threading.Tasks.Task.Execute()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 Microsoft.ML.ModelBuilder.AutoMLService.LocalDispatcher.<RunAsync>d__19.MoveNext() 位置 /_/src/Microsoft.ML.ModelBuilder.AutoMLService/Dispatcher/LocalDispatcher.cs:行号 164
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 Microsoft.ML.ModelBuilder.AutoMLService.LocalDispatcher.<AddTrialAsync>d__16.MoveNext() 位置 /_/src/Microsoft.ML.ModelBuilder.AutoMLService/Dispatcher/LocalDispatcher.cs:行号 49 (Microsoft.ML.ModelBuilder.Utils.Logger.Debug)
2022-01-19 09:45:32.3232 DEBUG update best config to trial id 0, current best metric is 0 (Microsoft.ML.ModelBuilder.Utils.Logger.Debug)
2022-01-19 09:45:32.3232 DEBUG create new thread 0 (Microsoft.ML.ModelBuilder.Utils.Logger.Debug)
```

**Comment by beccamc** [comment]
@ymind Looks like your stack trace is a little different. Do you mind opening a new issue?

**Comment by beccamc** [comment]
@LittleLittleCloud Can you look at the problem reported by Qin?

**Comment by LittleLittleCloud** [comment]
> This issue should already been fixed in latest main. I'll valiate it again though

SHould be fixed already

**Comment by vzhuqin** [comment]
not repro this issue on latest main: 16.12.2.2207401
can complete the training when switched from Forecasting scenario.
![image.png](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/2bca37e3-9b74-4614-b15e-7791000cfdf8)
