### ISSUE TITLE
Run Forecasting notebook error.

### ISSUE THREAD

**Issue by vzhuqin** [dotnet/machinelearning-modelbuilder#1992]
**System Information (please complete the following information):**
 - Notebook Editor [Preview]: 0.2.3.2207504
- ML.Net Model Builder 2022: 16.12.2.2207601
 - Microsoft Visual Studio Enterprise 2022 (64-bit) Version 17.0.5

**Describe the bug**
- On which step of the process did you run into an issue: Run Forecasting notebook 
- Clear description of the problem: the "Horozon" is set to default 10, but display exception: The horizon parameter should be greater than 0. (Parameter 'horizon')
![image](https://user-images.githubusercontent.com/81727020/151316382-dcb65c06-d179-4bdb-870e-004290258490.png)
![image](https://user-images.githubusercontent.com/81727020/151316434-df39da78-07a9-42cd-af3d-5b677388c6c0.png)

**To Reproduce**

1. Select Create a new project from the Visual Studio 2022 start window;
2. Choose the C# Console App (.NET Core) project template with .Net 6.0;
3. Add model builder by right click on the project;
4. Select Forecasting scenario>Local (CPU);
5. Input the csv data source, select the predict and time series columns;
6. Add Notebook to solution after training completed;
7. Open the Forecasting Notebook file, and click "Run All" button;
8. Display exception as above screenshot.

**Expected behavior**
No error when running forecasting notebook file.

**Additional context**
Error message:
System.ArgumentOutOfRangeException: The horizon parameter should be greater than 0. (Parameter 'horizon')
   at Microsoft.ML.Transforms.TimeSeries.AdaptiveSingularSpectrumSequenceModelerInternal.Forecast(ForecastResultBase`1& result, Int32 horizon)
   at Microsoft.ML.Transforms.TimeSeries.AdaptiveSingularSpectrumSequenceModelerInternal.Forecast(Int32 horizon)
   at Microsoft.ML.Transforms.TimeSeries.SsaForecastingBaseWrapper.SsaForecastingBase.State.Forecast(VBuffer`1& dst)
   at Microsoft.ML.Transforms.TimeSeries.SequentialForecastingTransformBase`2.Mapper.<CreateGetters>b__13_0(VBuffer`1& dst)
   at Microsoft.ML.Data.TypedCursorable`1.TypedRowBase.<>c__DisplayClass8_0`1.<CreateDirectVBufferSetter>b__0(TRow row)
   at Microsoft.ML.Data.TypedCursorable`1.TypedRowBase.FillValues(TRow row)
   at Microsoft.ML.Data.TypedCursorable`1.RowImplementation.FillValues(TRow row)
   at Microsoft.ML.PredictionEngineBase`2.FillValues(TDst prediction)
   at Microsoft.ML.Transforms.TimeSeries.TimeSeriesPredictionEngine`2.Predict(TSrc example, TDst& prediction, Nullable`1 horizon, Nullable`1 confidenceLevel)
   at Microsoft.ML.Transforms.TimeSeries.TimeSeriesPredictionEngine`2.Predict(Nullable`1 horizon, Nullable`1 confidenceLevel)
   at Submission#6.<<Initialize>>d__0.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.CodeAnalysis.Scripting.ScriptExecutionState.RunSubmissionsAsync[TResult](ImmutableArray`1 precedingExecutors, Func`2 currentExecutor, StrongBox`1 exceptionHolderOpt, Func`2 catchExceptionOpt, CancellationToken cancellationToken)

**Comment by vzhuqin** [comment]
Not repro this issue on latest main:
- Notebook Editor [Preview]: 0.2.3.2210302

- ML.Net Model Builder: 16.13.1.2210302

![image.png](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/5f2a7d40-74ef-4f20-b999-9750c20fd48e)
