### ISSUE TITLE
[Forecasting] Error thrown when making prediction using generated Web API project 

### ISSUE THREAD

**Issue by luisquintanilla** [dotnet/machinelearning-modelbuilder#2006]
**System Information (please complete the following information):**
 - Model Builder Version (available in Manage Extensions dialog): 16.13.1.2210302
 - Visual Studio Version: VS2022

**Describe the bug**
- On which step of the process did you run into an issue: Consume
- Clear description of the problem: When making an HTTP request using the generated Web API project, an error is thrown.

**To Reproduce**
1. Start generated Web API project
2. Make an HTTP POST request to `predict` Web API endpoint with ModelInput data

```json
{
	"ProductSales": 20.0
}
```

**Expected behavior**
I would expect a response that looks like a `ModelOutput` object. 

**Additional context**

Error Message:  

```text
 System.ArgumentOutOfRangeException: Must be a row to row mapper (Parameter 'transformer')
         at Microsoft.ML.Runtime.Contracts.CheckParam(IExceptionContext ctx, Boolean f, String paramName, String msg)
         at Microsoft.ML.PredictionEngineBase`2.TransformerChecker(IExceptionContext ectx, ITransformer transformer)
         at Microsoft.ML.PredictionEngineBase`2..ctor(IHostEnvironment env, ITransformer transformer, Boolean ignoreMissingColumns, SchemaDefinition inputSchemaDefinition, SchemaDefinition outputSchemaDefinition, Boolean ownsTransformer)
         at Microsoft.ML.PredictionEngine`2..ctor(IHostEnvironment env, ITransformer transformer, Boolean ignoreMissingColumns, SchemaDefinition inputSchemaDefinition, SchemaDefinition outputSchemaDefinition, Boolean ownsTransformer)
         at Microsoft.ML.PredictionEngineExtensions.CreatePredictionEngine[TSrc,TDst](ITransformer transformer, IHostEnvironment env, Boolean ignoreMissingColumns, SchemaDefinition inputSchemaDefinition, SchemaDefinition outputSchemaDefinition, Boolean ownsTransformer)
         at Microsoft.ML.ModelOperationsCatalog.CreatePredictionEngine[TSrc,TDst](ITransformer transformer, Boolean ignoreMissingColumns, SchemaDefinition inputSchemaDefinition, SchemaDefinition outputSchemaDefinition)
         at Microsoft.Extensions.ML.PredictionEnginePoolPolicy`2.Create()
         at Microsoft.Extensions.ObjectPool.DefaultObjectPool`1.Create()
         at Microsoft.Extensions.ObjectPool.DefaultObjectPool`1.Get()
         at Microsoft.Extensions.ML.PredictionEnginePool`2.GetPredictionEngine(String modelName)
         at Microsoft.Extensions.ML.PredictionEnginePoolExtensions.Predict[TData,TPrediction](PredictionEnginePool`2 predictionEnginePool, String modelName, TData example)
         at Microsoft.Extensions.ML.PredictionEnginePoolExtensions.Predict[TData,TPrediction](PredictionEnginePool`2 predictionEnginePool, TData example)
         at Program.<>c.<<<Main>$>b__0_2>d.MoveNext() in C:\Users\luquinta.REDMOND\source\repos\ReactorContainerAppsLive\TimeSeries_WebApi1\Program.cs:line 34
      --- End of stack trace from previous location ---
         at Microsoft.AspNetCore.Http.RequestDelegateFactory.<ExecuteTask>g__ExecuteAwaited|58_0[T](Task`1 task, HttpContext httpContext)
         at Microsoft.AspNetCore.Http.RequestDelegateFactory.<>c__DisplayClass46_3.<<HandleRequestBodyAndCompileRequestDelegate>b__2>d.MoveNext()
      --- End of stack trace from previous location ---
         at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
         at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
         at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
         at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

The reason for this error most likely is due to [PredictionEngine](https://docs.microsoft.com/en-us/dotnet/api/microsoft.ml.predictionengine-2?view=ml-dotnet) and [TimeSeriesPredictionEngine](https://docs.microsoft.com/en-us/dotnet/api/microsoft.ml.transforms.timeseries.timeseriespredictionengine-2?view=ml-dotnet) work slightly differently.

The generated code might need to change for this specific scenario. Here's a working sample of a MinimalWebAPI using TimeSeriesPredictionEngine.

[https://github.com/luisquintanilla/mlnet-minimal-weather](https://github.com/luisquintanilla/mlnet-minimal-weather). Note that this sample uses a preview version of .NET 6 so the updated version would look closer to the existing template.

**Comment by beccamc** [comment]
@LittleLittleCloud Can you take a look?

**Comment by Tradyn** [comment]
Can someone provide a fix for this?

**Comment by beccamc** [comment]
@LittleLittleCloud Is this fixed? Jake thinks it might be fixed.

**Comment by luisquintanilla** [comment]
IIRC, I tried with the latest release and it still wasn't fixed.

**Comment by luisquintanilla** [comment]
@LittleLittleCloud to investigate

**Comment by luisquintanilla** [comment]
@v-Hailishi can you please validate whether this has been fixed in the latest version. Thanks.

**Comment by v-Hailishi** [comment]
@luisquintanilla I have tried on the latest main branch 16.13.10.2246201 for VS2022, the webapi.program.cs has been updated like below and Web API project also can be run successfully.
![image](https://user-images.githubusercontent.com/99375895/189813292-feadce51-bd55-40be-980a-dd927843bbb4.png)
![image](https://user-images.githubusercontent.com/99375895/189813395-7a5b66e5-9e06-4733-90bd-9ebdc8cd2cd5.png)

**Comment by luisquintanilla** [comment]
Perfect. Thanks @v-Hailishi @LittleLittleCloud 

Closing this issue.
