### ISSUE TITLE
Forecasting: Training error for Data source from SQLPassword.

### ISSUE THREAD

**Issue by vzhuqin** [dotnet/machinelearning-modelbuilder#2017]
**System Information (please complete the following information):**
 - Model Builder Version (available in Manage Extensions dialog): 16.13.1.2210902 (latest main)
 - Microsoft Visual Studio Enterprise 2019: 16.11.10

**Describe the bug**
- On which step of the process did you run into an issue: Training Forecasting with Data source from SQLPassword.

**TestMatrix**
https://testpass.blob.core.windows.net/test-pass-data/forecasting.csv

**To Reproduce**
1. **Pre-requisite**: Do [Pre-requisites/SQLPassword](https://github.com/dotnet/machinelearning-tools/blob/main/docs/tests/Instructions/Pre-Requisites/SQLPassword.md) before repro this issue.
2. Select Create a new project from the Visual Studio 2019 start window;
3. Choose the C# Console App (.NET Core) project template with .Net 5.0;
4. Add model builder by right click on the project;
5. Select Forecasting scenario>Local (CPU);
6. On Data page, select>SQL Server>Microsoft SQL Server>SQL Server Authentication to input the data source;
7. Navigate to Train page after set the data column;
8. Click Start training button, prompt model builder error as below screenshot.

**Expected behavior**
No error for training Data source from SQLPassword.

**Screenshots**
Data settings:
![image](https://user-images.githubusercontent.com/81727020/153328775-e727e67d-6ff4-489b-938c-f9b2bfd66ac9.png)

Error screenshot:
![image](https://user-images.githubusercontent.com/81727020/153327352-5766eee1-8f29-47be-8e48-c8463a524b64.png)

**Additional context**
Error info:
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
   at System.Data.SqlClient.SqlDataReader.get_MetaData()
   at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption, Boolean shouldCacheForAlwaysEncrypted)
   at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method)
   at System.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior, String method)
   at Microsoft.ML.Data.DatabaseLoader.Cursor.get_DataReader()
   at Microsoft.ML.Data.DatabaseLoader.Cursor.MoveNextCore()
   at Microsoft.ML.Data.RootCursorBase.MoveNext()
   at Microsoft.ML.ModelBuilder.AutoMLService.Proposer.Controller.CountRows(IDataView data, Int64 maxRows) in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/Proposer/Controller.cs:line 174
   at Microsoft.ML.ModelBuilder.AutoMLService.Proposer.Controller.Initialize() in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/Proposer/Controller.cs:line 111
   at Microsoft.ML.ModelBuilder.AutoMLService.Experiments.LocalAutoMLExperiment.<ExecuteAsync>d__15.MoveNext() in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/Experiments/LocalAutoMLExperiment.cs:line 138
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ML.ModelBuilder.AutoMLEngine.<StartTrainingAsync>d__21.MoveNext() in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/AutoMLEngineService/AutoMLEngine.cs:line 160

**Comment by LittleLittleCloud** [comment]
@beccamc 

Is that because the column name is `Index` somehow

**Comment by v-Hailishi** [comment]
@beccamc @LittleLittleCloud I tried to change the column name "index" to "**index1**" when adding data "forecasting.csv" to the database. Then training Forecasting with Data source from SQLPassword is successful now.
Could you help to confirm whether this above error is expected or not?
![image](https://user-images.githubusercontent.com/99375895/158765186-83ef2b19-91fc-4173-b384-51076ffde8ad.png)

**Comment by beccamc** [comment]
Duplicate of https://github.com/dotnet/machinelearning-modelbuilder/issues/2070
