### ISSUE TITLE
CLI progress bar causes failure on Linux

### ISSUE THREAD

**Issue by beccamc** [dotnet/machinelearning-modelbuilder#2045]
Problem using the CLI on Linux machines. Per XiaoYun the problem is the progress bar feature. 

Start Training
start nni training
System.ArgumentOutOfRangeException: Count cannot be less than zero. (Parameter 'count')
   at System.String.Ctor(Char c, Int32 count)
   at Microsoft.ML.CLI.FixDuriationTimeProgressBar.get_ProgressBar() in /_/src/mlnet/Utilities/FixDuriationTimeProgressBar.cs:line 44
   at Microsoft.ML.CLI.FixDuriationTimeProgressBar.Draw() in /_/src/mlnet/Utilities/FixDuriationTimeProgressBar.cs:line 72
   at Microsoft.ML.CLI.Utilities.PBarConsolePrinter.Print(String msg) in /_/src/mlnet/Utilities/PBarConsolePrinter.cs:line 43
   at Microsoft.ML.CLI.Runners.AutoMLRunner.Instance_DiagnosticDataReceived(Object sender, DataReceivedEventArgs e) in /_/src/mlnet/Runners/AutoMLRunner.cs:line 109
   at Microsoft.ML.ModelBuilder.AutoMLService.AutoMLServiceLogger.Log(AutoMLServiceLogLevel loglevel, String msg) in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/AutoMLServiceLogger.cs:line 45
   at Microsoft.ML.ModelBuilder.AutoMLService.AutoMLServiceLogger.Info(String msg) in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/AutoMLServiceLogger.cs:line 27
   at Microsoft.ML.ModelBuilder.AutoMLService.Experiments.LocalAutoMLExperiment.ExecuteAsync(IDataView trainData, IDataView validateData, ColumnInformation columnInformation, CancellationToken cancellationToken, CancellationToken timeout) in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/Experiments/LocalAutoMLExperiment.cs:line 65
   at Microsoft.ML.ModelBuilder.AutoMLEngine.StartTrainingAsync(TrainingConfiguration config, PathConfiguration pathConfig, CancellationToken userCancellationToken) in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/AutoMLEngineService/AutoMLEngine.cs:line 160
   at Microsoft.ML.CLI.Runners.AutoMLRunner.ExecuteAsync() in /_/src/mlnet/Runners/AutoMLRunner.cs:line 88
   at Microsoft.ML.CLI.Program.TrainAsync(TrainingConfiguration trainingConfiguration, PathConfiguration pathConfig, AutoMLServiceLogLevel logLevel) in /_/src/mlnet/Program.cs:line 348
   at Microsoft.ML.CLI.Program.AutoMLCommandRunner(AutoMLCommand command, Boolean skipGenerateConsoleApp) in /_/src/mlnet/Program.cs:line 329
   at Microsoft.ML.CLI.Program.<>c.<<CreateRootCommandLineBuilder>b__4_1>d.MoveNext() in /_/src/mlnet/Program.cs:line 116
--- End of stack trace from previous location ---
   at System.CommandLine.Invocation.CommandHandler.GetExitCodeAsync(Object value, InvocationContext context)
   at System.CommandLine.Invocation.ModelBindingCommandHandler.InvokeAsync(InvocationContext context)
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass23_0.<<UseParseErrorReporting>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.ML.CLI.Program.<>c__DisplayClass4_0.<<CreateRootCommandLineBuilder>b__9>d.MoveNext() in /_/src/mlnet/Program.cs:line 290
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseSuggestDirective>b__24_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass22_0.<<UseParseDirective>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass11_0.<<UseDebugDirective>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<RegisterWithDotnetSuggest>b__10_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass14_0.<<UseExceptionHandler>b__0>d.MoveNext()

**Comment by beccamc** [comment]
@LittleLittleCloud FYI I filed this issue for tracking

**Comment by beccamc** [comment]
@LittleLittleCloud Is this resolved?

**Comment by LittleLittleCloud** [comment]
Nope it's not,, I haven't got time to look into it yet.

**Comment by luisquintanilla** [comment]
@LittleLittleCloud are we okay to close this issue since dotnet/machinelearning-tools#1425 has been merged?

**Comment by LittleLittleCloud** [comment]
Yep
