### ISSUE TITLE
Training has failed.

### ISSUE THREAD

**Issue by AmrAHammad** [dotnet/machinelearning-modelbuilder#2060]
**System Information (please complete the following information):**
 - Model Builder Version (available in Manage Extensions dialog): 
 - ML.NET Model Builder 2019 Version 16.13.1.2210301
 - Visual Studio Version  Microsoft Visual Studio Enterprise 2019
Version 16.11.10

Create a simple object detection model using small data 
- On which step of the process did you run into an issue:
An error in the training step.
- Clear description of the problem:
   at AzureML.AutoMLRunMonitoringImages.<MonitorParentRunAsync>d__1.MoveNext() in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/RemoteAutoML/AutoMLRunMonitoringImages.cs:line 137
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at AzureML.AutoMLRunnerImages.<RunAutoMLAsync>d__24.MoveNext() in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/RemoteAutoML/AutoMLRunnerImages.cs:line 190
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ML.ModelBuilder.AutoMLService.Experiments.AzureImageClassificationExperiment.<ExecuteAsync>d__14.MoveNext() in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/Experiments/AzureImageClassificationExperiment.cs:line 63
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ML.ModelBuilder.AutoMLEngine.<StartTrainingAsync>d__21.MoveNext() in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/AutoMLEngineService/AutoMLEngine.cs:line 160
 

run id https://ml.azure.com/experiments/id/18c91d44-f432-445e-b78c-80c4543fb483/runs/AutoML_4e8df8e6-b0c2-48ef-b4f5-51e744d543ef?wsid=/subscriptions/2f77bb1f-941c-489a-a7bb-3a5e73ae90c1/resourceGroups/InjazResourceGroup/providers/Microsoft.MachineLearningServices/workspaces/NewWorkspace

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by luisquintanilla** [comment]
Hi @AmrAHammad 

Sorry to hear you ran into this issue. We're currently working on a fix. In the meantime, follow issue #2056 where we're tracking this bug and posting updates. Closing this issue for now. Let us know if you have additional questions.
