### ISSUE TITLE
The remote server returned an error: (401) Unauthorized.

### ISSUE THREAD

**Issue by AmrAHammad** [dotnet/machinelearning-modelbuilder#2066]
System Information (please complete the following information):

Model Builder Version (available in Manage Extensions dialog): version 16.13.1.2210301
Visual Studio Version Microsoft Visual Studio Community 2019
Version 16.11.3
Describe the bug
while training object detection model , i got the below error , however , on Azure the model completed succesfully.

On which step of the process did you run into an issue:
Training
Clear description of the problem:
While training object detection model i received the following error
at AzureML.FailureCounter.d__6.MoveNext() in //src/Microsoft.ML.ModelBuilder.AutoMLService/RemoteAutoML/FailureCounter.cs:line 49
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at AzureML.AutoMLRunMonitoringImages.d__1.MoveNext() in //src/Microsoft.ML.ModelBuilder.AutoMLService/RemoteAutoML/AutoMLRunMonitoringImages.cs:line 146
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at AzureML.AutoMLRunnerImages.d__24.MoveNext() in //src/Microsoft.ML.ModelBuilder.AutoMLService/RemoteAutoML/AutoMLRunnerImages.cs:line 190
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Microsoft.ML.ModelBuilder.AutoMLService.Experiments.AzureImageClassificationExperiment.d__14.MoveNext() in //src/Microsoft.ML.ModelBuilder.AutoMLService/Experiments/AzureImageClassificationExperiment.cs:line 63
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Microsoft.ML.ModelBuilder.AutoMLEngine.d__21.MoveNext() in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/AutoMLEngineService/AutoMLEngine.cs:line 160
Please include run id https://ml.azure.com/experiments/id/18c91d44-f432-445e-b78c-80c4543fb483/runs/AutoML_8d9c450d-081b-4900-a283-ab345bbece0f?wsid=/subscriptions/2f77bb1f-941c-489a-a7bb-3a5e73ae90c1/resourceGroups/InjazResourceGroup/providers/Microsoft.MachineLearningServices/workspaces/NewWorkspace in the report

Expected behavior
Training complete succesfully

**Comment by beccamc** [comment]
Sorry you ran into this problem @AmrAHammad!  Are you able to access the run via Azure ML Workspace portal? Clicking on the link above should take you there. If you can access the link via the web, are you logged into VS with the same id?

**Comment by AmrAHammad** [comment]
> Sorry you ran into this problem @AmrAHammad! Are you able to access the run via Azure ML Workspace portal? Clicking on the link above should take you there. If you can access the link via the web, are you logged into VS with the same id?

Hello @beccamc ,
Yes, i can access the via Azure ML workspace portal.

**Comment by beccamc** [comment]
And you are logged in with the same user to VS?

**Comment by beccamc** [comment]
@JakeRadMSFT Can you add details here if there has been an investigation?

**Comment by AmrAHammad** [comment]
> And you are logged in with the same user to VS?

Yes

**Comment by beccamc** [comment]
Two things...
- Are you on the Azure global cloud? Or one of the other clouds (China, German, US Govt)? 
- Can you update your Model Builder to the latest version? https://marketplace.visualstudio.com/items?itemName=MLNET.07

**Comment by beccamc** [comment]
We've just released a new model builder! If you're not on the Azure global cloud your auth problem should now be fixed. - https://marketplace.visualstudio.com/items?itemName=MLNET.ModelBuilder2022
