### ISSUE TITLE
Data Classification:  Model Builder Error when start of training: Incorrect syntax near the keyword 'Key'.

### ISSUE THREAD

**Issue by KiloBravoLima** [dotnet/machinelearning-modelbuilder#2070]
**Model Builder Version**: _16.13.1.2210302_
**Visual Studion Version**:  _Microsoft Visual Studio Community 2022 (64-bit) - Current Version 17.1.1_

**Bug description**
_In Data Classification senerio, where a tabel, with a column named Key, is data source. The data can't be read because of SQL syntaks error . Key is a SQL keyword. The Key column  should be referenced as "[Key]" in SQL query text.

**Steps to Reproduce**
1. _Create new console app project._
2. _Add ML.Net Model builder_
3. Choose Data Classification seneario
4. Enviroment is Local CPU
5. Data input is SQL server, some DB table with column named Key.
6. Some other column selected to predict
7. Data Preview shows ok 10 rows of 39.985
8. Choose Time to train = 600 sec 
9. Press Start training button
10. Error message "Incorrect syntax near the keyword 'Key'" and stack dump shows up

**Expected Experience**
_Traning to run in 10 min_

**Actual Experience**
_Error message "Incorrect syntax near the keyword 'Key'" and stack dump shows up_

**Additional Context**
Stack 
Incorrect syntax near the keyword 'Key'.
at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
   at System.Data.SqlClient.SqlDataReader.get_MetaData()
   at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption, Boolean shouldCacheForAlwaysEncrypted)
   at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method)
   at System.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior, String method)
   at Microsoft.ML.Data.DatabaseLoader.Cursor.get_DataReader()
   at Microsoft.ML.Data.DatabaseLoader.Cursor.MoveNextCore()
   at Microsoft.ML.Data.RootCursorBase.MoveNext()
   at Microsoft.ML.ModelBuilder.AutoMLService.Proposer.Controller.CountRows(IDataView data, Int64 maxRows) in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/Proposer/Controller.cs:line 174
   at Microsoft.ML.ModelBuilder.AutoMLService.Proposer.Controller.Initialize() in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/Proposer/Controller.cs:line 111
   at Microsoft.ML.ModelBuilder.AutoMLService.Experiments.LocalAutoMLExperiment.<ExecuteAsync>d__15.MoveNext() in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/Experiments/LocalAutoMLExperiment.cs:line 138
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ML.ModelBuilder.AutoMLEngine.<StartTrainingAsync>d__21.MoveNext() in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/AutoMLEngineService/AutoMLEngine.cs:line 160

**Comment by beccamc** [comment]
This fix has shipped! Please install the latest version of Model Builder [16.14.0](https://marketplace.visualstudio.com/items?itemName=MLNET.ModelBuilder2022) to see the change. 

The SQL query now escapes column names. Let us know how it goes!
