### ISSUE TITLE
Data Classification: Model Builder Error message "Shuffle input cursor reader failed with an exception"

### ISSUE THREAD

**Issue by KiloBravoLima** [dotnet/machinelearning-modelbuilder#2071]
**System Information (please complete the following information):**
 - Model Builder Version (available in Manage Extensions dialog): 16.13.1.2210302
 - Visual Studio Version: Microsoft Visual Studio Community 2022 (64-bit) - Current Version 17.1.1

**Describe the bug**
- On which step of the process did you run into an issue: Training
- Clear description of the problem: Exception in Microsoft.ML.Transforms.RowShufflingTransformer.Cursor.MoveNextCore() when data input is a SQL server, and the choosen Table actually is a SQL server view. The SQL server view selects (all) columns from a single table, just renaming two columns of type String (from Key to ContainerKey and Type to ContainerType)

**To Reproduce**
1. Create new console app project.
2. Add ML.Net Model builder
3. Choose Data Classification seneario
4. Enviroment is Local CPU
5. Data input is SQL server, some DB view with two renamed columns (from Key to ContainerKey and Type to ContainerType)
6. Some other column selected to predict
7. Data Preview shows ok 10 rows of 39.985
8. Choose Time to train = 60 sec
9. Press Start training button
10. Error message "Shuffle input cursor reader failed with an exception'" and stack dump shows up
11. Pressing Start traning again actually will let the training run. In the loop an error message are written in Output pane: "Trial 689 encounter error with message: Read only 0 bytes in file, expected header size of 256"
12. After loop ends an Error message dialog are shown: Training time finished without any models trained.

**Expected behavior**
_Training runnig for 60 seconds. Producing a trained model._

**Additional context**
_ML Model log file
2022-03-17 14:28:23.3141 INFO Set log file path to C:\Users\kbl\AppData\Local\Temp\MLVSTools\logs\MLModel1-2FCBTX.txt (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2022-03-17 14:29:16.8359 INFO start nni training (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2022-03-17 14:29:16.8479 INFO Experiment output folder: C:\Users\kbl\AppData\Local\Temp\AutoML-NNI\Experiment-1C6Y0N (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2022-03-17 14:29:16.8479 DEBUG row count is unknown, count it explicitly (Microsoft.ML.ModelBuilder.Utils.Logger.Debug)
2022-03-17 14:29:17.3847 DEBUG count elapse 535ms (Microsoft.ML.ModelBuilder.Utils.Logger.Debug)
2022-03-17 14:29:17.3847 INFO |     Trainer                              MicroAccuracy  MacroAccuracy  Duration #Iteration                     | (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2022-03-17 14:29:17.5989 DEBUG Shuffle input cursor reader failed with an exception
   at Microsoft.ML.Transforms.RowShufflingTransformer.Cursor.MoveNextCore()
   at Microsoft.ML.Data.RootCursorBase.MoveNext()
   at Microsoft.ML.Data.LinkedRowFilterCursorBase.MoveNextCore()
   at Microsoft.ML.Data.RootCursorBase.MoveNext()
   at Microsoft.ML.Data.IO.BinarySaver.RowsPerBlockHeuristic(IDataView data, ColumnCodec[] actives)
   at Microsoft.ML.Data.IO.BinarySaver.SaveData(Stream stream, IDataView data, Int32[] colIndices)
   at Microsoft.ML.Data.DataSaverUtils.SaveDataView(IChannel ch, IDataSaver saver, IDataView view, Stream stream, Boolean keepHidden)
   at Microsoft.ML.BinaryLoaderSaverCatalog.SaveAsBinary(DataOperationsCatalog catalog, IDataView data, Stream stream, Boolean keepHidden)
   at Microsoft.ML.ModelBuilder.AutoMLService.Proposer.ResampleStrategyProposer.Initialize(String outputFolder) in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/Proposer/ResampleStrategyProposer.cs:line 97
   at Microsoft.ML.ModelBuilder.AutoMLService.Proposer.ResampleStrategyProposer.Propose(TrialParameter trialParameter) in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/Proposer/ResampleStrategyProposer.cs:line 59
   at Microsoft.ML.ModelBuilder.AutoMLService.Proposer.Controller.Propose() in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/Proposer/Controller.cs:line 66
   at Microsoft.ML.ModelBuilder.AutoMLService.Experiments.LocalAutoMLExperiment.<ExecuteAsync>d__15.MoveNext() in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/Experiments/LocalAutoMLExperiment.cs:line 163
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ML.ModelBuilder.AutoMLEngine.<StartTrainingAsync>d__21.MoveNext() in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/AutoMLEngineService/AutoMLEngine.cs:line 160 (Microsoft.ML.ModelBuilder.Utils.Logger.Debug)

**Comment by philipbawn** [comment]
I have the same problem on VS 17.0.6 model builder 16.13.1.2210302 with SQL server using a table. I exported the same data to a CSV the training process is now running.

**Comment by beccamc** [comment]
Sorry you're experiencing this problem! Do you have a DateTime or GUID column type in the SQL table?

**Comment by luisquintanilla** [comment]
Closing due to lack of activity. Work is already ongoing for DateTime support and ignoring GUID columns.
