### ISSUE TITLE
"Input string was not in a correct format" error while model is trained

### ISSUE THREAD

**Issue by zabanet** [dotnet/machinelearning-modelbuilder#2072]
- Model Builder Version: 16.13.1.2210302
 - Visual Studio Version: 17.1.1

- On which step of the process did you run into an issue:
  when training ObjectDetection model after seeing in the console "Child run status:Finalizing: 1": 
- Clear description of the problem:
Network error message is appearing (5 times in a row - my network is perfectly well):

![image](https://user-images.githubusercontent.com/34971815/159177956-47cf0fee-21f7-4407-9324-73711b7b0ac0.png)

When I click "Yes" for retry it shows the same message again and again. When I click "No" then "Input string was not in a correct format" error shows up in console (detailed stack trace below).  Attached json file and training log.

**To Reproduce**
1. Create console application (dotnet 6)
2. Add Machine Learning Model
3. Select Object Detection Scenario
4. Select Azure Subscription, create workspace, compute and experiment
5. Select data for learning (attached [Inovice-Recognizer-export.zip])
6. Start training

**Expected behavior**
Model should be trained and Evaluation enabled

**Additional context**

Model Builder Error:
   at AzureML.FailureCounter.<RecordFailureWithRetryWarningAsync>d__6.MoveNext() in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/RemoteAutoML/FailureCounter.cs:line 49
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at AzureML.AutoMLRunMonitoringImages.<MonitorParentRunAsync>d__1.MoveNext() in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/RemoteAutoML/AutoMLRunMonitoringImages.cs:line 146
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at AzureML.AutoMLRunnerImages.<RunAutoMLAsync>d__24.MoveNext() in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/RemoteAutoML/AutoMLRunnerImages.cs:line 190
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ML.ModelBuilder.AutoMLService.Experiments.AzureImageClassificationExperiment.<ExecuteAsync>d__14.MoveNext() in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/Experiments/AzureImageClassificationExperiment.cs:line 63
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ML.ModelBuilder.AutoMLEngine.<StartTrainingAsync>d__21.MoveNext() in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/AutoMLEngineService/AutoMLEngine.cs:line 160

Additional info:

Run id https://ml.azure.com/experiments/id/0bce9ab0-ea9c-4a95-b4e7-c4cfe32534b9/runs/AutoML_1b962f90-7893-4f2c-a091-f3166c78f72c?wsid=/subscriptions/552e21f8-c102-4adf-8653-1d3dd218f7ab/resourceGroups/DefaultResourceGroup-NEU/providers/Microsoft.MachineLearningServices/workspaces/CSI-ML in the report

[InvoiceModel-4214UV.txt](https://github.com/dotnet/machinelearning-modelbuilder/files/8309476/InvoiceModel-4214UV.txt)
[Inovice-Recognizer-export.zip](https://github.com/dotnet/machinelearning-modelbuilder/files/8309541/Inovice-Recognizer-export.zip)

**Comment by JellalEternal** [comment]
I have exactly the same "Network error message" followed by the same "Model Builder Error" when I have in console "Child run status:Finalizing: 1" :/
Do you find any solution ?

**Comment by zabanet** [comment]
No. Strange that maintainers didn't respond. Is this project alive?

**Comment by JellalEternal** [comment]
Yes strange that maintainers didn't respond :/ Yes it's still alive

**Comment by beccamc** [comment]
Sorry, this issue got lost somehow. 

1. Can you upgrade to the latest version of model builder? https://marketplace.visualstudio.com/items?itemName=MLNET.ModelBuilder2022
2. Are both of you on the Global Azure cloud?
3. Is there an error in the Azure run? Sometimes errors appear in the child runs.

**Comment by beccamc** [comment]
Sorry, we don't have enough information to investigate this issue. If you're still seeing a problem on the [latest model builder](https://marketplace.visualstudio.com/items?itemName=MLNET.ModelBuilder2022) please ping me and we will reopen.
