### ISSUE TITLE
Model Builder Error The remote server returned an error: (401) Unauthorized. 

### ISSUE THREAD

**Issue by AmrAHammad** [dotnet/machinelearning-modelbuilder#2077]
**System Information (please complete the following information):**
 - Model Builder Version (16.13.1.2210301) 
 - Visual Studio Version : Microsoft Visual Studio Enterprise 2019 , Version 16.11.10

**Describe the bug**
Error with training Object Detection Model on Azure
- On which step of the process did you run into an issue:
The failure in the training step
- Clear description of the problem:
   at AzureML.FailureCounter.<RecordFailureWithRetryWarningAsync>d__6.MoveNext() in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/RemoteAutoML/FailureCounter.cs:line 49
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at AzureML.AutoMLRunMonitoringImages.<MonitorParentRunAsync>d__1.MoveNext() in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/RemoteAutoML/AutoMLRunMonitoringImages.cs:line 146
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at AzureML.AutoMLRunnerImages.<RunAutoMLAsync>d__24.MoveNext() in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/RemoteAutoML/AutoMLRunnerImages.cs:line 190
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ML.ModelBuilder.AutoMLService.Experiments.AzureImageClassificationExperiment.<ExecuteAsync>d__14.MoveNext() in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/Experiments/AzureImageClassificationExperiment.cs:line 63
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ML.ModelBuilder.AutoMLEngine.<StartTrainingAsync>d__21.MoveNext() in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/AutoMLEngineService/AutoMLEngine.cs:line 160
 

Please include run id https://ml.azure.com/experiments/id/18c91d44-f432-445e-b78c-80c4543fb483/runs/AutoML_e3de7747-3410-4c8f-a005-9e9a99555fd1?wsid=/subscriptions/2f77bb1f-941c-489a-a7bb-3a5e73ae90c1/resourceGroups/InjazResourceGroup/providers/Microsoft.MachineLearningServices/workspaces/NewWorkspace in the report
**Expected behavior**
The model trained successfully 

**Screenshots**

**Additional context**

**Comment by beccamc** [comment]
@v-Hailishi Can you test if Object Detection is working? We've had a few 401 reports.

**Comment by v-Hailishi** [comment]
@beccamc  Object Detection is working well on the latest main branch: 16.13.5.2217801 for both VS2019&2022.
![image](https://user-images.githubusercontent.com/99375895/160516932-03cea147-380a-4859-82c3-ddfe92047aa0.png)
2019 URL: https://ml.azure.com/experiments/id/8ad34cd8-0b2e-445b-a3a7-5760c3306ece/runs/AutoML_197042bf-bcf1-4a8d-a732-f279c74ce272?wsid=/subscriptions/83635e26-687a-4333-a2a0-33e3cd1f573a/resourceGroups/FullTestPass/providers/Microsoft.MachineLearningServices/workspaces/FullTestPass&tid=72f988bf-86f1-41af-91ab-2d7cd011db47
2022 URL: https://ml.azure.com/experiments/id/8ad34cd8-0b2e-445b-a3a7-5760c3306ece/runs/AutoML_fa87cd38-d82b-4966-a590-f48110faa719?wsid=/subscriptions/83635e26-687a-4333-a2a0-33e3cd1f573a/resourceGroups/FullTestPass/providers/Microsoft.MachineLearningServices/workspaces/FullTestPass&tid=72f988bf-86f1-41af-91ab-2d7cd011db47#details

**Comment by beccamc** [comment]
Closing this as duplicate of https://github.com/dotnet/machinelearning-modelbuilder/issues/2066
