### ISSUE TITLE
MLModel builder can not working with SQL Server??

### ISSUE THREAD

**Issue by nnhao14102000** [dotnet/machinelearning-modelbuilder#2084]
**System Information (please complete the following information):**
 - Model Builder Version: 16.13.1.2210302
 - Visual Studio Version: 17.1.3
 - SQL Server 2019, SQL Server Basic type of Azure

**Describe the bug**
On which step of the process run into an issue:
- Step 1: choose a scenario that is Recommendation.
- Step 2: Choose the data source type is SQL Server, choose a table, columns all are OK.
- Step 3: Start to train and it shows an error: Shuffle input cursor reader failed with an exception (Error 1)
- Step 4: I try train again, and it shows an error: Training time finished without any models trained. (Error2)

Clear description of the problem:
- Error 1:
2022-04-01 13:40:48.7163 INFO Set log file path to C:\Users\Hao\AppData\Local\Temp\MLVSTools\logs\PtoRecommenderModelBuilder-HYOE5L.txt (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2022-04-01 13:42:01.1227 INFO start nni training (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2022-04-01 13:42:01.1227 INFO Experiment output folder: C:\Users\Hao\AppData\Local\Temp\AutoML-NNI\Experiment-XTJ16V (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2022-04-01 13:42:01.1227 DEBUG row count is unknown, count it explicitly (Microsoft.ML.ModelBuilder.Utils.Logger.Debug)
2022-04-01 13:42:01.3651 DEBUG count elapse 240ms (Microsoft.ML.ModelBuilder.Utils.Logger.Debug)
2022-04-01 13:42:01.3651 INFO |     Trainer                             RSquared Absolute-loss Squared-loss RMS-loss  Duration #Iteration      | (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2022-04-01 13:42:01.4044 DEBUG Shuffle input cursor reader failed with an exception
   at Microsoft.ML.Transforms.RowShufflingTransformer.Cursor.MoveNextCore()
   at Microsoft.ML.Data.RootCursorBase.MoveNext()
   at Microsoft.ML.Data.IO.BinarySaver.RowsPerBlockHeuristic(IDataView data, ColumnCodec[] actives)
   at Microsoft.ML.Data.IO.BinarySaver.SaveData(Stream stream, IDataView data, Int32[] colIndices)
   at Microsoft.ML.Data.DataSaverUtils.SaveDataView(IChannel ch, IDataSaver saver, IDataView view, Stream stream, Boolean keepHidden)
   at Microsoft.ML.BinaryLoaderSaverCatalog.SaveAsBinary(DataOperationsCatalog catalog, IDataView data, Stream stream, Boolean keepHidden)
   at Microsoft.ML.ModelBuilder.AutoMLService.Proposer.ResampleStrategyProposer.Initialize(String outputFolder) in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/Proposer/ResampleStrategyProposer.cs:line 89
   at Microsoft.ML.ModelBuilder.AutoMLService.Proposer.ResampleStrategyProposer.Propose(TrialParameter trialParameter) in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/Proposer/ResampleStrategyProposer.cs:line 59
   at Microsoft.ML.ModelBuilder.AutoMLService.Proposer.Controller.Propose() in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/Proposer/Controller.cs:line 66
   at Microsoft.ML.ModelBuilder.AutoMLService.Experiments.LocalAutoMLExperiment.<ExecuteAsync>d__15.MoveNext() in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/Experiments/LocalAutoMLExperiment.cs:line 163
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ML.ModelBuilder.AutoMLEngine.<StartTrainingAsync>d__21.MoveNext() in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/AutoMLEngineService/AutoMLEngine.cs:line 160 (Microsoft.ML.ModelBuilder.Utils.Logger.Debug)

Error 2:
2022-04-01 13:59:32.4157 DEBUG Training time finished without any models trained.
   at Microsoft.ML.ModelBuilder.AutoMLService.Experiments.LocalAutoMLExperiment.<ExecuteAsync>d__15.MoveNext() in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/Experiments/LocalAutoMLExperiment.cs:line 202
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ML.ModelBuilder.AutoMLEngine.<StartTrainingAsync>d__21.MoveNext() in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/AutoMLEngineService/AutoMLEngine.cs:line 160 (Microsoft.ML.ModelBuilder.Utils.Logger.Debug)

**Expected behavior**
Should success to build out the model

**Screenshots**
![image](https://user-images.githubusercontent.com/62060806/161211640-5dcea672-8848-403a-9cfa-1a523e326a3a.png)

**Comment by beccamc** [comment]
Sorry you're running into this problem! Do you have a DateTime or GUID column type in your SQL db? I've seen this before when Model Builder is using the wrong type for SQL columns.

**Comment by DataJuggler** [comment]
I am getting a similar error with a DateTime column in my data. Does model builder not work with DateTime columns?

As per feedback since this is in Preview, having the ability to write a query rather than select a table would be nice.

I could always create a View, but writing a query on the fly would be simpler.

**Comment by Moskus** [comment]
Same problem here, it wasn't clear that it might be the DateTime column. I also have a column with JSON strings, and the MLModel Builder didn't like that one either.

**Comment by beccamc** [comment]
We just released an [update](https://marketplace.visualstudio.com/items?itemName=MLNET.ModelBuilder2022) with DateTime support. Give it a try and let me know if it works?

If it doesn't work, are you able to share a sample of your SQL data via mdf file?

**Comment by beccamc** [comment]
Closing due to lack of activity. DateTime is now supported. If you run into further problems please ping me or open a new bug.
