### ISSUE TITLE
Model builder error "String reference not set to an instance of a String. Parameter name: NumberDecimalSeparator" on the "Evaluate" page.

### ISSUE THREAD

**Issue by v-Hailishi** [dotnet/machinelearning-modelbuilder#2110]
**System Information (please complete the following information):**
Windows OS: Windows-11-Enterprise-21H2
ML.Net Model Builder 2019&2022: 16.13.5.2225601 (Main Build)
Microsoft Visual Studio Enterprise: 2019(16.11.11); 2022(17.1.3)
.Net: 5.0 & 6.0

**Describe the bug**
- On which step of the process did you run into an issue: Predict the sample data source from SQLPassword and SQL Server Database File.

**To Reproduce**

  1. Pre-requisite: Do [Pre-requisites/SQLPassword](https://github.com/dotnet/machinelearning-tools/blob/main/docs/tests/Instructions/Pre-Requisites/SQLPassword.md) before repro this issue.
  2. Select Create a new project from the Visual Studio start window;
  4. Choose the C# Console App (.NET Core) project template;
  5. Add model builder by right click on the project;
  6. Select **"Data classification" or "Value predication" or "Recommendation"** scenario>Local (CPU);
  7. On Data page, select>SQL Server>Microsoft SQL Server>SQL Server Authentication to input the data source;
      Or select>SQL Server>Microsoft SQL Server Database File to input the data source;
  8. Complete the training.
  9. Click Predict button, prompt model builder error as below screenshot.

**Expected behavior**
After click Predict button, you can get the predict result instead of the model builder error.

**Screenshots**
![image](https://user-images.githubusercontent.com/99375895/167244753-b994669a-6571-4928-ab2b-430d6499fd8d.png)

**Additional context**
String reference not set to an instance of a String.
Parameter name: NumberDecimalSeparator
at System.Globalization.NumberFormatInfo.VerifyDecimalSeparator(String decSep, String propertyName)
   at System.Globalization.NumberFormatInfo.set_NumberDecimalSeparator(String value)
   at Microsoft.ML.ModelBuilder.ToolWindows.EvaluateViewModel.ParseNumberValue(Object value, String decimalMarker)
   at Microsoft.ML.ModelBuilder.ToolWindows.EvaluateViewModel.<PredictTextScenarioAsync>d__68.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Microsoft.ML.ModelBuilder.ToolWindows.EvaluateTabControl.<TryItOutText_Click>d__5.MoveNext()

**Comment by v-Hailishi** [comment]
The bug has been fixed on the latest main branch 16.13.6.2225901 for both of VS2022 & VS2019.
