### ISSUE TITLE
Add Notebook failed with model builder error on the Consume page. 

### ISSUE THREAD

**Issue by v-Hailishi** [dotnet/machinelearning-modelbuilder#2124]
Copied form https://github.com/microsoft/VS-Notebook/issues/245
**System Information (please complete the following information):**
Windows OS: Windows-11-Enterprise-21H2
ML.Net Model Builder 2022: 16.13.6.2226601 (Main Build)
Microsoft Visual Studio Enterprise: 2022(17.2.0)
Notebook version: **0.3.2.2226306**

**Describe the bug**
- On which step of the process did you run into an issue:
Add Notebook on the Consume page.

**To Reproduce**

  1. Select Create a new project from the Visual Studio start window;
  2. Choose the C# Console App and .NET6.0 project template;
  3. Add model builder by right click on the project;
  4. Select any scenario;
  5. Completed the training.
  6. On the "Consume" page, add a notebook.
  7. You will see the model builder error from the output window.
      "**The type initializer for 'Microsoft.DotNet.Interactive.Notebook.NotebookFileFormatHandler' threw an exception.**"

**Expected behavior**
You can add Notebook successfully on the Consume page.

**Screenshots:**
![image](https://user-images.githubusercontent.com/99375895/168713950-e0e9460b-657c-48a6-aba6-bacc90365774.png)

**Additional context:**
This issue is repro on all scenarios.

**Error info:**
The type initializer for 'Microsoft.DotNet.Interactive.Notebook.NotebookFileFormatHandler' threw an exception.
at Microsoft.DotNet.Interactive.Notebook.NotebookFileFormatHandler.Serialize(String fileName, NotebookDocument notebook, String newline)
   at Microsoft.ML.ModelBuilder.CodeGenerator.CSharp.NotebookCSFileGenerator.GenerateCSharpCode() in /_/src/Microsoft.ML.ModelBuilder.CodeGenerator/CSharp/NotebookCSFileGenerator.cs:line 266
   at Microsoft.ML.ModelBuilder.AutoMLService.ServiceFactory.CodeGeneratorService.<CreateNotebookCodesAsync>d__6.MoveNext() in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/ServiceFactory/CodeGeneratorService.cs:line 279   at StreamJsonRpc.JsonRpc.<InvokeCoreAsync>d__143`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.ML.ModelBuilder.ToolWindows.ConsumeViewModel.<AddNotebookToSolutionAsync>d__52.MoveNext()

**Comment by LittleLittleCloud** [comment]
My best guess is something wrong with System.Text.Json,, will take a look on Monday

**Comment by v-Hailishi** [comment]
The bug has been fixed on the latest main branch 6.13.6.2227301 and Notebook 0.3.3.2227302.
![image](https://user-images.githubusercontent.com/99375895/169939154-99699a43-7c1c-42dd-a635-eba716887845.png)
