### ISSUE TITLE
134 Columns parsing problems

### ISSUE THREAD

**Issue by sretz** [dotnet/machinelearning-modelbuilder#2125]
**System Information (please complete the following information):**
 - Model Builder Version (available in Manage Extensions dialog): 16.13.6.2226201
 - Visual Studio Version: 17.2.1

**Describe the bug**
- On which step of the process did you run into an issue: The problem happens on the Train step
- Clear description of the problem: 

**To Reproduce**
1. Scenario: Data classification
2. Environment: local
3-1. Data: use file below
[H01.20210912-W06.csv](https://github.com/dotnet/machinelearning-modelbuilder/files/8757841/H01.20210912-W06.csv)
3-2. advanced data options:
col0 is a label of type boolean and is categorical
col1 is Ignore
col2 is Ignore
col3 - col133 is a Feature set to Single.
3-3. Column to predict col0
4. Train: When I click on Start training I get the following exception in a popup:
Parsing failed with an exception: Could not parse value Up in line 1, column col0
   at Microsoft.ML.Data.TextLoader.Cursor.<ParseParallel>d__33.MoveNext()
   at Microsoft.ML.Data.TextLoader.Cursor.MoveNextCore()
   at Microsoft.ML.Data.RootCursorBase.MoveNext()
   at Microsoft.ML.ModelBuilder.AutoMLService.Proposer.Controller.CountRows(IDataView data, Int64 maxRows) in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/Proposer/Controller.cs:line 174
   at Microsoft.ML.ModelBuilder.AutoMLService.Proposer.Controller.Initialize() in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/Proposer/Controller.cs:line 111
   at Microsoft.ML.ModelBuilder.AutoMLService.Experiments.LocalAutoMLExperiment.<ExecuteAsync>d__15.MoveNext() in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/Experiments/LocalAutoMLExperiment.cs:line 138
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ML.ModelBuilder.AutoMLEngine.<StartTrainingAsync>d__21.MoveNext() in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/AutoMLEngineService/AutoMLEngine.cs:line 160
**Expected behavior**
Train data just like if it had fewer columns.

**Screenshots**
![image](https://user-images.githubusercontent.com/80936576/169900397-07dd47a6-6308-47a4-8806-70dba6d6b22f.png)

**Additional context**

**Comment by beccamc** [comment]
Sorry you ran into this problem! It looks like we didn't correctly predict that this dataset has a column header. Can you manually change the setting in the advanced data options to "Yes"? When I did that it trained for me. 

![image](https://user-images.githubusercontent.com/9122518/171666374-dec63f1e-462d-43fd-924a-fba015164287.png)

**Comment by beccamc** [comment]
Please try this again with the "Has Header" value changed to Yes. If you're still having problems after that let me know!
