### ISSUE TITLE
Not Implement Error when adding console app

### ISSUE THREAD

**Issue by LittleLittleCloud** [dotnet/machinelearning-modelbuilder#2137]
- Model Builder Version
 -  26f79b14df1935a971b00847f010311ba7d76528
 - Visual Studio Version
<img width="649" alt="image" src="https://user-images.githubusercontent.com/16876986/171955534-229b1ec4-91a7-4ab3-8e4a-e9eed905d923.png">

Can be reproduced when adding console app
Looks like this not implement error comes back again, @zewditu can you take a look

```
 Load the project into the solution...
Not implemented (Exception from HRESULT: 0x80004001 (E_NOTIMPL))
   at EnvDTE.Project.get_FullName()
   at Microsoft.ML.ModelBuilder.VsProjectSystem.<AddProjectAsync>d__22.MoveNext() in C:\Users\xiaoyuz\source\repos\machinelearning-tools\src\Microsoft.ML.ModelBuilder\VsProjectSystem.cs:line 85
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Microsoft.ML.ModelBuilder.ToolWindows.ConsumeViewModel.<AddProjectToSolutionAsync>d__53.MoveNext() in C:\Users\xiaoyuz\source\repos\machinelearning-tools\src\Microsoft.ML.ModelBuilder\ViewModels\ConsumeViewModel.cs:line 414

```

**Comment by beccamc** [comment]
Is this still relevant? @LittleLittleCloud
