### ISSUE TITLE
DateTime type doesn't work with Forecasting scenario 

### ISSUE THREAD

**Issue by beccamc** [dotnet/machinelearning-modelbuilder#2166]
**System Information (please complete the following information):**
 - Model Builder Version: 16.13.9

**Describe the bug**
Cannot use DateTime with forecasting. I set the Time Series column as a date and it doesn't work. 

![image](https://user-images.githubusercontent.com/9122518/173943757-3e263a5d-6bac-4a19-b8ad-33e359efe920.png)

Error on train: 

![image](https://user-images.githubusercontent.com/9122518/173943207-9c000faf-d881-4e25-b0ec-e62c8c16d72e.png)

   at Microsoft.ML.IDataViewExtensions.ToDataFrame(IDataView dataView, Int64 maxRows, String[] selectColumns)
   at Microsoft.ML.ModelBuilder.AutoMLService.Proposer.ResampleStrategyProposer.InitializeForecasting(TrialParameter trialParameter) in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/Proposer/ResampleStrategyProposer.cs:line 132
   at Microsoft.ML.ModelBuilder.AutoMLService.Proposer.ResampleStrategyProposer.Propose(TrialParameter trialParameter) in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/Proposer/ResampleStrategyProposer.cs:line 51
   at Microsoft.ML.ModelBuilder.AutoMLService.Proposer.Controller.Propose() in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/Proposer/Controller.cs:line 66
   at Microsoft.ML.ModelBuilder.AutoMLService.Experiments.LocalAutoMLExperiment.<ExecuteAsync>d__15.MoveNext() in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/Experiments/LocalAutoMLExperiment.cs:line 163
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ML.ModelBuilder.AutoMLEngine.<StartTrainingAsync>d__21.MoveNext() in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/AutoMLEngineService/AutoMLEngine.cs:line 160

**Comment by luisquintanilla** [comment]
+1 although the format was different for me. We're going to want to be able to support / parse various DateTime formats.

![image](https://user-images.githubusercontent.com/46974588/173954671-e8d62130-89c4-470d-b875-baf10f193b51.png)


[product-sales.csv](https://github.com/dotnet/machinelearning-modelbuilder/files/8913952/product-sales.csv)

**Comment by beccamc** [comment]
@LittleLittleCloud From this stack trace can you tell if this is AutoML or ML.NET?

**Comment by luisquintanilla** [comment]
Issue to be fixed with DateTime support in framework.

**Comment by imranshams** [comment]
Same issue, can anybody help? Any solution?

**Comment by LittleLittleCloud** [comment]
`Datetime` PR is out and once it's merged in we should be able to fix this issue by updating ml.net

@imranshams 
Currently model builder doesn't have any mechanism to make use of `time` column other than using it as index, so for now you can just unselect `Time series column` and select `use default index as time column` instead

**Comment by beccamc** [comment]
This is in [PR ](https://github.com/dotnet/machinelearning/pull/6302)in the ML.NET repo. The fix will need to ship and reference the new version in Model Builder before this can be closed.

**Comment by beccamc** [comment]
@LittleLittleCloud Can I update our ML.NET version?

**Comment by luisquintanilla** [comment]
Unable to repro in build 16.14.0.2252005 using SQL DB and CSV file



![Image](https://user-images.githubusercontent.com/46974588/197071579-098a5bd8-d418-4d84-a4ab-fa0efc2ed8d2.png)

**Comment by Wintermute79** [comment]
Sorry but I am still getting _this exact error_ with latest VisualStudio 2022 version 17.4.4

I tried to format the time column as
`2022-10-29 00:00:00.000 +0200`
and also
`2022-10-29T00:00:00.000+0200`

What is the actual solution?

**Comment by LittleLittleCloud** [comment]
Is error message the same?

**Comment by Wintermute79** [comment]
So sorry, I updated the NuGet packages to version 2.0.0 but forgot to update the Model Builder Extension from within Visual Studio itself! Me culpa!
It is now working perfectly well!
