### ISSUE TITLE
Version string portion was too short or too long.

### ISSUE THREAD

**Issue by Tradyn** [dotnet/machinelearning-modelbuilder#2173]
**System Information (please complete the following information):**
 - Model Builder Version : 16.13.9.2231505 
 - Visual Studio Version 17.2.4

**Describe the bug**
- On which step of the process did you run into an issue: AutoML model builder forecasting
- Clear description of the problem: When training complete, this error is thrown

**To Reproduce**
Run Train on data using Auto Model Builder Forecasting

**Expected behavior**
No error to be thrown

**Screenshots**

**Additional context**

*******************************************************************
   at System.Version.VersionResult.SetFailure(ParseFailureKind failure, String argument)
   at System.Version.TryParseVersion(String version, VersionResult& result)
   at System.Version.Parse(String input)
   at System.Version..ctor(String version)
   at Microsoft.ML.ModelBuilder.Utils.Utilities.InstalledVersionNeedsUpdate(String installedString, String requestedString)
   at Microsoft.ML.ModelBuilder.Utils.Utilities.<InstallNugetPackageAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.ML.ModelBuilder.ViewModels.TrainViewModel.<UpdateNugetDependenciesAsync>d__105.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Microsoft.ML.ModelBuilder.ViewModels.TrainViewModel.<GenerateCodeBehindFilesAsync>d__104.MoveNext()
**********************************************************************

**********************************************************************
*************************LOG****************************************
 (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2022-06-22 11:14:39.6329 INFO Forecasting (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2022-06-22 11:14:40.8925 INFO Generate code behind files (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2022-06-22 11:14:41.0201 INFO 

Copying generated code to project... (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2022-06-22 11:14:41.0201 INFO Copying pnl.consumption.cs to folder: G:\CryptoRepos\MLTest\ConsoleApp1\ConsoleApp1 (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2022-06-22 11:14:41.0201 INFO Copying pnl.training.cs to folder: G:\CryptoRepos\MLTest\ConsoleApp1\ConsoleApp1 (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2022-06-22 11:14:41.0201 INFO COMPLETED (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2022-06-22 11:14:41.0201 INFO 

Updating nuget dependencies... (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2022-06-22 11:14:41.0201 INFO Starting update NuGet dependencies async. (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2022-06-22 11:14:41.0810 INFO Installing nuget package, package ID: Microsoft.ML.TimeSeries, package Version: 1.7.1 (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2022-06-22 11:14:41.0840 DEBUG Version string portion was too short or too long.
   at System.Version.VersionResult.SetFailure(ParseFailureKind failure, String argument)
   at System.Version.TryParseVersion(String version, VersionResult& result)
   at System.Version.Parse(String input)
   at System.Version..ctor(String version)
   at Microsoft.ML.ModelBuilder.Utils.Utilities.InstalledVersionNeedsUpdate(String installedString, String requestedString)
   at Microsoft.ML.ModelBuilder.Utils.Utilities.<InstallNugetPackageAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.ML.ModelBuilder.ViewModels.TrainViewModel.<UpdateNugetDependenciesAsync>d__105.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Microsoft.ML.ModelBuilder.ViewModels.TrainViewModel.<GenerateCodeBehindFilesAsync>d__104.MoveNext() (Microsoft.ML.ModelBuilder.Utils.Logger.Debug)

**Comment by zewditu** [comment]
@LittleLittleCloud  Do you have context about this ?

**Comment by malterman** [comment]
Same error occurred for me at the end of a 10-minute learning phase.

 at System.Version.VersionResult.SetFailure(ParseFailureKind failure, String argument)
   at System.Version.TryParseVersion(String version, VersionResult& result)
   at System.Version.Parse(String input)
   at System.Version..ctor(String version)
   at Microsoft.ML.ModelBuilder.Utils.Utilities.InstalledVersionNeedsUpdate(String installedString, String requestedString)
   at Microsoft.ML.ModelBuilder.Utils.Utilities.<InstallNugetPackageAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.ML.ModelBuilder.ViewModels.TrainViewModel.<UpdateNugetDependenciesAsync>d__105.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Microsoft.ML.ModelBuilder.ViewModels.TrainViewModel.<GenerateCodeBehindFilesAsync>d__104.MoveNext()

**Comment by beccamc** [comment]
Does anyone have the package version for Microsoft.ML.TimeSeries (or whatever package is mentioned)?

**Comment by beccamc** [comment]
Anyone able to provide the package version?

**Comment by beccamc** [comment]
We don't have enough information to investigate this issue. Please open a new issue or leave a comment if you're able to provide more info. Thanks!
