### ISSUE TITLE
When i am input the data into the ML module, i encounter a bug here but dont know how to solve it .. . ..

### ISSUE THREAD

**Issue by heroic-defeat** [dotnet/machinelearning-modelbuilder#2175]
at Microsoft.ML.ModelBuilder.AutoMLService.Experiments.AutoMLExperiment`3.<ExecuteAsync>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ML.ModelBuilder.AutoMLEngine.<StartTrainingAsync>d__21.MoveNext() in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/AutoMLEngineService/AutoMLEngine.cs:line 167   at StreamJsonRpc.JsonRpc.<InvokeCoreAsync>d__143`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ML.ModelBuilder.ViewModels.TrainViewModel.<<StartTrainingAsync>b__109_0>d.MoveNext()

**Comment by beccamc** [comment]
Sorry you ran into this problem! Can you provide some more information...

- What scenario are you working on?
- What data are you using? Are you able to share a dataset sample?

**Comment by beccamc** [comment]
Sorry, we don't have enough information to solve this issue. If this is still a problem please provide the above details. Thanks!
