### ISSUE TITLE
Column names not properly escaped for SQL Server data source

### ISSUE THREAD

**Issue by wsficke** [dotnet/machinelearning-modelbuilder#2177]
**System Information (please complete the following information):**
 - Model Builder Version (available in Manage Extensions dialog): 16.13.9.2231505
 - Visual Studio Version: 17.2.5

**Describe the bug**
- On which step of the process did you run into an issue: "Train"
- Clear description of the problem: Column named "Group" results in SQL error "Incorrect syntax near the keyword 'Group'."

**To Reproduce**
1. In SSMS, create a table having a feature column named Group, and a label column
2. Add arbitrary data
3. Model Builder > Value Prediction > Local > Sql Server Input > set datasource/table/columns accordingly
4. Train > click train
5. Note that ADO.NET raises a SqlException due to invalid syntax

**Expected behavior**
All database object names should be escaped during query generation to prevent collision with SQL reserved words.  Group > [Group]

**Screenshots**

**Additional context**
Model Builder Error
Incorrect syntax near the keyword 'Group'.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
   at System.Data.SqlClient.SqlDataReader.get_MetaData()
   at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption, Boolean shouldCacheForAlwaysEncrypted)
   at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method)
   at System.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior, String method)
   at Microsoft.ML.Data.DatabaseLoader.Cursor.get_DataReader()
   at Microsoft.ML.Data.DatabaseLoader.Cursor.MoveNextCore()
   at Microsoft.ML.Data.RootCursorBase.MoveNext()
   at Microsoft.ML.ModelBuilder.AutoMLService.Proposer.Controller.CountRows(IDataView data, Int64 maxRows) in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/Proposer/Controller.cs:line 174
   at Microsoft.ML.ModelBuilder.AutoMLService.Proposer.Controller.Initialize() in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/Proposer/Controller.cs:line 111
   at Microsoft.ML.ModelBuilder.AutoMLService.Experiments.LocalAutoMLExperiment.<ExecuteAsync>d__15.MoveNext() in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/Experiments/LocalAutoMLExperiment.cs:line 138
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ML.ModelBuilder.AutoMLEngine.<StartTrainingAsync>d__21.MoveNext() in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/AutoMLEngineService/AutoMLEngine.cs:line 160

**Comment by beccamc** [comment]
Thank you for the detailed issue! This problem is on our backlog to fix. I'll bump up the priority given we have multiple reports. 

I'm going to close this issue as duplicate. Please track progress in this issue - https://github.com/dotnet/machinelearning-modelbuilder/issues/1871

Thank you for reporting!
