### ISSUE TITLE
Model builder error occurs when setting up workspace on the Environment page for Azure supported scenarios.

### ISSUE THREAD

**Issue by v-Hailishi** [dotnet/machinelearning-modelbuilder#2196]
**System Information (please complete the following information):**
Windows OS: Windows-11-Enterprise-21H2
ML.Net Model Builder 2019: (16.13.9.2236101) 
**URL: https://privategallery.blob.core.windows.net/gallery/refs/heads/u/zewd/GetAzureResources/atom.xml**
Microsoft Visual Studio Enterprise: 2019(16.11.16)
Net: 5.0

**Describe the bug**
- On which step of the process did you run into an issue:
Setting up workspace on the Environment page.
**The bug is only repro on VS2019, not repro on VS2022.**

**To Reproduce**
**Pre-Requisites: Install the Model Builder: 16.13.9.2236101 from private feed:
https://privategallery.blob.core.windows.net/gallery/refs/heads/u/zewd/GetAzureResources/atom.xml
  1. Select Create a new project from the Visual Studio start window.
  2. Choose the C# Console App and .NET5.0 project template.
  3. Add model builder by right click on the project.
  4. Select Image-classification or Object-Detection scenario.
  5. On the Environment page, choose **Azure** and click "Set up workspace" button
      You will see the error: **Could not load file or assembly 'System.Text.Json, Version=4.0.1.2, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The system cannot find the file specified.**

**Expected behavior: **
You can set up workspace successfully on the Environment page.

**Screenshots: **
![image](https://user-images.githubusercontent.com/99375895/178724672-8280b646-ed52-4f41-9f44-696ef1ade9ef.png)

**Additional context: **
Could not load file or assembly 'System.Text.Json, Version=4.0.1.2, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The system cannot find the file specified.
at Azure.ResourceManager.Resources.SubscriptionsRestOperations.List(CancellationToken cancellationToken)
   at Azure.ResourceManager.Resources.SubscriptionCollection.<>c__DisplayClass8_0.<GetAll>g__FirstPageFunc|0(Nullable`1 pageSizeHint)
   at Azure.Core.PageableHelpers.<>c__DisplayClass5_0`1.<CreateEnumerable>b__0(String continuationToken, Nullable`1 pageSizeHint)
   at Azure.Core.PageableHelpers.FuncPageable`1.<AsPages>d__4.MoveNext()
   at Azure.Pageable`1.<GetEnumerator>d__8.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Microsoft.ML.ModelBuilder.RemoteResourceManager.AzureResourceManager.<GetSubscriptionsAsync>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.ML.ModelBuilder.ToolWindows.AzureAttachViewModel.<LoadSubscriptionsAsync>d__55.MoveNext()
Failed to get subscriptions for tenant: Microsoft

**Comment by beccamc** [comment]
This would need to get fixed for the next release

**Comment by v-Hailishi** [comment]
The bug is still repro on the latest u/zewd/GetAzureResources branch: 16.13.9.2236301 for VS2019.

**Comment by zewditu** [comment]
@v-Hailishi  still investigating the issue.

**Comment by zewditu** [comment]
@v-Hailishi update Model Builder from the same private gallery and test it.

**Comment by v-Hailishi** [comment]
The bug has been fixed on the latest u/zewd/GetAzureResources branch: 16.13.9.2236604 for VS2019.
