### ISSUE TITLE
DEBUG Package restore failed. Rolling back package changes for 'ML-Model-Builder-2022'.

### ISSUE THREAD

**Issue by SPYazdani** [dotnet/machinelearning-modelbuilder#2234]
**Describe the bug**
- On which page of the tutorial did you run into an issue (URL): https://dotnet.microsoft.com/en-us/learn/ml-dotnet/get-started-tutorial/train

**Additional context**
Copying generated code to project... (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2022-09-03 16:08:10.0746 INFO Copying SentimentModel.consumption.cs to folder: C:\Users\Payam\Source\Repos\ML-Model-Builder-2022 (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2022-09-03 16:08:10.0746 INFO Copying SentimentModel.training.cs to folder: C:\Users\Payam\Source\Repos\ML-Model-Builder-2022 (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2022-09-03 16:08:10.0746 INFO COMPLETED (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2022-09-03 16:08:10.0746 INFO 

Updating nuget dependencies... (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2022-09-03 16:08:10.0746 INFO Starting update NuGet dependencies async. (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2022-09-03 16:08:10.0793 INFO Installing nuget package, package ID: Microsoft.ML, package Version: 1.7.1 (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2022-09-03 16:08:10.0793 DEBUG Package restore failed. Rolling back package changes for 'ML-Model-Builder-2022'.
   at NuGet.PackageManagement.NuGetPackageManager.<ExecuteBuildIntegratedProjectActionsAsync>d__89.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.PackageManagement.NuGetPackageManager.<ExecuteNuGetProjectActionsAsync>d__86.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.PackageManagement.NuGetPackageManager.<InstallPackageAsync>d__53.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.PackageManagement.NuGetPackageManager.<InstallPackageAsync>d__52.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.VisualStudio.Implementation.Extensibility.VsPackageInstaller.<InstallInternalCoreAsync>d__28.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at NuGet.VisualStudio.Implementation.Extensibility.VsPackageInstaller.<InstallInternalAsync>d__27.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at NuGet.VisualStudio.Implementation.Extensibility.VsPackageInstaller.<InstallInternalAsync>d__27.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Threading.JoinableTask.CompleteOnCurrentThread()
   at NuGet.VisualStudio.Implementation.Extensibility.VsPackageInstaller.InstallPackage(String source, Project project, String packageId, String version, Boolean ignoreDependencies)
   at Microsoft.ML.ModelBuilder.Utils.Utilities.<InstallNugetPackageAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.ML.ModelBuilder.ViewModels.TrainViewModel.<UpdateNugetDependenciesAsync>d__109.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Microsoft.ML.ModelBuilder.ViewModels.TrainViewModel.<GenerateCodeBehindFilesAsync>d__108.MoveNext() (Microsoft.ML.ModelBuilder.Utils.Logger.Debug)

**Comment by LittleLittleCloud** [comment]
Thanks for reporting the issue, we are actively working on a fix.

In the meanwhile, you can manually install `Microsoft.ML 1.7.1` to resolve this exception.

**Comment by SPYazdani** [comment]
Hi $contact_first_name $contact_last_name,
					    We've received your case $acase_name (# $acase_case_number) on $acase_date_entered
					    Status$acase_statusReference$acase_case_numberDescription$acase_description
On 09/09/2022, 04:01, ***@***.*** wrote:Thanks for reporting the issue, we are actively working on a fix.
In the meanwhile, you can manually install Microsoft.ML 1.7.1 to resolve this exception.

**Comment by beccamc** [comment]
@LittleLittleCloud Will this be in the next release? Is the version bump of ML.NET already in?

**Comment by SPYazdani** [comment]
Hi $contact_first_name $contact_last_name,
					    We've received your case $acase_name (# $acase_case_number) on $acase_date_entered
					    Status$acase_statusReference$acase_case_numberDescription$acase_description
On 20/09/2022, 06:07, ***@***.*** ***@***.*** Will this be in the next release? Is the version bump of ML.NET already in?

**Comment by LittleLittleCloud** [comment]
@beccamc 
We don't have any action item for this issue. The current mlnet version in generated project should already be 1.7.1.

**Comment by SPYazdani** [comment]
Hi $contact_first_name $contact_last_name,
					    We've received your case $acase_name (# $acase_case_number) on $acase_date_entered
					    Status$acase_statusReference$acase_case_numberDescription$acase_description
On 20/09/2022, 06:12, ***@***.*** ***@***.***

We don't have any action item for this issue. The current mlnet version in generated project should already be 1.7.1.

**Comment by beccamc** [comment]
@SPYazdani Please update the ML.NET version to 1.7.1. Newer versions of Model Builder will generate this correctly. Let us know if that doesn't work for you - thanks!

**Comment by SPYazdani** [comment]
Hi $contact_first_name $contact_last_name,
					    We've received your case $acase_name (# $acase_case_number) on $acase_date_entered
					    Status$acase_statusReference$acase_case_numberDescription$acase_description
On 20/09/2022, 06:16, ***@***.*** wrote:Closed #2234 as completed.

**Comment by SPYazdani** [comment]
Hi $contact_first_name $contact_last_name,
					    We've received your case $acase_name (# $acase_case_number) on $acase_date_entered
					    Status$acase_statusReference$acase_case_numberDescription$acase_description
On 20/09/2022, 06:16, ***@***.*** ***@***.*** Please update the ML.NET version to 1.7.1. Newer versions of Model Builder will generate this correctly. Let us know if that doesn't work for you - thanks!

**Comment by SPYazdani** [comment]
@beccamc This issue is not completed. Please go back and read the logs I posted.

**Comment by beccamc** [comment]
Are you on MB version 16.13.10.2241902? If not can you [update ](https://marketplace.visualstudio.com/items?itemName=MLNET.ModelBuilder2022)and try again?

**Comment by SPYazdani** [comment]
Hi $contact_first_name $contact_last_name,
					    We've received your case $acase_name (# $acase_case_number) on $acase_date_entered
					    Status$acase_statusReference$acase_case_numberDescription$acase_description
On 21/09/2022, 02:09, ***@***.*** wrote:Are you on MB version 16.13.10.2241902? If not can you update and try again?
