### ISSUE TITLE
Shuffle input cursor reader failed with an exception (Date type)

### ISSUE THREAD

**Issue by judahr** [dotnet/machinelearning-modelbuilder#2237]
**System Information (please complete the following information):**
 - Model Builder Version (available in Manage Extensions dialog): 16.13.10.2241902
 - Visual Studio Version: 17.3.2

**Describe the bug**
- On which step of the process did you run into an issue: Train Model
- 
- Clear description of the problem:
Using SQL Server view as the datasource, training produces an exception: Shuffle input cursor reader failed with an exception
**To Reproduce**
Create new console app project.
Add ML.Net Model builder
Choose Data Classification scenario
Environment is Local CPU
Data input is SQL server, some DB table with renamed columns.  Column types are Date, money, and int. (No datetime, no guids)
Data Preview shows ok 10 rows of 39.985
Choose Time to train = 60 sec
Press Start training button
Error message "Shuffle input cursor reader failed with an exception
   at Microsoft.ML.Transforms.RowShufflingTransformer.Cursor.MoveNextCore()
   at Microsoft.ML.Data.RootCursorBase.MoveNext()
   at Microsoft.ML.Data.LinkedRowFilterCursorBase.MoveNextCore()
   at Microsoft.ML.Data.RootCursorBase.MoveNext()
   at Microsoft.ML.Data.IO.BinarySaver.RowsPerBlockHeuristic(IDataView data, ColumnCodec[] actives)
   at Microsoft.ML.Data.IO.BinarySaver.SaveData(Stream stream, IDataView data, Int32[] colIndices)
   at Microsoft.ML.Data.DataSaverUtils.SaveDataView(IChannel ch, IDataSaver saver, IDataView view, Stream stream, Boolean keepHidden)
   at Microsoft.ML.BinaryLoaderSaverCatalog.SaveAsBinary(DataOperationsCatalog catalog, IDataView data, Stream stream, Boolean keepHidden)
   at Microsoft.ML.ModelBuilder.AutoMLService.Proposer.ResampleStrategyProposer.Initialize(String outputFolder) in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/Proposer/ResampleStrategyProposer.cs:line 99"

**Expected behavior**
Train a model without error.

**Screenshots**

**Additional context**

**Comment by beccamc** [comment]
@judahr Can you provide us more info about the SQL table you're using? The schema or sample data would be great.

**Comment by LittleLittleCloud** [comment]
It's probably because shuffle is not support for `Datetime` type? Let me take a look

**Comment by beccamc** [comment]
@judahr Any update on more info about your SQL data?

**Comment by beccamc** [comment]
Oh I see: 

> Column types are Date, money, and int

The Date type is probably the problem. Will investigate.

**Comment by beccamc** [comment]
@judahr Can you try again on [16.14.0](https://marketplace.visualstudio.com/items?itemName=MLNET.ModelBuilder2022)? We've fixed a few SQL data processing issues.

**Comment by beccamc** [comment]
This should be fixed on the latest version. Please let us know if it doesn't work. Thanks!
