### ISSUE TITLE
Regression model: "Index was outside the bounds of the array"

### ISSUE THREAD

**Issue by akade** [dotnet/machinelearning-modelbuilder#2258]
**System Information (please complete the following information):**
 - Model Builder Version: 16.13.10.2241902
 - Visual Studio Version: 17.3.4

**Describe the bug**
Training a regression model ("Value prediction scenario") fails with "Index was outside the bounds of the array". Maybe related to #1602 but this time it 's not a text classification task. I tried it with the taxi fare data and then it works. Special about my data is that it contains a lot of columns, 1489  to be exact.

**To Reproduce**
1. Create a csv file that contains floating-point data in 1489, including a header row
2. Use the first column as label
3. Start training

**Expected behavior**
Training should work as usual. Just as it does with the taxi fare data.

**Screenshots**
![image](https://user-images.githubusercontent.com/16369295/192361997-19b1be20-3b97-4be0-a4fb-807352dd5d5a.png)

**Additional context**
- I noticed that the row count in the preview is wrong:
![image](https://user-images.githubusercontent.com/16369295/192363514-8ab5866c-db0b-4321-b2a9-a6b897429bdd.png)
  However, it correctly displays some rows and the first 1000 cols
- The log file:
```
2022-09-26 21:11:03.9364 INFO Set log file path to ... (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2022-09-26 21:11:43.5105 INFO start regression (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2022-09-26 21:11:43.5105 INFO Evaluate Metric: RSquared (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2022-09-26 21:11:43.5105 INFO Available Trainers: LGBM,RF,FASTTREE,LBFGS,SDCA (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2022-09-26 21:11:43.5105 INFO Training time in second: 20 (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2022-09-26 21:11:44.5664 INFO |      Trainer                             RSquared   Duration       | (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2022-09-26 21:11:44.5664 INFO |--------------------------------------------------------------------| (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2022-09-26 21:11:44.5664 INFO |0     FastForestRegression                NaN        0.8780         | (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2022-09-26 21:11:44.6305 DEBUG Index was outside the bounds of the array.
   at Microsoft.ML.AutoML.PipelineProposer.Propose(TrialSettings settings)
   at Microsoft.ML.AutoML.AutoMLExperiment.<RunAsync>d__21.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ML.ModelBuilder.AutoMLService.Experiments.RegressionExperiment.<ExecuteAsync>d__13.MoveNext() in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/Experiments/RegressionExperiment.cs:line 100
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ML.ModelBuilder.AutoMLEngine.<StartTrainingAsync>d__21.MoveNext() in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/AutoMLEngineService/AutoMLEngine.cs:line 161 (Microsoft.ML.ModelBuilder.Utils.Logger.Debug)
```
- If you need some data file, tell me. I'll check if I can make it available to you.

**Comment by akade** [comment]
In the meantime I experimented a little bit more:
It seems that *not the number of columns is important but the number of rows*. I had only 68 rows in the initial dataset. If double the amount of data, it works.

**Comment by beccamc** [comment]
@akade Sorry you ran into this problem. Are you able to share your original dataset? It's weird that it says 0 of 0 rows. That says to me it didn't parse your data correctly.

**Comment by akade** [comment]
I cannot reproduce the 0 of 0 rows anymore - don't really know what changed. Anyway, the exception still happens.

This my original file but with random data and different col headers:
[Data.csv](https://github.com/dotnet/machinelearning-modelbuilder/files/9686980/Data.csv)

You can get the exception with a much less columns as well:
[Test.csv](https://github.com/dotnet/machinelearning-modelbuilder/files/9686947/Test.csv)

For both files, if you double the amount of rows the training proceeds as expected.

**Comment by beccamc** [comment]
I'm glad you found a work around. @LittleLittleCloud can you help with why the error message isn't better for a small dataset?

**Comment by LittleLittleCloud** [comment]
It's a bug in old AutoML.Net, and this error should have already been fixed in latest main.

**Comment by NirmitBhatt** [comment]
I get the same "Index was outside the bounds of the array" error when I try to train my data (total 12 columns and 1000 rows). Somehow if I "Ignore" any one feature from the **_Advanced data options..._** under **"Column to Predict (Label):"** it starts to train my data and the error disappears. Is it mandatory to ignore atleast one feature?

**Comment by beccamc** [comment]
@NirmitBhatt Are you able to share your dataset (or a part of it)? What does the column that you ignored look like?

It is not mandatory to ignore one column. I assume there is something different in the ignored column. Maybe free form text that contains special characters? Something like that?

**Comment by beccamc** [comment]
@NirmitBhatt Any update on the above questions?

**Comment by beccamc** [comment]
This should be fixed in our latest version - https://marketplace.visualstudio.com/items?itemName=MLNET.ModelBuilder2022
