### ISSUE TITLE
Error While Training SQL

### ISSUE THREAD

**Issue by MrElecmen** [dotnet/machinelearning-modelbuilder#2267]
**System Information (please complete the following information):**
 - Model Builder Version (available in Manage Extensions dialog): 
 - Visual Studio Version : Microsoft Visual Studio Enterprise 2022 (64-bit) 

**Describe the bug**
- On which step of the process did you run into an issue: Train
- Clear description of the problem: I get this error after 3 seconds

__________________________________________________________
   at Microsoft.ML.Transforms.RowShufflingTransformer.Cursor.MoveNextCore()
   at Microsoft.ML.Data.RootCursorBase.MoveNext()
   at Microsoft.ML.Data.IO.BinarySaver.RowsPerBlockHeuristic(IDataView data, ColumnCodec[] actives)
   at Microsoft.ML.Data.IO.BinarySaver.SaveData(Stream stream, IDataView data, Int32[] colIndices)
   at Microsoft.ML.Data.DataSaverUtils.SaveDataView(IChannel ch, IDataSaver saver, IDataView view, Stream stream, Boolean keepHidden)
   at Microsoft.ML.BinaryLoaderSaverCatalog.SaveAsBinary(DataOperationsCatalog catalog, IDataView data, Stream stream, Boolean keepHidden)
   at Microsoft.ML.ModelBuilder.AutoMLService.Proposer.ResampleStrategyProposer.Initialize(String outputFolder) in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/Proposer/ResampleStrategyProposer.cs:line 91
   at Microsoft.ML.ModelBuilder.AutoMLService.Proposer.ResampleStrategyProposer.Propose(TrialParameter trialParameter) in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/Proposer/ResampleStrategyProposer.cs:line 61
   at Microsoft.ML.ModelBuilder.AutoMLService.Proposer.Controller.Propose() in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/Proposer/Controller.cs:line 58
   at Microsoft.ML.ModelBuilder.AutoMLService.Experiments.LocalAutoMLExperiment.<ExecuteAsync>d__15.MoveNext() in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/Experiments/LocalAutoMLExperiment.cs:line 136
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ML.ModelBuilder.AutoMLEngine.<StartTrainingAsync>d__21.MoveNext() in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/AutoMLEngineService/AutoMLEngine.cs:line 167   at StreamJsonRpc.JsonRpc.<InvokeCoreAsync>d__143`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ML.ModelBuilder.ViewModels.TrainViewModel.<<StartTrainingAsync>b__109_0>d.MoveNext()
_________________________________________________________________________________________________

**To Reproduce**
1. Add New Machine Learning
2. Click on 'Value Prediction'
3. Select Data from Sql Server'....'

**Comment by beccamc** [comment]
Sorry you ran into this problem! Are you on Model Builder version [16.13.10.2241902](https://marketplace.visualstudio.com/items?itemName=MLNET.ModelBuilder2022)? Are you able to share your dataset?

**Comment by MrElecmen** [comment]
Yes I can share the data set
what do you need ?
db Schema and data ?
how can i share it ?

**Comment by beccamc** [comment]
The DB Schema would be helpful to start! Do you have Date, Datetime, GUID types? We have some bugs around certain SQL types that we're hoping to fix in the next release. If you have one of those types it could be the problem.

**Comment by LittleLittleCloud** [comment]
@MrElecmen you probabaly want to upgrade your model builder, the latest model builder version should be 17.13''ish and we push a few fixes in automl engine, which may contain the fix for your case.

**Comment by beccamc** [comment]
Please try the latest version of Model Builder and see if it resolves your issue. https://marketplace.visualstudio.com/items?itemName=MLNET.ModelBuilder2022
