### ISSUE TITLE
Bad Allocation Error

### ISSUE THREAD

**Issue by judahr** [dotnet/machinelearning-modelbuilder#2270]
**System Information (please complete the following information):**
 - Model Builder Version (available in Manage Extensions dialog): 16.13.10.2241902
 - Visual Studio Version

**Describe the bug**
- On which step of the process did you run into an issue: While training a model.  It had trained many times before without issue.
- Clear description of the problem:

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**
   at Microsoft.ML.Trainers.LightGbm.LightGbmInterfaceUtils.Check(Int32 res)
   at Microsoft.ML.Trainers.LightGbm.Booster.Update()
   at Microsoft.ML.Trainers.LightGbm.WrappedLightGbmTraining.Train(IChannel ch, IProgressChannel pch, Dictionary`2 parameters, Dataset dtrain, Dataset dvalid, Int32 numIteration, Boolean verboseEval, Int32 earlyStoppingRound)
   at Microsoft.ML.Trainers.LightGbm.LightGbmTrainerBase`4.TrainCore(IChannel ch, IProgressChannel pch, Dataset dtrain, CategoricalMetaData catMetaData, Dataset dvalid)
   at Microsoft.ML.Trainers.LightGbm.LightGbmTrainerBase`4.TrainModelCore(TrainContext context)
   at Microsoft.ML.Trainers.TrainerEstimatorBase`2.TrainTransformer(IDataView trainSet, IDataView validationSet, IPredictor initPredictor)
   at Microsoft.ML.Data.EstimatorChain`1.Fit(IDataView input)
   at Microsoft.ML.AutoML.BinaryClassificationTrainTestRunner.Run(TrialSettings settings, IServiceProvider provider)
   at Microsoft.ML.AutoML.AutoMLExperiment.<RunAsync>d__21.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ML.ModelBuilder.AutoMLService.Experiments.BinaryClassificationExperiment.<ExecuteAsync>d__13.MoveNext() in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/Experiments/BinaryClassificationExperiment.cs:line 101
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ML.ModelBuilder.AutoMLEngine.<StartTrainingAsync>d__21.MoveNext() in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/AutoMLEngineService/AutoMLEngine.cs:line 161

**Comment by beccamc** [comment]
Sorry you ran into this problem! Are you able to share more information about what you're doing? 

- Can you share your dataset?
- Is this still happening? Did a machine restart fix subsequent training?

**Comment by beccamc** [comment]
Any update on the above?

**Comment by judahr** [comment]
I'm unable to upload the data. Maybe someone else will run into this and can provide data.

**Comment by beccamc** [comment]
Poking around it looks like this may be a problem with out of memory exception when trying to create the dataset. After restart does the problem still reproduce? Is it a large dataset?

**Comment by beccamc** [comment]
Sorry you ran into this problem. If its still happening on our latest version let us know - https://marketplace.visualstudio.com/items?itemName=MLNET.ModelBuilder2022
