### ISSUE TITLE
Data Classification Out Of Memory

### ISSUE THREAD

**Issue by torronen** [dotnet/machinelearning-modelbuilder#2328]
**System Information (please complete the following information):**
 - Model Builder Version (available in Manage Extensions dialog): 16.13.10.2241902
 - Visual Studio 2022

**Describe the bug**
I am trying to classify a single text field (paragraph) to 400 categories. 
1. Create new ML Model
2. Select Data Classification
3. Select label column, and select one feature column 
4. Run the model
Then I receive out-of-memory error without more explanation.

There is plenty of physical memory left (about 80% of 128 GB RAM + 1 TB page file).
Dataset size is about 1.5 gb csv, about 150 000 rows.

**Ideal behavior**
Training starts and completes OR I run out of physical memory OR I get some suggestion on how to edit my dataset. For example, should I reduce number of categories or shorten the text?

**Comment by torronen** [comment]
Here is a log file for 10 categories, same dataset

[test-TEWJ8L.txt](https://github.com/dotnet/machinelearning-modelbuilder/files/9894039/test-TEWJ8L.txt)

`2022-10-29 12:17:35.6466 INFO Set log file path to C:\Users\Kwork\AppData\Local\Temp\MLVSTools\logs\test-TEWJ8L.txt (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2022-10-29 12:18:27.4556 INFO start multiclass classification (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2022-10-29 12:18:27.4556 INFO Evaluate Metric: MacroAccuracy (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2022-10-29 12:18:27.4556 INFO Available Trainers: LGBM,RF,FASTTREE,LBFGS,SDCA (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2022-10-29 12:18:27.4556 INFO Training time in second: 99999 (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2022-10-29 12:22:57.4658 DEBUG Exception of type 'System.OutOfMemoryException' was thrown.
   at Microsoft.ML.Internal.Utilities.VBufferUtils.CreateDense[T](Int32 length)
   at Microsoft.ML.Trainers.SdcaTrainerBase`3.TrainCore(IChannel ch, RoleMappedData data, LinearModelParameters predictor, Int32 weightSetCount)
   at Microsoft.ML.Trainers.StochasticTrainerBase`2.TrainModelCore(TrainContext context)
   at Microsoft.ML.Trainers.TrainerEstimatorBase`2.TrainTransformer(IDataView trainSet, IDataView validationSet, IPredictor initPredictor)
   at Microsoft.ML.Data.EstimatorChain`1.Fit(IDataView input)
   at Microsoft.ML.AutoML.MultiClassificationTrainTestRunner.Run(TrialSettings settings, IServiceProvider provider)
   at Microsoft.ML.AutoML.AutoMLExperiment.<RunAsync>d__21.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ML.ModelBuilder.AutoMLService.Experiments.MultiClassificationExperiment.<ExecuteAsync>d__13.MoveNext() in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/Experiments/MultiClassificationExperiment.cs:line 112
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ML.ModelBuilder.AutoMLEngine.<StartTrainingAsync>d__21.MoveNext() in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/AutoMLEngineService/AutoMLEngine.cs:line 161 (Microsoft.ML.ModelBuilder.Utils.Logger.Debug)`

**Comment by torronen** [comment]
@zewditu I noticed you had OOM for text classification in another issue. Is it possible the issues are related, and there is currently a bug with text classification? I do not have the GPU extensions right now, so mine is CPU only.

I have another issue with multiclassification, 10 categories, a few words per the only feature, 150k rows. Same dataset, not OOM, but still fails
[test-TEWJ8L.-2txt.txt](https://github.com/dotnet/machinelearning-modelbuilder/files/9894050/test-TEWJ8L.-2txt.txt)



   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.For(Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body)
   at Microsoft.ML.Trainers.SdcaTrainerBase`3.TrainCore(IChannel ch, RoleMappedData data, LinearModelParameters predictor, Int32 weightSetCount)
   at Microsoft.ML.Trainers.StochasticTrainerBase`2.TrainModelCore(TrainContext context)
   at Microsoft.ML.Trainers.TrainerEstimatorBase`2.TrainTransformer(IDataView trainSet, IDataView validationSet, IPredictor initPredictor)
   at Microsoft.ML.Data.EstimatorChain`1.Fit(IDataView input)
   at Microsoft.ML.AutoML.MultiClassificationTrainTestRunner.Run(TrialSettings settings, IServiceProvider provider)
   at Microsoft.ML.AutoML.AutoMLExperiment.<RunAsync>d__21.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ML.ModelBuilder.AutoMLService.Experiments.MultiClassificationExperiment.<ExecuteAsync>d__13.MoveNext() in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/Experiments/MultiClassificationExperiment.cs:line 112
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ML.ModelBuilder.AutoMLEngine.<StartTrainingAsync>d__21.MoveNext() in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/AutoMLEngineService/AutoMLEngine.cs:line 161

**Comment by zewditu** [comment]
@torronen   I want to confirm on thing, is the issue happened for Text classification using CPU training? 
For my case may machine does not have enough memory for GPU training,  
Foe CPU training @LittleLittleCloud  any thought on this?


For the question of " how to edit my dataset. For example, should I reduce number of categories or shorten the text?
@luisquintanilla  what should  be the user action when OOM happen in general ?

**Comment by beccamc** [comment]
I just want to remind the dev team for this bug we're talking about **Data Classification scenario**. We are releasing a new "Text Classification" scenario in the next build, but that isn't out yet. Zewditu's issue relates to the new scenario.

**Comment by torronen** [comment]
@LittleLittleCloud I am not. I think it is not yet in the release feed of VS Extensions. Is there a way to download pre-release versions for testing?

**Comment by torronen** [comment]
I remembered your earlier advice:  set AutoMLServiceBinaryClassifiers=LGBM;RF;FASTTREE;LBFGS. Now the training has been running for about 24 but I ran out of time. I will update here if it would not work, but it probably works.

So I think you are correct, it is related to SDCA. It seems not to be about physical memory. If someone wants to debug it further I can share this dataset. Thanks for the help everyone, my blocking issue is resolved although the OOM issue in SDCA remains.

Yes, it is CPU training. Beccamc is correct, this is about data classification. 

I have lots of text classification tasks so I am looking forward to testing the next release! Also volunteering for testing it if there is a pre-release available. I currently calculate lots of features + in some cases use embedding from a NN. If I understand correctly, text classification should work without too many additional calculated features.

Thanks everyone for the advice

**Comment by zewditu** [comment]
@torronen  thanks for your interest to test our pre-release.
@JakeRadMSFT @beccamc do we have a way to provide pre-release to Torrenen ?

**Comment by beccamc** [comment]
@torronen Thanks for your patience! The release is out with the advanced training options - https://marketplace.visualstudio.com/items?itemName=MLNET.ModelBuilder2022

**Comment by beccamc** [comment]
It also has the new Text Classification scenario if you want to give that a try ☺️

**Comment by torronen** [comment]
@beccamc Thanks, Text Classification seems to work nice. I was unsure where to find the correct documentation, so I have one question: Does it take anything marked as "Feature" into account or ignores them? I can set on field as text, but what about if I have multiple text fields, like Title + Contents? Is the other markes as a Feature ignored?

BTW, Data Classification is still running for 3-4 days now, no trials have finished yet. I think I should have probably disabled the slowest one, maybe random forest.

**Comment by beccamc** [comment]
@torronen Thanks for trying text classification. I'm glad that its working. 

Great question on the ignored columns. It is ignoring everything besides the Lable and Text columns. I agree it is confusing and we have work item to mark all of these as "Ignored" instead of "Feature". https://github.com/dotnet/machinelearning-modelbuilder/issues/2296

@luisquintanilla Have we also documented this? I know doc changes are still being published.

**Comment by beccamc** [comment]
Closing this in favor of 2296. Thanks for reporting!
