### ISSUE TITLE
Target 4294967295 is out of bounds - failure during Text Classification CPU Training 

### ISSUE THREAD

**Issue by uuxxaa** [dotnet/machinelearning-modelbuilder#2368]
**System Information (please complete the following information):**
 - Model Builder Version (available in Manage Extensions dialog): 16.14.0.2255902
 - Visual Studio Version VS 2022 17.4.0

**Describe the bug**
- On which step of the process did you run into an issue: Training
- Clear description of the problem: Training threw an exception

Target 4294967295 is out of bounds.
Exception raised from nll_loss_out_frame at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\LossNLL.cpp:230 (most recent call first):
00007FF829E5A4C200007FF829E5A460 c10.dll!c10::Error::Error [<unknown file> @ <unknown line number>]
00007FF829E33ED500007FF829E33E60 c10.dll!c10::IndexError::IndexError [<unknown file> @ <unknown line number>]
00007FFFDD491FB400007FFFDD48CE60 torch_cpu.dll!at::native::multi_margin_loss_cpu_out [<unknown file> @ <unknown line number>]
00007FFFDD4958F300007FFFDD48CE60 torch_cpu.dll!at::native::multi_margin_loss_cpu_out [<unknown file> @ <unknown line number>]
00007FFFDD49773400007FFFDD4976D0 torch_cpu.dll!at::native::structured_nll_loss_forward_out_cpu::impl [<unknown file> @ <unknown line number>]
00007FFFDDCDC3DE00007FFFDDCCB710 torch_cpu.dll!at::cpu::zero_ [<unknown file> @ <unknown line number>]
00007FFFDDCA19AE00007FFFDDC76730 torch_cpu.dll!at::cpu::bucketize_outf [<unknown file> @ <unknown line number>]
00007FFFDD8DB89000007FFFDD8874F0 torch_cpu.dll!at::_ops::zeros_out::redispatch [<unknown file> @ <unknown line number>]
00007FFFDDA6308300007FFFDDA62FE0 torch_cpu.dll!at::_ops::nll_loss_forward::redispatch [<unknown file> @ <unknown line number>]
00007FFFDE7FAFA300007FFFDE67A050 torch_cpu.dll!torch::autograd::GraphRoot::apply [<unknown file> @ <unknown line number>]
00007FFFDE7C60F200007FFFDE67A050 torch_cpu.dll!torch::autograd::GraphRoot::apply [<unknown file> @ <unknown line number>]
00007FFFDDA1698C00007FFFDDA16800 torch_cpu.dll!at::_ops::nll_loss_forward::call [<unknown file> @ <unknown line number>]
00007FFFDD497F0F00007FFFDD497E90 torch_cpu.dll!at::native::nll_loss [<unknown file> @ <unknown line number>]
00007FFFDDE5B6B200007FFFDDE57680 torch_cpu.dll!at::compositeimplicitautograd::where [<unknown file> @ <unknown line number>]
00007FFFDDE3AA5D00007FFFDDE0FD00 torch_cpu.dll!at::compositeimplicitautograd::broadcast_to [<unknown file> @ <unknown line number>]
00007FFFDDAE0C6F00007FFFDDAE0AE0 torch_cpu.dll!at::_ops::nll_loss::call [<unknown file> @ <unknown line number>]
00007FFFDD49888F00007FFFDD497F80 torch_cpu.dll!at::native::nll_loss_nd [<unknown file> @ <unknown line number>]
00007FFFDDE5B6E200007FFFDDE57680 torch_cpu.dll!at::compositeimplicitautograd::where [<unknown file> @ <unknown line number>]
00007FFFDDE3AACD00007FFFDDE0FD00 torch_cpu.dll!at::compositeimplicitautograd::broadcast_to [<unknown file> @ <unknown line number>]
00007FFFDD92142F00007FFFDD9212A0 torch_cpu.dll!at::_ops::nll_loss_nd::call [<unknown file> @ <unknown line number>]
00007FFFDD49653F00007FFFDD496250 torch_cpu.dll!at::native::cross_entropy_loss [<unknown file> @ <unknown line number>]
00007FFFDDE5968100007FFFDDE57680 torch_cpu.dll!at::compositeimplicitautograd::where [<unknown file> @ <unknown line number>]
00007FFFDDE3AB5200007FFFDDE0FD00 torch_cpu.dll!at::compositeimplicitautograd::broadcast_to [<unknown file> @ <unknown line number>]
00007FFFDDAC6B2300007FFFDDAC6980 torch_cpu.dll!at::_ops::cross_entropy_loss::call [<unknown file> @ <unknown line number>]
00007FFFDD1BFC7100007FFFDD1BFC40 torch_cpu.dll!at::cross_entropy_loss [<unknown file> @ <unknown line number>]
00007FF807BB5E0500007FF807BB5C60 LibTorchSharp.DLL!THSNN_cross_entropy [<unknown file> @ <unknown line number>]
00007FF878AE5734 <unknown symbol address> !<unknown symbol> [<unknown file> @ <unknown line number>]

--------
 at TorchSharp.torch.CheckForErrors()
   at TorchSharp.Modules.CrossEntropyLoss.forward(Tensor input, Tensor target)
   at Microsoft.ML.TorchSharp.NasBert.NasBertTrainer`2.TrainerBase.TrainStep(DataViewRowCursor cursor, ValueGetter`1 sentence1Getter, ValueGetter`1 sentence2Getter, ValueGetter`1 labelGetter, List`1& inputTensors, List`1& targets)
   at Microsoft.ML.TorchSharp.NasBert.NasBertTrainer`2.TrainerBase.Train(IDataView input)
   at Microsoft.ML.TorchSharp.NasBert.NasBertTrainer`2.Fit(IDataView input)
   at Microsoft.ML.Data.EstimatorChain`1.Fit(IDataView input)
   at Microsoft.ML.AutoML.SweepablePipelineRunner.Run(TrialSettings settings)
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.ML.AutoML.AutoMLExperiment.<RunAsync>d__26.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ML.ModelBuilder.AutoMLService.TextClassificationExperiment.<ExecuteAsync>d__13.MoveNext() in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/Experiments/TextClassificationExperiment.cs:line 131
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ML.ModelBuilder.AutoMLEngine.<StartTrainingAsync>d__21.MoveNext() in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/AutoMLEngineService/AutoMLEngine.cs:line 141

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by beccamc** [comment]
@uuxxaa Can you give more details about your dataset? What is the size?

**Comment by beccamc** [comment]
Duplicate. See 2369 for tracking.
