### ISSUE TITLE
New compute wizard fails with MinNodeCount must be specified. 

### ISSUE THREAD

**Issue by jaydeboer** [dotnet/machinelearning-modelbuilder#2386]
**Model Builder Version**: 16.14.0.2255902
**Visual Studion Version**: 17.4.1

**Bug description**
Receive error when trying to create compute resources for an object detection project in Visual Studio. 

```
ScaleSettings.MaxNodeCount and ScaleSettings.MinNodeCount must be specified for create compute.
Status: 400 (ScaleSettings.MaxNodeCount and ScaleSettings.MinNodeCount must be specified for create compute.)
ErrorCode: UserError
```

**Steps to Reproduce**
1. Create a new `.mbconfig` file
2. Choose `Object Detection` scenario
3. On the `Environment` tab, click the `Set up workspace` button
4. Selected `Visual Studio Enterprise` Subscription
5. Create a new `Machine Learning Workspace name`
6. Click the `New...` button 
7. Set the `Compute name`
8. St the `Compute Size` to `Standard_NC4as_T4_v3`
9. Set `Compute priority` to `Low priority`
10. Click the `Create` button

**Expected Experience**
I would expect that the compute resources would be created, and I would be returned to the previous dialog in the wizard.

**Actual Experience**
I receive the following error
```
ScaleSettings.MaxNodeCount and ScaleSettings.MinNodeCount must be specified for create compute.
Status: 400 (ScaleSettings.MaxNodeCount and ScaleSettings.MinNodeCount must be specified for create compute.)
ErrorCode: UserError

Content:
{
  "error": {
    "code": "UserError",
    "severity": null,
    "message": "ScaleSettings.MaxNodeCount and ScaleSettings.MinNodeCount must be specified for create compute.",
    "messageFormat": null,
    "messageParameters": null,
    "referenceCode": null,
    "detailsUri": null,
    "target": null,
    "details": [],
    "innerError": null,
    "debugInfo": null,
    "additionalInfo": null
  },
  "correlation": {
    "operation": "af0c4e14b071bf1ad124097cc8138c77",
    "request": "c6a058345902b3bf"
  },
  "environment": "northcentralus",
  "location": "northcentralus",
  "time": "2022-11-18T16:11:32.7653884+00:00",
  "componentName": "machinelearningcompute"
}

Headers:
Pragma: no-cache
x-ms-ratelimit-remaining-subscription-writes: REDACTED
Request-Context: REDACTED
x-ms-response-type: REDACTED
Strict-Transport-Security: REDACTED
X-Content-Type-Options: REDACTED
x-aml-cluster: REDACTED
x-request-time: REDACTED
x-ms-request-id: 670f5fe2-52f6-47a5-9e71-1177a8af2560
x-ms-correlation-request-id: REDACTED
x-ms-routing-request-id: REDACTED
Content-Length: 673
Cache-Control: no-cache
Content-Type: application/json; charset=utf-8
Date: Fri, 18 Nov 2022 16:11:32 GMT
Expires: -1

at Azure.ResourceManager.MachineLearning.ComputeRestOperations.<CreateOrUpdateAsync>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Azure.ResourceManager.MachineLearning.MachineLearningComputeCollection.<CreateOrUpdateAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ML.ModelBuilder.RemoteResourceManager.AzureResourceManager.<CreateAMLComputeAsync>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ML.ModelBuilder.AzureAttach.NewComputeDataContext.<CreateComputeAsync>d__23.MoveNext()
```
**Additional Context**

I am running Visual Studio in a Parallels VM on a MacBook Pro.

**Comment by zewditu** [comment]
@jaydeboer, sorry for hitting the issue, we will investigate it.

**Comment by Jenscaasen** [comment]
Having the same problem with Standard_NC6 image. Visual Studio 2022, up to date.

`ScaleSettings.MaxNodeCount and ScaleSettings.MinNodeCount must be specified for create compute.
Status: 400 (ScaleSettings.MaxNodeCount and ScaleSettings.MinNodeCount must be specified for create compute.)
ErrorCode: UserError

Content:
{
  "error": {
    "code": "UserError",
    "severity": null,
    "message": "ScaleSettings.MaxNodeCount and ScaleSettings.MinNodeCount must be specified for create compute.",
    "messageFormat": null,
    "messageParameters": null,
    "referenceCode": null,
    "detailsUri": null,
    "target": null,
    "details": [],
    "innerError": null,
    "debugInfo": null,
    "additionalInfo": null
  },
  "correlation": {
    "operation": "0c60e2ac1be04499761abfef25beb033",
    "request": "997aeb1b262dfb50"
  },
  "environment": "westeurope",
  "location": "westeurope",
  "time": "2023-01-06T10:54:55.7634809+00:00",
  "componentName": "machinelearningcompute"
}

Headers:
Pragma: no-cache
x-ms-ratelimit-remaining-subscription-writes: REDACTED
Request-Context: REDACTED
x-ms-response-type: REDACTED
Strict-Transport-Security: REDACTED
X-Content-Type-Options: REDACTED
x-aml-cluster: REDACTED
x-request-time: REDACTED
x-ms-request-id: 1b4fef80-045d-40fe-bbc6-7013444f3bdf
x-ms-correlation-request-id: REDACTED
x-ms-routing-request-id: REDACTED
Content-Length: 665
Cache-Control: no-cache
Content-Type: application/json; charset=utf-8
Date: Fri, 06 Jan 2023 10:54:55 GMT
Expires: -1
`

**Comment by ktravelet** [comment]
Same issue here:

![image](https://user-images.githubusercontent.com/14185506/219472974-34041102-b863-4ca2-95e1-4df65fa0f47b.png)

**Comment by beccamc** [comment]
@luisquintanilla We're getting multiple reports of this problem. We should investigate, I've added this to the March milestone.

**Comment by luisquintanilla** [comment]
@beccamc sounds good. Thanks.Bumped it to Pri0

**Comment by beccamc** [comment]
Work around for those struggling with this. You may be able to create a compute in the Azure ML Studio - https://ml.azure.com/

Go to Compute -> Compute Cluster -> New. 

![image](https://user-images.githubusercontent.com/9122518/219486392-337859ea-60b7-4230-9c33-7f1db5f4a8a6.png)

Any of these compute types will work....

NC T4 v3 VM series:
- "STANDARD_NC4AS_T4_V3",
- "STANDARD_NC16As_T4_V3"
- "STANDARD_NC64As_T4_V3"
- "STANDARD_NC24RS_V3"

NCv3-series:
- "STANDARD_NC6S_V3"
- "STANDARD_NC12S_V3"
- "STANDARD_NC24S_V3"
-  "STANDARD_NC24RS_V3*"

**Comment by ktravelet** [comment]
heyyy, this worked for me!  Created a "Standard_NC4as_T4_v3".  Just need to select it now in the Model Builder UI now!

**Comment by beccamc** [comment]
@JakeRadMSFT You probably want to fix this.

**Comment by slefcourt27** [comment]
Wanted to +1 this as I am encountering the same problem while following the tutorial from here: https://learn.microsoft.com/en-us/azure/machine-learning/tutorial-train-deploy-image-classification-model-vscode

**Comment by v-Hailishi** [comment]
The bug has been fixed on the latest main build 17.14.4.2318101.
![#2386](https://user-images.githubusercontent.com/99375895/229403679-6b8bf778-974d-4eca-8616-6b60136ec11c.gif)

**Comment by johnseed** [comment]
> Work around for those struggling with this. You may be able to create a compute in the Azure ML Studio - https://ml.azure.com/
> 
> Go to Compute -> Compute Cluster -> New.
> 
> ![image](https://user-images.githubusercontent.com/9122518/219486392-337859ea-60b7-4230-9c33-7f1db5f4a8a6.png)
> 
> Any of these compute types will work....
> 
> NC T4 v3 VM series:
> 
> * "STANDARD_NC4AS_T4_V3",
> * "STANDARD_NC16As_T4_V3"
> * "STANDARD_NC64As_T4_V3"
> * "STANDARD_NC24RS_V3"
> 
> NCv3-series:
> 
> * "STANDARD_NC6S_V3"
> * "STANDARD_NC12S_V3"
> * "STANDARD_NC24S_V3"
> * "STANDARD_NC24RS_V3*"
> 
> Once you create the compute it should be available via Model Builder.

I have created a STANDARD_NC64As_T4_V3, but it does not appear when selecting Compute. Only the sizes that are displayed in the drop-down menu when creating Compute are shown. 
ML Model Builder Version : 17.14.4.2312404

![image](https://user-images.githubusercontent.com/48501700/230296167-09debbf9-f59b-4a4a-bee2-33e649651b98.png)
![image](https://user-images.githubusercontent.com/48501700/230296297-0aa42090-05ab-42c3-9e58-96d0bf9f924b.png)
![image](https://user-images.githubusercontent.com/48501700/230296935-096d4418-28f0-4042-86bc-d5dd1af77ff5.png)
