### ISSUE TITLE
ML.NET CLI train command with version 3 mbconfig throws

### ISSUE THREAD

**Issue by soenneker** [dotnet/machinelearning-modelbuilder#2387]
**System Information (please complete the following information):**
 - Model Builder Version (available in Manage Extensions dialog): 16.14, and 16.13 CLI
 - Visual Studio Version: 22 Preview

**Describe the bug**
- On which step of the process did you run into an issue: mlnet cli `train` command
- Clear description of the problem: Upgraded VS extension from 16.13 to 16.14. This in turn upgraded my mbconfig files to version 3. When I try to run the mlnet cli `train` command with version 16.13 I get this exception:

```
System.ArgumentException: This version of Model Builder does not support version 3 of type TrainingConfig. Please update Model Builder to latest version in the VS Extension Manager.
   at Microsoft.ML.ModelBuilder.Configuration.MBConfigConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer) in /_/src/Microsoft.ML.ModelBuilder.TrainingConfiguration/MBConfigConverter.cs:line 51
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Deserialize(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Microsoft.ML.CLI.TrainingConfigurationHelper.LoadFromFileAsync(String filePath) in /_/src/mlnet/TrainingConfigurationHelper.cs:line 42
   at Microsoft.ML.CLI.Program.<>c.<<CreateRootCommandLineBuilder>b__4_4>d.MoveNext() in /_/src/mlnet/Program.cs:line 161
```

**To Reproduce**
1. Build version 3 (16.14) mbconfig
2. Update mlnet cli to latest version (16.13)
3. Execute command: `mlnet train --training-config test.mbconfig -v diag`

**Expected behavior**
Not throw.

**Comment by beccamc** [comment]
Thanks for filing this with details! As it seems you've figured out, this is because we've shipped a more recent version of Model Builder than the CLI. 

@LittleLittleCloud Can we get a new version of the CLI ready? @luisquintanilla We should take this into consideration for future releases. Especially important when we rev the version of the .mbconfig file.

**Comment by luisquintanilla** [comment]
> We should take this into consideration for future releases. Especially important when we rev the version of the .mbconfig file.

Yeah. That makes sense.

**Comment by beccamc** [comment]
@LittleLittleCloud What is needed for a new CLI version? cc @JakeRadMSFT

**Comment by LittleLittleCloud** [comment]
> @LittleLittleCloud What is needed for a new CLI version? cc @JakeRadMSFT

We need to release that new CLI by going to this link
https://devdiv.visualstudio.com/DevDiv/_release?_a=releases&view=mine&definitionId=2553
and approve the `Publish cli to NuGet`. We haven't make any significant change in CLI so we can just use the latest build.

Or just let me know if you want me to do this.

**Comment by LittleLittleCloud** [comment]
published

**Comment by luisquintanilla** [comment]
@v-Hailishi can you please validate that this issue has been resolved with the latest version of the ML.NET CLI

- [Windows](https://www.nuget.org/packages/mlnet-win-x64)
- [Mac](https://www.nuget.org/packages/mlnet-osx-x64)
- [Linux](https://www.nuget.org/packages/mlnet-linux-x64)

**Comment by v-Hailishi** [comment]
@luisquintanilla I have validated this issue on **Windows**, the bug has been fixed with the latest version of the ML.NET CLI 16.14.0.
