### ISSUE TITLE
Running the latest mlnet throws System.NotImplementedException exceptions.

### ISSUE THREAD

**Issue by gbanuk2** [dotnet/machinelearning-modelbuilder#2406]
**System Information (please complete the following information):**
 mlnet --version
16.14.0+4be0d1bbdd23182e304cd74a8b833c40fd980be3
 Visual Studio Version : 17.4.2

I've been using the command line mlnet tool to train my datasets. The previous version worked fine. The new version is crashing with some exceptions like below. The previous version was (16.13.9+3066041f1761935763bdd267a9bcbb64cb3ec543) the new version is (16.14.0+4be0d1bbdd23182e304cd74a8b833c40fd980be3).

**Describe the bug**
Running mlnet on the command line throws the bug:
C:\pubtemp>mlnet classification --dataset "Diameter.csv" --label-col 1 --name "Diameter" --train-time 60
Start Training
System.NotImplementedException: The method or operation is not implemented.
   at Microsoft.ML.ModelBuilder.AutoMLService.Experiments.ExperimentFactory.CreateExperiment(MLContext context, ITrainingConfiguration config, AutoMLDependService services, PathConfiguration pathConfig) in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/Experiments/ExperimentFactory.cs:line 36
   at Microsoft.ML.ModelBuilder.AutoMLEngine.StartTrainingAsync(ITrainingConfiguration config, PathConfiguration pathConfig, CancellationToken userCancellationToken) in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/AutoMLEngineService/AutoMLEngine.cs:line 135
   at Microsoft.ML.CLI.Runners.AutoMLRunner.ExecuteAsync() in /_/src/mlnet/Runners/AutoMLRunner.cs:line 89
   at Microsoft.ML.CLI.Program.TrainAsync(TrainingConfiguration trainingConfiguration, PathConfiguration pathConfig, AutoMLServiceLogLevel logLevel) in /_/src/mlnet/Program.cs:line 349
   at Microsoft.ML.CLI.Program.AutoMLCommandRunner(AutoMLCommand command, Boolean skipGenerateConsoleApp) in /_/src/mlnet/Program.cs:line 330
   at Microsoft.ML.CLI.Program.<>c.<<CreateRootCommandLineBuilder>b__4_0>d.MoveNext() in /_/src/mlnet/Program.cs:line 90
--- End of stack trace from previous location ---
   at System.CommandLine.Invocation.CommandHandler.GetExitCodeAsync(Object value, InvocationContext context)
   at System.CommandLine.Invocation.ModelBindingCommandHandler.InvokeAsync(InvocationContext context)
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass23_0.<<UseParseErrorReporting>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.ML.CLI.Program.<>c__DisplayClass4_0.<<CreateRootCommandLineBuilder>b__9>d.MoveNext() in /_/src/mlnet/Program.cs:line 291
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseSuggestDirective>b__24_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass22_0.<<UseParseDirective>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass11_0.<<UseDebugDirective>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<RegisterWithDotnetSuggest>b__10_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass14_0.<<UseExceptionHandler>b__0>d.MoveNext()
Check out log file for more information: C:\Users\bddev\AppData\Local\Temp\mlnet\log.txt
Exiting ...

Additional info from log.txt:
2022-12-06 13:02:43.3963 DEBUG Set log file path to C:\Users\bddev\AppData\Local\Temp\mlnet\log.txt (Microsoft.ML.CLI.Commands.MLCommand.set_LogFilePath)
2022-12-06 13:02:43.4245 DEBUG Set log file path to C:\Users\bddev\AppData\Local\Temp\mlnet\log.txt (Microsoft.ML.CLI.Commands.MLCommand.set_LogFilePath)
2022-12-06 13:02:43.4245 DEBUG Set log file path to C:\Users\bddev\AppData\Local\Temp\mlnet\log.txt (Microsoft.ML.CLI.Commands.MLCommand.set_LogFilePath)
2022-12-06 13:02:43.4331 DEBUG Set log file path to C:\Users\bddev\AppData\Local\Temp\mlnet\log.txt (Microsoft.ML.CLI.Commands.MLCommand.set_LogFilePath)
2022-12-06 13:02:43.4331 DEBUG Set log file path to C:\Users\bddev\AppData\Local\Temp\mlnet\log.txt (Microsoft.ML.CLI.Commands.MLCommand.set_LogFilePath)
2022-12-06 13:02:43.4331 DEBUG Set log file path to C:\Users\bddev\AppData\Local\Temp\mlnet\log.txt (Microsoft.ML.CLI.Commands.MLCommand.set_LogFilePath)
2022-12-06 13:02:43.4450 DEBUG Set log file path to C:\Users\bddev\AppData\Local\Temp\mlnet\log.txt (Microsoft.ML.CLI.Commands.MLCommand.set_LogFilePath)
2022-12-06 13:02:43.4450 DEBUG System.FormatException: String ' available trainer: LGBM, RF, FASTTREE, LBFGS, SDCA ' was not recognized as a valid Boolean.
   at System.Boolean.Parse(ReadOnlySpan`1 value)
   at System.Boolean.Parse(String value)
   at Microsoft.ML.CLI.FeatureFlagManager.ReadFeatureFlags(String ffPath) in /_/src/mlnet/FeatureFlagManager.cs:line 64 (Microsoft.ML.CLI.FeatureFlagManager.ReadFeatureFlags)
2022-12-06 13:02:43.4857 DEBUG Set log file path to C:\Users\bddev\AppData\Local\Temp\mlnet\log.txt (Microsoft.ML.CLI.Commands.MLCommand.set_LogFilePath)
2022-12-06 13:02:43.4857 DEBUG Set log level to Info (Microsoft.ML.CLI.Commands.MLCommand.set_Verbosity)
2022-12-06 13:02:43.8027 INFO Start Training (Microsoft.ML.CLI.Runners.AutoMLRunner+<ExecuteAsync>d__8.MoveNext)
2022-12-06 13:02:43.8185 DEBUG [Source=TextLoader; Binding, Kind=Trace] Channel started (Microsoft.ML.CLI.Runners.AutoMLRunner.Instance_DiagnosticDataReceived)
2022-12-06 13:02:43.8279 DEBUG [Source=TextLoader; Binding, Kind=Trace] Channel finished. Elapsed 00:00:00.0095776. (Microsoft.ML.CLI.Runners.AutoMLRunner.Instance_DiagnosticDataReceived)
2022-12-06 13:02:43.8279 DEBUG [Source=TextLoader; Binding, Kind=Trace] Channel disposed (Microsoft.ML.CLI.Runners.AutoMLRunner.Instance_DiagnosticDataReceived)
2022-12-06 13:02:43.8584 ERROR System.NotImplementedException: The method or operation is not implemented.
   at Microsoft.ML.ModelBuilder.AutoMLService.Experiments.ExperimentFactory.CreateExperiment(MLContext context, ITrainingConfiguration config, AutoMLDependService services, PathConfiguration pathConfig) in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/Experiments/ExperimentFactory.cs:line 36
   at Microsoft.ML.ModelBuilder.AutoMLEngine.StartTrainingAsync(ITrainingConfiguration config, PathConfiguration pathConfig, CancellationToken userCancellationToken) in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/AutoMLEngineService/AutoMLEngine.cs:line 135
   at Microsoft.ML.CLI.Runners.AutoMLRunner.ExecuteAsync() in /_/src/mlnet/Runners/AutoMLRunner.cs:line 89
   at Microsoft.ML.CLI.Program.TrainAsync(TrainingConfiguration trainingConfiguration, PathConfiguration pathConfig, AutoMLServiceLogLevel logLevel) in /_/src/mlnet/Program.cs:line 349
   at Microsoft.ML.CLI.Program.AutoMLCommandRunner(AutoMLCommand command, Boolean skipGenerateConsoleApp) in /_/src/mlnet/Program.cs:line 330
   at Microsoft.ML.CLI.Program.<>c.<<CreateRootCommandLineBuilder>b__4_0>d.MoveNext() in /_/src/mlnet/Program.cs:line 90
--- End of stack trace from previous location ---
   at System.CommandLine.Invocation.CommandHandler.GetExitCodeAsync(Object value, InvocationContext context)
   at System.CommandLine.Invocation.ModelBindingCommandHandler.InvokeAsync(InvocationContext context)
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass23_0.<<UseParseErrorReporting>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.ML.CLI.Program.<>c__DisplayClass4_0.<<CreateRootCommandLineBuilder>b__9>d.MoveNext() in /_/src/mlnet/Program.cs:line 291
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseSuggestDirective>b__24_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass22_0.<<UseParseDirective>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass11_0.<<UseDebugDirective>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<RegisterWithDotnetSuggest>b__10_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass14_0.<<UseExceptionHandler>b__0>d.MoveNext() (Microsoft.ML.CLI.Program+<>c__DisplayClass4_0.<CreateRootCommandLineBuilder>b__7)
2022-12-06 13:02:43.8677 DEBUG System.NotImplementedException: The method or operation is not implemented.
   at Microsoft.ML.ModelBuilder.AutoMLService.Experiments.ExperimentFactory.CreateExperiment(MLContext context, ITrainingConfiguration config, AutoMLDependService services, PathConfiguration pathConfig) in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/Experiments/ExperimentFactory.cs:line 36
   at Microsoft.ML.ModelBuilder.AutoMLEngine.StartTrainingAsync(ITrainingConfiguration config, PathConfiguration pathConfig, CancellationToken userCancellationToken) in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/AutoMLEngineService/AutoMLEngine.cs:line 135
   at Microsoft.ML.CLI.Runners.AutoMLRunner.ExecuteAsync() in /_/src/mlnet/Runners/AutoMLRunner.cs:line 89
   at Microsoft.ML.CLI.Program.TrainAsync(TrainingConfiguration trainingConfiguration, PathConfiguration pathConfig, AutoMLServiceLogLevel logLevel) in /_/src/mlnet/Program.cs:line 349
   at Microsoft.ML.CLI.Program.AutoMLCommandRunner(AutoMLCommand command, Boolean skipGenerateConsoleApp) in /_/src/mlnet/Program.cs:line 330
   at Microsoft.ML.CLI.Program.<>c.<<CreateRootCommandLineBuilder>b__4_0>d.MoveNext() in /_/src/mlnet/Program.cs:line 90
--- End of stack trace from previous location ---
   at System.CommandLine.Invocation.CommandHandler.GetExitCodeAsync(Object value, InvocationContext context)
   at System.CommandLine.Invocation.ModelBindingCommandHandler.InvokeAsync(InvocationContext context)
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass23_0.<<UseParseErrorReporting>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.ML.CLI.Program.<>c__DisplayClass4_0.<<CreateRootCommandLineBuilder>b__9>d.MoveNext() in /_/src/mlnet/Program.cs:line 291
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseSuggestDirective>b__24_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass22_0.<<UseParseDirective>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass11_0.<<UseDebugDirective>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<RegisterWithDotnetSuggest>b__10_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass14_0.<<UseExceptionHandler>b__0>d.MoveNext() (Microsoft.ML.CLI.Program+<>c__DisplayClass4_0.<CreateRootCommandLineBuilder>b__7)
2022-12-06 13:02:43.8677 INFO Check out log file for more information: C:\Users\bddev\AppData\Local\Temp\mlnet\log.txt (Microsoft.ML.CLI.Program+<>c__DisplayClass4_0.<CreateRootCommandLineBuilder>b__7)
2022-12-06 13:02:43.8677 INFO Exiting ... (Microsoft.ML.CLI.Program+<>c__DisplayClass4_0.<CreateRootCommandLineBuilder>b__7)

**Comment by zewditu** [comment]
@gbanuk2  sorry for hitting this issue!
@LittleLittleCloud   I think this is CLI issue,  do you have context about ?

**Comment by gbanuk2** [comment]
I'm not sure what else I can post. I tried installing the tools on a new system and have the same issue. I installed the tool like so:
dotnet tool install --global mlnet-win-x64

Also installed the .NET6.0 SDK
C:\pubtemp>dotnet --list-sdks
6.0.403 [C:\Program Files\dotnet\sdk]
7.0.100 [C:\Program Files\dotnet\sdk]

I installed visual studio 17.4.2 community.

**Comment by zewditu** [comment]
@gbanuk2  the latest ml.net is 2.0,  @LittleLittleCloud  knows more about how CLI works with ml.net 2.0.

**Comment by gbanuk2** [comment]
So I copied mlnet version (16.13.9+3066041f1761935763bdd267a9bcbb64cb3ec543) from a working system to the new system and it works fine. I can train files again. So something changed in the 16.14 version that causes it to crash.

**Comment by heidiPereira** [comment]
Hello! I have the same issue.

**Comment by LittleLittleCloud** [comment]
We will soon push a fix (version 16.14.1) for this issue.

**Comment by Thiago-Bastani** [comment]
16.15.1 still has this problem. I just downgraded it to version 16.13.4 and it works fine.
