### ISSUE TITLE
Closing select a folder dialog window for image classification leads to error

### ISSUE THREAD

**Issue by vese** [dotnet/machinelearning-modelbuilder#2410]
**System Information (please complete the following information):**
 - Model Builder Version: 16.14.0.2255902 
 - Visual Studio Version: 17.5.0 Preview 1.0

**Describe the bug**
- On which step of the process did you run into an issue: For local image classification scenario on step "Data".
- Clear description of the problem: Closing select a folder dialog window leads to error. (When no folder selected before)

**To Reproduce**
1. Select Image classification scenario
2. Click on Next step button on Environment step
3. Click on ... button to open Select a folder dialog window
4. Click on cross or Cancel button to close dialog window

**Expected behavior**
Select a folder dialog window is closed, error is not displayed

**Screenshots**
![image](https://user-images.githubusercontent.com/17708516/206871482-3f34401c-defb-4ba1-9403-9f8ad51d081d.png)

**Additional context**
2022-12-10 21:53:06.1051 DEBUG Value cannot be null.
Parameter name: path
   at System.IO.DirectoryInfo..ctor(String path)
   at Microsoft.ML.ModelBuilder.ViewModels.DataImageViewModel.DisplayImageDatasetErrors()
   at Microsoft.ML.ModelBuilder.ToolWindows.ImageDataControl.<SelectFolderButton_Click>d__2.MoveNext() (Microsoft.ML.ModelBuilder.Utils.Logger.Debug)

**Comment by v-Hailishi** [comment]
The bug has been fixed on the latest main build 16.14.2.2306101
![#2410](https://user-images.githubusercontent.com/99375895/212041322-adf58b89-699a-47d7-ab71-c1aeaf3ddbd2.gif)
