### ISSUE TITLE
Text Classification scenario training error "fail to install runtime"

### ISSUE THREAD

**Issue by abidur** [dotnet/machinelearning-modelbuilder#2425]
**System Information (please complete the following information):**
 - Model Builder Version (available in Manage Extensions dialog): 16.14.0.2255902
 - Visual Studio Version: 17.4.3

**Describe the bug**
- On which step of the process did you run into an issue:
- Training Text Classification
- Clear description of the problem:
- when I run training on text classification I immediately get the error "fail to install runtime". It happens in both CPU and GPU.

**To Reproduce**
1. Go to 'Model Builder'
2. Click on 'Text Classification'
3. Scroll down to 'Select data'
4. Set Label and Text columns
5. Start training
6. See error

**Expected behavior**
I get an error saying "fail to install runtime". Happens with any dataset.
2022-12-23 02:19:10.9179 DEBUG fail to install runtime
   at Microsoft.ML.ModelBuilder.AutoMLService.RuntimeManager.InstallRuntimeAsync(CancellationToken ct) in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/RuntimeManager/RuntimeManager.cs:line 127
   at Microsoft.ML.ModelBuilder.AutoMLService.TextClassificationExperiment.<ExecuteAsync>d__13.MoveNext() in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/Experiments/TextClassificationExperiment.cs:line 61
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ML.ModelBuilder.AutoMLEngine.<StartTrainingAsync>d__21.MoveNext() in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/AutoMLEngineService/AutoMLEngine.cs:line 141 (Microsoft.ML.ModelBuilder.Utils.Logger.Debug)

**Screenshots**
![image](https://user-images.githubusercontent.com/421514/209302365-950263c4-31b7-4160-97b3-613503e03d99.png)

**Comment by zewditu** [comment]
@abidur  sorry for hitting this issue.
@LittleLittleCloud  is this related to not consolidate torchsharp runtime version into the installation path?

**Comment by abidur** [comment]
Hello, any updates or work around ideas on this issue? Thanks!

**Comment by LittleLittleCloud** [comment]
Hi @abidur 

Sorry for the late reply. There're various reasons cause "fail to install runtime" error and we need to take a few extra steps to determine which one it is.

First thing first though, here's the workaround on how to manually install runtime

- go to %temp%ModelBuilder folder, you should see two folders: torchsharp-cpu.0.96.7 && torchsharp-cuda-windwos.0.96.7. If you don't find any folder, create one.
-  open cmd and cd to torchsharp-cuda-windwos.0.96.7 (suppose you are going to install gpu runtime)
- run `dotnet publish /path/to/torchsharp.gpu.csproj -r win-x64 -c Release --no-self-contained -o .`. You can find /path/to/torchsharp.gpu.csproj in model builder output windw
- rerun model builder

To help us determine what's going on, can you first send us a screenshot of %temp%ModelBuilder here? Another attempt that definitely worth a trial is to remove all folders under %temp%ModelBuilder and re-run model builder. This is because Model Builder only checks the existence of runtime folder instead of each dlls. Because runtime folder locates in temp folder, the content of which might be regularly removed by system, which also could cause runtime fail.
