### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by alliance225** [dotnet/machinelearning-modelbuilder#2431]
2023-01-06 20:13:25.1108 INFO Set log file path to C:\Users\babad\AppData\Local\Temp\MLVSTools\logs\SentimentModel-0DWZSH.txt (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2023-01-06 20:21:17.3186 INFO start nni training (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2023-01-06 20:21:17.3586 INFO Experiment output folder: C:\Users\babad\AppData\Local\Temp\AutoML-NNI\Experiment-1YPISG (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2023-01-06 20:21:17.3586 DEBUG row count is unknown, count it explicitly (Microsoft.ML.ModelBuilder.Utils.Logger.Debug)
2023-01-06 20:21:17.4475 DEBUG count elapse 86ms (Microsoft.ML.ModelBuilder.Utils.Logger.Debug)
2023-01-06 20:21:17.4686 INFO |     Trainer                              MicroAccuracy  MacroAccuracy  Duration #Iteration                     | (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2023-01-06 20:21:20.5374 DEBUG update train dataset C:\Users\babad\AppData\Local\Temp\AutoML-NNI\Experiment-1YPISG\cv.bin (Microsoft.ML.ModelBuilder.Utils.Logger.Debug)
2023-01-06 20:22:13.7411 DEBUG Training time finished without any models trained.
   at Microsoft.ML.ModelBuilder.AutoMLService.Experiments.LocalAutoMLExperiment.<ExecuteAsync>d__15.MoveNext() in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/Experiments/LocalAutoMLExperiment.cs:line 202
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ML.ModelBuilder.AutoMLEngine.<StartTrainingAsync>d__21.MoveNext() in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/AutoMLEngineService/AutoMLEngine.cs:line 160 (Microsoft.ML.ModelBuilder.Utils.Logger.Debug)
2023-01-06 20:30:51.0332 INFO start nni training (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2023-01-06 20:30:51.0569 INFO Experiment output folder: C:\Users\babad\AppData\Local\Temp\AutoML-NNI\Experiment-QOLHI3 (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2023-01-06 20:30:51.0569 DEBUG row count is unknown, count it explicitly (Microsoft.ML.ModelBuilder.Utils.Logger.Debug)
2023-01-06 20:30:51.1060 DEBUG count elapse 45ms (Microsoft.ML.ModelBuilder.Utils.Logger.Debug)
2023-01-06 20:30:51.1150 INFO |     Trainer                              MicroAccuracy  MacroAccuracy  Duration #Iteration                     | (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2023-01-06 20:30:51.5831 DEBUG update train dataset C:\Users\babad\AppData\Local\Temp\AutoML-NNI\Experiment-QOLHI3\cv.bin (Microsoft.ML.ModelBuilder.Utils.Logger.Debug)
2023-01-06 20:31:49.5861 DEBUG One or more errors occurred. (Microsoft.ML.ModelBuilder.Utils.Logger.Debug)
2023-01-06 20:31:49.7585 DEBUG    at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.For(Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body)
   at Microsoft.ML.Trainers.SdcaTrainerBase`3.TrainCore(IChannel ch, RoleMappedData data, LinearModelParameters predictor, Int32 weightSetCount)
   at Microsoft.ML.Trainers.StochasticTrainerBase`2.TrainModelCore(TrainContext context)
   at Microsoft.ML.Trainers.TrainerEstimatorBase`2.TrainTransformer(IDataView trainSet, IDataView validationSet, IPredictor initPredictor)
   at Microsoft.ML.Data.EstimatorChain`1.Fit(IDataView input)
   at Microsoft.ML.TrainCatalogBase.CrossValidateTrain(IDataView data, IEstimator`1 estimator, Int32 numFolds, String samplingKeyColumn, Nullable`1 seed)
   at Microsoft.ML.MulticlassClassificationCatalog.CrossValidate(IDataView data, IEstimator`1 estimator, Int32 numberOfFolds, String labelColumnName, String samplingKeyColumnName, Nullable`1 seed)
   at Microsoft.ML.ModelBuilder.AutoMLService.MulticlassClassificationRunner.RunCV(TrialParameter parameter, TrainingConfiguration config, IDataView datasetCache) in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/Runner/MulticlassClassificationRunner.cs:line 36
   at Microsoft.ML.ModelBuilder.AutoMLService.LocalDispatcher.Run() in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/Dispatcher/LocalDispatcher.cs:line 163
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ML.ModelBuilder.AutoMLService.LocalDispatcher.<RunAsync>d__19.MoveNext() in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/Dispatcher/LocalDispatcher.cs:line 181
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ML.ModelBuilder.AutoMLService.LocalDispatcher.<AddTrialAsync>d__16.MoveNext() in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/Dispatcher/LocalDispatcher.cs:line 49 (Microsoft.ML.ModelBuilder.Utils.Logger.Debug)
2023-01-06 20:31:49.8018 DEBUG Training time finished without any models trained.
   at Microsoft.ML.ModelBuilder.AutoMLService.Experiments.LocalAutoMLExperiment.<ExecuteAsync>d__15.MoveNext() in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/Experiments/LocalAutoMLExperiment.cs:line 202
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ML.ModelBuilder.AutoMLEngine.<StartTrainingAsync>d__21.MoveNext() in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/AutoMLEngineService/AutoMLEngine.cs:line 160 (Microsoft.ML.ModelBuilder.Utils.Logger.Debug)

**Comment by luisquintanilla** [comment]
Hi @alliance225 

Sorry to hear you ran into an issue. Can you please provide more details such as, is this in Model Builder or the CLI? What scenario were you trying to train?

**Comment by beccamc** [comment]
@alliance225 Sorry, we don't have enough information to investigate this. If you're still having a problem, please let us know. 

- What scenario you're working on 
- When you got this error. 
- If possible, the data you're working with.
