### ISSUE TITLE
Error running mlnet cli on MacOS

### ISSUE THREAD

**Issue by andresgutierrez** [dotnet/machinelearning-modelbuilder#2433]
**System Information (please complete the following information):**
 -  macOS Monterrey 12.5
 - mlnet --version 16.14.1+6737204c7385d9f8d1252a097a5f86747dc0ce81
 - dotnet --version 7.0.101

**Describe the bug**
- Exception running mlnet cli

**To Reproduce**
Run: 

`mlnet regression --dataset /Users/main/machinelearning-samples/datasets/taxi-fare-train.csv --label-col 6 --train-time 60`

```
Start Training
start regression
Evaluate Metric: RSquared                                                                                                                                                                         Available Trainers: LGBM,FASTFOREST,FASTTREE,LBFGS,SDCA                                                                                                                                           Training time in second: 60                                                                                                                                                                       |      Trainer                             RSquared   Duration       |                                                                                                                            |--------------------------------------------------------------------|                                                                                                                            |0     FastForestRegression                0.9078     0.4480         |                                                                                                                            |1     FastForestRegression                0.9087     0.3370         |                                                                                                                            |2     FastForestRegression                0.9094     0.4820         |                                                                                                                            |--------------------------------------------------------------------|                                                                                                                            |                          Experiment Results                        |                                                                                                                            |--------------------------------------------------------------------|                                                                                                                            |                               Summary                              |                                                                                                                            |--------------------------------------------------------------------|
|ML Task: regression                                                 |
|Dataset: /Users/main/machinelearning-samples/datasets/taxi-fare-train.csv|
|Label : fare_amount                                                 |
|Total experiment time :    59.0000 Secs                             |
|Total number of models explored: 8                                  |
|--------------------------------------------------------------------|
|                        Top 5 models explored                       |
|--------------------------------------------------------------------|
|      Trainer                             RSquared   Duration       |
|--------------------------------------------------------------------|
|4     FastForestRegression                0.9157     0.4730         |
|2     FastForestRegression                0.9094     0.4820         |
|1     FastForestRegression                0.9087     0.3370         |
|0     FastForestRegression                0.9078     0.4480         |
|3     FastTreeRegression                  -0.1917    0.2520         |
|--------------------------------------------------------------------|
save SampleRegression.mbconfig to /Users/main/machinelearning-samples/samples/csharp/getting-started/MLNET2/AutoMLQuickStart/SampleRegression
System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.ML.ModelBuilder.AutoMLService.ServiceFactory.CodeGeneratorService.SetTorchRunTimeFolderAndLoadModel(TrainingConfiguration configuration, String modelPath, MLContext& context, ITransformer& model, DataViewSchema& inputSchema) in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/ServiceFactory/CodeGeneratorService.cs:line 118
   at Microsoft.ML.ModelBuilder.AutoMLService.ServiceFactory.CodeGeneratorService.CreateConsoleAppProjectCodesAsync(TrainingConfiguration configuration, Dictionary`2 sampleData, String sampleProjectName, String nameSpace, String className, String modelPath, String[] labels, String targetFramework, Boolean isDev17, CancellationToken ct) in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/ServiceFactory/CodeGeneratorService.cs:line 61
   at Microsoft.ML.CLI.Program.GenerateConsoleAppAsync(TrainingConfiguration trainingConfiguration, TrainResult trainResult, PathConfiguration pathConfig, String dataset) in /_/src/mlnet/Program.cs:line 368
   at Microsoft.ML.CLI.Program.AutoMLCommandRunner(AutoMLCommand command, Boolean skipGenerateConsoleApp) in /_/src/mlnet/Program.cs:line 338
   at Microsoft.ML.CLI.Program.<>c.<<CreateRootCommandLineBuilder>b__4_1>d.MoveNext() in /_/src/mlnet/Program.cs:line 117
--- End of stack trace from previous location ---
   at System.CommandLine.Invocation.CommandHandler.GetExitCodeAsync(Object value, InvocationContext context)
   at System.CommandLine.Invocation.ModelBindingCommandHandler.InvokeAsync(InvocationContext context)
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass23_0.<<UseParseErrorReporting>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.ML.CLI.Program.<>c__DisplayClass4_0.<<CreateRootCommandLineBuilder>b__9>d.MoveNext() in /_/src/mlnet/Program.cs:line 291
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseSuggestDirective>b__24_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass22_0.<<UseParseDirective>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass11_0.<<UseDebugDirective>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<RegisterWithDotnetSuggest>b__10_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass14_0.<<UseExceptionHandler>b__0>d.MoveNext()
Check out log file for more information: /var/folders/t8/v_n0758d7vlgwx_kl8mkc5dr0000gn/T/mlnet/log.txt
Exiting ...
```

**Expected behavior**
No error and model + code generated.

**Comment by Keshish** [comment]
@LittleLittleCloud I also have the same issue

**Comment by nnchvxx** [comment]
I have the same issue. Did anyone resolve it?

**Comment by LittleLittleCloud** [comment]
I've tested it on most recent cli and this issue seems to go away. Feel free to reopen it if you encounter it again
