### ISSUE TITLE
Activating the "MicrosoftMLModelBuilderAutoML" service failed.

### ISSUE THREAD

**Issue by kamilk91** [dotnet/machinelearning-modelbuilder#2434]
**Model Builder Version**: _In which Model Builder version was the bug encountered?_

16.14.0.2255902

**Visual Studion Version**: _In which Visual Studio version was the bug encountered?_
17.4.2
**Bug description**

After dataset choosen (csv), i have this error
```
2023-01-11 11:24:34.4019 INFO Set log file path to C:\Users\kamil\AppData\Local\Temp\MLVSTools\logs\MLModel-HWFR10.txt (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2023-01-11 11:24:48.9053 DEBUG Activating the "MicrosoftMLModelBuilderAutoML" service failed.
   at Microsoft.ServiceHub.Framework.RemoteServiceBroker.<GetProxyAsync>d__33`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at Microsoft.VisualStudio.Utilities.ServiceBroker.GlobalBrokeredServiceContainer.ProfferedRemoteServiceBroker.<GetProxyAsync>d__19`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at Microsoft.VisualStudio.Utilities.ServiceBroker.GlobalBrokeredServiceContainer.View.<GetProxyAsync>d__19`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ML.ModelBuilder.AutoMLServiceFactory.<CreateAutoMLServiceAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ML.ModelBuilder.Actions.DataTextActions.<GetCsvDataProgramAsync>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ML.ModelBuilder.Actions.DataTextActions.<SetFilePathAsync>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ML.ModelBuilder.ToolWindows.DataTextViewModel.<SetFilePathAsync>d__122.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ML.ModelBuilder.ToolWindows.TextDataControl.<<BrowseFileButton_Click>b__4_0>d.MoveNext() (Microsoft.ML.ModelBuilder.Utils.Logger.Debug)
2023-01-11 11:26:31.8654 DEBUG Activating the "MicrosoftMLModelBuilderAutoML" service failed.
   at Microsoft.ServiceHub.Framework.RemoteServiceBroker.<GetProxyAsync>d__33`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at Microsoft.VisualStudio.Utilities.ServiceBroker.GlobalBrokeredServiceContainer.ProfferedRemoteServiceBroker.<GetProxyAsync>d__19`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at Microsoft.VisualStudio.Utilities.ServiceBroker.GlobalBrokeredServiceContainer.View.<GetProxyAsync>d__19`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ML.ModelBuilder.AutoMLServiceFactory.<CreateAutoMLServiceAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ML.ModelBuilder.Actions.DataTextActions.<GetCsvDataProgramAsync>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ML.ModelBuilder.Actions.DataTextActions.<SetFilePathAsync>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ML.ModelBuilder.ToolWindows.DataTextViewModel.<SetFilePathAsync>d__122.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ML.ModelBuilder.ToolWindows.TextDataControl.<<BrowseFileButton_Click>b__4_0>d.MoveNext() (Microsoft.ML.ModelBuilder.Utils.Logger.Debug)


```

**Steps to Reproduce**
1. Right click on .csproj file in vs2022
2. Add => Machine Learning model
3. Data classification => Local
4. Local CPU 
5. Data (here is error, when im adding file)

**Expected Experience**
Prepare correct model.
**Actual Experience**

![image](https://user-images.githubusercontent.com/26136300/211783043-26213ae3-8cb0-4cce-9040-84bbe85f9180.png)

**Additional Context**
_Add any other context about the problem here, such as unusual system configurations, network restrictions, etc._

**Comment by kamilk91** [comment]
Hello @luisquintanilla 
I tried it couple times with no result. Sorry for late reply.

**Comment by shwelc2** [comment]
I am getting the same issue on my windows arm/visual studio.  I have uninstalled/reinstalled also.

**Comment by tennaito** [comment]
I am getting a similar issue, after a try attempt to process a model with a file (.csv) with text and other fields it take a long time to process (unstopping) and than it loses the connection with the automl host. After that the ML.NET Model Builder is not working anymore (MS Visual Studio 2022) even if:
- Restart the computer;
- Install/Reinstall from Extensions installer (that option it emmits an error)
- Install/Reinstall from Visual Studio Installer (Individual Components)
- Force deletion of ModelBuilder folder on C:\Program Files\Microsoft Visual Studio\2022\Professional\Common7\IDE\CommonExtensions\Microsoft

Neither of that attempts resolved the issues. Tried the same with Visual Studio 2022 preview and that is not working too.

**Comment by faikozcan** [comment]
Having the same issue on macbook which runs windows on parallels desktop.
