### ISSUE TITLE
Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by fred-ahead** [dotnet/machinelearning-modelbuilder#2454]
**System Information (please complete the following information):**
 - Model Builder or CLI Version: 16.14.1+6737204c7385d9f8d1252a097a5f86747dc0ce81
 - Visual Studio Version (if applicable):

**Describe the bug**
- On which page of the tutorial did you run into an issue (URL): https://dotnet.microsoft.com/en-us/learn/ml-dotnet/get-started-tutorial/train
- Clear description of the problem: When attempting to run the classification command receive the following output:
System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.ML.ModelBuilder.AutoMLService.ServiceFactory.CodeGeneratorService.SetTorchRunTimeFolderAndLoadModel(TrainingConfiguration configuration, String modelPath, MLContext& context, ITransformer& model, DataViewSchema& inputSchema) in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/ServiceFactory/CodeGeneratorService.cs:line 118
   at Microsoft.ML.ModelBuilder.AutoMLService.ServiceFactory.CodeGeneratorService.CreateConsoleAppProjectCodesAsync(TrainingConfiguration configuration, Dictionary`2 sampleData, String sampleProjectName, String nameSpace, String className, String modelPath, String[] labels, String targetFramework, Boolean isDev17, CancellationToken ct) in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/ServiceFactory/CodeGeneratorService.cs:line 61
   at Microsoft.ML.CLI.Program.GenerateConsoleAppAsync(TrainingConfiguration trainingConfiguration, TrainResult trainResult, PathConfiguration pathConfig, String dataset) in /_/src/mlnet/Program.cs:line 368
   at Microsoft.ML.CLI.Program.AutoMLCommandRunner(AutoMLCommand command, Boolean skipGenerateConsoleApp) in /_/src/mlnet/Program.cs:line 338
   at Microsoft.ML.CLI.Program.<>c.<<CreateRootCommandLineBuilder>b__4_0>d.MoveNext() in /_/src/mlnet/Program.cs:line 90
--- End of stack trace from previous location ---
   at System.CommandLine.Invocation.CommandHandler.GetExitCodeAsync(Object value, InvocationContext context)
   at System.CommandLine.Invocation.ModelBindingCommandHandler.InvokeAsync(InvocationContext context)
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass23_0.<<UseParseErrorReporting>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.ML.CLI.Program.<>c__DisplayClass4_0.<<CreateRootCommandLineBuilder>b__9>d.MoveNext() in /_/src/mlnet/Program.cs:line 291
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseSuggestDirective>b__24_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass22_0.<<UseParseDirective>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass11_0.<<UseDebugDirective>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<RegisterWithDotnetSuggest>b__10_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass14_0.<<UseExceptionHandler>b__0>d.MoveNext()

**To Reproduce**
1. Run mlnet classification --dataset "yelp_labelled.txt" --label-col 1 --has-header false --name SentimentModel  --train-time 60mlnet

**Expected behavior**
A successful build of the classification dataset

**Comment by fred-ahead** [comment]
Only SentimentModel.mbconfig and SentimentModel.zip is created. The application code is not generated.

**Comment by luisquintanilla** [comment]
Hi @fred-ahead 

Sorry to hear you ran into this issue. We're looking into it.

@LittleLittleCloud can you please take a look at this one. Thanks.

**Comment by derekforeman** [comment]
I am seeing the same issue
mlnet version : 16.14.2+48a74e849ab32700b5af6489a96ff50c0e3bc429

**Comment by LittleLittleCloud** [comment]
Looking at it

**Comment by LittleLittleCloud** [comment]
We push a fix for it, in the meanwhile, a workaround can be adding a $Path variable in your system environment.

**Comment by fred-ahead** [comment]
@LittleLittleCloud What is missing from the path?  Happy to do that, just need to know what to add to my path.

**Comment by LittleLittleCloud** [comment]
@fred-ahead The content of $Path doesn't matter. This issue is caused because mlnet cli can't find $Path environment variable is missing in the system.

**Comment by joanimato** [comment]
@LittleLittleCloud can you elaborate? I'm running into the same exact issue with the mlnet cli on MacOs. My path variable is set and displays correctly when doing `echo $PATH`

**Comment by LittleLittleCloud** [comment]
@joanimato sure. We just push a fix to nuget and please update to the latest cli to deploy the fix.

More details on this error if anyone interests

MLNet cli checks if env:path exists in environment by calling
```
var path = Environment.GetVariable("Path")
```
and then adds runtime folder into `env:Path`.

by calling 

```
if (!path.contain(runtimefolder))
    path = /path/to/runtime;path
```

The problem is `Environment.GetVariable("Path")` returns a null if "Path" doesn't exist. And if "Path" is null, calling path.contain will trigger an object reference not set instance exception.

**Comment by fred-ahead** [comment]
If it checks for Path then that is most likely the issue as on a Mac the PATH variable is all caps.  Path does not work for Mac, neither does path. PATH does work though. On Windows the capitalization doesn't matter.

**Comment by fred-ahead** [comment]
To be clear, on a Mac this issue is easily resolved by doing the following:

export Path=$PATH

I was able to easily build the code with the above command.

**Comment by LittleLittleCloud** [comment]
it might affect text classification GPU training in Mac. @LittleLittleCloud to look into
