### ISSUE TITLE
"Admin" Mode error when training on Text Classification scenario

### ISSUE THREAD

**Issue by jwood803** [dotnet/machinelearning-modelbuilder#2471]
**System Information (please complete the following information):**
 - Model Builder Version (available in Manage Extensions dialog): 16.14.0.55902
 - Visual Studio Version: 17.4.4

**Describe the bug**
Getting exception when attempting to train on the Text Classification scenario

<img width="505" alt="image" src="https://user-images.githubusercontent.com/1578160/215918201-5867a747-23f1-4044-8eaf-0a9482359680.png">

**To Reproduce**
1. Use the Text Classification scenario
2. Use the [yelp dataset](https://raw.githubusercontent.com/dotnet/csharp-notebooks/main/machine-learning/data/yelp_labelled.txt)
3. Use local environment
4. Click the Train button

**Additional context**
Was run in a Windows VM on Azure. Can provide more information on that, if needed.

Full stack trace:
```plaintext
2023-02-01 00:29:10.5247 INFO start text classification  (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2023-02-01 00:29:10.6287 DEBUG Text Classification cannot be run when Visual Studio is an elevated 'Admin' mode. Please use Model Builder from a non-elevated Visual Studio.
   at Microsoft.ML.ModelBuilder.AutoMLService.RuntimeManager.InstallRuntimeAsync(CancellationToken ct) in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/RuntimeManager/RuntimeManager.cs:line 64
   at Microsoft.ML.ModelBuilder.AutoMLService.TextClassificationExperiment.<ExecuteAsync>d__13.MoveNext() in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/Experiments/TextClassificationExperiment.cs:line 61
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ML.ModelBuilder.AutoMLEngine.<StartTrainingAsync>d__21.MoveNext() in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/AutoMLEngineService/AutoMLEngine.cs:line 141 (Microsoft.ML.ModelBuilder.Utils.Logger.Debug)
```

**Comment by JakeRadMSFT** [comment]
Why are you running as admin? :) We did this for safety reasons for now.

**Comment by jwood803** [comment]
> Why are you running as admin? :) We did this for safety reasons for now.

I was able to configure my Azure VM with a user that's not admin and it's working great! I'll close this, but feel free to reopen, if needed.

**Comment by 13810737879** [comment]
hi，did you resolved this problem? how to fix it?
