### ISSUE TITLE
Sentence Similarity 2019 error

### ISSUE THREAD

**Issue by beccamc** [dotnet/machinelearning-modelbuilder#2508]
Sentence similarity is getting an error for me in VS 2019. I am not seeing this problem with the 2022 build. 

External component has thrown an exception.

   at TorchSharp.PInvoke.LibTorchSharp.THSTensor_matmul(IntPtr tensor, IntPtr target)
   at TorchSharp.torch.Tensor.matmul(Tensor target)
   at Microsoft.ML.TorchSharp.NasBert.Modules.MultiHeadAttention.forward(Tensor query, Tensor key, Tensor value, Tensor& outAttentionWeights, Tensor keyPaddingMask, Dictionary`2 incrementalState, Boolean needWeights, Boolean staticKv, Tensor attentionMask)
   at Microsoft.ML.TorchSharp.NasBert.Modules.Layers.SelfAttentionLayer.forward(Tensor x, Dictionary`2 param)
   at Microsoft.ML.TorchSharp.NasBert.Models.TransformerEncoder.ForwardOneLayer(Tensor input, Tensor paddingMask, Int32 i, Int32 blockPerLayer, Int32& blockIndex)
   at Microsoft.ML.TorchSharp.NasBert.Models.TransformerEncoder.forward(Tensor tokens, Tensor segmentLabels, Tensor positions)
   at Microsoft.ML.TorchSharp.NasBert.Models.NasBertModel.forward(Tensor srcTokens, Tensor mask)
   at Microsoft.ML.TorchSharp.NasBert.NasBertTrainer`2.TrainerBase.TrainStep(IHost host, DataViewRowCursor cursor, ValueGetter`1 sentence1Getter, ValueGetter`1 sentence2Getter, ValueGetter`1 labelGetter, List`1& inputTensors, List`1& targets)
   at Microsoft.ML.TorchSharp.NasBert.NasBertTrainer`2.TrainerBase.Train(IHost host, IDataView input)
   at Microsoft.ML.TorchSharp.NasBert.NasBertTrainer`2.Fit(IDataView input)
   at Microsoft.ML.Data.EstimatorChain`1.Fit(IDataView input)
   at Microsoft.ML.AutoML.SweepablePipelineRunner.Run(TrialSettings settings)
   at Microsoft.ML.AutoML.SweepablePipelineRunner.RunAsync(TrialSettings settings, CancellationToken ct)
   at Microsoft.ML.AutoML.AutoMLExperiment.<RunAsync>d__24.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ML.ModelBuilder.AutoMLService.Experiments.SentenceSimilarityExperiment.<ExecuteAsync>d__13.MoveNext() in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/Experiments/SentenceSimilarityExperiment.cs:line 103
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ML.ModelBuilder.AutoMLEngine.<StartTrainingAsync>d__21.MoveNext() in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/AutoMLEngineService/AutoMLEngine.cs:line 145

**Comment by beccamc** [comment]
CPU is training in 2019

![image](https://user-images.githubusercontent.com/9122518/220771254-6bd37d4b-a822-4b97-afd0-ad1f6c4cd19f.png)

**Comment by LittleLittleCloud** [comment]
Can't reproduce on my side.
