### ISSUE TITLE
ML.Net Model Builder fail to install runtime

### ISSUE THREAD

**Issue by yigit1287** [dotnet/machinelearning-modelbuilder#2513]
We were trying to build a model on gpu but the following error accured.

   konum: Microsoft.ML.ModelBuilder.AutoMLService.RuntimeManager.InstallRuntimeAsync(CancellationToken ct) /_/src/Microsoft.ML.ModelBuilder.AutoMLService/RuntimeManager/RuntimeManager.cs içinde: satır 148
   konum: Microsoft.ML.ModelBuilder.AutoMLService.LocalImageClassificationExperiment.<ExecuteAsync>d__13.MoveNext() /_/src/Microsoft.ML.ModelBuilder.AutoMLService/Experiments/LocalImageClassificationExperiment.cs içinde: satır 51
--- Özel durumun oluşturulduğu önceki konumdan başlayan yığın izlemesinin sonu ---
   konum: System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   konum: System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   konum: Microsoft.ML.ModelBuilder.AutoMLEngine.<StartTrainingAsync>d__21.MoveNext() /_/src/Microsoft.ML.ModelBuilder.AutoMLService/AutoMLEngineService/AutoMLEngine.cs içinde: satır 145

**Comment by zewditu** [comment]
@LittleLittleCloud could you look at our runtime for image classification?

**Comment by LittleLittleCloud** [comment]
@yigit1287 
Can you provide more information:
- model builder version
- complete log
- available dotnet sdks

Thanks

**Comment by yigit1287** [comment]
Thanks for your reply.

Model Builder Version 17.14.4.2312404

.net sdk 6.0.406

2023-02-28 08:03:37.0612 INFO Set log file path to C:\Users\*******\AppData\Local\Temp\MLVSTools\logs\MLModel2-OJ6OCZ.txt (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2023-02-28 08:03:57.1942 DEBUG Start AutoMLService pid: 16332 (Microsoft.ML.ModelBuilder.Utils.Logger.Debug)
2023-02-28 08:03:57.5945 DEBUG env:path: C:\Users\*******\AppData\Local\Temp\ModelBuilder\tensorflow-cuda.2.3.1;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1\bin;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1\libnvvp;;;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files (x86)\Common Files\Intel\Shared Libraries\redist\intel64_win\mpirt;C:\Program Files (x86)\Common Files\Intel\Shared Libraries\redist\intel64_win\compiler;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR;C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\110\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files\Microsoft SQL Server\120\DTS\Binn\;C:\Moldex3D\2020\Digimat-RP\Digimat\shortcuts;C:\Program Files\dotnet\;C:\Program Files\NVIDIA Corporation\Nsight Compute 2019.4.0\;C:\Program Files\Microsoft SQL Server\150\Tools\Binn\;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\170\Tools\Binn\;C:\Users\*******\AppData\Local\Programs\Python\Python37\Scripts\;C:\Users\*******\AppData\Local\Programs\Python\Python37\;C:\miniconda;C:\miniconda\Library\mingw-w64\bin;C:\miniconda\Library\usr\bin;C:\miniconda\Library\bin;C:\miniconda\Scripts;C:\Users\*******\AppData\Local\Microsoft\WindowsApps;C:\Users\*******\.dotnet\tools (Microsoft.ML.ModelBuilder.Utils.Logger.Debug)
2023-02-28 08:03:57.6015 DEBUG C:\Users\*******\AppData\Local\Temp\ModelBuilder\tensorflow-cuda.2.3.1\obj (Microsoft.ML.ModelBuilder.Utils.Logger.Debug)
2023-02-28 08:03:57.6015 DEBUG restore "c:\program files\microsoft visual studio\2022\community\common7\ide\extensions\u31waq0z.ka1\AutoMLService\RuntimeManager\tensorflow.gpu.csproj" --configfile "c:\program files\microsoft visual studio\2022\community\common7\ide\extensions\u31waq0z.ka1\AutoMLService\RuntimeManager\NuGet.config" -r win-x64 /p:TorchSharpVersion=0.98.3 /p:TensorflowRuntimeVersion=2.3.1 /p:BaseIntermediateOutputPath="C:\Users\*******\AppData\Local\Temp\ModelBuilder\tensorflow-cuda.2.3.1\obj" (Microsoft.ML.ModelBuilder.Utils.Logger.Debug)
2023-02-28 08:03:57.6015 DEBUG publish "c:\program files\microsoft visual studio\2022\community\common7\ide\extensions\u31waq0z.ka1\AutoMLService\RuntimeManager\tensorflow.gpu.csproj" -r win-x64 -c Release --no-self-contained -o C:\Users\*******\AppData\Local\Temp\ModelBuilder\tensorflow-cuda.2.3.1 --no-restore /p:TorchSharpVersion=0.98.3 /p:TensorflowRuntimeVersion=2.3.1 /p:BaseOutputPath="C:\Users\*******\AppData\Local\Temp\ModelBuilder\tensorflow-cuda.2.3.1\bin\\" /p:BaseIntermediateOutputPath="C:\Users\*******\AppData\Local\Temp\ModelBuilder\tensorflow-cuda.2.3.1\obj\\" (Microsoft.ML.ModelBuilder.Utils.Logger.Debug)
2023-02-28 08:03:57.6015 INFO start installing runtime in C:\Users\*******\AppData\Local\Temp\ModelBuilder\tensorflow-cuda.2.3.1 (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2023-02-28 08:03:58.1178 INFO   Determining projects to restore... (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2023-02-28 08:03:58.2409 INFO   All projects are up-to-date for restore. (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2023-02-28 08:03:58.4451 INFO clean up (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2023-02-28 08:03:58.5061 DEBUG fail to install runtime
   at Microsoft.ML.ModelBuilder.AutoMLService.RuntimeManager.InstallRuntimeAsync(CancellationToken ct) in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/RuntimeManager/RuntimeManager.cs:line 148
   at Microsoft.ML.ModelBuilder.AutoMLService.LocalImageClassificationExperiment.<ExecuteAsync>d__13.MoveNext() in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/Experiments/LocalImageClassificationExperiment.cs:line 51
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ML.ModelBuilder.AutoMLEngine.<StartTrainingAsync>d__21.MoveNext() in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/AutoMLEngineService/AutoMLEngine.cs:line 145 (Microsoft.ML.ModelBuilder.Utils.Logger.Debug)

**Comment by LittleLittleCloud** [comment]
Hi @yigit1287 The log looks fine,,, can you
1) share what's in ` C:\Users*\AppData\Local\Temp\ModelBuilder\tensorflow-cuda.2.3.1`
2) remove the content under ` C:\Users*\AppData\Local\Temp\ModelBuilder\tensorflow-cuda.2.3.1` and re-run model builder
3) if 1) and 2) doesn't resolve your issue, can you manually run

`dotnet restore "c:\program files\microsoft visual studio\2022\community\common7\ide\extensions\u31waq0z.ka1\AutoMLService\RuntimeManager\tensorflow.gpu.csproj" --configfile "c:\program files\microsoft visual studio\2022\community\common7\ide\extensions\u31waq0z.ka1\AutoMLService\RuntimeManager\NuGet.config" -r win-x64 /p:TorchSharpVersion=0.98.3 /p:TensorflowRuntimeVersion=2.3.1 /p:BaseIntermediateOutputPath="C:\Users*\AppData\Local\Temp\ModelBuilder\tensorflow-cuda.2.3.1\obj"`

and 
`dotnet publish "c:\program files\microsoft visual studio\2022\community\common7\ide\extensions\u31waq0z.ka1\AutoMLService\RuntimeManager\tensorflow.gpu.csproj" -r win-x64 -c Release --no-self-contained -o C:\Users*\AppData\Local\Temp\ModelBuilder\tensorflow-cuda.2.3.1 --no-restore /p:TorchSharpVersion=0.98.3 /p:TensorflowRuntimeVersion=2.3.1 /p:BaseOutputPath="C:\Users*\AppData\Local\Temp\ModelBuilder\tensorflow-cuda.2.3.1\bin\" /p:BaseIntermediateOutputPath="C:\Users*\AppData\Local\Temp\ModelBuilder\tensorflow-cuda.2.3.1\obj\"`

And let us know the output?

Thanks!

**Comment by kampa656** [comment]
PM> dotnet restore "c:\program files\microsoft visual studio\2022\community\common7\ide\extensions\u31waq0z.ka1\AutoMLService\RuntimeManager\tensorflow.gpu.csproj" --configfile "c:\program files\microsoft visual studio\2022\community\common7\ide\extensions\u31waq0z.ka1\AutoMLService\RuntimeManager\NuGet.config" -r win-x64 /p:TorchSharpVersion=0.98.3 /p:TensorflowRuntimeVersion=2.3.1 /p:BaseIntermediateOutputPath="C:\Users\New Asus\AppData\Local\Temp\ModelBuilder\tensorflow-cuda.2.3.1\obj"
  Determining projects to restore...
  All projects are up-to-date for restore.
PM> dotnet publish "c:\program files\microsoft visual studio\2022\community\common7\ide\extensions\u31waq0z.ka1\AutoMLService\RuntimeManager\tensorflow.gpu.csproj" -r win-x64 -c Release --no-self-contained -o C:\Users\New Asus\AppData\Local\Temp\ModelBuilder\tensorflow-cuda.2.3.1 --no-restore /p:TorchSharpVersion=0.98.3 /p:TensorflowRuntimeVersion=2.3.1 /p:BaseOutputPath="C:\Users\New Asus\AppData\Local\Temp\ModelBuilder\tensorflow-cuda.2.3.1\bin\" /p:BaseIntermediateOutputPath="C:\Users\New Asus\AppData\Local\Temp\ModelBuilder\tensorflow-cuda.2.3.1\obj\"
MSBuild version 17.5.0-preview-23061-01+040e2a90e for .NET
MSBUILD : error MSB1008: Only one project can be specified.
    Full command line: 'C:\Program Files\dotnet\sdk\7.0.201\MSBuild.dll -maxcpucount -verbosity:m -target:Publish --property:_IsPublishing=true --property:TorchSharpVersion=0.98.3 --property:TensorflowRuntimeVersion=2.3.1 --property:BaseOutputPath=C:\Users\New Asus\AppData\Local\Temp\ModelBuilder\tensorflow-cuda.2.3.1\bin" /p:BaseIntermediateOutputPath=C:\Users\New -property:PublishDir=C:\Users\New -property:_CommandLineDefinedOutputPath=true -property:SelfContained=False -property:_CommandLineDefinedSelfContained=true -property:RuntimeIdentifier=win-x64 -property:_CommandLineDefinedRuntimeIdentifier=true -property:Configuration=Release c:\program files\microsoft visual studio\2022\community\common7\ide\extensions\u31waq0z.ka1\AutoMLService\RuntimeManager\tensorflow.gpu.csproj Asus\AppData\Local\Temp\ModelBuilder\tensorflow-cuda.2.3.1 Asus\AppData\Local\Temp\ModelBuilder\tensorflow-cuda.2.3.1\obj" -distributedlogger:Microsoft.DotNet.Tools.MSBuild.MSBuildLogger,C:\Program Files\dotnet\sdk\7.0.201\dotnet.dll*Microsoft.DotNet.Tools.MSBuild.MSBuildForwardingLogger,C:\Program Files\dotnet\sdk\7.0.201\dotnet.dll'
  Switches appended by response files:
Switch: Asus\AppData\Local\Temp\ModelBuilder\tensorflow-cuda.2.3.1

For switch syntax, type "MSBuild -help"
