### ISSUE TITLE
Index was outside the bounds of the array.

### ISSUE THREAD

**Issue by sjh37** [dotnet/machinelearning-modelbuilder#2519]
- Microsoft Visual Studio Community 2022 (64-bit) - Version 17.5.1
- Microsoft.ML 2.0.1
- mlnet-win-x64 6.14.3

I get the following error when training from within Visual Studio:

```
2023-03-07 11:11:25.2278 INFO Set log file path to C:\Users\simon\AppData\Local\Temp\MLVSTools\logs\amd-91CKYG.txt (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2023-03-07 11:12:12.3917 INFO start regression (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2023-03-07 11:12:12.3917 INFO Evaluate Metric: MSE (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2023-03-07 11:12:12.3917 INFO Available Trainers: SDCA,LBFGS,LGBM,FASTTREE,FASTFOREST (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2023-03-07 11:12:12.3917 INFO Training time in second: 60 (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2023-03-07 11:12:14.7855 INFO |      Trainer                             MSE        Duration       | (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2023-03-07 11:12:14.7875 INFO |--------------------------------------------------------------------| (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2023-03-07 11:12:14.7875 INFO |0     FastForestRegression                9.2667     1.6240         | (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2023-03-07 11:12:14.8460 DEBUG found best trial - trial id: 0 (Microsoft.ML.ModelBuilder.Utils.Logger.Debug)
2023-03-07 11:12:15.3590 INFO |1     LightGbmRegression                  30.9090    0.5020         | (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2023-03-07 11:12:15.5699 INFO |2     FastTreeRegression                  2053.4544  0.2080         | (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2023-03-07 11:12:15.8172 INFO |3     LbfgsPoissonRegressionRegression    3235.5801  0.2450         | (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2023-03-07 11:12:47.2170 INFO |4     SdcaRegression                      4684.5957  31.3980        | (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2023-03-07 11:12:47.3575 INFO |5     FastForestRegression                8.0720     0.1350         | (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2023-03-07 11:12:47.3575 DEBUG found best trial - trial id: 5 (Microsoft.ML.ModelBuilder.Utils.Logger.Debug)
2023-03-07 11:12:47.7053 INFO |6     FastForestRegression                7.3348     0.3450         | (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2023-03-07 11:12:47.7053 DEBUG found best trial - trial id: 6 (Microsoft.ML.ModelBuilder.Utils.Logger.Debug)
2023-03-07 11:12:50.0796 INFO |7     FastForestRegression                7.2490     2.3720         | (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2023-03-07 11:12:50.0796 DEBUG found best trial - trial id: 7 (Microsoft.ML.ModelBuilder.Utils.Logger.Debug)
2023-03-07 11:13:12.1552 DEBUG trial fail - trial id: 8 (Microsoft.ML.ModelBuilder.Utils.Logger.Debug)
2023-03-07 11:13:12.1552 INFO |--------------------------------------------------------------------| (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2023-03-07 11:13:12.1552 INFO |                          Experiment Results                        | (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2023-03-07 11:13:12.1552 INFO |--------------------------------------------------------------------| (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2023-03-07 11:13:12.1552 INFO |                               Summary                              | (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2023-03-07 11:13:12.1552 INFO |--------------------------------------------------------------------| (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2023-03-07 11:13:12.1552 INFO |ML Task: regression                                                 | (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2023-03-07 11:13:12.1552 INFO |Dataset: C:\S\Source\Stocks\amd.csv                                 | (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2023-03-07 11:13:12.1552 INFO |Label : Label                                                       | (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2023-03-07 11:13:12.1552 INFO |Total experiment time :    59.0000 Secs                             | (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2023-03-07 11:13:12.1622 INFO |Total number of models explored: 9                                  | (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2023-03-07 11:13:12.1622 INFO |--------------------------------------------------------------------| (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2023-03-07 11:13:12.1622 INFO |                        Top 5 models explored                       | (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2023-03-07 11:13:12.1622 INFO |--------------------------------------------------------------------| (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2023-03-07 11:13:12.1622 INFO |      Trainer                             MSE        Duration       | (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2023-03-07 11:13:12.1622 INFO |--------------------------------------------------------------------| (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2023-03-07 11:13:12.1622 INFO |7     FastForestRegression                7.2490     2.3720         | (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2023-03-07 11:13:12.1622 INFO |6     FastForestRegression                7.3348     0.3450         | (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2023-03-07 11:13:12.1622 INFO |5     FastForestRegression                8.0720     0.1350         | (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2023-03-07 11:13:12.1622 INFO |0     FastForestRegression                9.2667     1.6240         | (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2023-03-07 11:13:12.1622 INFO |1     LightGbmRegression                  30.9090    0.5020         | (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2023-03-07 11:13:12.1622 INFO |--------------------------------------------------------------------| (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2023-03-07 11:13:12.8024 INFO Generate code behind files (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2023-03-07 11:13:12.8024 DEBUG Index was outside the bounds of the array.
   at Microsoft.ML.ModelBuilder.Utils.Utilities.Sanitize(String name)
   at Microsoft.ML.ModelBuilder.ViewModels.TrainViewModel.<GenerateCodeBehindFilesAsync>d__101.MoveNext() (Microsoft.ML.ModelBuilder.Utils.Logger.Debug)

```

**Comment by zewditu** [comment]
@sjh37 , can you tell us the Model Builder version you used?

**Comment by sjh37** [comment]
@zewditu The mbconfig is using version 3
![image](https://user-images.githubusercontent.com/4190514/223509448-833c4bbb-7f10-4edc-bf36-57e004dab619.png)

**Comment by zewditu** [comment]
@sjh37 I mean the Model Builder version you installed . 
To get the version you install in VS go to extension -> Manage extension  -> installed -> Model Builder 
![image](https://user-images.githubusercontent.com/36615490/223547191-1daffaa9-d62e-44ea-867a-e8a0c0e32828.png)

**Comment by sjh37** [comment]
@zewditu Sorry. Here is what is currently installed.
![image](https://user-images.githubusercontent.com/4190514/223673900-3c846d4f-39e4-4fc6-a218-82f02b8b421e.png)

**Comment by sjh37** [comment]
All worked perfectly with the non-GPU version

**Comment by sjh37** [comment]
Actually, not quite, it came up with an MSE of 0.0 for some of the models, which results in a score of `NaN`

```
|                        Top 5 models explored                       |
|      Trainer                             MSE        Duration       |
|17    FastForestRegression                0.0000     0.2730         |
|18    FastForestRegression                0.0000     0.1920         |
|20    FastForestRegression                0.0000     0.9650         |
|22    FastForestRegression                0.0000     0.2200         |
|24    FastForestRegression                0.0000     0.2400         |
```

**Comment by sjh37** [comment]
Running it with RMSE I got this error
```
Value cannot be null.
Parameter name: source

   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at Microsoft.ML.ModelBuilder.Configuration.TrainResult.ToMBConfig()
   at Microsoft.ML.ModelBuilder.Configuration.TrainingConfiguration.ToMBConfig()
   at Microsoft.ML.ModelBuilder.TrainingConfigurationHelper.<SaveToFileAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ML.ModelBuilder.ModelBuilderToolWindow.<>c__DisplayClass21_0.<<Microsoft-VisualStudio-Shell-Interop-IPersistFileFormat-Save>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Threading.JoinableTask.CompleteOnCurrentThread()
   at Microsoft.ML.ModelBuilder.ModelBuilderToolWindow.Microsoft.VisualStudio.Shell.Interop.IPersistFileFormat.Save(String pszFilename, Int32 fRemember, UInt32 nFormatIndex)
```

**Comment by sjh37** [comment]
An I was able to reproduce the original error running just 1 at a time

Index was outside the bounds of the array.

```
   at Microsoft.ML.ModelBuilder.Utils.Utilities.Sanitize(String name)
   at Microsoft.ML.ModelBuilder.ViewModels.TrainViewModel.<GenerateCodeBehindFilesAsync>d__101.MoveNext()
```

Log
```
2023-03-08 10:34:45.6396 INFO Set log file path to C:\Users\simon\AppData\Local\Temp\MLVSTools\logs\amd-H5H27S.txt (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2023-03-08 10:35:11.8764 INFO start regression (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2023-03-08 10:35:11.8764 INFO Evaluate Metric: RMSE (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2023-03-08 10:35:11.8764 INFO Available Trainers: SDCA,LBFGS,LGBM,FASTTREE,FASTFOREST (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2023-03-08 10:35:11.8764 INFO Training time in second: 60 (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2023-03-08 10:35:13.3312 INFO |      Trainer                             RMSE       Duration       | (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2023-03-08 10:35:13.3312 INFO |--------------------------------------------------------------------| (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2023-03-08 10:35:13.3352 INFO |0     FastForestRegression                2.7055     0.8980         | (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2023-03-08 10:35:13.3644 DEBUG found best trial - trial id: 0 (Microsoft.ML.ModelBuilder.Utils.Logger.Debug)
2023-03-08 10:35:13.6316 INFO |1     FastForestRegression                2.5445     0.2580         | (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2023-03-08 10:35:13.6316 DEBUG found best trial - trial id: 1 (Microsoft.ML.ModelBuilder.Utils.Logger.Debug)
2023-03-08 10:35:14.7991 INFO |2     FastForestRegression                2.6538     1.1640         | (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2023-03-08 10:36:06.5102 INFO |3     SdcaRegression                      68.4441    51.7100        | (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2023-03-08 10:36:06.6825 INFO |4     FastTreeRegression                  45.2826    0.1700         | (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2023-03-08 10:36:06.9023 INFO |5     LightGbmRegression                  5.5681     0.2180         | (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2023-03-08 10:36:07.0725 INFO |6     FastForestRegression                2.6679     0.1690         | (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2023-03-08 10:36:07.2290 INFO |7     FastForestRegression                2.7055     0.1550         | (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2023-03-08 10:36:07.8996 INFO |8     FastForestRegression                2.6245     0.6700         | (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2023-03-08 10:36:08.1085 INFO |9     LbfgsPoissonRegressionRegression    57.4367    0.2070         | (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2023-03-08 10:36:08.3037 INFO |10    FastForestRegression                2.5592     0.1930         | (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2023-03-08 10:36:08.5973 INFO |11    FastForestRegression                2.6268     0.2890         | (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2023-03-08 10:36:09.0195 INFO |12    FastForestRegression                2.6396     0.4200         | (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2023-03-08 10:36:09.2235 INFO |13    FastForestRegression                2.5116     0.2010         | (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2023-03-08 10:36:09.2245 DEBUG found best trial - trial id: 13 (Microsoft.ML.ModelBuilder.Utils.Logger.Debug)
2023-03-08 10:36:09.5924 INFO |14    FastForestRegression                2.6725     0.3640         | (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2023-03-08 10:36:09.7476 INFO |15    FastForestRegression                2.7055     0.1510         | (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2023-03-08 10:36:11.9424 INFO |--------------------------------------------------------------------| (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2023-03-08 10:36:11.9435 INFO |                          Experiment Results                        | (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2023-03-08 10:36:11.9435 INFO |--------------------------------------------------------------------| (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2023-03-08 10:36:11.9435 INFO |                               Summary                              | (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2023-03-08 10:36:11.9435 INFO |--------------------------------------------------------------------| (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2023-03-08 10:36:11.9435 INFO |ML Task: regression                                                 | (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2023-03-08 10:36:11.9435 INFO |Dataset: C:\S\Source\Stocks\amd.csv                                 | (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2023-03-08 10:36:11.9435 INFO |Label : Label                                                       | (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2023-03-08 10:36:11.9435 INFO |Total experiment time :    60.0000 Secs                             | (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2023-03-08 10:36:11.9435 INFO |Total number of models explored: 17                                 | (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2023-03-08 10:36:11.9435 INFO |--------------------------------------------------------------------| (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2023-03-08 10:36:11.9435 INFO |                        Top 5 models explored                       | (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2023-03-08 10:36:11.9435 INFO |--------------------------------------------------------------------| (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2023-03-08 10:36:11.9435 INFO |      Trainer                             RMSE       Duration       | (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2023-03-08 10:36:11.9435 INFO |--------------------------------------------------------------------| (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2023-03-08 10:36:11.9435 INFO |13    FastForestRegression                2.5116     0.2010         | (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2023-03-08 10:36:11.9435 INFO |1     FastForestRegression                2.5445     0.2580         | (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2023-03-08 10:36:11.9435 INFO |10    FastForestRegression                2.5592     0.1930         | (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2023-03-08 10:36:11.9435 INFO |8     FastForestRegression                2.6245     0.6700         | (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2023-03-08 10:36:11.9435 INFO |11    FastForestRegression                2.6268     0.2890         | (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2023-03-08 10:36:11.9435 INFO |--------------------------------------------------------------------| (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2023-03-08 10:36:12.2336 INFO Generate code behind files (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2023-03-08 10:36:12.2336 DEBUG Index was outside the bounds of the array.
   at Microsoft.ML.ModelBuilder.Utils.Utilities.Sanitize(String name)
   at Microsoft.ML.ModelBuilder.ViewModels.TrainViewModel.<GenerateCodeBehindFilesAsync>d__101.MoveNext() (Microsoft.ML.ModelBuilder.Utils.Logger.Debug)
```

**Comment by zewditu** [comment]
@sjh37  the latest version is 17.14.4.2312404 could you get it from visual studio market place https://marketplace.visualstudio.com/items?itemName=MLNET.ModelBuilder2022.

**Comment by sjh37** [comment]
I updated and was able to still get `Index was outside the bounds of the array.`
```
   at Microsoft.ML.ModelBuilder.Utils.Utilities.Sanitize(String name)
   at Microsoft.ML.ModelBuilder.ViewModels.TrainViewModel.<GenerateCodeBehindFilesAsync>d__101.MoveNext()
```

log

```
2023-03-08 19:53:12.2015 INFO Set log file path to C:\Users\simon\AppData\Local\Temp\MLVSTools\logs\qcom-2PU3P7.txt (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2023-03-08 20:18:40.1701 DEBUG Start AutoMLService pid: 6376 (Microsoft.ML.ModelBuilder.Utils.Logger.Debug)
2023-03-08 20:18:40.4693 INFO start regression (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2023-03-08 20:18:40.4693 INFO Evaluate Metric: MSE (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2023-03-08 20:18:40.4693 INFO Available Trainers: SDCA,LBFGS,LGBM,FASTTREE,FASTFOREST (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2023-03-08 20:18:40.4693 INFO Training time in second: 3600 (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2023-03-08 20:18:40.9569 INFO [Source=AutoMLExperiment-ChildContext, Kind=Info] [Source=Converter; InitDataset, Kind=Info] Making per-feature arrays (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2023-03-08 20:18:40.9669 INFO [Source=AutoMLExperiment-ChildContext, Kind=Info] [Source=Converter; InitBoundariesAndLabels, Kind=Info] Changing data from row-wise to column-wise (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2023-03-08 20:18:41.1048 INFO [Source=AutoMLExperiment-ChildContext, Kind=Info] [Source=Converter; InitDataset, Kind=Info] Processed 1438 instances (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2023-03-08 20:18:41.1048 INFO [Source=AutoMLExperiment-ChildContext, Kind=Info] [Source=Converter; InitDataset, Kind=Info] Binning and forming Feature objects (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2023-03-08 20:18:41.1926 INFO [Source=AutoMLExperiment-ChildContext, Kind=Info] [Source=FastTreeTraining; Training, Kind=Info] Reserved memory for tree learner: 3006900 bytes (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2023-03-08 20:18:41.1926 INFO [Source=AutoMLExperiment-ChildContext, Kind=Info] [Source=FastTreeTraining; Training, Kind=Info] Starting to train ... (Microsoft.ML.ModelBuilder.Utils.Logger.Info)

... truncated for brevity ...

2023-03-08 21:07:22.8744 INFO |--------------------------------------------------------------------| (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2023-03-08 21:07:22.8744 INFO |                          Experiment Results                        | (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2023-03-08 21:07:22.8744 INFO |--------------------------------------------------------------------| (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2023-03-08 21:07:22.8744 INFO |                               Summary                              | (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2023-03-08 21:07:22.8744 INFO |--------------------------------------------------------------------| (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2023-03-08 21:07:22.8744 INFO |ML Task: regression                                                 | (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2023-03-08 21:07:22.8744 INFO |Dataset: C:\S\Source\Stocks\qcom.csv                                | (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2023-03-08 21:07:22.8744 INFO |Label : Label                                                       | (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2023-03-08 21:07:22.8744 INFO |Total experiment time :  2922.0000 Secs                             | (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2023-03-08 21:07:22.8744 INFO |Total number of models explored: 649                                | (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2023-03-08 21:07:22.8744 INFO |--------------------------------------------------------------------| (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2023-03-08 21:07:22.8744 INFO |                        Top 5 models explored                       | (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2023-03-08 21:07:22.8744 INFO |--------------------------------------------------------------------| (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2023-03-08 21:07:22.8744 INFO |      Trainer                             MSE        Duration       | (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2023-03-08 21:07:22.8744 INFO |--------------------------------------------------------------------| (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2023-03-08 21:07:22.8744 INFO |164   FastForestRegression                0.0000     0.6010         | (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2023-03-08 21:07:22.8744 INFO |166   FastForestRegression                0.0000     1.6490         | (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2023-03-08 21:07:22.8744 INFO |167   FastForestRegression                0.0000     0.1140         | (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2023-03-08 21:07:22.8744 INFO |169   FastForestRegression                0.0000     1.9440         | (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2023-03-08 21:07:22.8744 INFO |172   FastForestRegression                0.0000     0.1590         | (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2023-03-08 21:07:22.8744 INFO |--------------------------------------------------------------------| (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2023-03-08 21:07:23.2728 INFO Generate code behind files (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2023-03-08 21:07:23.2798 DEBUG Index was outside the bounds of the array.
   at Microsoft.ML.ModelBuilder.Utils.Utilities.Sanitize(String name)
   at Microsoft.ML.ModelBuilder.ViewModels.TrainViewModel.<GenerateCodeBehindFilesAsync>d__101.MoveNext() (Microsoft.ML.ModelBuilder.Utils.Logger.Debug)
```

```
Running the best model returns
accuracy: NaN%, latest prediction NaN
