### ISSUE TITLE
DataSeries Date causing invalid date to single cast exception when retraining via MLModel1.Train(MLNetModelPath);

### ISSUE THREAD

**Issue by WebAppDevCo** [dotnet/machinelearning-modelbuilder#2547]
**System Information (please complete the following information):**
 - Model Builder Version (available in Manage Extensions dialog): 17.14.4.2312404
 - Visual Studio Version 17.5.2

**Describe the bug**
- On which step of the process did you run into an issue: Calling MLModel1.Train(MLNetModelPath) from code.
- Clear description of the problem:
Using a Date in the TimeSeries forecast seems unhandled by the MLModel1.training.cs file that was autogenerated. var pipeline = mlContext.Forecasting.ForecastBySsa(windowSize:63,seriesLength:6661,trainSize:5801,horizon:3,outputColumnName:@"Last",inputColumnName:@"Last",confidenceLowerBoundColumn:@"Last_LB",confidenceUpperBoundColumn:@"Last_UB");

**To Reproduce**
1. Go to '...' ML designer and create a Forecasting scenario and choose a datetime (or use index as default date time)  Running the scenario from the GUI works great. Calling the train function from code is causing exception.
System.InvalidCastException
  HResult=0x80004002
  Message=Unable to cast object of type 'System.DateTime' to type 'System.Single'.
  Source=System.Data.SqlClient
  StackTrace:
   at System.Data.SqlClient.SqlBuffer.get_Single()
   at System.Data.SqlClient.SqlDataReader.GetFloat(Int32 i)
   at Microsoft.ML.Data.DatabaseLoader.Cursor.<>c__DisplayClass37_0.<CreateSingleGetterDelegate>b__0(Single& value)
   at Microsoft.ML.Transforms.TimeSeries.AdaptiveSingularSpectrumSequenceModelerInternal.Train(RoleMappedData data)
   at Microsoft.ML.Transforms.TimeSeries.SsaForecastingTransformer..ctor(IHostEnvironment env, Options options, IDataView input)
   at Microsoft.ML.Transforms.TimeSeries.SsaForecastingEstimator.Fit(IDataView input)
   at ConsoleAppAmlEndpoint.MLModel1.RetrainModel(MLContext mlContext, IDataView trainData) in C:\Users\dave\Documents\Visual Studio 2022\Projects\ConsoleAppAmlEndpoint\MLModel1.training.cs:line 78
   at ConsoleAppAmlEndpoint.MLModel1.Train(String outputModelPath, String connectionString, String commandText) in C:\Users\dave\Documents\Visual Studio 2022\Projects\ConsoleAppAmlEndpoint\MLModel1.training.cs:line 29
   at ConsoleAppAmlEndpoint.Program.Main(String[] args) in C:\Users\dave\Documents\Visual Studio 2022\Projects\ConsoleAppAmlEndpoint\Program.cs:line 23

**Expected behavior**
The training file should have info needed to include DateSeries option from designer.

**Screenshots**
![image](https://user-images.githubusercontent.com/57567638/226432089-1678325a-e071-4a78-be9d-a43675b109f6.png)

**Additional context**
Add any other context about the problem here. If I need to programmatically set something, please let me know. I cannot automate training of daily data from a historical perspective at all unless I do so manually. Looking forward to your insight.
Dave Naile
MCSD

**Comment by WebAppDevCo** [comment]
I was able to resolve the issue by converting the SQL Date column data type to a date and then to a Real, which solved the problem.
Template:
public const string RetrainCommandString = @"SELECT [Time]
Updated Template:
public const string RetrainCommandString = @"SELECT cast(cast([Time] as datetime) as Real)
