### ISSUE TITLE
TRAINING MODEL  FAIL

### ISSUE THREAD

**Issue by ramini0530** [dotnet/machinelearning-modelbuilder#2565]
THIS TRAINING WORKED BEFORE WITH SAME DATA 
NOW IT KEEPS FAILING 

   at System.Version.VersionResult.SetFailure(ParseFailureKind failure, String argument)
   at System.Version.TryParseVersion(String version, VersionResult& result)
   at System.Version.Parse(String input)
   at System.Version..ctor(String version)
   at Microsoft.ML.ModelBuilder.Utils.Utilities.InstalledVersionNeedsUpdate(String installedString, String requestedString)
   at Microsoft.ML.ModelBuilder.Utils.Utilities.<InstallNugetPackageAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.ML.ModelBuilder.ViewModels.TrainViewModel.<UpdateNugetDependenciesAsync>d__105.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Microsoft.ML.ModelBuilder.ViewModels.TrainViewModel.<GenerateCodeBehindFilesAsync>d__104.MoveNext()

**Comment by zewditu** [comment]
@ramini0530  can you tell us more information? Such as how to reproduce it, vs version, Model Builder version

**Comment by zewditu** [comment]
@ramini0530  there is not enough information to investigate more.

If you still hit the issue feel free to reopen it with more information.

**Comment by ramini0530** [comment]
thanks for the response im learning now how to overcome some of the
obstacles

what information can i give more then the error the auto.ml  auto generate?

i am trying to use the model on some other older. net framework code
haven't seen actual machine learning advanteges yet but i hope i will see
once it's is complete

the error is seen when i try to load the data but not all the time
so. etimes it works
sometimes it shoes a message box of the error i sent previosly


בתאריך יום ג׳, 4 באפר׳ 2023, 20:53, מאת zewditu Hailemariam ‏<
***@***.***>:

**Comment by zewditu** [comment]
@ramini0530  are you able to tell us  which version of model builder you are using ?
your data , is that sql or  file?
