### ISSUE TITLE
Apparent Dependency Error Running mlnet on Ubuntu 22.04

### ISSUE THREAD

**Issue by caspem** [dotnet/machinelearning-modelbuilder#2593]
**System Information (please complete the following information):**
 - Model Builder or CLI Version: 16.15.0+9eb8df17556afffd838b6b14a2c726d91a05bec9
 - Visual Studio Version (if applicable): n/a

**Describe the bug**
- On which page of the tutorial did you run into an issue (URL): https://dotnet.microsoft.com/en-us/learn/ml-dotnet/get-started-tutorial/train
- Clear description of the problem:  When executing the `mlnet classification --dataset "yelp_labelled.txt" --label-col 1 --has-header false --name SentimentModel  --train-time 60` command in Ubuntu 22.04 i am receiving a dependency injection error.

`System.InvalidOperationException: Unable to resolve service for type 'Microsoft.ML.AutoML.IDatasetManager' while attempting to activate 'Microsoft.ML.AutoML.SweepablePipelineRunner'.
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateArgumentCallSites(Type implementationType, CallSiteChain callSiteChain, ParameterInfo[] parameters, Boolean throwIfCallSiteNotFound)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateConstructorCallSite(ResultCache lifetime, Type serviceType, Type implementationType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.TryCreateExact(ServiceDescriptor descriptor, Type serviceType, CallSiteChain callSiteChain, Int32 slot)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.TryCreateExact(Type serviceType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateCallSite(Type serviceType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.GetCallSite(Type serviceType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.CreateServiceAccessor(Type serviceType)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.ML.AutoML.AutoMLExperiment.RunAsync(CancellationToken ct)
   at Microsoft.ML.ModelBuilder.AutoMLService.Experiments.MultiClassificationExperiment.ExecuteAsync(IDataView trainData, IDataView validateData, CancellationToken ct) in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/Experiments/MultiClassificationExperiment.cs:line 134
   at Microsoft.ML.ModelBuilder.AutoMLEngine.StartTrainingAsync(ITrainingConfiguration config, PathConfiguration pathConfig, CancellationToken userCancellationToken) in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/AutoMLEngineService/AutoMLEngine.cs:line 161
   at Microsoft.ML.CLI.Runners.AutoMLRunner.ExecuteAsync() in /_/src/mlnet/Runners/AutoMLRunner.cs:line 89
   at Microsoft.ML.CLI.Program.TrainAsync(ITrainingConfiguration trainingConfiguration, PathConfiguration pathConfig, AutoMLServiceLogLevel logLevel) in /_/src/mlnet/Program.cs:line 389
   at Microsoft.ML.CLI.Program.RunAutoMLCommandAndGetResult(AutoMLCommand command, Boolean skipGenerateConsoleApp) in /_/src/mlnet/Program.cs:line 370
   at Microsoft.ML.CLI.Program.<>c.<<CreateRootCommandLineBuilder>b__4_0>d.MoveNext() in /_/src/mlnet/Program.cs:line 91
--- End of stack trace from previous location ---
   at System.CommandLine.Invocation.CommandHandler.GetExitCodeAsync(Object value, InvocationContext context)
   at System.CommandLine.Invocation.ModelBindingCommandHandler.InvokeAsync(InvocationContext context)
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass23_0.<<UseParseErrorReporting>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.ML.CLI.Program.<>c__DisplayClass4_0.<<CreateRootCommandLineBuilder>b__10>d.MoveNext() in /_/src/mlnet/Program.cs:line 326
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseSuggestDirective>b__24_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass22_0.<<UseParseDirective>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass11_0.<<UseDebugDirective>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<RegisterWithDotnetSuggest>b__10_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass14_0.<<UseExceptionHandler>b__0>d.MoveNext()`

**To Reproduce**
1. Install .NET Core 6.0 SDK in Ubuntu 22.04
2. Install mlnet using: `dotnet tool install -g mlnet-linux-x64`
4. Create myMLApp dir
5. Change directory to myMLApp
6. Download the [data set](https://archive.ics.uci.edu/ml/machine-learning-databases/00331/sentiment%20labelled%20sentences.zip) and copy yelp_labelled.txt file to the myMLApp directory.
7. Execute the command: `mlnet classification --dataset "yelp_labelled.txt" --label-col 1 --has-header false --name SentimentModel  --train-time 60`

**Expected behavior**
the command line completes successfully, and a training Summary is displayed.

**Additional context**
I am attempting to do this on a WSL2 install of ubuntu 22.04.

**Comment by Megumemed** [comment]
This issue also affects the latest Windows release, see below screenshot
![image](https://user-images.githubusercontent.com/38935748/233714395-4f312f99-8839-4c36-ac0a-049c1d404318.png)

**Comment by profet23** [comment]
> This issue also affects the latest Windows release, see below screenshot ![image](https://user-images.githubusercontent.com/38935748/233714395-4f312f99-8839-4c36-ac0a-049c1d404318.png) ![image](https://user-images.githubusercontent.com/38935748/233714513-5b5d8911-fd0a-4962-935a-7d1168c2b746.png)

Also seeing this.

**Comment by soenneker** [comment]
This was unpleasant to run into.

I updated my model builder in VS and it migrated my mbconfigs to new versions. Once on the new version I couldn't simply uninstall the version 16.15.x and reinstall 16.14. I needed to revert the mbconfigs.

I mean this respectfully: shouldn't this situation be test covered? This seems like a fairly fundamental operation. I'm more than happy to assist..

**Comment by LittleLittleCloud** [comment]
@soenneker which part makes you upset. The migration one or fail to find an option to downgrade extension.

The migration happens when new fields are added to mbconfig. (for example, we add validationOption in the most recent release). Migration from previous version to newer one is well-tested but not vice-versa.

About downgrading vsix, unfortunately VS doesn't provide that as built-in function and you can only download the latest version from official vs market place. However you can install from previous vsix as a work-around.

**Comment by LittleLittleCloud** [comment]
@caspem I just release 16.15.1, which should fix this issue

**Comment by soenneker** [comment]
@LittleLittleCloud Don't get me wrong I'm not upset; I totally understand how going backwards in versions is not well tested. I mean dependencies not being resolved, that part seems like it should be tested, that's all. You probably agree.

I just tested with 16.15.1 and it has the same issue?

**Comment by LittleLittleCloud** [comment]
@soenneker Yeah that's true. The dependency issue should be detected before release. 

And do you hit the same dependency issue with `16.15.1`? Please let us know if you hit exactly the same issue although it's really not what we want to see..

**Comment by gerwim** [comment]
I have this issue too, in Visual Studio on Windows:

![image](https://github.com/dotnet/machinelearning-modelbuilder/assets/1841721/433c8e6e-bc12-4f13-8383-0d24c147081b)


Stacktrace:
```
Unable to resolve service for type 'Microsoft.ML.AutoML.IDatasetManager' while attempting to activate 'Microsoft.ML.AutoML.SweepablePipelineRunner'.
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateArgumentCallSites(Type implementationType, CallSiteChain callSiteChain, ParameterInfo[] parameters, Boolean throwIfCallSiteNotFound)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateConstructorCallSite(ResultCache lifetime, Type serviceType, Type implementationType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.TryCreateExact(ServiceDescriptor descriptor, Type serviceType, CallSiteChain callSiteChain, Int32 slot)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.TryCreateExact(Type serviceType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateCallSite(Type serviceType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.GetCallSite(Type serviceType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.CreateServiceAccessor(Type serviceType)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetService[T](IServiceProvider provider)
   at Microsoft.ML.AutoML.AutoMLExperiment.<RunAsync>d__24.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ML.ModelBuilder.AutoMLService.Experiments.MultiClassificationExperiment.<ExecuteAsync>d__14.MoveNext() in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/Experiments/MultiClassificationExperiment.cs:line 133
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ML.ModelBuilder.AutoMLEngine.<StartTrainingAsync>d__21.MoveNext() in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/AutoMLEngineService/AutoMLEngine.cs:line 169
```

**Comment by LittleLittleCloud** [comment]
@gerwim Can you share your mbconfig here.

In the meantime, would you mind to create a new thread? The issue you get is in model builder and not mlnet.cli.

**Comment by LittleLittleCloud** [comment]
Close due to no response. Feel free to reopen it if you have more questions
