### ISSUE TITLE
at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)    at Microsoft.ML.ModelBuilder.AutoMLService.RuntimeManager.InstallRuntimeAsync(CancellationToken ct) in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/RuntimeManager/RuntimeManager.cs:line 142    at Microsoft.ML.ModelBuilder.AutoMLService.TextClassificationExperiment.<ExecuteAsync>d__13.MoveNext() in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/Experiments/TextClassificationExperiment.cs:line 62 --- End of stack trace from previous location where exception was thrown ---    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)    at Microsoft.ML.ModelBuilder.AutoMLEngine.<StartTrainingAsync>d__21.MoveNext() in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/AutoMLEngineService/AutoMLEngine.cs:line 145

### ISSUE THREAD

**Issue by VIKASKHILLARE** [dotnet/machinelearning-modelbuilder#2598]
at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at Microsoft.ML.ModelBuilder.AutoMLService.RuntimeManager.InstallRuntimeAsync(CancellationToken ct) in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/RuntimeManager/RuntimeManager.cs:line 142
   at Microsoft.ML.ModelBuilder.AutoMLService.TextClassificationExperiment.<ExecuteAsync>d__13.MoveNext() in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/Experiments/TextClassificationExperiment.cs:line 62
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ML.ModelBuilder.AutoMLEngine.<StartTrainingAsync>d__21.MoveNext() in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/AutoMLEngineService/AutoMLEngine.cs:line 145

**Comment by VIKASKHILLARE** [comment]
> at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo) at Microsoft.ML.ModelBuilder.AutoMLService.RuntimeManager.InstallRuntimeAsync(CancellationToken ct) in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/RuntimeManager/RuntimeManager.cs:line 142 at Microsoft.ML.ModelBuilder.AutoMLService.TextClassificationExperiment.d__13.MoveNext() in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/Experiments/TextClassificationExperiment.cs:line 62 --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at Microsoft.ML.ModelBuilder.AutoMLEngine.d__21.MoveNext() in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/AutoMLEngineService/AutoMLEngine.cs:line 145

**Comment by VIKASKHILLARE** [comment]
![image](https://user-images.githubusercontent.com/59758082/234177585-91745eca-0b74-4895-a7fd-2adb5a70183e.png)

please look it into this snapshot

**Comment by VIKASKHILLARE** [comment]
> Can you put a shorter titile for this issue.
> 
> And more information on exception you get will be helpful

![image](https://user-images.githubusercontent.com/59758082/234177699-fefc66bb-b4c7-4776-82ed-8adcfddee47e.png)

**Comment by LittleLittleCloud** [comment]
Do you have dotnet installed and available in the user environment. The runtime manager requires `dotnet` to install torchsharp runtime

**Comment by LittleLittleCloud** [comment]
dup of #https://github.com/dotnet/machinelearning-modelbuilder/issues/2598
