### ISSUE TITLE
The whole Model builder experience feels broken...

### ISSUE THREAD

**Issue by dozer75** [dotnet/machinelearning-modelbuilder#2602]
**System Information (please complete the following information):**
 - Model Builder or CLI Version: Model Builder 17.15.0.2321402
 - Visual Studio Version (if applicable):
   - Visual Studio Professional 17.5.4+33530.505
   - Visual Studio Community 17.5.4+33530.505

**Describe the bug**
Well, this Model Builder tool seems to be very poorly written or maintained, it has several issues. The most easiest to see if those you get by just running the Machine Learning Model and follow the steps outlined in the [getting started guide](https://dotnet.microsoft.com/en-us/learn/ml-dotnet/get-started-tutorial/intro).

The two most easiest to find is that the scenario page is missing the images. The second is that after the initial training I always get following error (I get this both when I run the getting started guide and other scenarios).

Missing images:
<img width="1004" alt="image" src="https://user-images.githubusercontent.com/7486163/234208540-d0d84c7a-dc0d-4e58-8a5d-e3f9dc8dcf3e.png">

Error:
```
Updating nuget dependencies... (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2023-04-25 08:32:52.5050 INFO Starting update NuGet dependencies async. (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2023-04-25 08:32:52.5361 INFO Project Miscellaneous Files cannot be accessed. It may be unloaded. (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2023-04-25 08:32:52.5361 INFO Couldn't find project named C:\Development\ML.NET\src\myMLApp\myMLApp.csproj (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2023-04-25 08:32:52.5361 INFO Installing nuget package, package ID: Microsoft.ML, package Version: 2.0.0 (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2023-04-25 08:32:52.5361 DEBUG Value cannot be null.
Parameter name: project
   at NuGet.VisualStudio.Implementation.Extensibility.VsPackageInstallerServices.GetInstalledPackages(Project project)
   at Microsoft.ML.ModelBuilder.Utils.Utilities.<InstallNugetPackageAsync>d__20.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.ML.ModelBuilder.ViewModels.TrainViewModel.<UpdateNugetDependenciesAsync>d__101.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Microsoft.ML.ModelBuilder.ViewModels.TrainViewModel.<GenerateCodeBehindFilesAsync>d__100.MoveNext() (Microsoft.ML.ModelBuilder.Utils.Logger.Debug)
```
**Expected behavior**
Well, the model builder should work is at least what we can expect.

**Comment by LittleLittleCloud** [comment]
Can you share the target framework of `myMLApp`? There might be some edge cases in retrieving project name in some target frameworks.

**Comment by dozer75** [comment]
I have tried both .NET 6 and .NET 7 with the same result. Interesting enough, I created a VM on azure with the preconfigured VS2022 professional installation, and there it works, but not on any of my personal computers.. I have verified the versions of both studio and the model builder, and they are both the same on all environments.

One difference though (if we can trust the logs) is that on my local computer it tries to add the 2.0.0 of the Microsoft.ML NuGet package, while on the VM it adds 1.7.0...

Here is the complete log from a simple run on my computer (with .NET 7):
```
2023-04-26 08:55:22.9684 INFO Set log file path to C:\Users\<user>\AppData\Local\Temp\MLVSTools\logs\MLModel1-6HLURX.txt (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2023-04-26 08:55:49.0951 DEBUG Start AutoMLService pid: 58756 (Microsoft.ML.ModelBuilder.Utils.Logger.Debug)
2023-04-26 08:55:49.3848 INFO start multiclass classification (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2023-04-26 08:55:49.3848 INFO Evaluate Metric: MacroAccuracy (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2023-04-26 08:55:49.3848 INFO Available Trainers: LGBM,FASTFOREST,FASTTREE,LBFGS,SDCA (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2023-04-26 08:55:49.3848 INFO Training time in second: 10 (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2023-04-26 08:55:52.4468 INFO |      Trainer                             MacroAccuracy Duration    | (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2023-04-26 08:55:52.4468 INFO |--------------------------------------------------------------------| (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2023-04-26 08:55:52.4468 INFO |0     FastTreeOva                         0,6643     2,5940         | (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2023-04-26 08:55:52.4754 DEBUG found best trial - trial id: 0 (Microsoft.ML.ModelBuilder.Utils.Logger.Debug)
2023-04-26 08:55:55.4973 INFO |1     FastForestOva                       0,7180     3,0120         | (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2023-04-26 08:55:55.4973 DEBUG found best trial - trial id: 1 (Microsoft.ML.ModelBuilder.Utils.Logger.Debug)
2023-04-26 08:55:57.7503 INFO |2     FastTreeOva                         0,7293     2,2410         | (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2023-04-26 08:55:57.7503 DEBUG found best trial - trial id: 2 (Microsoft.ML.ModelBuilder.Utils.Logger.Debug)
2023-04-26 08:55:58.8085 INFO |3     SdcaMaximumEntropyMulti             0,5000     1,0520         | (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2023-04-26 08:55:59.1734 INFO [Source=AutoMLExperiment, Kind=Info] cancel training because cancellation token is invoked... (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2023-04-26 08:55:59.2923 INFO |--------------------------------------------------------------------| (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2023-04-26 08:55:59.2923 INFO |                          Experiment Results                        | (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2023-04-26 08:55:59.2923 INFO |--------------------------------------------------------------------| (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2023-04-26 08:55:59.2923 INFO |                               Summary                              | (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2023-04-26 08:55:59.2923 INFO |--------------------------------------------------------------------| (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2023-04-26 08:55:59.2923 INFO |ML Task: multiclass classification                                  | (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2023-04-26 08:55:59.2923 INFO |Dataset: C:\Development\ML.NET\data\yelp_labelled.txt               | (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2023-04-26 08:55:59.2923 INFO |Label : col1                                                        | (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2023-04-26 08:55:59.2923 INFO |Total experiment time :     9,0000 Secs                             | (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2023-04-26 08:55:59.2923 INFO |Total number of models explored: 5                                  | (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2023-04-26 08:55:59.2923 INFO |--------------------------------------------------------------------| (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2023-04-26 08:55:59.2923 INFO |                        Top 4 models explored                       | (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2023-04-26 08:55:59.2998 INFO |--------------------------------------------------------------------| (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2023-04-26 08:55:59.2998 INFO |      Trainer                             MacroAccuracy Duration    | (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2023-04-26 08:55:59.2998 INFO |--------------------------------------------------------------------| (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2023-04-26 08:55:59.2998 INFO |2     FastTreeOva                         0,7293     2,2410         | (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2023-04-26 08:55:59.2998 INFO |1     FastForestOva                       0,7180     3,0120         | (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2023-04-26 08:55:59.2998 INFO |0     FastTreeOva                         0,6643     2,5940         | (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2023-04-26 08:55:59.2998 INFO |3     SdcaMaximumEntropyMulti             0,5000     1,0520         | (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2023-04-26 08:55:59.2998 INFO |--------------------------------------------------------------------| (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2023-04-26 08:55:59.4861 INFO [Source=AutoMLExperiment, Kind=Info] cancel training because cancellation token is invoked... (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2023-04-26 08:56:00.8010 INFO Generate code behind files (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2023-04-26 08:56:05.6012 INFO 

Copying generated code to project... (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2023-04-26 08:56:05.6152 INFO Copying MLModel1.consumption.cs to folder: C:\Development\ML.NET\src\Test2 (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2023-04-26 08:56:05.6152 INFO Copying MLModel1.training.cs to folder: C:\Development\ML.NET\src\Test2 (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2023-04-26 08:56:05.6152 INFO Copying MLModel1.evaluate.cs to folder: C:\Development\ML.NET\src\Test2 (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2023-04-26 08:56:05.6152 INFO COMPLETED (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2023-04-26 08:56:05.6152 INFO 

Updating nuget dependencies... (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2023-04-26 08:56:05.6152 INFO Starting update NuGet dependencies async. (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2023-04-26 08:56:05.6501 INFO Project Miscellaneous Files cannot be accessed. It may be unloaded. (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2023-04-26 08:56:05.6501 INFO Couldn't find project named C:\Development\ML.NET\src\Test2\Test2.csproj (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2023-04-26 08:56:05.6501 INFO Installing nuget package, package ID: Microsoft.ML, package Version: 2.0.0 (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2023-04-26 08:56:05.6760 DEBUG Value cannot be null.
Parameter name: project
   at NuGet.VisualStudio.Implementation.Extensibility.VsPackageInstallerServices.GetInstalledPackages(Project project)
   at Microsoft.ML.ModelBuilder.Utils.Utilities.<InstallNugetPackageAsync>d__20.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.ML.ModelBuilder.ViewModels.TrainViewModel.<UpdateNugetDependenciesAsync>d__101.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Microsoft.ML.ModelBuilder.ViewModels.TrainViewModel.<GenerateCodeBehindFilesAsync>d__100.MoveNext() (Microsoft.ML.ModelBuilder.Utils.Logger.Debug)
```

**Comment by LittleLittleCloud** [comment]
@dozer75 Can you share with us your VS version on local compute && azure? There might be a change in VS SDK which prevents model builder from getting project name

**Comment by dozer75** [comment]
It is in the initial post, but here it is again:

> **System Information (please complete the following information):**
> 
> * Model Builder or CLI Version: Model Builder 17.15.0.2321402
> * Visual Studio Version (if applicable):
>   * Visual Studio Professional 17.5.4+33530.505
>   * Visual Studio Community 17.5.4+33530.505

**Comment by dozer75** [comment]
Yes, as said, everything has the same version on all my instances both local and Azure based.

**Comment by dozer75** [comment]
Strange thing, I started a new test project today on my Azure VM and all of the sudden I get the same error as described there as well (but with 1.7.0 ML packages, which is still strange all compared)...
