### ISSUE TITLE
Failed to train the model

### ISSUE THREAD

**Issue by INT-Soubhik** [dotnet/machinelearning-modelbuilder#2614]
**LogData is below....................--->**

```
2023-05-03 09:50:01.3285 INFO Set log file path to C:\Users\Soubhik Nandy\AppData\Local\Temp\MLVSTools\logs\SentimentModel-3VOJTG.txt (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2023-05-03 10:09:18.7677 DEBUG Start AutoMLService pid: 17644 (Microsoft.ML.ModelBuilder.Utils.Logger.Debug)
2023-05-03 10:09:18.9606 DEBUG env:path: C:\Users\Soubhik Nandy\AppData\Local\Temp\ModelBuilder\tensorflow-cpu.2.3.1;C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\wbin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\170\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\150\Tools\Binn\;C:\Program Files\Microsoft SQL Server\150\Tools\Binn\;C:\Program Files\Microsoft SQL Server\150\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\150\DTS\Binn\;C:\Program Files\Azure Data Studio\bin;C:\Program Files\Git\cmd;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\TortoiseGit\bin;C:\Program Files\dotnet\;C:\Users\Soubhik Nandy\AppData\Local\Microsoft\WindowsApps;;C:\Program Files\Azure Data Studio\bin;C:\Users\Soubhik Nandy\.dotnet\tools (Microsoft.ML.ModelBuilder.Utils.Logger.Debug)
2023-05-03 10:09:18.9606 DEBUG C:\Users\Soubhik Nandy\AppData\Local\Temp\ModelBuilder\tensorflow-cpu.2.3.1\obj (Microsoft.ML.ModelBuilder.Utils.Logger.Debug)
2023-05-03 10:09:18.9606 INFO restore "c:\program files\microsoft visual studio\2022\community\common7\ide\extensions\yezdkzix.qdo\AutoMLService\RuntimeManager\tensorflow.cpu.csproj" --configfile "c:\program files\microsoft visual studio\2022\community\common7\ide\extensions\yezdkzix.qdo\AutoMLService\RuntimeManager\NuGet.config" -r win-x64 /p:UsingToolXliff=false /p:TorchSharpVersion=0.98.3 /p:TorchSharpCudaRuntimeVersion=1.11.0.1 /p:TensorflowRuntimeVersion=2.3.1 /p:BaseIntermediateOutputPath="C:\Users\Soubhik Nandy\AppData\Local\Temp\ModelBuilder\tensorflow-cpu.2.3.1\obj" (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2023-05-03 10:09:18.9606 INFO publish "c:\program files\microsoft visual studio\2022\community\common7\ide\extensions\yezdkzix.qdo\AutoMLService\RuntimeManager\tensorflow.cpu.csproj" -r win-x64 -c Release --no-self-contained -o C:\Users\Soubhik Nandy\AppData\Local\Temp\ModelBuilder\tensorflow-cpu.2.3.1 --no-restore /p:UsingToolXliff=false /p:TorchSharpVersion=0.98.3 /p:TorchSharpCudaRuntimeVersion=1.11.0.1 /p:TensorflowRuntimeVersion=2.3.1 /p:BaseOutputPath="C:\Users\Soubhik Nandy\AppData\Local\Temp\ModelBuilder\tensorflow-cpu.2.3.1\bin\\" /p:BaseIntermediateOutputPath="C:\Users\Soubhik Nandy\AppData\Local\Temp\ModelBuilder\tensorflow-cpu.2.3.1\obj\\" (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2023-05-03 10:09:18.9606 INFO start installing runtime in C:\Users\Soubhik Nandy\AppData\Local\Temp\ModelBuilder\tensorflow-cpu.2.3.1 (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2023-05-03 10:09:19.2015 INFO  (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2023-05-03 10:09:19.2035 INFO Welcome to .NET 7.0! (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2023-05-03 10:09:19.2035 INFO --------------------- (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2023-05-03 10:09:19.2035 INFO SDK Version: 7.0.203 (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2023-05-03 10:09:19.2035 INFO  (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2023-05-03 10:09:19.2035 INFO Telemetry (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2023-05-03 10:09:19.2035 INFO --------- (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2023-05-03 10:09:19.2035 INFO The .NET tools collect usage data in order to help us improve your experience. It is collected by Microsoft and shared with the community. You can opt-out of telemetry by setting the DOTNET_CLI_TELEMETRY_OPTOUT environment variable to '1' or 'true' using your favorite shell. (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2023-05-03 10:09:19.2035 INFO  (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2023-05-03 10:09:19.2035 INFO Read more about .NET CLI Tools telemetry: https://aka.ms/dotnet-cli-telemetry (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2023-05-03 10:09:19.2035 INFO  (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2023-05-03 10:09:19.2035 INFO ---------------- (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2023-05-03 10:09:19.2035 INFO Installed an ASP.NET Core HTTPS development certificate. (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2023-05-03 10:09:19.2035 INFO To trust the certificate run 'dotnet dev-certs https --trust' (Windows and macOS only). (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2023-05-03 10:09:19.2035 INFO Learn about HTTPS: https://aka.ms/dotnet-https (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2023-05-03 10:09:19.2035 INFO ---------------- (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2023-05-03 10:09:19.2035 INFO Write your first app: https://aka.ms/dotnet-hello-world (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2023-05-03 10:09:19.2035 INFO Find out what's new: https://aka.ms/dotnet-whats-new (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2023-05-03 10:09:19.2035 INFO Explore documentation: https://aka.ms/dotnet-docs (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2023-05-03 10:09:19.2035 INFO Report issues and find source on GitHub: https://github.com/dotnet/core (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2023-05-03 10:09:19.2035 INFO Use 'dotnet --help' to see available commands or visit: https://aka.ms/dotnet-cli (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2023-05-03 10:09:19.2035 INFO -------------------------------------------------------------------------------------- (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2023-05-03 10:09:20.0120 INFO   Determining projects to restore... (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2023-05-03 10:09:34.3933 INFO   Restored c:\program files\microsoft visual studio\2022\community\common7\ide\extensions\yezdkzix.qdo\AutoMLService\RuntimeManager\tensorflow.cpu.csproj (in 14.15 sec). (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2023-05-03 10:09:34.6103 INFO MSBuild version 17.5.1+f6fdcf537 for .NET (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2023-05-03 10:09:34.6113 INFO MSBUILD : error MSB1008: Only one project can be specified. (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2023-05-03 10:09:34.6113 INFO     Full command line: 'C:\Program Files\dotnet\sdk\7.0.203\MSBuild.dll -maxcpucount -verbosity:m -target:Publish --property:_IsPublishing=true --property:UsingToolXliff=false --property:TorchSharpVersion=0.98.3 --property:TorchSharpCudaRuntimeVersion=1.11.0.1 --property:TensorflowRuntimeVersion=2.3.1 --property:BaseOutputPath=C:\Users\Soubhik Nandy\AppData\Local\Temp\ModelBuilder\tensorflow-cpu.2.3.1\bin\ --property:BaseIntermediateOutputPath=C:\Users\Soubhik Nandy\AppData\Local\Temp\ModelBuilder\tensorflow-cpu.2.3.1\obj\ -property:PublishDir=C:\Users\Soubhik -property:_CommandLineDefinedOutputPath=true -property:SelfContained=False -property:_CommandLineDefinedSelfContained=true -property:RuntimeIdentifier=win-x64 -property:_CommandLineDefinedRuntimeIdentifier=true -property:Configuration=Release c:\program files\microsoft visual studio\2022\community\common7\ide\extensions\yezdkzix.qdo\AutoMLService\RuntimeManager\tensorflow.cpu.csproj Nandy\AppData\Local\Temp\ModelBuilder\tensorflow-cpu.2.3.1 -distributedlogger:Microsoft.DotNet.Tools.MSBuild.MSBuildLogger,C:\Program Files\dotnet\sdk\7.0.203\dotnet.dll*Microsoft.DotNet.Tools.MSBuild.MSBuildForwardingLogger,C:\Program Files\dotnet\sdk\7.0.203\dotnet.dll' (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2023-05-03 10:09:34.6113 INFO   Switches appended by response files: (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2023-05-03 10:09:34.6113 INFO Switch: Nandy\AppData\Local\Temp\ModelBuilder\tensorflow-cpu.2.3.1 (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2023-05-03 10:09:34.6113 INFO  (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2023-05-03 10:09:34.6113 INFO For switch syntax, type "MSBuild -help" (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2023-05-03 10:09:34.6726 INFO clean up (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2023-05-03 10:09:34.7517 DEBUG fail to install runtime
   at Microsoft.ML.ModelBuilder.AutoMLService.RuntimeManager.InstallRuntimeAsync(CancellationToken ct) in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/RuntimeManager/RuntimeManager.cs:line 56
   at Microsoft.ML.ModelBuilder.AutoMLService.LocalImageClassificationExperiment.<ExecuteAsync>d__13.MoveNext() in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/Experiments/LocalImageClassificationExperiment.cs:line 51
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ML.ModelBuilder.AutoMLEngine.<StartTrainingAsync>d__21.MoveNext() in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/AutoMLEngineService/AutoMLEngine.cs:line 161 (Microsoft.ML.ModelBuilder.Utils.Logger.Debug)
2023-05-03 10:10:06.9641 DEBUG Start AutoMLService pid: 17644 (Microsoft.ML.ModelBuilder.Utils.Logger.Debug)
2023-05-03 10:10:07.0064 DEBUG env:path: C:\Users\Soubhik Nandy\AppData\Local\Temp\ModelBuilder\tensorflow-cpu.2.3.1;;C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\wbin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\170\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\150\Tools\Binn\;C:\Program Files\Microsoft SQL Server\150\Tools\Binn\;C:\Program Files\Microsoft SQL Server\150\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\150\DTS\Binn\;C:\Program Files\Azure Data Studio\bin;C:\Program Files\Git\cmd;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\TortoiseGit\bin;C:\Program Files\dotnet\;C:\Users\Soubhik Nandy\AppData\Local\Microsoft\WindowsApps;;C:\Program Files\Azure Data Studio\bin;C:\Users\Soubhik Nandy\.dotnet\tools (Microsoft.ML.ModelBuilder.Utils.Logger.Debug)
2023-05-03 10:10:07.0064 DEBUG C:\Users\Soubhik Nandy\AppData\Local\Temp\ModelBuilder\tensorflow-cpu.2.3.1\obj (Microsoft.ML.ModelBuilder.Utils.Logger.Debug)
2023-05-03 10:10:07.0064 INFO restore "c:\program files\microsoft visual studio\2022\community\common7\ide\extensions\yezdkzix.qdo\AutoMLService\RuntimeManager\tensorflow.cpu.csproj" --configfile "c:\program files\microsoft visual studio\2022\community\common7\ide\extensions\yezdkzix.qdo\AutoMLService\RuntimeManager\NuGet.config" -r win-x64 /p:UsingToolXliff=false /p:TorchSharpVersion=0.98.3 /p:TorchSharpCudaRuntimeVersion=1.11.0.1 /p:TensorflowRuntimeVersion=2.3.1 /p:BaseIntermediateOutputPath="C:\Users\Soubhik Nandy\AppData\Local\Temp\ModelBuilder\tensorflow-cpu.2.3.1\obj" (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2023-05-03 10:10:07.0064 INFO publish "c:\program files\microsoft visual studio\2022\community\common7\ide\extensions\yezdkzix.qdo\AutoMLService\RuntimeManager\tensorflow.cpu.csproj" -r win-x64 -c Release --no-self-contained -o C:\Users\Soubhik Nandy\AppData\Local\Temp\ModelBuilder\tensorflow-cpu.2.3.1 --no-restore /p:UsingToolXliff=false /p:TorchSharpVersion=0.98.3 /p:TorchSharpCudaRuntimeVersion=1.11.0.1 /p:TensorflowRuntimeVersion=2.3.1 /p:BaseOutputPath="C:\Users\Soubhik Nandy\AppData\Local\Temp\ModelBuilder\tensorflow-cpu.2.3.1\bin\\" /p:BaseIntermediateOutputPath="C:\Users\Soubhik Nandy\AppData\Local\Temp\ModelBuilder\tensorflow-cpu.2.3.1\obj\\" (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2023-05-03 10:10:07.0064 INFO start installing runtime in C:\Users\Soubhik Nandy\AppData\Local\Temp\ModelBuilder\tensorflow-cpu.2.3.1 (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2023-05-03 10:10:07.6441 INFO   Determining projects to restore... (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2023-05-03 10:10:07.7970 INFO   All projects are up-to-date for restore. (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2023-05-03 10:10:08.0212 INFO MSBuild version 17.5.1+f6fdcf537 for .NET (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2023-05-03 10:10:08.0212 INFO MSBUILD : error MSB1008: Only one project can be specified. (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2023-05-03 10:10:08.0212 INFO     Full command line: 'C:\Program Files\dotnet\sdk\7.0.203\MSBuild.dll -maxcpucount -verbosity:m -target:Publish --property:_IsPublishing=true --property:UsingToolXliff=false --property:TorchSharpVersion=0.98.3 --property:TorchSharpCudaRuntimeVersion=1.11.0.1 --property:TensorflowRuntimeVersion=2.3.1 --property:BaseOutputPath=C:\Users\Soubhik Nandy\AppData\Local\Temp\ModelBuilder\tensorflow-cpu.2.3.1\bin\ --property:BaseIntermediateOutputPath=C:\Users\Soubhik Nandy\AppData\Local\Temp\ModelBuilder\tensorflow-cpu.2.3.1\obj\ -property:PublishDir=C:\Users\Soubhik -property:_CommandLineDefinedOutputPath=true -property:SelfContained=False -property:_CommandLineDefinedSelfContained=true -property:RuntimeIdentifier=win-x64 -property:_CommandLineDefinedRuntimeIdentifier=true -property:Configuration=Release c:\program files\microsoft visual studio\2022\community\common7\ide\extensions\yezdkzix.qdo\AutoMLService\RuntimeManager\tensorflow.cpu.csproj Nandy\AppData\Local\Temp\ModelBuilder\tensorflow-cpu.2.3.1 -distributedlogger:Microsoft.DotNet.Tools.MSBuild.MSBuildLogger,C:\Program Files\dotnet\sdk\7.0.203\dotnet.dll*Microsoft.DotNet.Tools.MSBuild.MSBuildForwardingLogger,C:\Program Files\dotnet\sdk\7.0.203\dotnet.dll' (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2023-05-03 10:10:08.0212 INFO   Switches appended by response files: (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2023-05-03 10:10:08.0212 INFO Switch: Nandy\AppData\Local\Temp\ModelBuilder\tensorflow-cpu.2.3.1 (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2023-05-03 10:10:08.0212 INFO  (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2023-05-03 10:10:08.0212 INFO For switch syntax, type "MSBuild -help" (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2023-05-03 10:10:08.0998 INFO clean up (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2023-05-03 10:10:08.0998 DEBUG fail to install runtime
   at Microsoft.ML.ModelBuilder.AutoMLService.RuntimeManager.InstallRuntimeAsync(CancellationToken ct) in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/RuntimeManager/RuntimeManager.cs:line 56
   at Microsoft.ML.ModelBuilder.AutoMLService.LocalImageClassificationExperiment.<ExecuteAsync>d__13.MoveNext() in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/Experiments/LocalImageClassificationExperiment.cs:line 51
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ML.ModelBuilder.AutoMLEngine.<StartTrainingAsync>d__21.MoveNext() in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/AutoMLEngineService/AutoMLEngine.cs:line 161 (Microsoft.ML.ModelBuilder.Utils.Logger.Debug)

```

**Comment by LittleLittleCloud** [comment]
Dup of #2621.

We'll track down issue in that thread
