### ISSUE TITLE
Training the model failed for data classfication scenario

### ISSUE THREAD

**Issue by balajinaraharisetty** [dotnet/machinelearning-modelbuilder#2641]
**System Information (please complete the following information):**
 - Model Builder or CLI Version: https://dotnet.microsoft.com/en-us/learn/ml-dotnet/get-started-tutorial/train
 - Visual Studio Version (if applicable): Version 17.4.5

**Describe the bug**
- On which page of the tutorial did you run into an issue (URL): https://dotnet.microsoft.com/en-us/learn/ml-dotnet/get-started-tutorial/train
- Clear description of the problem: 2023-05-18 11:17:57.4956 INFO Set log file path to C:\Users\Balaji N\AppData\Local\Temp\MLVSTools\logs\SentimentModel-7A2V9M.txt (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2023-05-18 11:18:53.0393 DEBUG Start AutoMLService pid: 7448 (Microsoft.ML.ModelBuilder.Utils.Logger.Debug)
2023-05-18 11:18:53.4588 INFO start multiclass classification (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2023-05-18 11:18:53.4588 INFO Evaluate Metric: MacroAccuracy (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2023-05-18 11:18:53.4588 INFO Available Trainers: LGBM,FASTFOREST,FASTTREE,LBFGS,SDCA (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2023-05-18 11:18:53.4588 INFO Training time in second: 60 (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2023-05-18 11:19:52.6313 INFO [Source=AutoMLExperiment, Kind=Info] cancel training because cancellation token is invoked... (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2023-05-18 11:19:52.7308 DEBUG Training time finished without completing a successful trial. Either no trial completed or the metric for all completed trials are NaN or Infinity
   at Microsoft.ML.AutoML.AutoMLExperiment.<RunAsync>d__24.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ML.ModelBuilder.AutoMLService.Experiments.MultiClassificationExperiment.<ExecuteAsync>d__14.MoveNext() in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/Experiments/MultiClassificationExperiment.cs:line 134
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ML.ModelBuilder.AutoMLEngine.<StartTrainingAsync>d__21.MoveNext() in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/AutoMLEngineService/AutoMLEngine.cs:line 161 (Microsoft.ML.ModelBuilder.Utils.Logger.Debug)

**To Reproduce**
1. I followed the steps mentioned when clicked on "Train". 
2. We are getting the following error. Please find below screenshot
![image](https://github.com/dotnet/machinelearning-modelbuilder/assets/67501998/c8be73d0-578f-4d66-b019-c9981bd392fb)

**Expected behavior**
2023-05-18 11:17:57.4956 INFO Set log file path to C:\Users\Balaji N\AppData\Local\Temp\MLVSTools\logs\SentimentModel-7A2V9M.txt (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2023-05-18 11:18:53.0393 DEBUG Start AutoMLService pid: 7448 (Microsoft.ML.ModelBuilder.Utils.Logger.Debug)
2023-05-18 11:18:53.4588 INFO start multiclass classification (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2023-05-18 11:18:53.4588 INFO Evaluate Metric: MacroAccuracy (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2023-05-18 11:18:53.4588 INFO Available Trainers: LGBM,FASTFOREST,FASTTREE,LBFGS,SDCA (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2023-05-18 11:18:53.4588 INFO Training time in second: 60 (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2023-05-18 11:19:52.6313 INFO [Source=AutoMLExperiment, Kind=Info] cancel training because cancellation token is invoked... (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2023-05-18 11:19:52.7308 DEBUG Training time finished without completing a successful trial. Either no trial completed or the metric for all completed trials are NaN or Infinity
   at Microsoft.ML.AutoML.AutoMLExperiment.<RunAsync>d__24.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ML.ModelBuilder.AutoMLService.Experiments.MultiClassificationExperiment.<ExecuteAsync>d__14.MoveNext() in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/Experiments/MultiClassificationExperiment.cs:line 134
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ML.ModelBuilder.AutoMLEngine.<StartTrainingAsync>d__21.MoveNext() in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/AutoMLEngineService/AutoMLEngine.cs:line 161 (Microsoft.ML.ModelBuilder.Utils.Logger.Debug)

**Screenshots**
![image](https://github.com/dotnet/machinelearning-modelbuilder/assets/67501998/f8470e34-162a-417a-b5f6-342940e67eb9)

**Comment by LittleLittleCloud** [comment]
Looks like no trial has been completed before times up, maybe extend training time here?

**Comment by chasegalloway** [comment]
I'm having the same problem right now, did you ever find a solution?

**Comment by wmail-ak** [comment]
I am too

> I'm having the same problem right now, did you ever find a solution?
