### ISSUE TITLE
SQL connection is not valid when modifying Command Timeout

### ISSUE THREAD

**Issue by wrenhansen** [dotnet/machinelearning-modelbuilder#2646]
- Model Builder Version (available in Manage Extensions dialog): 
 - 17.16.0.23.26802
 
 - Visual Studio Version
Microsoft Visual Studio Community 2022 (64-bit) - Version 17.6.0

**Describe the bug**
Unable to load data from a MSSQL View after changing Command Timeout on the database connection.
Receiving error: SQL connection is not valid. 
Error appears as soon as I click OK
Works fine if this setting is not modified and I use a query that is less complex.

**To Reproduce**
1. Connect to a database
2. Select Server/DB
3. Click on Advanced 
4. Change Command Timeout
5. Click OK on Advanced
6. Click OK on Connection Properties
7. Receive Error
![image](https://github.com/dotnet/machinelearning-modelbuilder/assets/1238851/a5d04635-0332-4702-99cd-11912a87a7d8)

**Expected behavior**
Use the modified (extended timeout) so my complex view can be loaded

2023-05-23 05:24:36.6997 DEBUG SQL connection is not valid. If reloading Model Builder, please re-open the SQL Source dialog to reauthenticate.
   at Microsoft.ML.ModelBuilder.DataProviders.SQLDataProvider.GetSQLConnectionString(TabularSqlDataSource sqlData)
   at Microsoft.ML.ModelBuilder.ToolWindows.DataTextViewModel.<InitiateSQLSelectionAsync>d__137.MoveNext() (Microsoft.ML.ModelBuilder.Utils.Logger.Debug)

 at Microsoft.ML.ModelBuilder.DataProviders.SQLDataProvider.GetSQLConnectionString(TabularSqlDataSource sqlData)
   at Microsoft.ML.ModelBuilder.ToolWindows.DataTextViewModel.<InitiateSQLSelectionAsync>d__137.MoveNext()

![image](https://github.com/dotnet/machinelearning-modelbuilder/assets/1238851/bd3983ef-bc66-43a4-8ad7-931fecadae3c)

Full Log file:
2023-05-23 05:24:04.8010 DEBUG update ModelBuilderDataContext_287.TrainDataContext (Microsoft.ML.ModelBuilder.Utils.Logger.Debug)
2023-05-23 05:24:04.8010 DEBUG update DataTextViewModel_297.TextColumn (Microsoft.ML.ModelBuilder.Utils.Logger.Debug)
2023-05-23 05:24:04.8010 DEBUG update ModelBuilderDataContext_287.GetCompletedTabAsync (Microsoft.ML.ModelBuilder.Utils.Logger.Debug)
2023-05-23 05:24:04.8010 DEBUG update DataTextViewModel_297.IsCompleted (Microsoft.ML.ModelBuilder.Utils.Logger.Debug)
2023-05-23 05:24:04.8010 DEBUG update DataTabDataContext_296.IsCompleted (Microsoft.ML.ModelBuilder.Utils.Logger.Debug)
2023-05-23 05:24:04.8010 DEBUG update DataTextViewModel_297.PossibleTextColumnList (Microsoft.ML.ModelBuilder.Utils.Logger.Debug)
2023-05-23 05:24:04.8010 DEBUG update ModelBuilderDataContext_287.CreateEvaluateTabViewModelAsync (Microsoft.ML.ModelBuilder.Utils.Logger.Debug)
2023-05-23 05:24:04.8010 DEBUG update ModelBuilderDataContext_287.CreateConsumeTabViewModelAsync (Microsoft.ML.ModelBuilder.Utils.Logger.Debug)
2023-05-23 05:24:04.8010 DEBUG update ModelBuilderDataContext_287.GetCompletedTabAsync (Microsoft.ML.ModelBuilder.Utils.Logger.Debug)
2023-05-23 05:24:04.8010 DEBUG update DataTextViewModel_297.SelectedTextColumn (Microsoft.ML.ModelBuilder.Utils.Logger.Debug)
2023-05-23 05:24:04.8010 DEBUG update ModelBuilderDataContext_287.CreateTrainTabViewModelAsync (Microsoft.ML.ModelBuilder.Utils.Logger.Debug)
2023-05-23 05:24:04.8010 DEBUG update ModelBuilderDataContext_287.CreateEvaluateTabViewModelAsync (Microsoft.ML.ModelBuilder.Utils.Logger.Debug)
2023-05-23 05:24:04.8010 DEBUG update DataTextViewModel_297.ShowTextColumnSearchBox (Microsoft.ML.ModelBuilder.Utils.Logger.Debug)
2023-05-23 05:24:04.8010 DEBUG update ModelBuilderDataContext_287.TrainDataContext (Microsoft.ML.ModelBuilder.Utils.Logger.Debug)
2023-05-23 05:24:04.8010 DEBUG update ModelBuilderDataContext_287.GetCompletedTabAsync (Microsoft.ML.ModelBuilder.Utils.Logger.Debug)
2023-05-23 05:24:04.8010 DEBUG update ModelBuilderDataContext_287.CreateEvaluateTabViewModelAsync (Microsoft.ML.ModelBuilder.Utils.Logger.Debug)
2023-05-23 05:24:04.8010 DEBUG update ModelBuilderDataContext_287.CreateConsumeTabViewModelAsync (Microsoft.ML.ModelBuilder.Utils.Logger.Debug)
2023-05-23 05:24:36.6997 DEBUG SQL connection is not valid. If reloading Model Builder, please re-open the SQL Source dialog to reauthenticate.
   at Microsoft.ML.ModelBuilder.DataProviders.SQLDataProvider.GetSQLConnectionString(TabularSqlDataSource sqlData)
   at Microsoft.ML.ModelBuilder.ToolWindows.DataTextViewModel.<InitiateSQLSelectionAsync>d__137.MoveNext() (Microsoft.ML.ModelBuilder.Utils.Logger.Debug)

**Comment by LittleLittleCloud** [comment]
Would you mind sharing your modified sql connect string in your .mbconfig (after purging sensitive information) so we can take a look

**Comment by wrenhansen** [comment]
Data Source=DESKTOP-XXXXX;Initial Catalog=Glass;Integrated Security=True;Command Timeout=120

The test connection validates in the Connection Properties screen

***@***.***

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by LittleLittleCloud** [comment]
Thanks, @zewditu  can you take a look

**Comment by wrenhansen** [comment]
I replied to the email with this info, but adding it here as well:

Data Source=DESKTOP-XXXXX;Initial Catalog=Glass;Integrated Security=True;**Command Timeout=120**

I find I receive this error when changing any property in the Advanced Properties.

The test connection validates in the Connection Properties screen
![image](https://github.com/dotnet/machinelearning-modelbuilder/assets/1238851/89a64b14-63d1-4520-8f55-cf2f1aae35db)

**Comment by wrenhansen** [comment]
Sounds good. Is there a way to test this prior to the June 2023 release?

**Comment by zewditu** [comment]
We are still looking into it, we will fix it in the next release
