### ISSUE TITLE
MLNET Cli fails with System.NotImplementedException when running image-classification command

### ISSUE THREAD

**Issue by DanielSe** [dotnet/machinelearning-modelbuilder#2679]
**System Information (please complete the following information):**
 - mlnet cli version: 16.15.1+5cfa5322dc43fb36001cafd7c46e716141dfa219
 - os: mlnet-osx-x64 / mlnet-linux-x64

**Describe the bug**
- When running an mlnet image-classification command an exception is encountered:
```
System.NotImplementedException: The method or operation is not implemented.
   at Microsoft.ML.ModelBuilder.AutoMLService.Experiments.ExperimentFactory.CreateExperiment(MLContext context, ITrainingConfiguration config, AutoMLDependService services, PathConfiguration pathConfig) in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/Experiments/ExperimentFactory.cs:line 38
   at Microsoft.ML.ModelBuilder.AutoMLEngine.StartTrainingAsync(ITrainingConfiguration config, PathConfiguration pathConfig, CancellationToken userCancellationToken) in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/AutoMLEngineService/AutoMLEngine.cs:line 154
   at Microsoft.ML.CLI.Runners.AutoMLRunner.ExecuteAsync() in /_/src/mlnet/Runners/AutoMLRunner.cs:line 86
   at Microsoft.ML.CLI.Program.TrainAsync(ITrainingConfiguration trainingConfiguration, PathConfiguration pathConfig, AutoMLServiceLogLevel logLevel) in /_/src/mlnet/Program.cs:line 388
   at Microsoft.ML.CLI.Program.<>c.<<CreateRootCommandLineBuilder>b__4_3>d.MoveNext() in /_/src/mlnet/Program.cs:line 162
--- End of stack trace from previous location ---
   at System.CommandLine.Invocation.CommandHandler.GetExitCodeAsync(Object value, InvocationContext context)
   at System.CommandLine.Invocation.ModelBindingCommandHandler.InvokeAsync(InvocationContext context)
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass23_0.<<UseParseErrorReporting>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.ML.CLI.Program.<>c__DisplayClass4_0.<<CreateRootCommandLineBuilder>b__10>d.MoveNext() in /_/src/mlnet/Program.cs:line 325
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseSuggestDirective>b__24_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass22_0.<<UseParseDirective>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass11_0.<<UseDebugDirective>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<RegisterWithDotnetSuggest>b__10_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass14_0.<<UseExceptionHandler>b__0>d.MoveNext()
```

**To Reproduce**
1. Download ´assets.zip´ from https://github.com/dotnet/machinelearning-samples/tree/main/samples/modelbuilder/ImageClassification_Azure_LandUse
2. Extract archive: `$ unzip assets.zip`
3. Run: `$ mlnet image-classification --dataset ./assets`

**Expected behavior**
Expection is for the Cli tool to use AutoML to train a model on the dataset.

**Comment by Thiago-Bastani** [comment]
Got thet problem too. They had fixed it in a previous issue, but I guess it's back again.

**Comment by xumix** [comment]
same here
