### ISSUE TITLE
Cannot find model.zip

### ISSUE THREAD

**Issue by vinbrule** [dotnet/machinelearning-modelbuilder#272]
Problem encountered on https://dotnet.microsoft.com/learn/ml-dotnet/get-started-tutorial/consume
Operating System: macos

Error: when `dotnet run`

Unhandled Exception: System.IO.FileNotFoundException: Could not find file '/Users/xxx/Downloads/tmp/myMLApp/consumeModelApp/MLModel.zip'.
   at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at Microsoft.ML.ModelOperationsCatalog.Load(String filePath, DataViewSchema& inputSchema)
   at consumeModelApp.Program.ConsumeModel() in /Users/van/Downloads/tmp/myMLApp/consumeModelApp/Program.cs:line 19
   at consumeModelApp.Program.Main(String[] args) in /Users/van/Downloads/tmp/myMLApp/consumeModelApp/Program.cs:line 11

**Comment by beccamc** [comment]
@vinbrule Are you still experiencing this problem on the latest version of the CLI?

**Comment by beccamc** [comment]
@vinbrule I can't reproduce this anymore and I think it has been fixed. If you are still seeing the problem please let me know and we can reopen the issue. Thanks for reporting!
