### ISSUE TITLE
Consume Model doesn't work when referenced by .NET Full Framework

### ISSUE THREAD

**Issue by BeginTry** [dotnet/machinelearning-modelbuilder#274]
Problem encountered on https://dotnet.microsoft.com/learn/ml-dotnet/get-started-tutorial/consume
Operating System: Windows 10 Pro

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

```
namespace ML_Test
{
    class Program
    {
        static void Main(string[] args)
        {
            // Add input data
            var input = new ModelInput();
            input.TweetText = "Dave, that is really cool.";

            // Load model and predict output of sample data
            ModelOutput result = ConsumeModel.Predict(input);

            Console.WriteLine(result.Prediction.ToString());
            Console.ReadKey();
        }
    }
}
```

<pre>
System.IO.FileNotFoundException
  HResult=0x80070002
  Message=Could not load file or assembly 'System.Memory, Version=4.0.1.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The system cannot find the file specified.
  Source=Microsoft.ML.Data
  StackTrace:
   at Microsoft.ML.Data.IO.CodecFactory..ctor(IHostEnvironment env, MemoryStreamPool memPool)
   at Microsoft.ML.Data.IO.BinaryLoader..ctor(Arguments args, IHost host, Stream stream, Boolean leaveOpen)
   at Microsoft.ML.ModelOperationsCatalog.Load(Stream stream, DataViewSchema& inputSchema)
   at Microsoft.ML.ModelOperationsCatalog.Load(String filePath, DataViewSchema& inputSchema)
   at ML_TestML.Model.ConsumeModel.Predict(ModelInput input) in C:\Users\Dave\Documents\Visual Studio 2017\Projects\ML_Test\ML_TestML.Model\ConsumeModel.cs:line 24
   at ML_Test.Program.Main(String[] args) in C:\Users\Dave\Documents\Visual Studio 2017\Projects\ML_Test\ML_Test\Program.cs:line 20
</pre>

![image](https://user-images.githubusercontent.com/27367041/66280029-c03b1200-e882-11e9-8fd9-9b1399b0540a.png)
![image](https://user-images.githubusercontent.com/27367041/66280185-86b6d680-e883-11e9-9e1b-78e81b4bb131.png)

**Comment by JakeRadMSFT** [comment]
Re-opened because it should work with .NET Full Framework

**Comment by LittleLittleCloud** [comment]
Not work with net472
```
Unhandled Exception: System.DllNotFoundException: Unable to load DLL 'CpuMathNative': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
   at Microsoft.ML.Internal.CpuMath.Thunk.SumSqU(Single* ps, Int32 c)
   at Microsoft.ML.Internal.CpuMath.CpuMathUtils.SumSq(Single mean, ReadOnlySpan`1 src)
   at Microsoft.ML.Transforms.LpNormNormalizingTransformer.Mapper.L2Norm(ReadOnlySpan`1 values, Single mean)
   at Microsoft.ML.Transforms.LpNormNormalizingTransformer.Mapper.<>c__DisplayClass8_0.<MakeGetter>b__5(VBuffer`1& dst)
   at Microsoft.ML.Data.ColumnConcatenatingTransformer.Mapper.BoundColumn.<>c__DisplayClass18_0`1.<MakeGetter>b__0(VBuffer`1& dst)
   at Microsoft.ML.Transforms.NormalizeTransform.AffineColumnFunction.Sng.ImplVec.<>c__DisplayClass5_0.<GetGetter>b__0(VBuffer`1& dst)
   at Microsoft.ML.Data.SchemaBindableBinaryPredictorWrapper.CalibratedRowMapper.EnsureCachedResultValueMapper(ValueMapper`3 mapper, Int64& cachedPosition, ValueGetter`1 featureGetter, VBuffer`1& features, Single& score, Single& prob, DataViewRow input)
   at Microsoft.ML.Data.SchemaBindableBinaryPredictorWrapper.CalibratedRowMapper.<>c__DisplayClass14_0.<CreateGetters>b__0(Single& dst)
   at Microsoft.ML.Data.PredictedLabelScorerBase.EnsureCachedPosition[TScore](Int64& cachedPosition, TScore& score, DataViewRow boundRow, ValueGetter`1 scoreGetter)
   at Microsoft.ML.Data.BinaryClassifierScorer.<>c__DisplayClass15_0.<GetPredictedLabelGetter>b__1(Boolean& dst)
   at Microsoft.ML.Data.TypedCursorable`1.TypedRowBase.<>c__DisplayClass10_0`1.<CreateDirectSetter>b__0(TRow row)
   at Microsoft.ML.Data.TypedCursorable`1.TypedRowBase.FillValues(TRow row)
   at Microsoft.ML.Data.TypedCursorable`1.RowImplementation.FillValues(TRow row)
   at Microsoft.ML.PredictionEngineBase`2.FillValues(TDst prediction)
   at Microsoft.ML.PredictionEngine`2.Predict(TSrc example, TDst& prediction)
   at Microsoft.ML.PredictionEngineBase`2.Predict(TSrc example)
   at Net_frameworkML.Model.ConsumeModel.Predict(ModelInput input) in C:\Users\xiaoyuz\source\repos\net-frameworkML.Model\ConsumeModel.cs:line 28
   at net_framework.Program.Main(String[] args) in C:\Users\xiaoyuz\source\repos\net-framework\Program.cs:line 19
Press any key to continue . . .
```

**Comment by JakeRadMSFT** [comment]
There seems to be a VS/MSBuild issue here.

**Comment by beccamc** [comment]
Posting the workaround for anyone else who encounters this issue.. 

This is a bug in the .NET Full Framework non-SDK-style project format. We are pursing a permanent fix with the .NET team. 
 
To get unblocked, upgrade your .NET Framework project to use the [SDK-style](https://docs.microsoft.com/en-us/dotnet/standard/frameworks), or start a new project using .NET Core. Checkout this [blog ](https://www.hanselman.com/blog/UpgradingAnExistingNETProjectFilesToTheLeanNewCSPROJFormatFromNETCore.aspx) by Scott Hanselman for more help.
 
If you can't upgrade to the SDK-style, use the following to get unblocked with the non-SDK-style project format..

1. Set the target platform to x64
`<PlatformTarget>x64</PlatformTarget>`
 
2. Add a package reference to your project for [Microsoft.ML](https://www.nuget.org/packages/Microsoft.ML) (latest version) 
`<PackageReference Include="Microsoft.ML" Version="1.5.0-preview" />`
