### ISSUE TITLE
CLI Training ImageClassification Scenario (config) Fails: Model Builder does not support version 2 of type ClassificationTrainingOption

### ISSUE THREAD

**Issue by darrabam** [dotnet/machinelearning-modelbuilder#2740]
**System Information:**
 - Model Builder Version (available in Manage Extensions dialog):  17.17.0.2332602
 - Visual Studio Version: 17.6.4
 - mlnet-win-x64: 16.15.1 
 > dotnet tool update --global mlnet-win-x64
Tool 'mlnet-win-x64' was reinstalled with the latest stable version (version '16.15.1').

**Describe the bug**
- Trying to retrain an ImageClassification Scenario using the command:
`mlnet.exe train --training-config MYPATH\MLModel.mbconfig`

The command fails with the error:
System.AggregateException: One or more errors occurred. (This version of Model Builder does not support version 2 of type ClassificationTrainingOption. Please update Model Builder to latest version in the VS Extension Manager.)
 ---> System.ArgumentException: This version of Model Builder does not support version 2 of type ClassificationTrainingOption. Please update Model Builder to latest version in the VS Extension Manager.
   at Microsoft.ML.ModelBuilder.Configuration.MBConfigConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer) in /_/src/Microsoft.ML.ModelBuilder.TrainingConfiguration/MBConfigConverter.cs:line 73
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Populate(JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerProxy.PopulateInternal(JsonReader reader, Object target)
   at Newtonsoft.Json.JsonSerializer.Populate(JsonReader reader, Object target)
   at Microsoft.ML.ModelBuilder.Configuration.MBConfigConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer) in /_/src/Microsoft.ML.ModelBuilder.TrainingConfiguration/MBConfigConverter.cs:line 161
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Deserialize(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Microsoft.ML.CLI.TrainingConfigurationHelper.LoadFromFileAsync(String filePath) in /_/src/mlnet/TrainingConfigurationHelper.cs:line 35
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at Microsoft.ML.CLI.Commands.TrainingCommand.ToTrainingConfiguration() in /_/src/mlnet/Commands/TrainingCommand.cs:line 21
   at Microsoft.ML.CLI.Program.<>c.<<CreateRootCommandLineBuilder>b__4_4>d.MoveNext() in /_/src/mlnet/Program.cs:line 171
--- End of stack trace from previous location ---
   at System.CommandLine.Invocation.CommandHandler.GetExitCodeAsync(Object value, InvocationContext context)
   at System.CommandLine.Invocation.ModelBindingCommandHandler.InvokeAsync(InvocationContext context)
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass23_0.<<UseParseErrorReporting>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.ML.CLI.Program.<>c__DisplayClass4_0.<<CreateRootCommandLineBuilder>b__10>d.MoveNext() in /_/src/mlnet/Program.cs:line 325
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseSuggestDirective>b__24_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass22_0.<<UseParseDirective>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass11_0.<<UseDebugDirective>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<RegisterWithDotnetSuggest>b__10_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass14_0.<<UseExceptionHandler>b__0>d.MoveNext()

Check out log file for more information: [log.txt](https://github.com/dotnet/machinelearning-modelbuilder/files/11995398/log.txt)

**To Reproduce**
1. Generate a machine learning model (ImageClassification Scenario) using Visual Studio 2022.
2. Once completed successfully, note the path of the produced MLModel.mbconfig file.
3. Open a CMD and run the command `mlnet.exe train --training-config MYPATH\MLModel.mbconfig`
If the mlnet.exe is not found, install it using the command `dotnet tool install --global mlnet-win-x64`

**Expected behavior**
Command should run and retrain the model without errors. 

**Workaround**
Manually edit *.mbconfig and change the `"Version"` to 1 (under the TrainingOption)

**Comment by LittleLittleCloud** [comment]
@darrabam It's because the version of `TrainingOption` is too new for the latest mlnet cli to load.

@LittleLittleCloud make a new release of mlnet.cli to fix this issue.

**Comment by LittleLittleCloud** [comment]
Should be fixed on the latest release. Feel free to reopen it if you see it again
