### ISSUE TITLE
The given key was not present in the dictionary.

### ISSUE THREAD

**Issue by aboudoux** [dotnet/machinelearning-modelbuilder#2742]
Hello,
I'm trying to train my custom model with the local Object detection scenario. everything go fine until Channel finished that crash with the following exception

 at System.ThrowHelper.ThrowKeyNotFoundException()
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at Microsoft.ML.TorchSharp.AutoFormerV2.ObjectDetectionMetrics.ImageIoU(List`1 objectLabel, List`1 annotation, Dictionary`2 iouDic, Dictionary`2 groundTruthBoxes)
   at Microsoft.ML.TorchSharp.AutoFormerV2.ObjectDetectionMetrics.GenerateIOUDic(List`1 annotations, List`1 objectLabelList, Dictionary`2 iouDic, Dictionary`2 groundTruthBoxes)
   at Microsoft.ML.TorchSharp.AutoFormerV2.ObjectDetectionMetrics.MeasureMetrics(IDataView dataView, Column labelCol, Column actualBoundingBoxColumn, Column predictedLabelCol, Column predictedBoundingBoxColumn, Column scoreCol)
   at Microsoft.ML.ModelBuilder.AutoMLService.LocalObjectDetectionMetricManager.Evaluate(MLContext context, IDataView eval) in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/MetricManagers/LocalObjectDetectionMetricManager.cs:line 24
   at Microsoft.ML.AutoML.SweepablePipelineRunner.Run(TrialSettings settings)
   at Microsoft.ML.AutoML.SweepablePipelineRunner.RunAsync(TrialSettings settings, CancellationToken ct)
   at Microsoft.ML.AutoML.AutoMLExperiment.<RunAsync>d__24.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ML.ModelBuilder.AutoMLService.LocalObjectDetectionExperiment.<ExecuteAsync>d__13.MoveNext() in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/Experiments/LocalObjectDetectionExperiment.cs:line 133
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ML.ModelBuilder.AutoMLEngine.<StartTrainingAsync>d__21.MoveNext() in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/AutoMLEngineService/AutoMLEngine.cs:line 169

**Comment by LittleLittleCloud** [comment]
@aboudoux Would you mind sharing your .mbconfig with us.

**Comment by Nekiplay** [comment]
I have the same problem, my mbconfig
[LordsMobile.zip](https://github.com/dotnet/machinelearning-modelbuilder/files/12063566/LordsMobile.zip)

**Comment by Nekiplay** [comment]
I have the same problem, my mbconfig
```json
{
  "Scenario": "ObjectDetection",
  "DataSource": {
    "Version": 0,
    "Type": "Coco",
    "FilePath": "C:\\Users\\Nekiplay\\Desktop\\CocoAnatator\\coco-annotator\\datasets\\LordsMobile\\.exports\\coco-1689492909.3708026.json"
  },
  "Environment": {
    "Type": "LocalCPU",
    "Version": 1
  },
  "Type": "TrainingConfig",
  "Version": 4,
  "TrainingOption": {
    "Version": 0,
    "Type": "ObjectDetectionTrainingOption",
    "TrainingTime": 2147483647,
    "Epoch": 5,
    "ScoreThreshold": 0.35,
    "IOUThreshold": 0.5,
    "ValidationOption": {
      "Version": 0,
      "Type": "TrainValidateSplitValidationOption",
      "SplitRatio": 0.2
    },
    "ResizeOption": {
      "Version": 0,
      "Type": "Resize",
      "Width": 800,
      "Height": 600
    }
  }
}
```

**Comment by Nekiplay** [comment]
> Hello, I'm trying to train my custom model with the local Object detection scenario. everything go fine until Channel finished that crash with the following exception
> 
> at System.ThrowHelper.ThrowKeyNotFoundException() at System.Collections.Generic.Dictionary`2.get_Item(TKey key) at Microsoft.ML.TorchSharp.AutoFormerV2.ObjectDetectionMetrics.ImageIoU(List`1 objectLabel, List`1 annotation, Dictionary`2 iouDic, Dictionary`2 groundTruthBoxes) at Microsoft.ML.TorchSharp.AutoFormerV2.ObjectDetectionMetrics.GenerateIOUDic(List`1 annotations, List`1 objectLabelList, Dictionary`2 iouDic, Dictionary`2 groundTruthBoxes) at Microsoft.ML.TorchSharp.AutoFormerV2.ObjectDetectionMetrics.MeasureMetrics(IDataView dataView, Column labelCol, Column actualBoundingBoxColumn, Column predictedLabelCol, Column predictedBoundingBoxColumn, Column scoreCol) at Microsoft.ML.ModelBuilder.AutoMLService.LocalObjectDetectionMetricManager.Evaluate(MLContext context, IDataView eval) in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/MetricManagers/LocalObjectDetectionMetricManager.cs:line 24 at Microsoft.ML.AutoML.SweepablePipelineRunner.Run(TrialSettings settings) at Microsoft.ML.AutoML.SweepablePipelineRunner.RunAsync(TrialSettings settings, CancellationToken ct) at Microsoft.ML.AutoML.AutoMLExperiment.d__24.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at Microsoft.ML.ModelBuilder.AutoMLService.LocalObjectDetectionExperiment.d__13.MoveNext() in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/Experiments/LocalObjectDetectionExperiment.cs:line 133 --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at Microsoft.ML.ModelBuilder.AutoMLEngine.d__21.MoveNext() in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/AutoMLEngineService/AutoMLEngine.cs:line 169

I found the cause of the problem, don't export a model with unlabeled categories

**Comment by LittleLittleCloud** [comment]
@aboudoux @Nekiplay May I ask how many different kind of labels does your dataset have? I'm suspecting that this issue is causes because some labels are classified into test dataset and not in train dataset during train-validation split.

**Comment by Nekiplay** [comment]
> @aboudoux @Nekiplay May I ask how many different kind of labels does your dataset have? I'm suspecting that this issue is causes because some labels are classified into test dataset and not in train dataset during train-validation split.
> 
> I also have trouble in reproducing this issue on all testing dataset I have. Would be appreciated if anyone can guide me through how to reproducing this bug.

There was one label for 1 category and 0 for the other after I removed their exports model training went fine
