### ISSUE TITLE
Error when clicked "Train"

### ISSUE THREAD

**Issue by igorzavalny** [dotnet/machinelearning-modelbuilder#2749]
**System Information (please complete the following information):**
 - Model Builder Version (available in Manage Extensions dialog): 17.17.02332602
 - Visual Studio Version 2022

**Describe the bug**
- On which step of the process did you run into an issue: https://learn.microsoft.com/en-us/training/modules/predictive-maintenance-model-builder/5-exercise-train-model-builder
- Clear description of the problem: error when clicked "Training"

**To Reproduce**

**Expected behavior**
Training completed
**Screenshots**

**Additional context**
   at Microsoft.ML.Data.TextLoader.Cursor.<ParseParallel>d__33.MoveNext()
   at Microsoft.ML.Data.TextLoader.Cursor.MoveNextCore()
   at Microsoft.ML.Data.RootCursorBase.MoveNext()
   at Microsoft.ML.Data.LinkedRowFilterCursorBase.MoveNextCore()
   at Microsoft.ML.Data.RootCursorBase.MoveNext()
   at Microsoft.ML.Transforms.ValueToKeyMappingTransformer.Train(IHostEnvironment env, IChannel ch, ColInfo[] infos, IDataView keyData, ColumnOptionsBase[] columns, IDataView trainingData, Boolean autoConvert)
   at Microsoft.ML.Transforms.ValueToKeyMappingTransformer..ctor(IHostEnvironment env, IDataView input, ColumnOptionsBase[] columns, IDataView keyData, Boolean autoConvert)
   at Microsoft.ML.Transforms.ValueToKeyMappingEstimator.Fit(IDataView input)
   at Microsoft.ML.Data.EstimatorChain`1.Fit(IDataView input)
   at Microsoft.ML.Transforms.OneHotEncodingTransformer..ctor(ValueToKeyMappingEstimator term, IEstimator`1 toVector, IDataView input)
   at Microsoft.ML.Transforms.OneHotEncodingEstimator.Fit(IDataView input)
   at Microsoft.ML.Data.EstimatorChain`1.Fit(IDataView input)
   at Microsoft.ML.AutoML.SweepablePipelineRunner.Run(TrialSettings settings)
   at Microsoft.ML.AutoML.SweepablePipelineRunner.RunAsync(TrialSettings settings, CancellationToken ct)
   at Microsoft.ML.AutoML.AutoMLExperiment.<RunAsync>d__24.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ML.ModelBuilder.AutoMLService.Experiments.MultiClassificationExperiment.<ExecuteAsync>d__14.MoveNext() in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/Experiments/MultiClassificationExperiment.cs:line 140
--- End of stack trace from pr
[MLModel1-H7Z2YZ.txt](https://github.com/dotnet/machinelearning-modelbuilder/files/12149176/MLModel1-H7Z2YZ.txt)
evious location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ML.ModelBuilder.AutoMLEngine.<StartTrainingAsync>d__21.MoveNext() in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/AutoMLEngineService/AutoMLEngine.cs:line 169

**Comment by LittleLittleCloud** [comment]
Would you mind sharing the training dataset you have? Looks like it's something wrong with the dataset you have.

**Comment by LittleLittleCloud** [comment]
close due to no respond, feel free to reopen it if you have any other issues.
