### ISSUE TITLE
File Path was not loaded in machine learning data model 

### ISSUE THREAD

**Issue by erisekasap** [dotnet/machinelearning-modelbuilder#2757]
2023-08-05 13:36:53.3356 INFO Set log file path to C:\Users\Eris\AppData\Local\Temp\MLVSTools\logs\MLModel1-LTJ6D0.txt (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2023-08-05 13:39:22.1015 TRACE Current user is null (Microsoft.ML.ModelBuilder.ToolWindows.AzureAttachViewModel.LoadSubscriptionsAsync)
2023-08-05 13:39:24.1177 TRACE Current user is not null (Microsoft.ML.ModelBuilder.ToolWindows.AzureAttachViewModel+<LoadSubscriptionsAsync>d__55.MoveNext)
2023-08-05 13:39:29.4669 TRACE Current user is not null (Microsoft.ML.ModelBuilder.ToolWindows.AzureAttachViewModel+<LoadSubscriptionsAsync>d__55.MoveNext)
2023-08-05 13:45:41.5011 INFO start nni training (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2023-08-05 13:45:41.5561 INFO Experiment output folder: C:\Users\Eris\AppData\Local\Temp\AutoML-NNI\Experiment-UIY3RC (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2023-08-05 13:45:41.5581 DEBUG row count is unknown, count it explicitly (Microsoft.ML.ModelBuilder.Utils.Logger.Debug)
2023-08-05 13:45:41.5581 DEBUG count elapse 0ms (Microsoft.ML.ModelBuilder.Utils.Logger.Debug)
2023-08-05 13:45:41.5581 INFO |     Trainer                              MicroAccuracy  MacroAccuracy  Duration #Iteration                     | (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2023-08-05 13:45:42.2058 DEBUG update train dataset C:\Users\Eris\AppData\Local\Temp\AutoML-NNI\Experiment-UIY3RC\train.bin (Microsoft.ML.ModelBuilder.Utils.Logger.Debug)
2023-08-05 13:45:42.2198 DEBUG update test dataset C:\Users\Eris\AppData\Local\Temp\AutoML-NNI\Experiment-UIY3RC\test.bin (Microsoft.ML.ModelBuilder.Utils.Logger.Debug)
2023-08-05 13:45:42.9155 INFO Trial 0 encounter error with message: Only one class found in the Label column. To build a multiclass classification model, the number of classes needs to be 2 or greater
Parameter name: labelCount (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2023-08-05 13:45:43.0038 DEBUG    at Microsoft.ML.Vision.ImageClassificationTrainer.InitializeTrainingGraph(IDataView input)
   at Microsoft.ML.Vision.ImageClassificationTrainer.TrainModelCore(TrainContext trainContext)
   at Microsoft.ML.Trainers.TrainerEstimatorBase`2.TrainTransformer(IDataView trainSet, IDataView validationSet, IPredictor initPredictor)
   at Microsoft.ML.Data.EstimatorChain`1.Fit(IDataView input)
   at Microsoft.ML.ModelBuilder.AutoMLService.MulticlassClassificationRunner.RunTrainTestSplit(TrialParameter parameter, TrainingConfiguration config, IDataView trainDatasetCache, IDataView testDatasetCache) in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/Runner/MulticlassClassificationRunner.cs:line 70
   at Microsoft.ML.ModelBuilder.AutoMLService.LocalDispatcher.Run() in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/Dispatcher/LocalDispatcher.cs:line 172
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ML.ModelBuilder.AutoMLService.LocalDispatcher.<RunAsync>d__19.MoveNext() in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/Dispatcher/LocalDispatcher.cs:line 181
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ML.ModelBuilder.AutoMLService.LocalDispatcher.<AddTrialAsync>d__16.MoveNext() in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/Dispatcher/LocalDispatcher.cs:line 49 (Microsoft.ML.ModelBuilder.Utils.Logger.Debug)
2023-08-05 13:45:43.0038 DEBUG update best config to trial id 0, current best metric is 0 (Microsoft.ML.ModelBuilder.Utils.Logger.Debug)
2023-08-05 13:45:43.0038 DEBUG create new thread 0 (Microsoft.ML.ModelBuilder.Utils.Logger.Debug)
2023-08-05 13:45:43.0298 INFO 
===============================================Experiment Results=================================================
------------------------------------------------------------------------------------------------------------------
|                                                     Summary                                                    |
------------------------------------------------------------------------------------------------------------------
|ML Task: ImageClassification                                                                                    |
|Dataset:                                                                                                        |
|Label : Label                                                                                                   |
|Total experiment time : 0,00 Secs                                                                               |
|Total number of models explored: 0                                                                              |
------------------------------------------------------------------------------------------------------------------
 (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2023-08-05 13:45:43.0298 INFO |                                              Top 0 models explored                                             |
------------------------------------------------------------------------------------------------------------------
|     Trainer                              MicroAccuracy  MacroAccuracy  Duration #Iteration                     |
------------------------------------------------------------------------------------------------------------------
 (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2023-08-05 13:45:43.0738 DEBUG filePath cannot be null or empty
Parameter name: filePath
   at Microsoft.ML.Runtime.Contracts.CheckNonEmpty(IExceptionContext ctx, String s, String paramName)
   at Microsoft.ML.ModelOperationsCatalog.Load(String filePath, DataViewSchema& inputSchema)
   at Microsoft.ML.ModelBuilder.AutoMLService.Experiments.LocalAutoMLExperiment.<ExecuteAsync>d__15.MoveNext() in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/Experiments/LocalAutoMLExperiment.cs:line 231
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ML.ModelBuilder.AutoMLEngine.<StartTrainingAsync>d__21.MoveNext() in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/AutoMLEngineService/AutoMLEngine.cs:line 160 (Microsoft.ML.ModelBuilder.Utils.Logger.Debug)
2023-08-05 13:45:55.0212 INFO start nni training (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2023-08-05 13:45:55.0212 INFO Experiment output folder: C:\Users\Eris\AppData\Local\Temp\AutoML-NNI\Experiment-S8O0R2 (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2023-08-05 13:45:55.0212 DEBUG row count is unknown, count it explicitly (Microsoft.ML.ModelBuilder.Utils.Logger.Debug)
2023-08-05 13:45:55.0212 DEBUG count elapse 0ms (Microsoft.ML.ModelBuilder.Utils.Logger.Debug)
2023-08-05 13:45:55.0212 INFO |     Trainer                              MicroAccuracy  MacroAccuracy  Duration #Iteration                     | (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2023-08-05 13:45:55.0402 DEBUG update train dataset C:\Users\Eris\AppData\Local\Temp\AutoML-NNI\Experiment-S8O0R2\train.bin (Microsoft.ML.ModelBuilder.Utils.Logger.Debug)
2023-08-05 13:45:55.0402 DEBUG update test dataset C:\Users\Eris\AppData\Local\Temp\AutoML-NNI\Experiment-S8O0R2\test.bin (Microsoft.ML.ModelBuilder.Utils.Logger.Debug)
2023-08-05 13:45:55.0472 INFO Trial 0 encounter error with message: Only one class found in the Label column. To build a multiclass classification model, the number of classes needs to be 2 or greater
Parameter name: labelCount (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2023-08-05 13:45:55.0472 DEBUG    at Microsoft.ML.Vision.ImageClassificationTrainer.InitializeTrainingGraph(IDataView input)
   at Microsoft.ML.Vision.ImageClassificationTrainer.TrainModelCore(TrainContext trainContext)
   at Microsoft.ML.Trainers.TrainerEstimatorBase`2.TrainTransformer(IDataView trainSet, IDataView validationSet, IPredictor initPredictor)
   at Microsoft.ML.Data.EstimatorChain`1.Fit(IDataView input)
   at Microsoft.ML.ModelBuilder.AutoMLService.MulticlassClassificationRunner.RunTrainTestSplit(TrialParameter parameter, TrainingConfiguration config, IDataView trainDatasetCache, IDataView testDatasetCache) in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/Runner/MulticlassClassificationRunner.cs:line 70
   at Microsoft.ML.ModelBuilder.AutoMLService.LocalDispatcher.Run() in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/Dispatcher/LocalDispatcher.cs:line 172
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ML.ModelBuilder.AutoMLService.LocalDispatcher.<RunAsync>d__19.MoveNext() in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/Dispatcher/LocalDispatcher.cs:line 181
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ML.ModelBuilder.AutoMLService.LocalDispatcher.<AddTrialAsync>d__16.MoveNext() in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/Dispatcher/LocalDispatcher.cs:line 49 (Microsoft.ML.ModelBuilder.Utils.Logger.Debug)
2023-08-05 13:45:55.0472 DEBUG update best config to trial id 0, current best metric is 0 (Microsoft.ML.ModelBuilder.Utils.Logger.Debug)
2023-08-05 13:45:55.0472 DEBUG create new thread 0 (Microsoft.ML.ModelBuilder.Utils.Logger.Debug)
2023-08-05 13:45:55.0472 INFO 
===============================================Experiment Results=================================================
------------------------------------------------------------------------------------------------------------------
|                                                     Summary                                                    |
------------------------------------------------------------------------------------------------------------------
|ML Task: ImageClassification                                                                                    |
|Dataset:                                                                                                        |
|Label : Label                                                                                                   |
|Total experiment time : 0,00 Secs                                                                               |
|Total number of models explored: 0                                                                              |
------------------------------------------------------------------------------------------------------------------
 (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2023-08-05 13:45:55.0472 INFO |                                              Top 0 models explored                                             |
------------------------------------------------------------------------------------------------------------------
|     Trainer                              MicroAccuracy  MacroAccuracy  Duration #Iteration                     |
------------------------------------------------------------------------------------------------------------------
 (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2023-08-05 13:45:55.0702 DEBUG filePath cannot be null or empty
Parameter name: filePath
   at Microsoft.ML.Runtime.Contracts.CheckNonEmpty(IExceptionContext ctx, String s, String paramName)
   at Microsoft.ML.ModelOperationsCatalog.Load(String filePath, DataViewSchema& inputSchema)
   at Microsoft.ML.ModelBuilder.AutoMLService.Experiments.LocalAutoMLExperiment.<ExecuteAsync>d__15.MoveNext() in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/Experiments/LocalAutoMLExperiment.cs:line 231
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ML.ModelBuilder.AutoMLEngine.<StartTrainingAsync>d__21.MoveNext() in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/AutoMLEngineService/AutoMLEngine.cs:line 160 (Microsoft.ML.ModelBuilder.Utils.Logger.Debug)
2023-08-05 13:46:44.7770 INFO start nni training (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2023-08-05 13:46:44.8360 INFO Experiment output folder: C:\Users\Eris\AppData\Local\Temp\AutoML-NNI\Experiment-FZWKAD (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2023-08-05 13:46:44.8360 DEBUG row count is unknown, count it explicitly (Microsoft.ML.ModelBuilder.Utils.Logger.Debug)
2023-08-05 13:46:44.8360 DEBUG count elapse 0ms (Microsoft.ML.ModelBuilder.Utils.Logger.Debug)
2023-08-05 13:46:44.8470 INFO |     Trainer                              MicroAccuracy  MacroAccuracy  Duration #Iteration                     | (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2023-08-05 13:46:45.4120 DEBUG update train dataset C:\Users\Eris\AppData\Local\Temp\AutoML-NNI\Experiment-FZWKAD\train.bin (Microsoft.ML.ModelBuilder.Utils.Logger.Debug)
2023-08-05 13:46:45.4250 DEBUG update test dataset C:\Users\Eris\AppData\Local\Temp\AutoML-NNI\Experiment-FZWKAD\test.bin (Microsoft.ML.ModelBuilder.Utils.Logger.Debug)
2023-08-05 13:46:45.8800 INFO Trial 0 encounter error with message: Only one class found in the Label column. To build a multiclass classification model, the number of classes needs to be 2 or greater
Parameter name: labelCount (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2023-08-05 13:46:45.9600 DEBUG    at Microsoft.ML.Vision.ImageClassificationTrainer.InitializeTrainingGraph(IDataView input)
   at Microsoft.ML.Vision.ImageClassificationTrainer.TrainModelCore(TrainContext trainContext)
   at Microsoft.ML.Trainers.TrainerEstimatorBase`2.TrainTransformer(IDataView trainSet, IDataView validationSet, IPredictor initPredictor)
   at Microsoft.ML.Data.EstimatorChain`1.Fit(IDataView input)
   at Microsoft.ML.ModelBuilder.AutoMLService.MulticlassClassificationRunner.RunTrainTestSplit(TrialParameter parameter, TrainingConfiguration config, IDataView trainDatasetCache, IDataView testDatasetCache) in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/Runner/MulticlassClassificationRunner.cs:line 70
   at Microsoft.ML.ModelBuilder.AutoMLService.LocalDispatcher.Run() in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/Dispatcher/LocalDispatcher.cs:line 172
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
![Capture](https://github.com/dotnet/machinelearning-modelbuilder/assets/87287001/318dc76d-6f78-4464-9ab3-3f5f288607ea)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ML.ModelBuilder.AutoMLService.LocalDispatcher.<RunAsync>d__19.MoveNext() in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/Dispatcher/LocalDispatcher.cs:line 181
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ML.ModelBuilder.AutoMLService.LocalDispatcher.<AddTrialAsync>d__16.MoveNext() in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/Dispatcher/LocalDispatcher.cs:line 49 (Microsoft.ML.ModelBuilder.Utils.Logger.Debug)
2023-08-05 13:46:45.9600 DEBUG update best config to trial id 0, current best metric is 0 (Microsoft.ML.ModelBuilder.Utils.Logger.Debug)
2023-08-05 13:46:45.9600 DEBUG create new thread 0 (Microsoft.ML.ModelBuilder.Utils.Logger.Debug)
2023-08-05 13:46:45.9860 INFO 
===============================================Experiment Results=================================================
------------------------------------------------------------------------------------------------------------------
|                                                     Summary                                                    |
------------------------------------------------------------------------------------------------------------------
|ML Task: ImageClassification                                                                                    |
|Dataset:                                                                                                        |
|Label : Label                                                                                                   |
|Total experiment time : 0,00 Secs                                                                               |
|Total number of models explored: 0                                                                              |
------------------------------------------------------------------------------------------------------------------
 (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2023-08-05 13:46:45.9860 INFO |                                              Top 0 models explored                                             |
------------------------------------------------------------------------------------------------------------------
|     Trainer                              MicroAccuracy  MacroAccuracy  Duration #Iteration                     |
------------------------------------------------------------------------------------------------------------------
 (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2023-08-05 13:46:46.0170 DEBUG filePath cannot be null or empty
Parameter name: filePath
   at Microsoft.ML.Runtime.Contracts.CheckNonEmpty(IExceptionContext ctx, String s, String paramName)
   at Microsoft.ML.ModelOperationsCatalog.Load(String filePath, DataViewSchema& inputSchema)
   at Microsoft.ML.ModelBuilder.AutoMLService.Experiments.LocalAutoMLExperiment.<ExecuteAsync>d__15.MoveNext() in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/Experiments/LocalAutoMLExperiment.cs:line 231
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ML.ModelBuilder.AutoMLEngine.<StartTrainingAsync>d__21.MoveNext() in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/AutoMLEngineService/AutoMLEngine.cs:line 160 (Microsoft.ML.ModelBuilder.Utils.Logger.Debug)

**Comment by LittleLittleCloud** [comment]
From the stacktrace, it seems that you are using an out-dated version of model builder? Would you update model buiilder to latest version and try again

**Comment by LittleLittleCloud** [comment]
close due to no respond, feel free to reopen it if you have any issues
