### ISSUE TITLE
Categorical prediction handled as non-catagorical.

### ISSUE THREAD

**Issue by Elantonio** [dotnet/machinelearning-modelbuilder#2763]
Scenario Value Prediction

Data with a categorical  column2predict (values -1,0,1)

Evaluate gives prediction -0.01 !?!?
![image](https://github.com/dotnet/machinelearning-modelbuilder/assets/7442635/657d805f-d0a2-4ec6-8f1c-093f6436fbbf)

Prediction should be -1, 0 or 1!

**Comment by LittleLittleCloud** [comment]
Can you try "Data Classification" scenario? You are playing with Regression model and that's why you get a numeric result

**Comment by Elantonio** [comment]
> Can you try "Data Classification" scenario? You are playing with Regression model and that's why you get a numeric result

As it is possible to mark the Label column as Categorical I assumed it had some use.
So I marked the Label column as categorical, assuming it would then only choose from the 3 available values(taking the closest one to the regression result).
I could round it and get the Category that way.
But then what is the use of being able to mark the Label column as Categorical?

**Comment by LittleLittleCloud** [comment]
Sorry, Maybe I didn't make myself clear... What I mean is you can choose the `Data Classification` card on the first `Scenario` tab (see below picture). Based on the screenshot you share with us, it looks like you pick the `value prediction` card, which uses regression model to fit a numeric label and that's why you are getting non-catagorical prediction value

![image](https://github.com/dotnet/machinelearning-modelbuilder/assets/16876986/ebbdfe4a-156f-4f5d-92ec-c7dc9478e424)

**Comment by Elantonio** [comment]
Hi,

 

You said it very clear.
The point I was making is that, in my logic, in regression a value marked as categorical and having only 3 values should be predicted as categorical, thus one of the 3 values. (Taking the available values in the train set as being the categories).
Otherwise there is no use/effect in declaring the predict column as category.
And is it is of no use/effect it should not be possible to set the predict column as category.

Thanks for your effort and thinking with me!

 

Best Rgds, Ton

**Comment by Elantonio** [comment]
Sorry to bother you but do you know where i can report a bug?

BUG:
at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)   at System.Threading.Tasks.Task`1.get_Result()   at Microsoft.ML.AutoML.AutoMLExperiment.Run()   at Microsoft.ML.AutoML.RegressionExperiment.Execute(IDataView trainData, ColumnInformation columnInformation, IEstimator`1 preFeaturizer, IProgress`1 progressHandler)   at Microsoft.ML.AutoML.RegressionExperiment.Execute(IDataView trainData, String labelColumnName, String samplingKeyColumn, IEstimator`1 preFeaturizer, IProgress`1 progressHandler)   at cAlgo.Predictor.<>c__DisplayClass12_0.<TrainAsync>b__1() in C:\Users\Ton\Documents\MLPredict\MLPredict\Predictor.cs:line 94   at System.Threading.Tasks.Task`1.InnerInvoke()   at System.Threading.Tasks.Task.<>c.<.cctor>b__271_0(Object obj)   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)

 

Source:

public async Task TrainAsync(  )

        {

            IsTrained = false;

            // Extract header row

            try

            {

                var FileSizeMB = (double)(new FileInfo(TrainData.DataPath).Length) / 1024 / 1024;

                var TrainTimeInSeconds =(uint) Math.Min(10,( FileSizeMB *FileSizeMB * TrainTimeFactor / 100*60).RoundUp(0));

 

                ColumnInferenceResults columnInference =

                       MyContext.Auto().InferColumns(TrainData.DataPath, labelColumnName: LabelName, groupColumns: false);

 

                foreach (var name in TrainData.CategoricalColumnNames)

                {

                    columnInference.ColumnInformation.NumericColumnNames.Remove(name);

                   columnInference.ColumnInformation.CategoricalColumnNames.Add(name);

                }

                // Create IDataView from data

                TextLoader loader = MyContext.Data.CreateTextLoader(columnInference.TextLoaderOptions);

               IDataView DataView = loader.Load(TrainData.DataPath);

                DataView = MyContext.Data.ShuffleRows(DataView);

 

                // Define experiment settings

                var experimentSettings = new RegressionExperimentSettings

               {

                    MaxExperimentTimeInSeconds = TrainTimeInSeconds,

                    OptimizingMetric = RegressionMetric.RSquared,

                    CacheBeforeTrainer = CacheBeforeTrainer.Auto

                };

 

                // Create experiment

                var experiment = MyContext.Auto().CreateRegressionExperiment(experimentSettings);

                var progressHandler = new Progress<RunDetail<RegressionMetrics>>(p =>

                {

                    DebugWrite($"Current result - TrainerName: {p.TrainerName}, RuntimeInSeconds: {p.RuntimeInSeconds}, ValidationMetrics: {p.ValidationMetrics}");

                });

                // Run experiment

(ERRORLINE 94)  var result = Task.Run(() => experiment.Execute(DataView, labelColumnName: LabelName, progressHandler: progressHandler));

 

                // Get best model

                var model = result.Result.BestRun.Model;

                RSquared = result.Result.BestRun.ValidationMetrics.RSquared;

 

                // Create prediction engine

                PredictionEngine = MyContext.Model.CreatePredictionEngine<dynamic, ModelOutput>(model);

                IsTrained = true;

            }

            catch (Exception ex) { System.Diagnostics.Debug.WriteLine(ex.Message + " " + ex.StackTrace.ToString()); }

 

        }

**Comment by LittleLittleCloud** [comment]
You can report it here. What's the exception message you get? Is that something related to non-numeric label value for regression trainers?

**Comment by Elantonio** [comment]
No it is not related to non-numeric label value for regression trainers; that I would not have perceived as a bug.

Sorry i forgot to mention the exception that (stupid)
Here it is:
NullReferenceException: Object reference not set to an instance of an object.



Best rgds,
Ton

**Comment by LittleLittleCloud** [comment]
That bug sounds so familiar to me. Could it be similar to this issue?
https://github.com/dotnet/machinelearning/issues/6558

**Comment by Elantonio** [comment]
There are similarities  

In my also running the experiment from the modelbuilder on csv works OK

 

There are differences 

I’m running
  ML 2.0.1
  and AutoML 0.20.1


But nevertheless I tried the fix (specifying TrainSet & TestSet)

and now …….

IT WORKS !!

Thanks a very big lot!
although it stays a bug ;-)

Best rgds,

Ton

**Comment by LittleLittleCloud** [comment]
Cool, glad to see you figure this out!

**Comment by Elantonio** [comment]
Hi Xiaoyun,

 

I was glad it worked too, but a little later it went haywire again!

System.NullReferenceException

  HResult=0x80004003

  Message=Object reference not set to an instance of an object.

  Source=Microsoft.ML.AutoML

  StackTrace:

   at Microsoft.ML.AutoML.SweepablePipeline..ctor(Dictionary`2 estimators, Entity schema, String currentSchema)

   at Microsoft.ML.AutoML.SweepablePipeline.AppendEntity(Boolean allowSkip, Entity entity)

   at Microsoft.ML.AutoML.RegressionExperiment.CreateRegressionPipeline(IDataView trainData, ColumnInformation columnInformation, IEstimator`1 preFeaturizer)

   at Microsoft.ML.AutoML.RegressionExperiment.Execute(IDataView trainData, IDataView validationData, ColumnInformation columnInformation, IEstimator`1 preFeaturizer, IProgress`1 progressHandler)

   at Microsoft.ML.AutoML.RegressionExperiment.Execute(IDataView trainData, IDataView validationData, String labelColumnName, IEstimator`1 preFeaturizer, IProgress`1 progressHandler)

   at cAlgo.Predictor.<Train2Async>d__16.MoveNext() in C:\Users\Ton\Documents\Sources\MLPredict\MLPredict\Predictor.cs:line 175



on the following code:



       public async Task<(double Rsquared, bool IsTrained, PredictionEngine<ExpandoObject, ModelOutput> PredictionEngine)> Train2Async()

        {

            try

            {   // Extract header row

                var FileSizeMB = (double)(new FileInfo(TrainData.DataPath).Length) / 1024 / 1024;

                var TrainTimeInSeconds = (uint)Math.Max(10, Math.Sqrt(FileSizeMB) * TrainTimeFactor * 100).RoundUp(0);

 

                var MyContext = new MLContext();

                ColumnInferenceResults columnInference =

                       MyContext.Auto().InferColumns(TrainData.DataPath, labelColumnName: LabelName, groupColumns: false);

 

                foreach (var name in TrainData.CategoricalColumnNames)

                {

                    columnInference.ColumnInformation.NumericColumnNames.Remove(name);

                    columnInference.ColumnInformation.CategoricalColumnNames.Add(name);

                }

 

                // Load data

                var data = MakeExpando();

 

                // Convert data to IDataView

                var dataView = MyContext.Data.LoadFromEnumerable(data);

 

                // Split data into training and test sets

                var trainTestSplit = MyContext.Data.TrainTestSplit(dataView);

 

                // Define experiment settings

                var experimentSettings = new RegressionExperimentSettings

                {

                    MaxExperimentTimeInSeconds = 60,

                    OptimizingMetric = RegressionMetric.RSquared,

                    CacheBeforeTrainer = CacheBeforeTrainer.Auto

                };

 

                // Create experiment

                var experiment = MyContext.Auto().CreateRegressionExperiment(experimentSettings);

 

                // Run experiment

ERRORLINE=>    var result = experiment.Execute(trainTestSplit.TrainSet, trainTestSplit.TestSet);

 

                // Get best model

                var model = result.BestRun.Model;

                //

                RSquared = result.BestRun.ValidationMetrics.RSquared;//.result.Result.BestRun.ValidationMetrics.RSquared;

 

                // Get feature importance

                var featureImportance = MyContext.Regression.PermutationFeatureImportance(model, trainTestSplit.TestSet);

                var featureImportanceValues = featureImportance.Select(x => x.Value.RSquared.Mean).ToArray();

                var featureNames = data.First().Select(x => x.Key).ToArray();

 

                // Print feature importance

                for (int i = 0; i < featureNames.Length; i++)

                {

                    Console.WriteLine($"{featureNames[i]}: {featureImportanceValues[i]:0.00}");

                }

 

                // Create prediction engine

                var predictionEngine = MyContext.Model.CreatePredictionEngine<ExpandoObject, ModelOutput>(model);

 

                return (RSquared, IsTrained, PredictionEngine);

            }

            catch (Exception ex) { Lib.LogPrint(ThisRobot, ex.Message + " " + ex.StackTrace.ToString()); }

            return (double.NaN, false, null);

        }

        List<ExpandoObject> MakeExpando()

        {

            var data = new List<ExpandoObject>();

 

            // Read header row

            var header = TrainData.HeaderCollection;

 

            // Read data rows

            foreach (var row in TrainData.Rows)

            {

                var line = row.ToArray();

                dynamic dataPoint = new ExpandoObject();

                for (int i = 0; i < header.Length; i++)

                {

                    ((IDictionary<string, object>)dataPoint)[header[i]] = (float)line[i];

                }

                data.Add(dataPoint);

            }

            return data;

        }



What am I doing Wrong here?
I just want to do an AutoML run on a dataset that has no defined columns at instantiation.

Only after loading the csv the columns and their header are known (similar to mbconfig)

Best Rgds,

Ton

**Comment by LittleLittleCloud** [comment]
@Elantonio Would you still get the error if you remove the following lines?
```
                foreach (var name in TrainData.CategoricalColumnNames)

                {

                    columnInference.ColumnInformation.NumericColumnNames.Remove(name);

                    columnInference.ColumnInformation.CategoricalColumnNames.Add(name);

                }
```

**Comment by Elantonio** [comment]
Hi Xiaoyun,



Sorry no avail, error is still the same
System.NullReferenceException

  HResult=0x80004003

  Message=Object reference not set to an instance of an object.

  Source=Microsoft.ML.AutoML

  StackTrace:

   at Microsoft.ML.AutoML.SweepablePipeline..ctor(Dictionary`2 estimators, Entity schema, String currentSchema)

   at Microsoft.ML.AutoML.SweepablePipeline.AppendEntity(Boolean allowSkip, Entity entity)

   at Microsoft.ML.AutoML.RegressionExperiment.CreateRegressionPipeline(IDataView trainData, ColumnInformation columnInformation, IEstimator`1 preFeaturizer)

   at Microsoft.ML.AutoML.RegressionExperiment.Execute(IDataView trainData, IDataView validationData, ColumnInformation columnInformation, IEstimator`1 preFeaturizer, IProgress`1 progressHandler)

   at Microsoft.ML.AutoML.RegressionExperiment.Execute(IDataView trainData, IDataView validationData, String labelColumnName, IEstimator`1 preFeaturizer, IProgress`1 progressHandler)

 

 

Best rgds,
Ton.

 

PS I feel I’m missing a clue on how to train dynamic input and reusing its predictionengine and having columnimportance info.
do you know of a sample where this has been done before?
