### ISSUE TITLE
Model Builder - Object Detection (Local) The system cannot find the file specified

### ISSUE THREAD

**Issue by Jayz816** [dotnet/machinelearning-modelbuilder#2767]
**System Information (please complete the following information):**
 - Model Builder Version 2022 (17.17.0.2332602)
 - Visual Studio 2022

**Describe the bug**
- On which step of the process did you run into an issue:
- Clear description of the problem:

**To Reproduce**
1. Complete the Labelling with VOTT
2. Create Console Project
3. Right click "project name" at explorer inside VS2002 -> Add -> Machine Model Learning
4. Create a new filename detection.mbconfig
5. Select "Object Detection (local) in Scenario
6. Select "Local (CPU)" since my laptop doesn't have a good GPU (Click Next Step)
7. Select the Json file exported from VOTT, data preview without any issue. (Click Next Step)
8. At the Train page, click "Start Training" 
9. Error produce, with "The system cannot find the file specified"

**Expected behavior**
Was followed the step from the internet, but ended up with the errors.

**Screenshots**
![image](https://github.com/dotnet/machinelearning-modelbuilder/assets/99977997/faf376c5-a08c-495b-83d6-8acfd54ae929)

**Additional context**
(File logs as below): 
2023-09-11 00:43:45.7794 DEBUG update TrainViewModel_12.RemainingSeconds (Microsoft.ML.ModelBuilder.Utils.Logger.Debug)
2023-09-11 00:43:45.7794 DEBUG update TrainViewModel_12.RemainingTime (Microsoft.ML.ModelBuilder.Utils.Logger.Debug)
2023-09-11 00:43:46.7950 DEBUG update TrainViewModel_12.RemainingSeconds (Microsoft.ML.ModelBuilder.Utils.Logger.Debug)
2023-09-11 00:43:46.7950 DEBUG update TrainViewModel_12.RemainingTime (Microsoft.ML.ModelBuilder.Utils.Logger.Debug)
2023-09-11 00:43:47.7964 DEBUG update TrainViewModel_12.RemainingSeconds (Microsoft.ML.ModelBuilder.Utils.Logger.Debug)
2023-09-11 00:43:47.7964 DEBUG update TrainViewModel_12.RemainingTime (Microsoft.ML.ModelBuilder.Utils.Logger.Debug)
2023-09-11 00:43:49.2248 DEBUG update TrainViewModel_12.ModelsExploredCount (Microsoft.ML.ModelBuilder.Utils.Logger.Debug)
2023-09-11 00:43:49.2248 DEBUG update TrainViewModel_12.RemoteRunStatusUrl (Microsoft.ML.ModelBuilder.Utils.Logger.Debug)
2023-09-11 00:43:49.2248 DEBUG update TrainViewModel_12.BestTrainer (Microsoft.ML.ModelBuilder.Utils.Logger.Debug)
2023-09-11 00:43:49.2248 DEBUG update TrainViewModel_12.TrainStatus (Microsoft.ML.ModelBuilder.Utils.Logger.Debug)
2023-09-11 00:43:49.2248 DEBUG update TrainViewModel_12.IsResetTrainingEnabled (Microsoft.ML.ModelBuilder.Utils.Logger.Debug)
2023-09-11 00:43:49.2248 DEBUG update TrainViewModel_12.RemainingTime (Microsoft.ML.ModelBuilder.Utils.Logger.Debug)
2023-09-11 00:43:49.2248 DEBUG update TrainViewModel_12.ExplorationTime (Microsoft.ML.ModelBuilder.Utils.Logger.Debug)
2023-09-11 00:43:49.2248 DEBUG update TrainViewModel_12.ExplorationTimeLabel (Microsoft.ML.ModelBuilder.Utils.Logger.Debug)
2023-09-11 00:43:49.2248 DEBUG update TrainViewModel_12.IsResetTrainingEnabled (Microsoft.ML.ModelBuilder.Utils.Logger.Debug)
2023-09-11 00:43:49.2248 DEBUG update TrainViewModel_12.HasFinishedTraining (Microsoft.ML.ModelBuilder.Utils.Logger.Debug)
2023-09-11 00:43:49.2248 DEBUG update TrainViewModel_12.IsTrainingOptionEnabled (Microsoft.ML.ModelBuilder.Utils.Logger.Debug)
2023-09-11 00:43:49.2248 DEBUG update TrainViewModel_12.TrainButtonLabel (Microsoft.ML.ModelBuilder.Utils.Logger.Debug)
2023-09-11 00:43:49.2248 DEBUG update TrainViewModel_12.IsTrainingButtonEnabled (Microsoft.ML.ModelBuilder.Utils.Logger.Debug)
2023-09-11 00:43:49.2308 DEBUG update TrainViewModel_12.TrainButtonLabel (Microsoft.ML.ModelBuilder.Utils.Logger.Debug)
2023-09-11 00:43:49.2308 DEBUG update TrainViewModel_12.RemainingTime (Microsoft.ML.ModelBuilder.Utils.Logger.Debug)
2023-09-11 00:43:49.2308 DEBUG update TrainViewModel_12.IsTraining (Microsoft.ML.ModelBuilder.Utils.Logger.Debug)
2023-09-11 00:43:49.2308 DEBUG update TrainViewModel_12.IsCompleted (Microsoft.ML.ModelBuilder.Utils.Logger.Debug)
2023-09-11 00:43:49.2308 DEBUG update ModelBuilderDataContext_0.CreateConsumeTabViewModelAsync (Microsoft.ML.ModelBuilder.Utils.Logger.Debug)
2023-09-11 00:43:49.2308 DEBUG update ModelBuilderDataContext_0.CreateEvaluateTabViewModelAsync (Microsoft.ML.ModelBuilder.Utils.Logger.Debug)
2023-09-11 00:43:49.2308 DEBUG update ModelBuilderDataContext_0.GetCompletedTabAsync (Microsoft.ML.ModelBuilder.Utils.Logger.Debug)
2023-09-11 00:43:49.2308 DEBUG update TrainViewModel_12.TrainingDidNotSucceed (Microsoft.ML.ModelBuilder.Utils.Logger.Debug)
2023-09-11 00:43:49.2632 DEBUG update TrainViewModel_12.RemainingSeconds (Microsoft.ML.ModelBuilder.Utils.Logger.Debug)
2023-09-11 00:43:49.2632 DEBUG update TrainViewModel_12.TrainStatus (Microsoft.ML.ModelBuilder.Utils.Logger.Debug)
2023-09-11 00:43:49.2632 DEBUG update TrainViewModel_12.IsResetTrainingEnabled (Microsoft.ML.ModelBuilder.Utils.Logger.Debug)
2023-09-11 00:43:49.2632 DEBUG update TrainViewModel_12.IsTrainingOptionEnabled (Microsoft.ML.ModelBuilder.Utils.Logger.Debug)
2023-09-11 00:43:49.2632 DEBUG update TrainViewModel_12.IsTrainingButtonEnabled (Microsoft.ML.ModelBuilder.Utils.Logger.Debug)
2023-09-11 00:43:49.2632 DEBUG update TrainViewModel_12.TrainButtonLabel (Microsoft.ML.ModelBuilder.Utils.Logger.Debug)
2023-09-11 00:43:49.2632 DEBUG update TrainViewModel_12.RemainingTime (Microsoft.ML.ModelBuilder.Utils.Logger.Debug)
2023-09-11 00:43:49.2632 DEBUG update TrainViewModel_12.RemainingTime (Microsoft.ML.ModelBuilder.Utils.Logger.Debug)
2023-09-11 00:43:49.2632 DEBUG update TrainViewModel_12.IsTraining (Microsoft.ML.ModelBuilder.Utils.Logger.Debug)
2023-09-11 00:43:49.2632 DEBUG update TrainViewModel_12.IsCompleted (Microsoft.ML.ModelBuilder.Utils.Logger.Debug)
2023-09-11 00:43:49.2632 DEBUG update ModelBuilderDataContext_0.CreateConsumeTabViewModelAsync (Microsoft.ML.ModelBuilder.Utils.Logger.Debug)
2023-09-11 00:43:49.2632 DEBUG update ModelBuilderDataContext_0.CreateEvaluateTabViewModelAsync (Microsoft.ML.ModelBuilder.Utils.Logger.Debug)
2023-09-11 00:43:49.2632 DEBUG update ModelBuilderDataContext_0.GetCompletedTabAsync (Microsoft.ML.ModelBuilder.Utils.Logger.Debug)
2023-09-11 00:43:49.2632 DEBUG update TrainViewModel_12.TrainingDidNotSucceed (Microsoft.ML.ModelBuilder.Utils.Logger.Debug)
2023-09-11 00:43:49.2802 INFO start Object detection  (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2023-09-11 00:43:49.2802 DEBUG env:path: C:\Users\username\AppData\Local\Temp\ModelBuilder\torchsharp-cpu-0.99.5;;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.2;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.2\bin;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.2\include;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.2\x64;C:\opencv\build\include;C:\opencv\build\x64\vc14\bin;C:\opencv\build\x64\vc14\lib;C:\opencv\build\x64\vc15\bin;C:\opencv\build\x64\vc15\lib;C:\opencv\build\bin;C:\Program Files\nodejs;C:\Users\username\AppData\Local\Microsoft\WindowsApps;C:\Users\username\.dotnet\tools;C:\Program Files\Azure Data Studio\bin;C:\Users\username\AppData\Local\Programs\Microsoft VS Code\bin;C:\Users\username\AppData\Local\Pandoc\;C:\Users\username\AppData\Roaming\npm;C:\Program Files\nodejs; (Microsoft.ML.ModelBuilder.Utils.Logger.Debug)
2023-09-11 00:43:49.2802 DEBUG C:\Users\username\AppData\Local\Temp\ModelBuilder\torchsharp-cpu-0.99.5\obj (Microsoft.ML.ModelBuilder.Utils.Logger.Debug)
2023-09-11 00:43:49.2802 INFO restore "c:\program files\microsoft visual studio\2022\community\common7\ide\extensions\aeowiwmr.5oo\AutoMLService\RuntimeManager\torchsharp.cpu.csproj" --configfile "c:\program files\microsoft visual studio\2022\community\common7\ide\extensions\aeowiwmr.5oo\AutoMLService\RuntimeManager\NuGet.config" -r win-x64 /p:UsingToolXliff=false /p:TorchSharpVersion=0.99.5 /p:TorchSharpCudaRuntimeVersion=1.13.0.1 /p:TensorflowRuntimeVersion=2.3.1 /p:BaseIntermediateOutputPath="C:\Users\username\AppData\Local\Temp\ModelBuilder\torchsharp-cpu-0.99.5\obj" (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2023-09-11 00:43:49.2802 INFO publish "c:\program files\microsoft visual studio\2022\community\common7\ide\extensions\aeowiwmr.5oo\AutoMLService\RuntimeManager\torchsharp.cpu.csproj" -r win-x64 -c Release --no-self-contained -o "C:\Users\username\AppData\Local\Temp\ModelBuilder\torchsharp-cpu-0.99.5" --no-restore /p:UsingToolXliff=false /p:TorchSharpVersion=0.99.5 /p:TorchSharpCudaRuntimeVersion=1.13.0.1 /p:TensorflowRuntimeVersion=2.3.1 /p:BaseOutputPath="C:\Users\username\AppData\Local\Temp\ModelBuilder\torchsharp-cpu-0.99.5\bin\\" /p:BaseIntermediateOutputPath="C:\Users\username\AppData\Local\Temp\ModelBuilder\torchsharp-cpu-0.99.5\obj\\" (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2023-09-11 00:43:49.2802 INFO start installing runtime in C:\Users\username\AppData\Local\Temp\ModelBuilder\torchsharp-cpu-0.99.5 (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2023-09-11 00:43:49.2988 DEBUG The system cannot find the file specified
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at Microsoft.ML.ModelBuilder.AutoMLService.RuntimeManager.InstallRuntimeAsync(CancellationToken ct) in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/RuntimeManager/RuntimeManager.cs:line 153
   at Microsoft.ML.ModelBuilder.AutoMLService.LocalObjectDetectionExperiment.<ExecuteAsync>d__13.MoveNext() in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/Experiments/LocalObjectDetectionExperiment.cs:line 51
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ML.ModelBuilder.AutoMLEngine.<StartTrainingAsync>d__21.MoveNext() in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/AutoMLEngineService/AutoMLEngine.cs:line 169 (Microsoft.ML.ModelBuilder.Utils.Logger.Debug)
2023-09-11 00:43:49.2988 DEBUG update TrainViewModel_12.TrainStatus (Microsoft.ML.ModelBuilder.Utils.Logger.Debug)
2023-09-11 00:43:49.2988 DEBUG update TrainViewModel_12.IsResetTrainingEnabled (Microsoft.ML.ModelBuilder.Utils.Logger.Debug)
2023-09-11 00:43:49.2988 DEBUG update TrainViewModel_12.IsTrainingOptionEnabled (Microsoft.ML.ModelBuilder.Utils.Logger.Debug)
2023-09-11 00:43:49.2988 DEBUG update TrainViewModel_12.IsTrainingButtonEnabled (Microsoft.ML.ModelBuilder.Utils.Logger.Debug)
2023-09-11 00:43:49.2988 DEBUG update TrainViewModel_12.TrainButtonLabel (Microsoft.ML.ModelBuilder.Utils.Logger.Debug)
2023-09-11 00:43:49.2988 DEBUG update TrainViewModel_12.RemainingTime (Microsoft.ML.ModelBuilder.Utils.Logger.Debug)
2023-09-11 00:43:49.2988 DEBUG update TrainViewModel_12.IsTraining (Microsoft.ML.ModelBuilder.Utils.Logger.Debug)
2023-09-11 00:43:49.2988 DEBUG update TrainViewModel_12.IsCompleted (Microsoft.ML.ModelBuilder.Utils.Logger.Debug)
2023-09-11 00:43:49.2988 DEBUG update ModelBuilderDataContext_0.CreateConsumeTabViewModelAsync (Microsoft.ML.ModelBuilder.Utils.Logger.Debug)
2023-09-11 00:43:49.2988 DEBUG update ModelBuilderDataContext_0.CreateEvaluateTabViewModelAsync (Microsoft.ML.ModelBuilder.Utils.Logger.Debug)
2023-09-11 00:43:49.2988 DEBUG update ModelBuilderDataContext_0.GetCompletedTabAsync (Microsoft.ML.ModelBuilder.Utils.Logger.Debug)
2023-09-11 00:43:49.2988 DEBUG update TrainViewModel_12.TrainingDidNotSucceed (Microsoft.ML.ModelBuilder.Utils.Logger.Debug)
2023-09-11 00:43:50.2639 DEBUG update TrainViewModel_12.RemainingSeconds (Microsoft.ML.ModelBuilder.Utils.Logger.Debug)
2023-09-11 00:43:50.2639 DEBUG update TrainViewModel_12.RemainingTime (Microsoft.ML.ModelBuilder.Utils.Logger.Debug)

**Comment by LittleLittleCloud** [comment]
Do you have `dotnet` installed on your system?

**Comment by Mushroomizer** [comment]
## I have the exact same issue, to a tee.

>The only difference is that I am not using a console app, but a WebApi Instead

```
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <InvariantGlobalization>true</InvariantGlobalization>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.4.0" />
  </ItemGroup>

</Project>
```

>Please see the output of dotnet --info

```dotnet --info
.NET SDK:
 Version:           8.0.100
 Commit:            57efcf1350
 Workload version:  8.0.100-manifests.8d38d0cc

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19045
 OS Platform: Windows
 RID:         win-x64
 Base Path:   C:\Program Files\dotnet\sdk\8.0.100\

.NET workloads installed:
 Workload version: 8.0.100-manifests.8d38d0cc
There are no installed workloads to display.

Host:
  Version:      8.0.0
  Architecture: x64
  Commit:       5535e31a71

.NET SDKs installed:
  3.1.417 [C:\Program Files\dotnet\sdk]
  5.0.406 [C:\Program Files\dotnet\sdk]
  6.0.101 [C:\Program Files\dotnet\sdk]
  8.0.100 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.23 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.22 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.23 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.14 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.15 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.23 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.14 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.15 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 8.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
  ```
  
  # Not sure what the issue could be, any pointers?

**Comment by NiLpzb** [comment]
有处理了吗？

**Comment by LittleLittleCloud** [comment]
@NiLpzb Did you also hit the same issue?

**Comment by NiLpzb** [comment]
> @NiLpzb您是否也遇到了同样的问题？

遇到  不知道怎么处理
![image](https://github.com/dotnet/machinelearning-modelbuilder/assets/89648234/c01eeefc-688c-4436-9dde-def64ebb9de0)
