### ISSUE TITLE
Model Builder Doesn't Work in New Version 17.17

### ISSUE THREAD

**Issue by aliajboy** [dotnet/machinelearning-modelbuilder#2776]
**System Information (please complete the following information):**
 - Working version that I test is 16.13.9.2235601 and New Version is 17.17.0.2332602 that Doesn't work
 - Visual Studio Version 17.7.4

**Describe the bug**
- On the training page, it won't train and always give me an error. I have tested this on 2 PCs and none of them worked. I have set the training time to 10- 60- 120- 150 and 300 but none of them can Train model. My model is the sample CSV that Microsoft put on it's Learning Tutorial. It has 1000 row of data. 

**Error Message**
"Training time finished without completing a successful trial. Either no trial completed or the metric for all completed trials are NaN or Infinity"
"at Microsoft.ML.AutoML.AutoMLExperiment.<RunAsync>d__24.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ML.ModelBuilder.AutoMLService.Experiments.MultiClassificationExperiment.<ExecuteAsync>d__14.MoveNext() in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/Experiments/MultiClassificationExperiment.cs:line 140
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ML.ModelBuilder.AutoMLEngine.<StartTrainingAsync>d__21.MoveNext() in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/AutoMLEngineService/AutoMLEngine.cs:line 169"

**Steps to reproduce the behavior:**
just do the Learning Tutorial of Microsoft at this link :
https://dotnet.microsoft.com/en-us/learn/ml-dotnet/get-started-tutorial/train

**Screenshots**
![image](https://github.com/dotnet/machinelearning-modelbuilder/assets/73298440/1c06336b-a003-40b6-9cef-a02f65098692)

**Additional context**
i5-11400
ddr4-16gb-3600mhz
RTX3060ti-8GB
NVME 512GB (3500MB/s)

**Comment by aliajboy** [comment]
I found the problem and it was col0 and col1 selection. It was opposite yesterday and even the image was col0 on microsoft website!
I put it on col1 and It fixed everything.
