### ISSUE TITLE
Training time finished without completing a successful trial. Either no trial completed or the metric for all completed trials are NaN or Infinity

### ISSUE THREAD

**Issue by ImTheSadra** [dotnet/machinelearning-modelbuilder#2777]
at Microsoft.ML.AutoML.AutoMLExperiment.<RunAsync>d__24.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ML.ModelBuilder.AutoMLService.Experiments.MultiClassificationExperiment.<ExecuteAsync>d__14.MoveNext() in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/Experiments/MultiClassificationExperiment.cs:line 140
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ML.ModelBuilder.AutoMLEngine.<StartTrainingAsync>d__21.MoveNext() in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/AutoMLEngineService/AutoMLEngine.cs:line 169
   
i have this error
im reading https://dotnet.microsoft.com/en-us/learn/ml-dotnet/get-started-tutorial/train
anyone can help me?
i hope i write currectly (im persion)

**Comment by jbliss12** [comment]
I am having this same issue.  I even set the training time to 240 seconds.

**Comment by LittleLittleCloud** [comment]
How large the dataset do you have.

**Comment by jbliss12** [comment]
It was very small.  Probably only 60 records.  I had to tell it which column to look at when I was doing the import and it worked nicely that time.

So, issue resolved.

Jim

**Comment by jbliss12** [comment]
By the way, you can close my ticket at this time.

Jim

**Comment by Manmansui** [comment]
Make sure the column to predict correctly chosen
