### ISSUE TITLE
ModelBuilder CLI fails to start image-classification training

### ISSUE THREAD

**Issue by DanielSe** [dotnet/machinelearning-modelbuilder#2781]
**System Information (please complete the following information):**
 - mlnet cli version 16.15.1+5cfa5322dc43fb36001cafd7c46e716141dfa219
 - mlnet-osx-x64 v16.15.1

**Describe the bug**
Starting image-classification tasks fails with System.NotImplementedException.

**To Reproduce**
`dotnet tool install --global mlnet-osx-x64`
`mlnet image-classification --dataset . --name "Test"`

**Expected behavior**
Training starts

**Screenshots**

**Additional context**
Output:
```
mlnet image-classification --dataset . --name "Test"
Start Training
System.NotImplementedException: The method or operation is not implemented.
   at Microsoft.ML.ModelBuilder.AutoMLService.Experiments.ExperimentFactory.CreateExperiment(MLContext context, ITrainingConfiguration config, AutoMLDependService services, PathConfiguration pathConfig) in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/Experiments/ExperimentFactory.cs:line 38
   at Microsoft.ML.ModelBuilder.AutoMLEngine.StartTrainingAsync(ITrainingConfiguration config, PathConfiguration pathConfig, CancellationToken userCancellationToken) in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/AutoMLEngineService/AutoMLEngine.cs:line 154
   at Microsoft.ML.CLI.Runners.AutoMLRunner.ExecuteAsync() in /_/src/mlnet/Runners/AutoMLRunner.cs:line 86
   at Microsoft.ML.CLI.Program.TrainAsync(ITrainingConfiguration trainingConfiguration, PathConfiguration pathConfig, AutoMLServiceLogLevel logLevel) in /_/src/mlnet/Program.cs:line 388
   at Microsoft.ML.CLI.Program.<>c.<<CreateRootCommandLineBuilder>b__4_3>d.MoveNext() in /_/src/mlnet/Program.cs:line 162
--- End of stack trace from previous location ---
   at System.CommandLine.Invocation.CommandHandler.GetExitCodeAsync(Object value, InvocationContext context)
   at System.CommandLine.Invocation.ModelBindingCommandHandler.InvokeAsync(InvocationContext context)
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass23_0.<<UseParseErrorReporting>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.ML.CLI.Program.<>c__DisplayClass4_0.<<CreateRootCommandLineBuilder>b__10>d.MoveNext() in /_/src/mlnet/Program.cs:line 325
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseSuggestDirective>b__24_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass22_0.<<UseParseDirective>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass11_0.<<UseDebugDirective>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<RegisterWithDotnetSuggest>b__10_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass14_0.<<UseExceptionHandler>b__0>d.MoveNext()
Check out log file for more information: /var/folders/bb/gsppf39j4_q85758jl2231km0000gn/T/mlnet/log.txt
Exiting ...
```

Log contents:
```
2023-10-27 13:09:18.9767 DEBUG Set log file path to /var/folders/bb/gsppf39j4_q85758jl2231km0000gn/T/mlnet/log.txt (Microsoft.ML.CLI.Commands.MLCommand.set_LogFilePath)
2023-10-27 13:09:19.0918 DEBUG Set log file path to /var/folders/bb/gsppf39j4_q85758jl2231km0000gn/T/mlnet/log.txt (Microsoft.ML.CLI.Commands.MLCommand.set_LogFilePath)
2023-10-27 13:09:19.0962 DEBUG Set log file path to /var/folders/bb/gsppf39j4_q85758jl2231km0000gn/T/mlnet/log.txt (Microsoft.ML.CLI.Commands.MLCommand.set_LogFilePath)
2023-10-27 13:09:19.0978 DEBUG Set log file path to /var/folders/bb/gsppf39j4_q85758jl2231km0000gn/T/mlnet/log.txt (Microsoft.ML.CLI.Commands.MLCommand.set_LogFilePath)
2023-10-27 13:09:19.1003 DEBUG Set log file path to /var/folders/bb/gsppf39j4_q85758jl2231km0000gn/T/mlnet/log.txt (Microsoft.ML.CLI.Commands.MLCommand.set_LogFilePath)
2023-10-27 13:09:19.1010 DEBUG Set log file path to /var/folders/bb/gsppf39j4_q85758jl2231km0000gn/T/mlnet/log.txt (Microsoft.ML.CLI.Commands.MLCommand.set_LogFilePath)
2023-10-27 13:09:19.1010 DEBUG Set log file path to /var/folders/bb/gsppf39j4_q85758jl2231km0000gn/T/mlnet/log.txt (Microsoft.ML.CLI.Commands.MLCommand.set_LogFilePath)
2023-10-27 13:09:19.1029 DEBUG Set log file path to /var/folders/bb/gsppf39j4_q85758jl2231km0000gn/T/mlnet/log.txt (Microsoft.ML.CLI.Commands.MLCommand.set_LogFilePath)
2023-10-27 13:09:19.1121 DEBUG System.FormatException: String ' available trainer: LGBM, RF, FASTTREE, LBFGS, SDCA ' was not recognized as a valid Boolean.
   at System.Boolean.Parse(ReadOnlySpan`1 value)
   at System.Boolean.Parse(String value)
   at Microsoft.ML.CLI.FeatureFlagManager.ReadFeatureFlags(String ffPath) in /_/src/mlnet/FeatureFlagManager.cs:line 69 (Microsoft.ML.CLI.FeatureFlagManager.ReadFeatureFlags)
2023-10-27 13:09:19.1731 DEBUG Set log file path to /var/folders/bb/gsppf39j4_q85758jl2231km0000gn/T/mlnet/log.txt (Microsoft.ML.CLI.Commands.MLCommand.set_LogFilePath)
2023-10-27 13:09:19.1778 DEBUG Set log level to Info (Microsoft.ML.CLI.Commands.MLCommand.set_Verbosity)
2023-10-27 13:09:19.2122 INFO Start Training (Microsoft.ML.CLI.Runners.AutoMLRunner+<ExecuteAsync>d__8.MoveNext)
2023-10-27 13:09:19.3087 ERROR System.NotImplementedException: The method or operation is not implemented.
   at Microsoft.ML.ModelBuilder.AutoMLService.Experiments.ExperimentFactory.CreateExperiment(MLContext context, ITrainingConfiguration config, AutoMLDependService services, PathConfiguration pathConfig) in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/Experiments/ExperimentFactory.cs:line 38
   at Microsoft.ML.ModelBuilder.AutoMLEngine.StartTrainingAsync(ITrainingConfiguration config, PathConfiguration pathConfig, CancellationToken userCancellationToken) in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/AutoMLEngineService/AutoMLEngine.cs:line 154
   at Microsoft.ML.CLI.Runners.AutoMLRunner.ExecuteAsync() in /_/src/mlnet/Runners/AutoMLRunner.cs:line 86
   at Microsoft.ML.CLI.Program.TrainAsync(ITrainingConfiguration trainingConfiguration, PathConfiguration pathConfig, AutoMLServiceLogLevel logLevel) in /_/src/mlnet/Program.cs:line 388
   at Microsoft.ML.CLI.Program.<>c.<<CreateRootCommandLineBuilder>b__4_3>d.MoveNext() in /_/src/mlnet/Program.cs:line 162
--- End of stack trace from previous location ---
   at System.CommandLine.Invocation.CommandHandler.GetExitCodeAsync(Object value, InvocationContext context)
   at System.CommandLine.Invocation.ModelBindingCommandHandler.InvokeAsync(InvocationContext context)
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass23_0.<<UseParseErrorReporting>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.ML.CLI.Program.<>c__DisplayClass4_0.<<CreateRootCommandLineBuilder>b__10>d.MoveNext() in /_/src/mlnet/Program.cs:line 325
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseSuggestDirective>b__24_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass22_0.<<UseParseDirective>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass11_0.<<UseDebugDirective>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<RegisterWithDotnetSuggest>b__10_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass14_0.<<UseExceptionHandler>b__0>d.MoveNext() (Microsoft.ML.CLI.Program+<>c__DisplayClass4_0.<CreateRootCommandLineBuilder>b__8)
2023-10-27 13:09:19.3116 DEBUG System.NotImplementedException: The method or operation is not implemented.
   at Microsoft.ML.ModelBuilder.AutoMLService.Experiments.ExperimentFactory.CreateExperiment(MLContext context, ITrainingConfiguration config, AutoMLDependService services, PathConfiguration pathConfig) in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/Experiments/ExperimentFactory.cs:line 38
   at Microsoft.ML.ModelBuilder.AutoMLEngine.StartTrainingAsync(ITrainingConfiguration config, PathConfiguration pathConfig, CancellationToken userCancellationToken) in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/AutoMLEngineService/AutoMLEngine.cs:line 154
   at Microsoft.ML.CLI.Runners.AutoMLRunner.ExecuteAsync() in /_/src/mlnet/Runners/AutoMLRunner.cs:line 86
   at Microsoft.ML.CLI.Program.TrainAsync(ITrainingConfiguration trainingConfiguration, PathConfiguration pathConfig, AutoMLServiceLogLevel logLevel) in /_/src/mlnet/Program.cs:line 388
   at Microsoft.ML.CLI.Program.<>c.<<CreateRootCommandLineBuilder>b__4_3>d.MoveNext() in /_/src/mlnet/Program.cs:line 162
--- End of stack trace from previous location ---
   at System.CommandLine.Invocation.CommandHandler.GetExitCodeAsync(Object value, InvocationContext context)
   at System.CommandLine.Invocation.ModelBindingCommandHandler.InvokeAsync(InvocationContext context)
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass23_0.<<UseParseErrorReporting>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.ML.CLI.Program.<>c__DisplayClass4_0.<<CreateRootCommandLineBuilder>b__10>d.MoveNext() in /_/src/mlnet/Program.cs:line 325
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseSuggestDirective>b__24_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass22_0.<<UseParseDirective>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass11_0.<<UseDebugDirective>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<RegisterWithDotnetSuggest>b__10_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass14_0.<<UseExceptionHandler>b__0>d.MoveNext() (Microsoft.ML.CLI.Program+<>c__DisplayClass4_0.<CreateRootCommandLineBuilder>b__8)
2023-10-27 13:09:19.3124 INFO Check out log file for more information: /var/folders/bb/gsppf39j4_q85758jl2231km0000gn/T/mlnet/log.txt (Microsoft.ML.CLI.Program+<>c__DisplayClass4_0.<CreateRootCommandLineBuilder>b__8)
2023-10-27 13:09:19.3124 INFO Exiting ... (Microsoft.ML.CLI.Program+<>c__DisplayClass4_0.<CreateRootCommandLineBuilder>b__8)
```

**Comment by zewditu** [comment]
@LittleLittleCloud could you take look?
Thanks.

**Comment by LittleLittleCloud** [comment]
#2679

**Comment by LittleLittleCloud** [comment]
@DanielSe this issue should be resolved in the latest mlnet cli, could you give it a shot?

**Comment by v-Hailishi** [comment]
The bug has been fixed on the latest .NET CLI version 16.17.17.
![image](https://github.com/dotnet/machinelearning-modelbuilder/assets/99375895/04fa23b7-a931-46fe-9532-38c74a0c3f1b)
![image](https://github.com/dotnet/machinelearning-modelbuilder/assets/99375895/10b55955-307b-4ebf-9471-bf1f73523a26)
