### ISSUE TITLE
Error training ObjectDetection on Azure

### ISSUE THREAD

**Issue by MattiaDurli** [dotnet/machinelearning-modelbuilder#2801]
**System Information (please complete the following information):**
 - Model Builder Version 17.17.0.2332602
 - Visual Studio Version 17.8.0

**Describe the bug**
- Training an ObjectDetection model on Azure, I receive this error (tried multiple times on different days):

Training has failed. Please go to Azure portal to see more details.

at AzureML.AutoMLRunMonitoringImages.<MonitorParentRunAsync>d__1.MoveNext() in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/RemoteAutoML/AutoMLRunMonitoringImages.cs:line 126
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at AzureML.AutoMLRunnerImages.<RunAutoMLAsync>d__26.MoveNext() in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/RemoteAutoML/AutoMLRunnerImages.cs:line 215
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ML.ModelBuilder.AutoMLService.Experiments.AzureImageClassificationExperiment.<ExecuteAsync>d__14.MoveNext() in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/Experiments/AzureImageClassificationExperiment.cs:line 60
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ML.ModelBuilder.AutoMLEngine.<StartTrainingAsync>d__21.MoveNext() in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/AutoMLEngineService/AutoMLEngine.cs:line 169
   
   
   Encountered an internal AutoML Image error. Error Message/Code: Potential temporary hardware failure - please resubmit the run. If that does not solve the problem, please file a support ticket for further investigation.. Traceback:   File "utils.py", line 348, in wrapper
    return func(*args, **kwargs)
  File "runner.py", line 126, in run
    utils.launch_training_with_retries(
  File "utils.py", line 1558, in wrapper
    retry = func(*args, **kwargs)
  File "utils.py", line 1592, in launch_training_with_retries
    distributed_utils.launch_single_or_distributed_training(
  File "distributed_utils.py", line 418, in launch_single_or_distributed_training
    train_worker_fn(0, settings, *additional_train_worker_fn_args)
  File "utils.py", line 348, in wrapper
    return func(*args, **kwargs)
  File "runner.py", line 264, in train_worker
    model_wrapper = detection.setup_model(model_name=model_name,
  File "detection.py", line 77, in setup_model
    model_wrapper.to_device(device)
  File "base_model_wrapper.py", line 367, in to_device
    self.model.to(device)
  File "module.py", line 989, in to
    return self._apply(convert)
  File "module.py", line 641, in _apply
    module._apply(fn)
  File "module.py", line 641, in _apply
    module._apply(fn)
  File "module.py", line 641, in _apply
    module._apply(fn)
  File "module.py", line 664, in _apply
    param_applied = fn(param)
  File "module.py", line 987, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
. Additional information: CUDA error: all CUDA-capable devices are busy or unavailable
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1..

**To Reproduce**
I annotated a series of images with VOTT, a year ago.
I trained a model with an older version of VS and AutoML that produced a working ONNX model.
Now I tried to train again with a more recent version of VS and AutoML, starting from scratch: console project, add ML model... choose ObjectDetection...

**Expected behavior**
The job to terminate without errors.

**Comment by LittleLittleCloud** [comment]
![image](https://github.com/dotnet/machinelearning-modelbuilder/assets/16876986/0ed8ae54-0f48-4426-bd99-75a292f18647)

Seems to be a hardware issue, maybe try remove the AML workspace/compute and start over?

**Comment by LittleLittleCloud** [comment]
Any updates?
