### ISSUE TITLE
Builder can't train LightGBM model

### ISSUE THREAD

**Issue by MaksymButenko** [dotnet/machinelearning-modelbuilder#2814]
**System Information (please complete the following information):**
 - Model Builder Version (available in Manage Extensions dialog): 17.17.0.2332602
 - Visual Studio Version: Version 17.6.2

**Describe the bug**
Builder can't train LightGBM model

**To Reproduce**
0. Create new project, don't reference anything additionally
1. Right mouse click on project .net 6 (or .net 7), select Add->Machine learning model
1. Choose Value prediction scenario, select Local CPU training env
2. Load any file
(e,g. csv with content
F1,F2
1,2
2,4
3,6
4,8
)
4. Choose any column (e.g. F2) as column to predict
5. On next step click Advanced training options, on Trainers deselect anything but LightGBM
save it
6. click Start training

**Expected behavior**
it start training

**Actual behavior**
it throw Object reference not set to an instance of an object.
on 
   at Microsoft.ML.AutoML.ConcatenateEntity.ToString()
   at Microsoft.ML.AutoML.SweepablePipeline.AppendEntity(Boolean allowSkip, Entity entity)
   at Microsoft.ML.ModelBuilder.AutoMLService.Experiments.RegressionExperiment.<ExecuteAsync>d__14.MoveNext() in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/Experiments/RegressionExperiment.cs:line 109
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ML.ModelBuilder.AutoMLEngine.<StartTrainingAsync>d__21.MoveNext() in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/AutoMLEngineService/AutoMLEngine.cs:line 169

**Additional context**
I think it worked with previous (not sure which) version of Builder
I see some similar issue in github, but not same
also, if machinelearning-modelbuilder use https://github.com/dotnet/machinelearning ?
if yes - how to see which version of dotnet/machinelearning it use ? (as I see some similar issue have been fixed in 3.0.0)

**Comment by MaksymButenko** [comment]
upd: just to note - I've updates Visual Studio to 17.8.3 and it installed modelbuilder version 17.15.0.2337001
and seems it's working with same steps in 17.15.0.2337001

**Comment by zewditu** [comment]
@LittleLittleCloud  do we have specific versions of ML.Net or Model Builder that works for ` LightGBM`?

**Comment by LittleLittleCloud** [comment]
@MaksymButenko I can't reproduce this issue on latest main. Would you mind sharing your `.mbconfig` with us and maybe the sample dataset?

**Comment by MaksymButenko** [comment]
I need to prepare all this data, and probably debug it by myself a bit before continue discussion (as currently previous version works for me)
I suggest to close this request for now, or I can provide data/some examples in probably 2 weeks from now
