### ISSUE TITLE
Image Classification "The type initializer for 'Tensorflow.Binding" Exception

### ISSUE THREAD

**Issue by pstricker** [dotnet/machinelearning-modelbuilder#2840]
**System Information (please complete the following information):**
 - Model Builder Version: 17.15.0.2337001
 - Visual Studio Version: 17.8.6

**Describe the bug**
- On which step of the process did you run into an issue: Train
- Clear description of the problem: After selecting an Image Classification scenario and selecting Local environment, and selecting a Data folder with two subfolders, when initiating the Train step, the Model Build Error dialog message had the following stack trace:

   at Microsoft.ML.Vision.ImageClassificationTrainer..ctor(IHostEnvironment env, Options options)
   at Microsoft.ML.AutoML.CodeGen.ImageClassificationMulti.BuildFromOption(MLContext context, ImageClassificationOption param)
   at Microsoft.ML.AutoML.SweepablePipeline.BuildFromOption(MLContext context, Parameter parameter)
   at Microsoft.ML.AutoML.SweepablePipelineRunner.Run(TrialSettings settings)
   at Microsoft.ML.AutoML.SweepablePipelineRunner.RunAsync(TrialSettings settings, CancellationToken ct)
   at Microsoft.ML.AutoML.AutoMLExperiment.<RunAsync>d__24.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ML.ModelBuilder.AutoMLService.LocalImageClassificationExperiment.<ExecuteAsync>d__13.MoveNext() in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/Experiments/LocalImageClassificationExperiment.cs:line 116
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ML.ModelBuilder.AutoMLEngine.<StartTrainingAsync>d__21.MoveNext() in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/AutoMLEngineService/AutoMLEngine.cs:line 161
 

**To Reproduce**
1. On the Scenario screen, click on "Image Classification" under the "Computer Vision" section.
2. On the Environment screen, click on "Local (CPU)" and the click on the "Next Step" button.
3. On the Data screen, click on the ellipses icon (...) and navigate to folder containing two sub-folders with images inside each folder.
4. Wait for "Data Preview" section to populate and hit "Next Step" button.
5. On Train screen, click on "Start training" button
6. See Model Builder Error dialog appear with "The type initializer for 'Tensorflow.Binding' threw an exception."

**Expected behavior**
Expected training to complete successfully.

**Screenshots**
![Screenshot 2024-02-03 165856](https://github.com/dotnet/machinelearning-modelbuilder/assets/3308247/ac48d208-c93f-4047-aacd-0a5d06cf62ab)
![Screenshot 2024-02-03 165905](https://github.com/dotnet/machinelearning-modelbuilder/assets/3308247/2da62893-aa60-4c57-9d5c-970ed2d238c6)
![Screenshot 2024-02-03 165919](https://github.com/dotnet/machinelearning-modelbuilder/assets/3308247/c6bde9d4-2783-42db-af85-3c1f7ff66e38)
![Screenshot 2024-02-03 165935](https://github.com/dotnet/machinelearning-modelbuilder/assets/3308247/ce74e4ec-8dc5-49bb-8d18-937c3113a297)

**Additional context**
Utilizing a MacBook Air M2 with Parallels Desktop

**Comment by LittleLittleCloud** [comment]
@pstricker the  TF runtime used by model builder is compiled against x64 and doesn't support M2 chip

**Comment by pstricker** [comment]
Yes, running windows using Parallels Desktop virtualization. Sounds like using Local CPU isn’t an option for me. Thanks!
