### ISSUE TITLE
ML.NET engine suddenly stopped working. Error: [Training time finished without completing...]

### ISSUE THREAD

**Issue by Stefanopr** [dotnet/machinelearning-modelbuilder#2854]
**System Information (please complete the following information):**
 - Model Builder Version (available in Manage Extensions dialog): 17.17.0.2332602
 - Visual Studio Version: 17.9.0

**Describe the bug**
I have been using ML successfully for a long time without any issues. Suddenly, it stopped working. No matter which source file I use for training, including files that I have already used successfully, I always get the same error:

Training time finished without completing a successful trial. Either no trial completed or the metric for all completed trials are NaN or Infinity
   at Microsoft.ML.AutoML.AutoMLExperiment.<RunAsync>d__24.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ML.ModelBuilder.AutoMLService.Experiments.MultiClassificationExperiment.<ExecuteAsync>d__14.MoveNext() in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/Experiments/MultiClassificationExperiment.cs:line 140
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ML.ModelBuilder.AutoMLEngine.<StartTrainingAsync>d__21.MoveNext() in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/AutoMLEngineService/AutoMLEngine.cs:line 169

Attaching screenshot and log file.

I tried to uninstall the extension, reboot, reinstall, but nothing changed.

Than you very much

[LogFile-CC3IXF.txt](https://github.com/dotnet/machinelearning-modelbuilder/files/14330018/LogFile-CC3IXF.txt)
![Screenshot 2024-02-19 114603](https://github.com/dotnet/machinelearning-modelbuilder/assets/160485370/338bd2a3-3f9f-46d6-b45b-f1a867b41573)

**Comment by PElanchezhiyan** [comment]
@Stefanopr , What is the resolution for this issue?

**Comment by Stefanopr** [comment]
Hi,
It was actually my fault.
I was pressing "Data classification" square button instead of "Value prediction" square button.
