### ISSUE TITLE
The given key was not present in the dictionary

### ISSUE THREAD

**Issue by vominhthanh2001** [dotnet/machinelearning-modelbuilder#2880]
at System.ThrowHelper.ThrowKeyNotFoundException()
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at Microsoft.ML.TorchSharp.AutoFormerV2.ObjectDetectionMetrics.ImageIoU(List`1 objectLabel, List`1 annotation, Dictionary`2 iouDic, Dictionary`2 groundTruthBoxes)
   at Microsoft.ML.TorchSharp.AutoFormerV2.ObjectDetectionMetrics.GenerateIOUDic(List`1 annotations, List`1 objectLabelList, Dictionary`2 iouDic, Dictionary`2 groundTruthBoxes)
   at Microsoft.ML.TorchSharp.AutoFormerV2.ObjectDetectionMetrics.MeasureMetrics(IDataView dataView, Column labelCol, Column actualBoundingBoxColumn, Column predictedLabelCol, Column predictedBoundingBoxColumn, Column scoreCol)
   at Microsoft.ML.ModelBuilder.AutoMLService.LocalObjectDetectionMetricManager.Evaluate(MLContext context, IDataView eval) in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/MetricManagers/LocalObjectDetectionMetricManager.cs:line 24
   at Microsoft.ML.AutoML.SweepablePipelineRunner.Run(TrialSettings settings)
   at Microsoft.ML.AutoML.SweepablePipelineRunner.RunAsync(TrialSettings settings, CancellationToken ct)
   at Microsoft.ML.AutoML.AutoMLExperiment.<RunAsync>d__24.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ML.ModelBuilder.AutoMLService.LocalObjectDetectionExperiment.<ExecuteAsync>d__13.MoveNext() in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/Experiments/LocalObjectDetectionExperiment.cs:line 133
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ML.ModelBuilder.AutoMLEngine.<StartTrainingAsync>d__21.MoveNext() in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/AutoMLEngineService/AutoMLEngine.cs:line 212

![bugTrain](https://github.com/dotnet/machinelearning-modelbuilder/assets/62367534/085cb33e-76d2-4702-b740-f68db4db2c3c)

Advanced training options
![optionsBug](https://github.com/dotnet/machinelearning-modelbuilder/assets/62367534/f8c1431e-859e-458d-9292-c07e33f45b33)

File Result Coco : 
[Select-2-objects-that-are-the-same-shape-7.json](https://github.com/dotnet/machinelearning-modelbuilder/files/14605318/Select-2-objects-that-are-the-same-shape-7.json)

**Comment by LittleLittleCloud** [comment]
@michaelgsharp Do you know what might cause this error? Unobservce label in test dataset?

**Comment by thisIsDeadCode** [comment]
I have the same problem, I created the Vott json using Vott
I loaded it into VS but I get an error
[MLModel1-FB8SQJ.txt](https://github.com/user-attachments/files/16119479/MLModel1-FB8SQJ.txt)

![image](https://github.com/dotnet/machinelearning-modelbuilder/assets/105701529/c097043b-eecf-4cb0-8e9d-4ec6778b6841)
![image](https://github.com/dotnet/machinelearning-modelbuilder/assets/105701529/7942df43-b9bc-4cf4-b2bd-bbb3345ad7a9)
![image](https://github.com/dotnet/machinelearning-modelbuilder/assets/105701529/320480fb-1db7-4bfb-a279-00146f77832f)
![image](https://github.com/dotnet/machinelearning-modelbuilder/assets/105701529/adc6b59d-7203-409b-b9dd-24415723373c)

**Comment by thisIsDeadCode** [comment]
[EKF-export.json](https://github.com/user-attachments/files/16119525/EKF-export.json)

**Comment by thisIsDeadCode** [comment]
I left a couple of pictures and now this error is not reproduced
This bug depends on the number of elements in json

![image](https://github.com/dotnet/machinelearning-modelbuilder/assets/105701529/cf689467-571d-458b-9289-593d07980562)
[EKF-export.json](https://github.com/user-attachments/files/16119658/EKF-export.json)
