### ISSUE TITLE
Training Failed choosing local CPU in Object detection scenario, 'TorchSharp.torch' threw an exception

### ISSUE THREAD

**Issue by NickAtMixxus** [dotnet/machinelearning-modelbuilder#2891]
**System Information (please complete the following information):**
 - 17.18.2.2415501
 - Visual Studio Version: Visual Studio Community 2022, 17.9.5 (Installer reports All installations are up to date)

**Describe the bug**
Training Failed choosing local CPU in Object detection scenario

**To Reproduce**
In .mbconfig UI Scenario, choose Object detection, in Environment choose Local (CPU), Next step, in Data add .json file, created from vott after labeling images. (Images are then visible in Data Preview
Next step, Train
Training starts but is soon interrupted  with Model Builder Error:
The type initializer for 'TorchSharp.torch' threw an exception.

**Expected behavior**
Expected to have a completed Training or some info if something is not installed or missing.

**Additional context**
Something may be wrong in my setup, I have had an older version of Model builder that I could train successfully. I have tried new projects, a clean install of Visual Studio and removed and reinstalled , both auto and manual installation of Model Builder (from Visual Studio Marketplace), tried two sets of different images, tagged in Vott.

Also noticing that under Advanced training options, in the fields Score threshold and IOU threshold the default settings (0.35 and 0.5) has red text next to them: "Not a valid input. The input must be a valid float and m"... it's impossible to read the rest of the sentence, and you can't expand the window. Trying to change those values have so far made no difference.

Some more details
From Log file
End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ML.ModelBuilder.AutoMLEngine.<StartTrainingAsync>d__21.MoveNext() in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/AutoMLEngineService/AutoMLEngine.cs:line 212

**Comment by vulvquang** [comment]
I had the same error, however you can try to use Object Detection on Aruze Machine Learning.

**Comment by NickAtMixxus** [comment]
Thanks, good to know! I'll just have to wait for some update then. 
About Azure, I thought I'd test on CPU/GPU first to not spend anything before I know I have some useful images. But I tried to start the Azure alternative but I'm not done yet. Even though watching a bunch of quick start videos.  Even though I could create a free account it is pretty hard to understand which way to go to create a compute. In the Azure portal or in the Azure Machine Learning Studio? The profile looks a bit different in portal vs studio. (There are so many docs and tutorials for those with different dates also docs for AI Studio, AutoML Computer vision.) I get the impression that Azure and Machine Learning area is frequently updated and changed and it's a bit confusing now to keep up.

**Comment by LittleLittleCloud** [comment]
@NickAtMixxus Can you share the complete log of model builder(where you can find the url on visual studio output window),, from you mention (The type initializer for 'TorchSharp.torch' threw an exception.) I wonder if this error is caused by the failure of loading torch.dll

**Comment by NickAtMixxus** [comment]
@LittleLittleCloud

OK. Just a quick update, I have also tried training on GPU, that training is also quickly aborted with an error message. (I have installed CUDA 10.1 since that was mentioned in an Image Classification tutorial, I tried previously with a recent CUDA version but did not seem to matter.)

**Attaching files with message from Output window from CPU training and GPU training, and complete LOG files also from both CPU and GPU training.** 
[OutputWinObjDetTrainCPU.txt](https://github.com/dotnet/machinelearning-modelbuilder/files/15011072/OutputWinObjDetTrainCPU.txt)
[OutputWinObjDetTrainGPU.txt](https://github.com/dotnet/machinelearning-modelbuilder/files/15011075/OutputWinObjDetTrainGPU.txt)
[LOGcopyCPUtrain.txt](https://github.com/dotnet/machinelearning-modelbuilder/files/15011080/LOGcopyCPUtrain.txt)
[LOGcopyGPUtrain.txt](https://github.com/dotnet/machinelearning-modelbuilder/files/15011083/LOGcopyGPUtrain.txt)



And here are the error messages for each training

Error Message CPU Training

The type initializer for 'TorchSharp.torch' threw an exception.

at Microsoft.ML.TorchSharp.Utils.TorchUtils.InitializeDevice(IHostEnvironment env)
   at Microsoft.ML.TorchSharp.AutoFormerV2.ObjectDetectionTrainer.Trainer..ctor(ObjectDetectionTrainer parent, IChannel ch, IDataView input)
   at Microsoft.ML.TorchSharp.AutoFormerV2.ObjectDetectionTrainer.Fit(IDataView input)
   at Microsoft.ML.Data.EstimatorChain`1.Fit(IDataView input)
   at Microsoft.ML.AutoML.SweepablePipelineRunner.Run(TrialSettings settings)
   at Microsoft.ML.AutoML.SweepablePipelineRunner.RunAsync(TrialSettings settings, CancellationToken ct)
   at Microsoft.ML.AutoML.AutoMLExperiment.<RunAsync>d__24.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ML.ModelBuilder.AutoMLService.LocalObjectDetectionExperiment.<ExecuteAsync>d__13.MoveNext() in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/Experiments/LocalObjectDetectionExperiment.cs:line 133
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ML.ModelBuilder.AutoMLEngine.<StartTrainingAsync>d__21.MoveNext() in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/AutoMLEngineService/AutoMLEngine.cs:line 212



Error Message GPU Training

The type initializer for 'TorchSharp.torch' threw an exception.
at TorchSharp.torch.TryInitializeDeviceType(DeviceType deviceType)
   at Microsoft.ML.ModelBuilder.AutoMLService.LocalObjectDetectionExperiment.<ExecuteAsync>d__13.MoveNext() in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/Experiments/LocalObjectDetectionExperiment.cs:line 53
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ML.ModelBuilder.AutoMLEngine.<StartTrainingAsync>d__21.MoveNext() in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/AutoMLEngineService/AutoMLEngine.cs:line 212

**Comment by RehanSaeed** [comment]
Did you get anywhere with this? I'm getting this error when using text classification.

This other thread suggests installing certain C++ packages: https://github.com/dotnet/TorchSharp/issues/1113

**Comment by LittleLittleCloud** [comment]
@RehanSaeed Can you try running text classification from `mlnet-cli` to help verify that torchsharp training is supported on your platform?

You can install mlnet-cli (mlnet-cli for win-x64) from nuget: https://www.nuget.org/packages/mlnet-win-x64

And the cmd is 
```
mlnet text-classification --dataset /path/to/dataset --label-col <label_col_name> --text-col <text_col_name>
```

**Comment by RehanSaeed** [comment]
Unfortunately, I get the following error:

```
Use train validate split with ratio: 0.1
[Source=AutoMLExperiment-ChildContext, Kind=Trace] [Source=TorchSharpBaseTrainer; TrainModel, Kind=Trace] Starting epoch 0
System.Runtime.InteropServices.ExternalException (0x80004005): Target 4294967295 is out of bounds.
Exception raised from nll_loss_out_frame at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\LossNLL.cpp:252 (most recent call first):
00007FFB2FFCAF4200007FFB2FFCAEE0 c10.dll!c10::Error::Error [<unknown file> @ <unknown line number>]
00007FFB2FF8447500007FFB2FF84400 c10.dll!c10::IndexError::IndexError [<unknown file> @ <unknown line number>]
00007FFAF474CFE400007FFAF47480B0 torch_cpu.DLL!at::native::multi_margin_loss_cpu_out [<unknown file> @ <unknown line number>]
00007FFAF475052400007FFAF47480B0 torch_cpu.DLL!at::native::multi_margin_loss_cpu_out [<unknown file> @ <unknown line number>]
00007FFAF4752BA400007FFAF4752B40 torch_cpu.DLL!at::native::structured_nll_loss_forward_out_cpu::impl [<unknown file> @ <unknown line number>]
00007FFAF537D4D900007FFAF5359AE0 torch_cpu.DLL!at::cpu::where_outf [<unknown file> @ <unknown line number>]
00007FFAF53307AF00007FFAF52D5560 torch_cpu.DLL!at::cpu::bucketize_outf [<unknown file> @ <unknown line number>]
00007FFAF4DA333700007FFAF4D27150 torch_cpu.DLL!at::_ops::zeros_out::redispatch [<unknown file> @ <unknown line number>]
00007FFAF4FDF70000007FFAF4FDF630 torch_cpu.DLL!at::_ops::nll_loss_forward::redispatch [<unknown file> @ <unknown line number>]
00007FFAF6577FDA00007FFAF62E6990 torch_cpu.DLL!torch::autograd::CopySlices::~CopySlices [<unknown file> @ <unknown line number>]
00007FFAF654537900007FFAF62E6990 torch_cpu.DLL!torch::autograd::CopySlices::~CopySlices [<unknown file> @ <unknown line number>]
00007FFAF4F6338E00007FFAF4F63140 torch_cpu.DLL!at::_ops::nll_loss_forward::call [<unknown file> @ <unknown line number>]
00007FFAF475412E00007FFAF4754070 torch_cpu.DLL!at::native::nll_loss_symint [<unknown file> @ <unknown line number>]
00007FFAF5646BE600007FFAF5642710 torch_cpu.DLL!at::compositeimplicitautograd::where [<unknown file> @ <unknown line number>]
00007FFAF56293F300007FFAF55E2420 torch_cpu.DLL!at::compositeimplicitautograd::broadcast_to_symint [<unknown file> @ <unknown line number>]
00007FFAF509C31E00007FFAF509C0D0 torch_cpu.DLL!at::_ops::nll_loss::call [<unknown file> @ <unknown line number>]
00007FFAF4753C7100007FFAF4753320 torch_cpu.DLL!at::native::nll_loss_nd_symint [<unknown file> @ <unknown line number>]
00007FFAF5646C6600007FFAF5642710 torch_cpu.DLL!at::compositeimplicitautograd::where [<unknown file> @ <unknown line number>]
00007FFAF562948300007FFAF55E2420 torch_cpu.DLL!at::compositeimplicitautograd::broadcast_to_symint [<unknown file> @ <unknown line number>]
00007FFAF4E0B80E00007FFAF4E0B5C0 torch_cpu.DLL!at::_ops::nll_loss_nd::call [<unknown file> @ <unknown line number>]
00007FFAF4752A1100007FFAF4752690 torch_cpu.DLL!at::native::cross_entropy_loss_symint [<unknown file> @ <unknown line number>]
00007FFAF5644CD500007FFAF5642710 torch_cpu.DLL!at::compositeimplicitautograd::where [<unknown file> @ <unknown line number>]
00007FFAF562952800007FFAF55E2420 torch_cpu.DLL!at::compositeimplicitautograd::broadcast_to_symint [<unknown file> @ <unknown line number>]
00007FFAF507A1AD00007FFAF5079F40 torch_cpu.DLL!at::_ops::cross_entropy_loss::call [<unknown file> @ <unknown line number>]
00007FFB3124EEDF00007FFB3124ED00 LibTorchSharp.DLL!THSNN_cross_entropy [<unknown file> @ <unknown line number>]
00007FFBD98233A8 <unknown symbol address> !<unknown symbol> [<unknown file> @ <unknown line number>]

   at TorchSharp.torch.CheckForErrors()
   at TorchSharp.Modules.CrossEntropyLoss.forward(Tensor input, Tensor target)
   at Microsoft.ML.TorchSharp.NasBert.NasBertTrainer`2.NasBertTrainerBase.RunModelAndBackPropagate(List`1& inputTensors, Tensor& targetsTensor)
   at Microsoft.ML.TorchSharp.TorchSharpBaseTrainer`2.TrainerBase.TrainStep(IHost host, DataViewRowCursor cursor, ValueGetter`1 labelGetter, List`1& inputTensors, List`1& targets)
   at Microsoft.ML.TorchSharp.TorchSharpBaseTrainer`2.TrainerBase.Train(IHost host, IDataView input)
   at Microsoft.ML.TorchSharp.TorchSharpBaseTrainer`2.Fit(IDataView input)
   at Microsoft.ML.Data.EstimatorChain`1.Fit(IDataView input)
   at Microsoft.ML.AutoML.SweepablePipelineRunner.Run(TrialSettings settings)
   at Microsoft.ML.AutoML.SweepablePipelineRunner.RunAsync(TrialSettings settings, CancellationToken ct)
   at Microsoft.ML.AutoML.AutoMLExperiment.RunAsync(CancellationToken ct)
   at Microsoft.ML.ModelBuilder.AutoMLService.TextClassificationExperiment.ExecuteAsync(IDataView trainData, IDataView validateData, CancellationToken ct) in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/Experiments/TextClassificationExperiment.cs:line 126
   at Microsoft.ML.ModelBuilder.AutoMLEngine.StartTrainingAsync(ITrainingConfiguration config, PathConfiguration pathConfig, CancellationToken userCancellationToken) in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/AutoMLEngineService/AutoMLEngine.cs:line 178
   at Microsoft.ML.CLI.Runners.AutoMLRunner.ExecuteAsync() in /_/src/mlnet/Runners/AutoMLRunner.cs:line 95
   at Microsoft.ML.CLI.Program.TrainAsync(ITrainingConfiguration trainingConfiguration, PathConfiguration pathConfig, AutoMLServiceLogLevel logLevel) in /_/src/mlnet/Program.cs:line 428
   at Microsoft.ML.CLI.Program.<>c.<<CreateRootCommandLineBuilder>b__5_8>d.MoveNext() in /_/src/mlnet/Program.cs:line 317
--- End of stack trace from previous location ---
   at System.CommandLine.Invocation.CommandHandler.GetExitCodeAsync(Object value, InvocationContext context)
   at System.CommandLine.Invocation.ModelBindingCommandHandler.InvokeAsync(InvocationContext context)
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass23_0.<<UseParseErrorReporting>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.ML.CLI.Program.<>c__DisplayClass5_0.<<CreateRootCommandLineBuilder>b__11>d.MoveNext() in /_/src/mlnet/Program.cs:line 360
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseSuggestDirective>b__24_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass22_0.<<UseParseDirective>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass11_0.<<UseDebugDirective>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<RegisterWithDotnetSuggest>b__10_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass14_0.<<UseExceptionHandler>b__0>d.MoveNext()
```
