### ISSUE TITLE
training QnA on local CPU using SQUAD2 Dataset

### ISSUE THREAD

**Issue by vulvquang** [dotnet/machinelearning-modelbuilder#2893]
**System Information (please complete the following information):**
 - Model Builder Version (available in Manage Extensions dialog): 
 - Visual Studio Version

**Describe the bug**
- On which step of the process did you run into an issue:
- Clear description of the problem:

**To Reproduce**

**Expected behavior**

**Screenshots**
unmatched!
  at Microsoft.ML.TorchSharp.Roberta.QATrainer.Trainer.AlignAnswerPosition(IReadOnlyList`1 tokens, String text)
   at Microsoft.ML.TorchSharp.Roberta.QATrainer.Trainer.PrepareData(ValueGetter`1 contextGetter, ValueGetter`1 questionGetter, ValueGetter`1 answerGetter, ValueGetter`1 answerIndexGetter)
   at Microsoft.ML.TorchSharp.Roberta.QATrainer.Trainer.TrainStep(IHost host, DataViewRowCursor cursor, ValueGetter`1 contextGetter, ValueGetter`1 questionGetter, ValueGetter`1 answerGetter, ValueGetter`1 answerIndexGetter, List`1& inputTensors, List`1& targetTensors, IProgressChannel pch)
   at Microsoft.ML.TorchSharp.Roberta.QATrainer.Trainer.Train(IHost host, IDataView input, IProgressChannel pch)
   at Microsoft.ML.TorchSharp.Roberta.QATrainer.Fit(IDataView input)
   at Microsoft.ML.Data.EstimatorChain`1.Fit(IDataView input)
   at Microsoft.ML.AutoML.SweepablePipelineRunner.Run(TrialSettings settings)
   at Microsoft.ML.AutoML.SweepablePipelineRunner.RunAsync(TrialSettings settings, CancellationToken ct)
   at Microsoft.ML.AutoML.AutoMLExperiment.<RunAsync>d__24.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ML.ModelBuilder.AutoMLService.Experiments.QuestionAnswerExperiment.<ExecuteAsync>d__13.MoveNext() in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/Experiments/QuestionAnswerExperiment.cs:line 105
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ML.ModelBuilder.AutoMLEngine.<StartTrainingAsync>d__21.MoveNext() in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/AutoMLEngineService/AutoMLEngine.cs:line 212
**Additional context**

**Comment by vulvquang** [comment]
Tried with smaller number of dataset and OK

**Comment by vulvquang** [comment]
it is better to close

**Comment by vulvquang** [comment]
Tried with smaller number of dataset and OK
