### ISSUE TITLE
I tried to launch the new frosty mod manager 1.0.6.3 even running as administrator but it showed me this

### ISSUE THREAD

**Issue by TrooperJJ** [dotnet/machinelearning-modelbuilder#2897]
The given key was not present in the dictionary.

   at System.ThrowHelper.ThrowKeyNotFoundException()
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at Frosty.Core.Config.get_Item(String option, ConfigScope scope, String profile)
   at Frosty.Core.Config.Get[T](String option, T defaultValue, ConfigScope scope, String profile)
   at Frosty.Core.FrostyConfiguration..ctor(String profile)
   at FrostyModManager.App.Application_Startup(Object sender, StartupEventArgs e)
   at System.Windows.Application.OnStartup(StartupEventArgs e)
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegat

**Comment by LittleLittleCloud** [comment]
Are you posting the issue to the wrong repo,, this repo is related to model builder

**Comment by Loveforwa** [comment]
Have you solved this, cuz I have the same problem.

**Comment by Loveforwa** [comment]
Don't want to bother, I find the solution https://steamcommunity.com/app/1238000/discussions/0/3758851615172218695/

**Comment by aeschylusshepherd** [comment]
Thank you for posting your fix on here.  It worked for me too!!
