### ISSUE TITLE
SON-RPC connection with the remote party was lost before the request could complete.

### ISSUE THREAD

**Issue by Haresj** [dotnet/machinelearning-modelbuilder#2898]
DEBUG The JSON-RPC connection with the remote party was lost before the request could complete.
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at StreamJsonRpc.JsonRpc.<InvokeCoreAsync>d__162.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at StreamJsonRpc.JsonRpc.<InvokeCoreAsync>d__151`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ML.ModelBuilder.ViewModels.TrainViewModel.<<StartTrainingAsync>b__92_0>d.MoveNext() (Microsoft.ML.ModelBuilder.Utils.Logger.Debug)

**Comment by Megasoft2** [comment]
Hi. Based on ML.NET and Nvidia 
I have the same issue.
Any resolution?

Sincerely

**Comment by Megasoft2** [comment]
I suggest using VS 2022 Preview
Works for me!

Sincerely

**Comment by wangzimeiyingtao** [comment]
Same question. I have updated to the preview version

**Comment by Megasoft2** [comment]
> Same question. I have updated to the preview version

It worked for me with Visual Studio 2022 Enterprise Version 17.10.0 Preview 3.0

**Comment by LittleLittleCloud** [comment]
We pushed a fix to this issue in model builder 17.18.2. Also it seems that the servicehub connection is improved in visual studio preview?
