### ISSUE TITLE
Sequence contains no elements exception - Recommendation Scenario

### ISSUE THREAD

**Issue by ks1990cn** [dotnet/machinelearning-modelbuilder#2956]
**System Information (please complete the following information):**
 - Model Builder or CLI Version:  .Net 8
 - Visual Studio Version (if applicable): V22

**Describe the bug**
While starting training for recommendation for studios rating in my case (similar to movie recommendation).

**To Reproduce**

https://github.com/user-attachments/assets/c83194d7-1321-4f2b-8cca-86ea30921916

```

   at System.Linq.Enumerable.Average(IEnumerable`1 source)
   at Microsoft.ML.ModelBuilder.AutoMLService.ArrayMath.RSquared(Double[] truth, Double[] pred) in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/ArrayMath.cs:line 190
   at Microsoft.ML.ModelBuilder.AutoMLService.RecommendationMetricManager.Evaluate(MLContext context, IDataView eval) in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/MetricManagers/RecommendationMetricManager.cs:line 55
   at Microsoft.ML.AutoML.SweepablePipelineRunner.Run(TrialSettings settings)
   at Microsoft.ML.AutoML.SweepablePipelineRunner.RunAsync(TrialSettings settings, CancellationToken ct)
   at Microsoft.ML.AutoML.AutoMLExperiment.<RunAsync>d__24.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ML.ModelBuilder.AutoMLService.RecommendationExperiment.<ExecuteAsync>d__13.MoveNext() in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/Experiments/RecommendationExperiment.cs:line 140
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ML.ModelBuilder.AutoMLEngine.<StartTrainingAsync>d__21.MoveNext() in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/AutoMLEngineService/AutoMLEngine.cs:line 199
```
**Expected behavior**
Training should successfully run

**Comment by ks1990cn** [comment]
Problem is with my less size data
