### ISSUE TITLE
Error getting - The JSON-RPC connection with the remote party was lost before the request could complete.

### ISSUE THREAD

**Issue by sankasumadura** [dotnet/machinelearning-modelbuilder#2966]
Getting the error The JSON-RPC connection with the remote party was lost before the request could complete.
from model builder error window
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at StreamJsonRpc.JsonRpc.<InvokeCoreAsync>d__162.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at StreamJsonRpc.JsonRpc.<InvokeCoreAsync>d__151`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ML.ModelBuilder.ViewModels.TrainViewModel.<<StartTrainingAsync>b__92_0>d.MoveNext()

**Comment by ICCCCOM** [comment]
I also encountered this issues.

**Comment by ICCCCOM** [comment]
I also encountered this issues when I clicked the start training button.

**Comment by ICCCCOM** [comment]
Good news, after updating the ML model, I successfully completed the training
https://marketplace.visualstudio.com/items?itemName=MLNET.ModelBuilder2022

**Comment by hscodesolution** [comment]
i am facing this issue, i am running Microsoft Visual Studio Professional 2022 (64-bit) - Version 17.11.5 and my ML.NET Model Builder version is 17.18.4.2425601 

Also, i noticed that, error comes only when i try to train using GPU. When i train using CPU this error is not coming and training completed successfully. (I am training model using image classification scenario)
