### ISSUE TITLE
Invalid input stream contents (Parameter 'imageStream')

### ISSUE THREAD

**Issue by acrigney** [dotnet/machinelearning-modelbuilder#2976]
using VS2022 preview
For object detection I have been using VoTT to label and create my json export file and when trying to run training locally I get this error.
Invalid input stream contents (Parameter 'imageStream')

at Microsoft.ML.Data.MLImage.CreateFromStream(Stream imageStream)
   at Microsoft.ML.Data.ImageLoadingTransformer.Mapper.<>c__DisplayClass4_0.<MakeGetterImageDataViewType>b__1(MLImage& dst)
   at Microsoft.ML.Transforms.Image.ImageResizingTransformer.Mapper.<>c__DisplayClass3_0.<MakeGetter>b__1(MLImage& dst)
   at Microsoft.ML.TorchSharp.AutoFormerV2.ObjectDetectionTrainer.Trainer.PrepareData(ValueGetter`1 labelGetter, ValueGetter`1 imageGetter, ValueGetter`1 boundingBoxGetter)
   at Microsoft.ML.TorchSharp.AutoFormerV2.ObjectDetectionTrainer.Trainer.TrainStep(IHost host, DataViewRowCursor cursor, ValueGetter`1 boundingBoxGetter, ValueGetter`1 imageGetter, ValueGetter`1 labelGetter, IProgressChannel pch)
   at Microsoft.ML.TorchSharp.AutoFormerV2.ObjectDetectionTrainer.Trainer.Train(IHost host, IDataView input, IProgressChannel pch)
   at Microsoft.ML.TorchSharp.AutoFormerV2.ObjectDetectionTrainer.Fit(IDataView input)
   at Microsoft.ML.Data.EstimatorChain`1.Fit(IDataView input)
   at Microsoft.ML.AutoML.SweepablePipelineRunner.Run(TrialSettings settings)
   at Microsoft.ML.AutoML.SweepablePipelineRunner.RunAsync(TrialSettings settings, CancellationToken ct)
   at Microsoft.ML.AutoML.AutoMLExperiment.RunAsync(CancellationToken ct)
   at Microsoft.ML.ModelBuilder.AutoMLService.LocalObjectDetectionExperiment.ExecuteAsync(IDataView trainData, IDataView validateData, CancellationToken ct) in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/Experiments/LocalObjectDetectionExperiment.cs:line 133
   at Microsoft.ML.ModelBuilder.AutoMLEngine.StartTrainingAsync(ITrainingConfiguration config, PathConfiguration pathConfig, CancellationToken userCancellationToken) in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/AutoMLEngineService/AutoMLEngine.cs:line 178

I thought this problem might be caused by my image sizes but I have reduced them now and still getting the error.

**System Information (please complete the following information):**
 - Model Builder Version (available in Manage Extensions dialog): 
 - 17.8.4.2425601
 - Visual Studio Version
 - Version 17.12.0 Preview 2.1
And Version 17.11.4

**Describe the bug**
- On which step of the process did you run into an issue:
- When running training.
- 

**To Reproduce**
Us VoTT to label images, run training.

**Expected behavior**
Training should finish with no errors.

**Screenshots**

**Additional context**

**Comment by LittleLittleCloud** [comment]
@acrigney Looks like you are still using 17.8.4？ Maybe update model builder to 17.18.2 and try again?

**Comment by LittleLittleCloud** [comment]
Close due to no response. Feel free to reopen if necessary

**Comment by WadekarSatyam** [comment]
I have ML.NET Model Builder with Version of 17.18.4.2443003
But still getting error message - "**Invalid input stream contents (Parameter 'imageStream')**"
Call stack
   at Microsoft.ML.Data.MLImage.CreateFromStream(Stream imageStream)
   at TFImageClassification.Controllers.ImageClassificationController.<ClassifyImage>d__7.MoveNext() in C:\Users\SatyamWadekar\source\repos\ML\machinelearning-samples-main\samples\csharp\end-to-end-apps\DeepLearning_ImageClassification_TF\TFImageClassification\Controllers\ImageClassificationController.cs:line 60

**Comment by LittleLittleCloud** [comment]
@WadekarSatyam 
The stacktrace doesn't looks like from model builder, is that from a third-party app
