### ISSUE TITLE
Activating the "MicrosoftMLModelBuilderAutoML" service failed

### ISSUE THREAD

**Issue by dieron** [dotnet/machinelearning-modelbuilder#2982]
**System Information:**
 - Model Builder Version (available in Manage Extensions dialog): v17.18.4.2443003
 - Visual Studio Version Microsoft Visual Studio Professional 2022 (ARM 64-bit) - Preview, Version 17.12.0 Preview 5.0

**Describe the bug**
- On which step of the process did you run into an issue: After choosing a CVS/Text file to analyze
- Clear description of the problem: The Model Builder wizard fails on the Add Data step

**To Reproduce**
1. Select Add Machine Learning model in a context menu
2. Choose Value Prediction option
3. Go to the Data step
4. Choose any CVS or Text file
5. See Model Builder Error dialog

**Expected behavior**
The data is imported and analyzed, Data Preview is displayed

**Screenshots**
![Image](https://github.com/user-attachments/assets/b2cfd194-703d-48c7-b5f4-a63bce9347d4)

**Additional context**
`   at Microsoft.ServiceHub.Framework.RemoteServiceBroker.<GetProxyAsync>d__36`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at Microsoft.VisualStudio.Utilities.ServiceBroker.GlobalBrokeredServiceContainer.ProfferedRemoteServiceBroker.<GetProxyAsync>d__19`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at Microsoft.VisualStudio.Utilities.ServiceBroker.GlobalBrokeredServiceContainer.View.<GetProxyAsync>d__19`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ML.ModelBuilder.AutoMLServiceFactory.<CreateAutoMLServiceAsync>d__0.MoveNext() in /_/src/Microsoft.ML.ModelBuilder/AutoMLServiceFactory.cs:line 68
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ML.ModelBuilder.Actions.DataTextActions.<GetCsvDataProgramAsync>d__14.MoveNext() in /_/src/Microsoft.ML.ModelBuilder/Actions/DataTextActions.cs:line 275
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ML.ModelBuilder.Actions.DataTextActions.<SetFilePathAsync>d__2.MoveNext() in /_/src/Microsoft.ML.ModelBuilder/Actions/DataTextActions.cs:line 61
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ML.ModelBuilder.ToolWindows.DataTextViewModel.<SetFilePathAsync>d__136.MoveNext() in /_/src/Microsoft.ML.ModelBuilder/ViewModels/DataTextViewModel.cs:line 683
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ML.ModelBuilder.ToolWindows.TextDataControl.<<BrowseFileButton_Click>b__3_0>d.MoveNext() in /_/src/Microsoft.ML.ModelBuilder/ToolWindows/DataTabComponents/TextDataControl.xaml.cs:line 69`

**Comment by LittleLittleCloud** [comment]
@dieron Are you running on an arm machine?

**Comment by dieron** [comment]
Yes. It's a Microsoft ARM Dev Kit machine.

**Comment by LittleLittleCloud** [comment]
Thanks @dieron  Although I feel like the service activation would still fail, would you might try the latest model builder v17.19.2 from vS marketplace when you have time.

**Comment by dieron** [comment]
Confirmed. The latest model builder from the VS marketplace fails.

**Comment by faikozcan** [comment]
Any update on this issue? I am having the similar problem while trying to import csv file on a macbook running windows with parallels desktop.

**Comment by LittleLittleCloud** [comment]
@faikozcan We are actively looking that

**Comment by LittleLittleCloud** [comment]
@dieron and @faikozcan We push a fix for support arm64. Here's the vsix artifact, would you please help us  a favor and see if it works on your arm device?

- https://drive.google.com/file/d/1nsQnyrt6pH0zjxR1g_ohkM55zzD1A1pT/view?usp=sharing

**Comment by dieron** [comment]
Hi

It still doesn't work on my machine. However, I updated Windows recently


Activating the "MicrosoftMLModelBuilderAutoML" service failed.

   at
Microsoft.ServiceHub.Framework.RemoteServiceBroker.<GetProxyAsync>d__36`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task
task)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at
Microsoft.VisualStudio.Utilities.ServiceBroker.GlobalBrokeredServiceContainer.ProfferedRemoteServiceBroker.<GetProxyAsync>d__19`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task
task)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at
Microsoft.VisualStudio.Utilities.ServiceBroker.GlobalBrokeredServiceContainer.View.<GetProxyAsync>d__19`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task
task)
   at
Microsoft.ML.ModelBuilder.AutoMLServiceFactory.<CreateAutoMLServiceAsync>d__0.MoveNext()
in /_/src/Microsoft.ML.ModelBuilder/AutoMLServiceFactory.cs:line 68
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task
task)
   at
Microsoft.ML.ModelBuilder.Actions.DataTextActions.<GetCsvDataProgramAsync>d__14.MoveNext()
in /_/src/Microsoft.ML.ModelBuilder/Actions/DataTextActions.cs:line 275
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task
task)
   at
Microsoft.ML.ModelBuilder.Actions.DataTextActions.<SetFilePathAsync>d__2.MoveNext()
in /_/src/Microsoft.ML.ModelBuilder/Actions/DataTextActions.cs:line 61
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task
task)
   at
Microsoft.ML.ModelBuilder.ToolWindows.DataTextViewModel.<SetFilePathAsync>d__136.MoveNext()
in /_/src/Microsoft.ML.ModelBuilder/ViewModels/DataTextViewModel.cs:line 683
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task
task)
   at
Microsoft.ML.ModelBuilder.ToolWindows.TextDataControl.<<BrowseFileButton_Click>b__3_0>d.MoveNext()
in
/_/src/Microsoft.ML.ModelBuilder/ToolWindows/DataTabComponents/TextDataControl.xaml.cs:line
69


[image: image.png]

[image: image.png]


Thank you,

Volodymyr

**Comment by LittleLittleCloud** [comment]
@dieron Thanks for confirming that. Would you pls help us a favor and do one more check while I find an arm64 device to debug?

- Uninstall Model Builder component from VS installer

![Image](https://github.com/user-attachments/assets/14b9818a-1363-47a8-a29b-94988952ae4b)


- Reinstall the vsix I share above.

This is to make sure that the new automl service from updated vsix get registered in Visual studio

**Comment by dieron** [comment]
No, it didn't help. I uninstalled the extension and the component in VS
Installer. But it's still the same error.


Volodymyr

**Comment by PeterB57** [comment]
I've the same problem. Did you get any solution?

**Comment by LittleLittleCloud** [comment]
@PeterB57 @dieron 

Sorry to get back late on this thread. I give this issue another shot by packaging all runtimes in the vsix and wish it could resolve the bug.

Here's the build to try out
- https://drive.google.com/file/d/1jOpgLKPgQUg6AoC0pmwvU8p7klB3ueXh/view?usp=sharing

Please let me know if it works on your arm64 device.

**Comment by PeterB57** [comment]
Thanks for the answer and help! I installed the build.

Now it look like ModelBuilder read the txt-file. Data preview is filled.
But  I can't continue:
* The file-path are empty
* I can't select "Column to predict (Label)"
* I can't open "Advanced data options..."
* The button "Next step" is disabled.

Here is a printscreen:

![Image](https://github.com/user-attachments/assets/9a1822b2-98b6-42c6-821b-24c3312020f6)

**Comment by LittleLittleCloud** [comment]
@PeterB57 Might because the view model fail to update correctly? Maybe try `control + s` to save the window -> close model builder -> reopen model builder and try again.

Also would you might share with us the dataset for further investigation

**Comment by PeterB57** [comment]
I opened the project from my other surface with Window 10. In that PC everything worked perfect. After that I opened in the PC with Windows 11, and now it looks like everything works fine. 
Thank you for all help!

**Comment by RoneyThomas** [comment]
Still an issue on VS 17.14.38 on Windows 11 ARM.
