### ISSUE TITLE
Training time finished without completing a successful trial. Either no trial completed or the metric for all completed trials are NaN or Infinity

### ISSUE THREAD

**Issue by pravula06** [dotnet/machinelearning-modelbuilder#2990]
Training time finished without completing a successful trial. Either no trial completed or the metric for all completed trials are NaN or Infinity

at Microsoft.ML.AutoML.AutoMLExperiment.RunAsync(CancellationToken ct)
   at Microsoft.ML.ModelBuilder.AutoMLService.Experiments.MultiClassificationExperiment.ExecuteAsync(IDataView trainData, IDataView validateData, CancellationToken ct) in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/Experiments/MultiClassificationExperiment.cs:line 140
   at Microsoft.ML.ModelBuilder.AutoMLEngine.StartTrainingAsync(ITrainingConfiguration config, PathConfiguration pathConfig, CancellationToken userCancellationToken) in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/AutoMLEngineService/AutoMLEngine.cs:line 178

**Comment by bagalaty** [comment]
same Issue, I have follow up the same steps here (https://dotnet.microsoft.com/en-us/learn/ml-dotnet/get-started-tutorial/train) on my project and got the same error.

**Comment by aaak5691** [comment]
same error i am getting , is there any solution ?

**Comment by Dulante35** [comment]
same issue,Has anyone solved it

**Comment by Dulante35** [comment]
Set training time longer than 60 seconds ,different pc  may different, when i set tranning time 180s ,it works normally
