### ISSUE TITLE
Image classification + azure - unable to download model

### ISSUE THREAD

**Issue by briacht** [dotnet/machinelearning-modelbuilder#310]
When training image classification with Azure attach, training in VS fails and get the error message below.

Was able to fix the error by creating new folder and re-training -- C:\Users\brachtma\AppData\Local\Temp\MLVSTools\igniteDesktopAppML\igniteDesktopAppML.Model\

**Describe the bug**
_From Output:_

Completed a training run

Downloading best model to C:\Users\brachtma\AppData\Local\Temp\MLVSTools\igniteDesktopAppML\igniteDesktopAppML.Model\bestModel.onnx..
Could not find a part of the path 'C:\Users\brachtma\AppData\Local\Temp\MLVSTools\igniteDesktopAppML\igniteDesktopAppML.Model\bestModel.onnx'.

Could not find a part of the path 'C:\Users\brachtma\AppData\Local\Temp\MLVSTools\igniteDesktopAppML\igniteDesktopAppML.Model\bestModel.onnx'.
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at StreamJsonRpc.JsonRpc.<InvokeCoreAsync>d__94`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ML.ModelBuilder.AutoMLServiceFactory.AutoMLServiceProxy.<StartRemoteTrainingAsync>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ML.ModelBuilder.TrainSession.<<Start>b__40_0>d.MoveNext()

**Comment by luisquintanilla** [comment]
I got the same error.

Downloading best model to C:\Users\luquinta.REDMOND\AppData\Local\Temp\MLVSTools\BugBashModelBuilder01282020ML\BugBashModelBuilder01282020ML.Model\bestModel.onnx..
Completed a training run

Could not find a part of the path 'C:\Users\luquinta.REDMOND\AppData\Local\Temp\MLVSTools\BugBashModelBuilder01282020ML\BugBashModelBuilder01282020ML.Model\bestModel.onnx'.
