### ISSUE TITLE
[Azure] Error when using Standard_NV12 Compute

### ISSUE THREAD

**Issue by luisquintanilla** [dotnet/machinelearning-modelbuilder#526]
**System Information (please complete the following information):**
 - Model Builder Version: 16.0.2002.1901
 - Visual Studio Version: VS2017

**Describe the bug**
When training an image classification model in Azure using Standard_NV12 compute, an error is thrown once training is complete.

**Expected behavior**
Model trains successfully

## Additional Context

Training data consists of weather dataset with 1125 images. 

###  Compute Properties

![image](https://user-images.githubusercontent.com/46974588/74871355-53a04b80-5329-11ea-86ed-c61d288ba5a4.png)

### Dialog Box + Stack Trace

![image](https://user-images.githubusercontent.com/46974588/74871431-75013780-5329-11ea-9776-0ef9b7ff96b4.png)

**Object reference not set to an instance of an object.**

```
at AzureML.AutoMLRunnerImages.<RunAutoMLAsync>d__29.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ML.ModelBuilder.AutoMLService.Experiments.AzureImageClassificationExperiment.<ExecuteAsync>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ML.ModelBuilder.AutoMLEngine.<StartTrainingAsync>d__28.MoveNext()
```

### Azure driver_log.txt

```
Starting the daemon thread to refresh tokens in background for process with pid = 125
Entering Run History Context Manager.
Preparing to call script [ hd_image_classification_dnn_driver.py ] with arguments: ['--data-folder', '/mnt/batch/tasks/shared/LS_root/jobs/mbwkspc/azureml/automl_7fdc920f-d244-403b-93f1-d720129104e0_hd_0/mounts/workspaceblobstore', '--labels-file-root', '/mnt/batch/tasks/shared/LS_root/jobs/mbwkspc/azureml/automl_7fdc920f-d244-403b-93f1-d720129104e0_hd_0/mounts/workspaceblobstore', '--model_name', 'seresnext', '--strategy', 'diff_lr']
After variable expansion, calling script [ hd_image_classification_dnn_driver.py ] with arguments: ['--data-folder', '/mnt/batch/tasks/shared/LS_root/jobs/mbwkspc/azureml/automl_7fdc920f-d244-403b-93f1-d720129104e0_hd_0/mounts/workspaceblobstore', '--labels-file-root', '/mnt/batch/tasks/shared/LS_root/jobs/mbwkspc/azureml/automl_7fdc920f-d244-403b-93f1-d720129104e0_hd_0/mounts/workspaceblobstore', '--model_name', 'seresnext', '--strategy', 'diff_lr']

Downloading: "https://automlcesdkdataresources.blob.core.windows.net/models-vision-pretrained/se_resnext50_32x4d-a260b3a4.pth" to /root/.cache/torch/checkpoints/se_resnext50_32x4d-a260b3a4.pth

  0%|          | 0.00/105M [00:00<?, ?B/s]
  0%|          | 144k/105M [00:00<01:18, 1.41MB/s]
  1%|          | 944k/105M [00:00<00:58, 1.87MB/s]
  4%|▍         | 4.01M/105M [00:00<00:41, 2.58MB/s]
  8%|▊         | 8.01M/105M [00:00<00:28, 3.58MB/s]
 12%|█▏        | 12.8M/105M [00:00<00:19, 4.88MB/s]
 14%|█▍        | 14.9M/105M [00:01<00:24, 3.95MB/s]
 16%|█▌        | 16.4M/105M [00:01<00:22, 4.22MB/s]
 17%|█▋        | 17.6M/105M [00:02<00:23, 3.89MB/s]
 18%|█▊        | 18.6M/105M [00:02<00:22, 4.03MB/s]
 18%|█▊        | 19.4M/105M [00:02<00:22, 4.08MB/s]
 19%|█▉        | 20.1M/105M [00:02<00:22, 4.01MB/s]
 20%|█▉        | 20.6M/105M [00:02<00:20, 4.36MB/s]
 20%|██        | 21.2M/105M [00:02<00:18, 4.68MB/s]
 21%|██        | 21.9M/105M [00:03<00:17, 4.89MB/s]
 21%|██▏       | 22.5M/105M [00:03<00:17, 5.07MB/s]
 22%|██▏       | 23.1M/105M [00:03<00:16, 5.37MB/s]
 23%|██▎       | 23.9M/105M [00:03<00:14, 5.74MB/s]
 23%|██▎       | 24.5M/105M [00:03<00:14, 5.73MB/s]
 24%|██▍       | 25.1M/105M [00:03<00:14, 5.76MB/s]
 24%|██▍       | 25.8M/105M [00:03<00:13, 6.00MB/s]
 25%|██▌       | 26.6M/105M [00:03<00:13, 6.34MB/s]
 26%|██▌       | 27.4M/105M [00:03<00:11, 6.82MB/s]
 27%|██▋       | 28.1M/105M [00:04<00:11, 6.76MB/s]
 28%|██▊       | 29.0M/105M [00:04<00:11, 7.25MB/s]
 29%|██▊       | 30.1M/105M [00:04<00:09, 8.00MB/s]
 30%|██▉       | 31.4M/105M [00:04<00:08, 8.81MB/s]
 31%|███       | 32.2M/105M [00:04<00:08, 8.83MB/s]
 32%|███▏      | 33.4M/105M [00:04<00:08, 9.36MB/s]
 33%|███▎      | 34.9M/105M [00:04<00:07, 10.5MB/s]
 34%|███▍      | 36.0M/105M [00:04<00:06, 10.7MB/s]
 36%|███▌      | 37.7M/105M [00:04<00:05, 11.9MB/s]
 37%|███▋      | 39.4M/105M [00:05<00:05, 12.7MB/s]
 39%|███▊      | 40.7M/105M [00:05<00:05, 12.7MB/s]
 40%|███▉      | 42.0M/105M [00:05<00:05, 12.8MB/s]
 42%|████▏     | 43.8M/105M [00:05<00:04, 13.9MB/s]
 43%|████▎     | 45.2M/105M [00:05<00:04, 13.9MB/s]
 45%|████▍     | 47.0M/105M [00:05<00:04, 14.7MB/s]
 46%|████▌     | 48.5M/105M [00:05<00:04, 14.8MB/s]
 48%|████▊     | 50.4M/105M [00:05<00:03, 15.5MB/s]
 49%|████▉     | 52.0M/105M [00:05<00:03, 14.3MB/s]
 51%|█████     | 53.9M/105M [00:06<00:03, 15.2MB/s]
 53%|█████▎    | 56.0M/105M [00:06<00:03, 16.3MB/s]
 55%|█████▍    | 57.6M/105M [00:06<00:03, 16.2MB/s]
 56%|█████▌    | 59.3M/105M [00:06<00:02, 16.3MB/s]
 58%|█████▊    | 60.9M/105M [00:06<00:02, 15.9MB/s]
 60%|█████▉    | 62.8M/105M [00:06<00:02, 16.5MB/s]
 61%|██████    | 64.4M/105M [00:06<00:02, 16.1MB/s]
 63%|██████▎   | 66.4M/105M [00:06<00:02, 16.9MB/s]
 65%|██████▍   | 68.0M/105M [00:06<00:02, 16.8MB/s]
 67%|██████▋   | 70.6M/105M [00:07<00:01, 18.4MB/s]
 69%|██████▊   | 72.4M/105M [00:07<00:01, 18.4MB/s]
 71%|███████   | 74.4M/105M [00:07<00:01, 18.8MB/s]
 72%|███████▏  | 76.3M/105M [00:07<00:01, 18.6MB/s]
 75%|███████▍  | 78.7M/105M [00:07<00:01, 19.7MB/s]
 77%|███████▋  | 80.7M/105M [00:07<00:01, 20.0MB/s]
 79%|███████▉  | 83.4M/105M [00:07<00:01, 21.3MB/s]
 81%|████████  | 85.5M/105M [00:07<00:00, 21.3MB/s]
 83%|████████▎ | 88.0M/105M [00:07<00:00, 20.7MB/s]
 86%|████████▌ | 90.6M/105M [00:08<00:00, 21.6MB/s]
 88%|████████▊ | 92.7M/105M [00:08<00:00, 19.9MB/s]
 90%|█████████ | 95.3M/105M [00:08<00:00, 21.0MB/s]
 92%|█████████▏| 97.3M/105M [00:08<00:00, 19.2MB/s]
 95%|█████████▍| 100M/105M [00:08<00:00, 19.8MB/s] 
 97%|█████████▋| 103M/105M [00:08<00:00, 21.2MB/s]
 99%|█████████▉| 105M/105M [00:08<00:00, 20.3MB/s]
100%|██████████| 105M/105M [00:08<00:00, 12.5MB/s]
[model: seresnext, #param: 25519092]
[start training: train batch_size: 80, val batch_size: 80]
Type: Unclassified
Class: RuntimeError
Message: [Hidden as it may contain PII]
Traceback:
[Hidden as it may contain PII]


The experiment failed. Finalizing run...
Cleaning up all outstanding Run operations, waiting 300.0 seconds
2 items cleaning up...
Cleanup took 0.0015499591827392578 seconds
Starting the daemon thread to refresh tokens in background for process with pid = 125
Traceback (most recent call last):
  File "hd_image_classification_dnn_driver.py", line 6, in <module>
    runner.run(automl_settings, multilabel=False)
  File "/azureml-envs/azureml_a978bb0284b9ce9dc72c2755c7eeaa98/lib/python3.7/site-packages/azureml/contrib/automl/dnn/vision/classification/runner.py", line 142, in run
    settings=automl_settings)
  File "/azureml-envs/azureml_a978bb0284b9ce9dc72c2755c7eeaa98/lib/python3.7/site-packages/azureml/contrib/automl/dnn/vision/classification/trainer/trainer.py", line 138, in train_model
    device=device, multilabel=multilabel)
  File "/azureml-envs/azureml_a978bb0284b9ce9dc72c2755c7eeaa98/lib/python3.7/site-packages/azureml/contrib/automl/dnn/vision/classification/trainer/trainer.py", line 240, in _train
    outputs = model_wrapper.model(inputs)
  File "/azureml-envs/azureml_a978bb0284b9ce9dc72c2755c7eeaa98/lib/python3.7/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/azureml-envs/azureml_a978bb0284b9ce9dc72c2755c7eeaa98/lib/python3.7/site-packages/pretrainedmodels/models/senet.py", line 364, in forward
    x = self.features(x)
  File "/azureml-envs/azureml_a978bb0284b9ce9dc72c2755c7eeaa98/lib/python3.7/site-packages/pretrainedmodels/models/senet.py", line 350, in features
    x = self.layer2(x)
  File "/azureml-envs/azureml_a978bb0284b9ce9dc72c2755c7eeaa98/lib/python3.7/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/azureml-envs/azureml_a978bb0284b9ce9dc72c2755c7eeaa98/lib/python3.7/site-packages/torch/nn/modules/container.py", line 92, in forward
    input = module(input)
  File "/azureml-envs/azureml_a978bb0284b9ce9dc72c2755c7eeaa98/lib/python3.7/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/azureml-envs/azureml_a978bb0284b9ce9dc72c2755c7eeaa98/lib/python3.7/site-packages/pretrainedmodels/models/senet.py", line 123, in forward
    out = self.bn3(out)
  File "/azureml-envs/azureml_a978bb0284b9ce9dc72c2755c7eeaa98/lib/python3.7/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/azureml-envs/azureml_a978bb0284b9ce9dc72c2755c7eeaa98/lib/python3.7/site-packages/torch/nn/modules/batchnorm.py", line 81, in forward
    exponential_average_factor, self.eps)
  File "/azureml-envs/azureml_a978bb0284b9ce9dc72c2755c7eeaa98/lib/python3.7/site-packages/torch/nn/functional.py", line 1670, in batch_norm
    training, momentum, eps, torch.backends.cudnn.enabled
RuntimeError: CUDA out of memory. Tried to allocate 124.00 MiB (GPU 0; 7.94 GiB total capacity; 7.38 GiB already allocated; 61.00 MiB free; 54.97 MiB cached)

2020/02/19 19:55:52 mpirun version string: {
mpirun (Open MPI) 3.1.2

Report bugs to http://www.open-mpi.org/community/help/
}
```

**Comment by JakeRadMSFT** [comment]
@beccamc, 

RuntimeError: CUDA out of memory. Tried to allocate 124.00 MiB (GPU 0; 7.94 GiB total capacity; 7.38 GiB already allocated; 61.00 MiB free; 54.97 MiB cached)

https://docs.microsoft.com/en-us/azure/virtual-machines/linux/sizes-gpu#deployment-considerations

**Comment by beccamc** [comment]
@justinormont Can you help with this? The machine has 24 GPU GB based on the specs, but it seems to be running out of memory and failing.

**Comment by JakeRadMSFT** [comment]
Lets filter out all NV.

**Comment by justinormont** [comment]
Optimizing for multi-GPUs is work in progress.

Two options:
* Disallow VMs with <= 14GB of RAM per GPU
* Reduce the batch size

I agree w/ @JakeRadMSFT's suggestion. I'd go with the option to filter these VM SKUs for the moment. Generally I'd rather avoid having Model Builder consider hyperparameters like `batch size` and the closely tied-together `learning rate`; hyperparameters should be the domain of the AutoML code.
