### ISSUE TITLE
Error creating Workspace

### ISSUE THREAD

**Issue by JakeRadMSFT** [dotnet/machinelearning-modelbuilder#534]
Index and length must refer to a location within the string.
Parameter name: length

   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at StreamJsonRpc.JsonRpc.<InvokeCoreAsync>d__94`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ML.ModelBuilder.AutoMLServiceFactory.AutoMLServiceProxy.<PutCreateWorkspaceAsync>d__28.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ML.ModelBuilder.AzureAttach.NewWorkspaceDataContext.<CreateWorkspaceAsync>d__31.MoveNext()

![image](https://user-images.githubusercontent.com/31937616/75044850-26fa4a00-5477-11ea-9ce8-b0b7edaecf1d.png)

**Comment by beccamc** [comment]
Dup of #543. Closing.
