### ISSUE TITLE
Image Classification - Model Builder

### ISSUE THREAD

**Issue by rasikhegde** [dotnet/machinelearning-modelbuilder#601]
Below was the error while training the model for image classification

  at System.Linq.Enumerable.Select[TSource,TResult](IEnumerable`1 source, Func`2 selector)
   at Microsoft.ML.ModelBuilder.AutoMLService.Experiments.AutoMLExperiment`3.<ExecuteAsync>d__23.MoveNext() in E:\A\_work\1326\s\Microsoft.ML.ModelBuilder.AutoMLService\Experiments\AutoMLExperiment.cs:line 117
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ML.ModelBuilder.AutoMLEngine.<StartTrainingAsync>d__28.MoveNext() in E:\A\_work\1326\s\Microsoft.ML.ModelBuilder.AutoMLService\AutoMLEngineService\AutoMLEngine.cs:line 134

**Comment by LittleLittleCloud** [comment]
Could you show us error message other than the stack trace

regards

**Comment by beccamc** [comment]
@rasikhegde Can you provide more information about the problem, including the error message. Are you still seeing a problem?

**Comment by beccamc** [comment]
![image](https://user-images.githubusercontent.com/9122518/79489754-a10b0300-7fd0-11ea-9cfa-76d9089b111d.png)
