### ISSUE TITLE
Value cannot be null. Parameter name: process (ErrorKind: Error HResult: 80004003)

### ISSUE THREAD

**Issue by arodrigu12** [dotnet/machinelearning-modelbuilder#643]
**System Information (please complete the following information):**
 - Model Builder Version: the latest as of 3/20/2020
 - Visual Studio Version: Microsoft Visual Studio Community 2019
Version 16.5.1

Additional information about my system:
System Type	X86-based PC
Processor	Pentium(R) Dual-Core CPU       T4400  @ 2.20GHz, 2200 Mhz, 2 Core(s), 2 Logical Processor(s)
Installed Physical Memory (RAM)	3.00 GB

**Describe the bug**
Training step of the ML.NET introductory tutorial did not complete. Received the following error: ErrorKind: Error HResult: 80004003. See below for details.

**To Reproduce**
Steps to reproduce the behavior: Follow tutorial exactly as indicated.

**Expected behavior**
I expected the Train step to complete successfully

**Screenshots**

**Additional context**
Model Builder Error

Value cannot be null.
Parameter name: process (ErrorKind: Error HResult: 80004003)

   at StreamJsonRpc.JsonRpc.<InvokeCoreAsync>d__115`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ServiceHub.Client.HubClient.RemoteServiceBrokerWrapper.<>c__DisplayClass9_1.<<RequestServiceChannelAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.ServiceHub.Client.HubClient.RemoteServiceBrokerWrapper.<>c__DisplayClass9_1.<<RequestServiceChannelAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ServiceHub.Utility.Shared.ServiceHubRetry.<ExecuteAsync>d__0`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.ServiceHub.Utility.Shared.ServiceHubRetry.<ExecuteAsync>d__0`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ServiceHub.Client.HubClient.RemoteServiceBrokerWrapper.<RequestServiceChannelAsync>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ServiceHub.Framework.RemoteServiceBroker.<GetPipeAsync>d__31.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ServiceHub.Client.HubClient.<GetPipeAsync>d__34.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ServiceHub.Client.HubClient.<RequestServiceAsync>d__31.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ML.ModelBuilder.AutoMLServiceFactory.<CreateAutoMLServiceAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ML.ModelBuilder.TrainSession.<InitializeAutoMLServiceAsync>d__59.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ML.ModelBuilder.TrainSession.<StartAsync>d__48.MoveNext()

**Comment by LittleLittleCloud** [comment]
Thanks for your report, Unfortunately, the training engine in ModelBuilder is x64 based, so you can't start training on a x86-based system. Sorry for the inconvenience.

**Comment by LittleLittleCloud** [comment]
Closing this issue due to no response,  if you're still seeing a problem, feel free to reopen it, thanks for reporting!
