### ISSUE TITLE
Update SQL to use streaming to fix System.OutOfMemoryException

### ISSUE THREAD

**Issue by barlowjc** [dotnet/machinelearning-modelbuilder#647]
Problem encountered on https://dotnet.microsoft.com/learn/ml-dotnet/get-started-tutorial/train
Operating System: windows

First off, I am new to ML.NET (and ML as a whole) and I've never filed a bug on GitHub so... sorry if I suck at this. 

I am trying to set up a model using a SQL Server table as my data source. I am selecting one label and 18 features from the same table and this table contains a little more than 3 million records in it. When I finish selecting my label/features and click on the Train button, I get a prompt telling me that VS will download 1.1 GB of data from the SQL Server (hosted on the same machine) which I acknowledge. I get feedback indicating that the download is in progress and this lasts for 30 - 60 seconds. Then I get the following error:

`Error retrieving SQL data: "Exception of type 'System.OutOfMemoryException' was thrown."
   at Microsoft.ML.ModelBuilder.ToolWindows.ModelBuilderDataContext.<DownloadSqlFileAsync>b__88_0()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ML.ModelBuilder.ToolWindows.ModelBuilderDataContext.<DownloadSqlFileAsync>d__88.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ML.ModelBuilder.ToolWindows.ModelBuilderDataContext.<<OnDataChanged>b__77_1>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ML.ModelBuilder.ToolWindows.TrainTabDataContext.<BuildTrainModelParametersAsync>d__138.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ML.ModelBuilder.ToolWindows.TrainTabDataContext.<StartTrainingAsync>d__130.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.ML.ModelBuilder.ToolWindows.TrainTabControl.<<StartTraining_Click>b__5_0>d.MoveNext()`

Some fun facts:

- I've watched the RAM count on the machine while the attempt to train is made and it's not getting above 65% of total RAM available.

- In the same VS solution, I have another app where I routinely read the entirety of the table in question into memory via EF.

- I am using Windows 10 Pro, VS 2019 Community, and SQL Express (14.0.1000).  

- I am using the ML.NET Model Builder (Preview) v16.0.2003.302

- My project was targeting .NET Core 2.1 when I started but I rolled forward to 3.1 to see if that helped (it did not)

- I see the RAM count increase by maybe 3 or so GB before the error occurs. It smells so badly like it's running the process in 32-bit (which would make sense of all of this) but if there's a setting for this, I can't find it. I've checked the Build properties for my ML project and made sure that's set to 64-bit but I'm not sure that's even what is being used when you're training the model.

**Comment by LittleLittleCloud** [comment]
Sorry for the late reply
ModelBuilder is a 32-bit extension since Visual Studio is 32bit. So it can reach only 4 GB Ram at most.
@beccamc Maybe we need to use streaming to download large sql and write to file

**Comment by JakeRadMSFT** [comment]
@LittleLittleCloud we should move the SQL code to a ServiceHubService - It's 64bit over there.

Also, why would we need more than 4gb at a time. It should be streaming?

**Comment by JakeRadMSFT** [comment]
I can't get this to work ... I'm blocked by this:

https://app.zenhub.com/workspaces/mlnet-tools-5cde1c97e3106e39e8ae08fc/issues/dotnet/machinelearning-modelbuilder/1293

Seems to throw the same error for connecting from file too.

**Comment by vzhuqin** [comment]
@beccamc  could you help to validate this issue as I do not have the suitable dataset to verify?

**Comment by beccamc** [comment]
Sure, I can validate

**Comment by beccamc** [comment]
I'm closing this, will reopen if any customers run into trouble.
