### ISSUE TITLE
"Cannot find service module info file" Exception during training-stage

### ISSUE THREAD

**Issue by frankhaugen** [dotnet/machinelearning-modelbuilder#654]
**System Information (please complete the following information):**
 - Model Builder Version: 16.0.2003.302
 - Visual Studio Version: 16.6.0 Preview 2.1

(Stack trace and csv-data at the bottom)

**Describe the bug**
When running the training in the Model Builder it crashes with a "Cannot find service module info file"

Detailed message:
```
Cannot find service module info file 'MicrosoftMLModelBuilderAutoML.servicehub.service.json' in 'C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\common7\ServiceHub\Services' (ErrorKind: ServiceModuleInfoNotFound)
```

**To Reproduce**
1. Start the Ml.net Model Builder
2. Select "Custom Scenario"
3. On "Add Data"-page add the file (bottom of this post, rename from txt to csv)
4. Select "Survived" as Label
5. Let Features be the four remaining columns
6. Go to "Train"-page and set task to "Multiclass-classification", and train time to 60 seconds
7. Get exception, (with little information about finding a solution and a link to report bug here)

**Expected behavior**
The training to finish without incident, (or the error message to be more helpful)

**Screenshots**
Data step:
![image](https://user-images.githubusercontent.com/13543585/78461745-f2132100-76cb-11ea-9975-2580a20b38a5.png)

Error message:
![image](https://user-images.githubusercontent.com/13543585/78462042-c6de0100-76ce-11ea-936c-41732a0a9742.png)

Train step, after error occurred:
![image](https://user-images.githubusercontent.com/13543585/78461727-d740ac80-76cb-11ea-9f25-52d5c50d8051.png)

**Stack Trace**
```
   at StreamJsonRpc.JsonRpc.<InvokeCoreAsync>d__115`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ServiceHub.Client.HubClient.RemoteServiceBrokerWrapper.<>c__DisplayClass9_0.<<RequestServiceChannelAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.ServiceHub.Client.HubClient.RemoteServiceBrokerWrapper.<>c__DisplayClass9_0.<<RequestServiceChannelAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ServiceHub.Utility.Shared.ServiceHubRetry.<ExecuteAsync>d__0`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.ServiceHub.Utility.Shared.ServiceHubRetry.<ExecuteAsync>d__0`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ServiceHub.Client.HubClient.RemoteServiceBrokerWrapper.<RequestServiceChannelAsync>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ServiceHub.Framework.RemoteServiceBroker.<GetPipeAsync>d__31.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ServiceHub.Client.HubClient.<GetPipeAsync>d__34.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ServiceHub.Client.HubClient.<RequestServiceAsync>d__31.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ML.ModelBuilder.AutoMLServiceFactory.<CreateAutoMLServiceAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ML.ModelBuilder.TrainSession.<InitializeAutoMLServiceAsync>d__59.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ML.ModelBuilder.TrainSession.<StartAsync>d__48.MoveNext()
```

**Data**
[full2.txt](https://github.com/dotnet/machinelearning-modelbuilder/files/4432568/full2.txt)

**Comment by frankhaugen** [comment]
@JakeRadMSFT Have you had the opportunity to investigate this?

**Comment by beccamc** [comment]
@frankhaugen Thanks for reporting with details, it makes the investigation much easier! 

As of VS version 16.6 Preview 2, we've started shipping Model Builder with VS instead of as an extension. Based on your version numbers above, it looks like you have the VS with Model Builder (16.6 Preview 2) and Model Builder installed as an extension (16.0.2003.302).  Could you try uninstalling Model Builder as the extension, and using the preview feature?

You probably know you can uninstall an extension via the Manage Extensions window -> Uninstall. You can then enable the VS Model Builder in the Preview Features window. 
![image](https://user-images.githubusercontent.com/9122518/79488581-cac32a80-7fce-11ea-8dc5-c20c16dcd348.png)

Could you please give this a try and see if it resolves the problem? Thanks!

**Comment by frankhaugen** [comment]
@beccamc Thank you for a detailed reply, and your praise, and the training now works great

__But evaluating on the other hand__
![image](https://user-images.githubusercontent.com/13543585/79556665-ae43f280-80a1-11ea-9d9b-dc7f89ad2af2.png)


```
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at StreamJsonRpc.JsonRpc.<InvokeCoreAsync>d__94`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ML.ModelBuilder.AutoMLServiceFactory.AutoMLServiceProxy.<PredictMultiClassClassificationAsync>d__16.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ML.ModelBuilder.TrainSession.<PredictMultiClassClassificationAsync>d__49.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.ML.ModelBuilder.ToolWindows.EvaluateTabDataContext.<MulticlassficationAsync>d__143.MoveNext()
```

The bugs here is that the error message could be fleshed out to include "expecting X got Y", and that the default suggestion, (based on a random row), should never be able to fail due to a "format exception"

Should I file a new issue??

**Comment by beccamc** [comment]
@frankhaugen I'm glad the work around fixed it!  Let's move to a new issue for the Try It Out issue. I've filed a new one here - #682 

Thanks for finding and reporting these bugs!
