### ISSUE TITLE
Initial Try It Out input shouldn't fail & failure should have better message

### ISSUE THREAD

**Issue by beccamc** [dotnet/machinelearning-modelbuilder#682]
Reported by @frankhaugen

Try it out's initial random row may contain invalid data. 

The bugs here is that the error message could be fleshed out to include "expecting X got Y", and that the default suggestion, (based on a random row), should never be able to fail due to a "format exception"

![image.png](https://images.zenhubusercontent.com/5d55c3d68fac840001314eaa/d2206dfe-3b3a-40dd-95e1-2d98e7939cd4)

   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at StreamJsonRpc.JsonRpc.<InvokeCoreAsync>d__94`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ML.ModelBuilder.AutoMLServiceFactory.AutoMLServiceProxy.<PredictMultiClassClassificationAsync>d__16.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ML.ModelBuilder.TrainSession.<PredictMultiClassClassificationAsync>d__49.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.ML.ModelBuilder.ToolWindows.EvaluateTabDataContext.<MulticlassficationAsync>d__143.MoveNext()

**Comment by beccamc** [comment]
1. This should be an expected exception
2.  Message should be more descriptive, e.g. "expecting X got Y"
3. Ensure pre-filled value is valid

**Comment by beccamc** [comment]
This is fixed by https://github.com/dotnet/machinelearning-tools/pull/812
