### ISSUE TITLE
Vehicles.csv - Unable to split the file provided into multiple, consistent columns.

### ISSUE THREAD

**Issue by luisquintanilla** [dotnet/machinelearning-modelbuilder#731]
**System Information (please complete the following information):**
 - Model Builder Version: 16.1.0.2021002
 - Visual Studio Version: VS 2019 16.6 Preview 4

**Describe the bug**

I used the following dataset: https://www.kaggle.com/austinreese/craigslist-carstrucks-data

It's sparse and is 1.4 GB. Here is the error and stack trace:

```text
Unable to split the file provided into multiple, consistent columns.

   at Microsoft.ML.AutoML.ColumnInferenceApi.InferSplit(MLContext context, TextFileSample sample, Nullable`1 separatorChar, Nullable`1 allowQuotedStrings, Nullable`1 supportSparse)
   at Microsoft.ML.AutoML.ColumnInferenceApi.InferColumns(MLContext context, String path, ColumnInformation columnInfo, Nullable`1 separatorChar, Nullable`1 allowQuotedStrings, Nullable`1 supportSparse, Boolean trimWhitespace, Boolean groupColumns, Boolean hasHeader)
   at Microsoft.ML.ModelBuilder.AutoMLEngine.InferColumns(MLContext context, AutoMLServiceParamater config, ColumnInformation columnInformation)
   at Microsoft.ML.ModelBuilder.AutoMLEngine.<StartTrainingAsync>d__30.MoveNext() in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/AutoMLEngineService/AutoMLEngine.cs:line 112
```

**Comment by JakeRadMSFT** [comment]
@beccamc do we know what's causing this to fail?

@luisquintanilla - is it failing during training or data preview?

**Comment by luisquintanilla** [comment]
@JakeRadMSFT data preview

**Comment by beccamc** [comment]
Open investigations: 
- Can we move the InferColumns call (or similar functionality) to data page? 
- Can Prose do this for us instead?

**Comment by beccamc** [comment]
See Prose example file [https://app.zenhub.com/files/186917455/c3748d27-2c7a-4b4f-bdb4-409238e61671/download](https://app.zenhub.com/files/186917455/c3748d27-2c7a-4b4f-bdb4-409238e61671/download)

**Comment by beccamc** [comment]
I successfully trained this dataset (it to two hours but it finished!)
