### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by islamelgaidi** [dotnet/machinelearning-modelbuilder#732]
Problem encountered on https://dotnet.microsoft.com/learn/ml-dotnet/get-started-tutorial/install
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

06/05/2020 21:25:33 - Found setup instance a1e14ef5 but not in launchable state.
06/05/2020 21:25:33 - Install Error : System.I
[VSIXInstaller_4ea8e0d4-cba0-42fe-be53-3b8c0d6b756b.log](https://github.com/dotnet/machinelearning-modelbuilder/files/4589062/VSIXInstaller_4ea8e0d4-cba0-42fe-be53-3b8c0d6b756b.log)
nvalidOperationException: Cannot find setup engine instance.
   at Microsoft.VisualStudio.ExtensionManager.SetupEngineUtility.GetCurrentSetupInstance(IEngineHost engineHost)
   at Microsoft.VisualStudio.ExtensionManager.SetupEngineService.CreateEngine(IEngineHost engineHost, IServiceProvider serviceProvider, InstallFlags installFlags)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.PerformSetupEngineInstall(InstallableExtensionImpl extension, Boolean installPerMachine, Boolean isPackComponent, IDictionary`2 extensionsInstalledSoFar, List`1 extensionsUninstalledSoFar, IInstalledExtensionList modifiedInstalledExtensionsList, IProgress`1 progress, InstallFlags installFlags, AsyncOperation asyncOp, Version targetedVsVersion, IInstalledExtension& newExtension)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.InstallInternal(InstallableExtensionImpl extension, InstallFlags installFlags, IDictionary`2 extensionsInstalledSoFar, List`1 extensionsUninstalledSoFar, IInstalledExtensionList modifiedInstalledExtensionsList, AsyncOperation asyncOp, IProgress`1 progress, Version targetedVsVersion)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.BeginInstall(IInstallableExtension installableExtension, InstallFlags installFlags, AsyncOperation asyncOp, Version targetedVsVersion)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.InstallWorker(IInstallableExtension extension, InstallFlags installFlags, AsyncOperation asyncOp)

**Comment by beccamc** [comment]
Thanks for reporting @islamelgaidi and sorry you're running into issues. This looks like a problem with Visual Studio. Can you try to update VS? If that doesn't work can you try to repair VS?

**Comment by beccamc** [comment]
@islamelgaidi Are you still seeing problems?

**Comment by beccamc** [comment]
@islamelgaidi Closing this issue as I don't have enough information to help solve the problem. If you still need help please reopen!
