### ISSUE TITLE
Model Builder Error

### ISSUE THREAD

**Issue by jmorfeu** [dotnet/machinelearning-modelbuilder#766]
**System Information (please complete the following information):**
 - Model Builder Version: 16.0.2003.302
 - Visual Studio Version: Microsoft Visual Studio Community 2019
Version 16.3.8

**Describe the bug**
   at Microsoft.ML.ModelBuilder.AutoMLService.Experiments.AutoMLExperiment`3.<ExecuteAsync>d__23.MoveNext() in E:\A\_work\1326\s\Microsoft.ML.ModelBuilder.AutoMLService\Experiments\AutoMLExperiment.cs:line 103
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ML.ModelBuilder.AutoMLEngine.<StartTrainingAsync>d__28.MoveNext() in E:\A\_work\1326\s\Microsoft.ML.ModelBuilder.AutoMLService\AutoMLEngineService\AutoMLEngine.cs:line 134

**To Reproduce**
1. Create a New Proyect
2. Add ML 
3. Go ahead until Traing when it finish launch the error

**Comment by JakeRadMSFT** [comment]
Hello, 
Thanks for reporting this issue.  In order to help, I need more information. 

Can you share the following details:
- What scenario type did you run?
- Can you share the dataset or information about it?

Cheers,
Jake

**Comment by JakeRadMSFT** [comment]
Resolving this due to lack of details/response. Please provide more details and re-open!

@jmorfeu Sorry you're hitting this issue! We'd love to help but need more information.
