### ISSUE TITLE
Value cannot be null. Parameter name: source

### ISSUE THREAD

**Issue by sajadbaghalaghdam** [dotnet/machinelearning-modelbuilder#768]
at System.Linq.Enumerable.Select[TSource,TResult](IEnumerable`1 source, Func`2 selector)
   at Microsoft.ML.ModelBuilder.AutoMLService.Experiments.AutoMLExperiment`3.<ExecuteAsync>d__23.MoveNext() in E:\A\_work\1326\s\Microsoft.ML.ModelBuilder.AutoMLService\Experiments\AutoMLExperiment.cs:line 117
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ML.ModelBuilder.AutoMLEngine.<StartTrainingAsync>d__28.MoveNext() in E:\A\_work\1326\s\Microsoft.ML.ModelBuilder.AutoMLService\AutoMLEngineService\AutoMLEngine.cs:line 134

**Comment by JakeRadMSFT** [comment]
Hello, 
Thanks for reporting this issue.  In order to help, I need more information. 

Can you share the following details:
- Visual Studio Version
- Model Builder Version
- What scenario type did you run?
- Can you share the dataset or information about it?

Cheers,
Jake

**Comment by JakeRadMSFT** [comment]
@sajadbaghalaghdam resolving due to lack of activity and not enough details.

If you're still hitting this issue - Please re-open and provide the details requested above.

Cheers,
Jake
