### ISSUE TITLE
ML.net Model builder Azure machine learning can't create enterprise workspace 

### ISSUE THREAD

**Issue by lonewolfnsp** [dotnet/machinelearning-modelbuilder#797]
when trying to set up Azure workspace for machine learning, it keeps failing wyhen  trying to create the workspace with error: "Long running operation failed with status: 'failed'. Additional info: at least one resource deployment operation failed.

nelow is the defails: 
   at Microsoft.Rest.ClientRuntime.Azure.LRO.AzureLRO`2.CheckForErrors()
   at Microsoft.Rest.ClientRuntime.Azure.LRO.PutLRO`2.CheckForErrors()
   at Microsoft.Rest.ClientRuntime.Azure.LRO.AzureLRO`2.<StartPollingAsync>d__20.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Rest.ClientRuntime.Azure.LRO.AzureLRO`2.<BeginLROAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Rest.Azure.AzureClientExtensions.<GetLongRunningOperationResultAsync>d__1`2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Rest.Azure.AzureClientExtensions.<GetLongRunningOperationResultAsync>d__0`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Rest.Azure.AzureClientExtensions.<GetPutOrPatchOperationResultAsync>d__5`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.Azure.Management.ResourceManager.Fluent.DeploymentsOperations.<CreateOrUpdateWithHttpMessagesAsync>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.Azure.Management.ResourceManager.Fluent.DeploymentsOperationsExtensions.<CreateOrUpdateAsync>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.Azure.Management.ResourceManager.Fluent.DeploymentImpl.<CreateResourceAsync>d__60.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.Azure.Management.ResourceManager.Fluent.DeploymentImpl.<CreateAsync>d__59.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Azure.MachineLearning.Services.Workspaces.WorkspaceOperations.<CreateAsync>d__10.MoveNext() in /_/src/Microsoft.ML.AzureMLClient/Workspaces/WorkspaceOperations.cs:line 187
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Azure.MachineLearning.Services.AMLRest.AzureAttachManager.<PutCreateWorkspaceAsync>d__10.MoveNext() in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/AMLRest/AzureAttachManager.cs:line 131
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ML.ModelBuilder.AutoMLEngine.<PutCreateWorkspaceAsync>d__43.MoveNext() in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/AutoMLEngineService/AutoMLEngine.cs:line 265

What do I need to do?

**Comment by beccamc** [comment]
@lonewolfnsp  Thanks for using our Azure experience and for reporting problems! Can you try two things? Go to portal.azure.com...

1. Check the _Notifications_ -> _Activity Log_. The stack trace isn't giving me a good idea of what went wrong in the create process. Can you see if Azure logged something there regarding the failed create?
![image](https://user-images.githubusercontent.com/9122518/83669927-32d1ce00-a587-11ea-875a-a8fb39edab57.png)


2. Can you try to create a workspace from the portal? I want to see if there is something off with the subscription and the portal gives us more information.  Go to https://ms.portal.azure.com/#create/Microsoft.MachineLearningServices. Make sure you select Workspace edition: "Enterprise". You also should select from one of these regions                 `"australiaeast", "northeurope", "westeurope", "uksouth","eastus", "eastus2", "northcentralus", "southcentralus", "westus2"`. 

![image](https://user-images.githubusercontent.com/9122518/83670072-6f9dc500-a587-11ea-8319-ac91fb876265.png)


Thanks in advance!

**Comment by lonewolfnsp** [comment]
> 
> 
> @lonewolfnsp Thanks for using our Azure experience and for reporting problems! Can you try two things? Go to portal.azure.com...
> 
>     1. Check the _Notifications_ -> _Activity Log_. The stack trace isn't giving me a good idea of what went wrong in the create process. Can you see if Azure logged something there regarding the failed create?
>        ![image](https://user-images.githubusercontent.com/9122518/83669927-32d1ce00-a587-11ea-875a-a8fb39edab57.png)
> 
>     2. Can you try to create a workspace from the portal? I want to see if there is something off with the subscription and the portal gives us more information.  Go to https://ms.portal.azure.com/#create/Microsoft.MachineLearningServices. Make sure you select Workspace edition: "Enterprise". You also should select from one of these regions                 `"australiaeast", "northeurope", "westeurope", "uksouth","eastus", "eastus2", "northcentralus", "southcentralus", "westus2"`.
> 
> 
> ![image](https://user-images.githubusercontent.com/9122518/83670072-6f9dc500-a587-11ea-8319-ac91fb876265.png)
> 
> Thanks in advance!

I
I tried recreating the Azure training using VS again, but I don't see any activity logs. However, the required resources are created in Azure, the container registry, key vault, storage, etc. It's just the ML's model builder that fails.. 

As for step 2, I was able to successfully create the enterprise workspace with the same resources allocated: container registry, key vault, etc.. 

One thing, does this have something to do with my location? I'm from Singapore.. not US... does it matter?

**Comment by beccamc** [comment]
@lonewolfnsp It could be a location issue. Now that it's created successfully can it be selected from model builder?

**Comment by lonewolfnsp** [comment]
> 
> 
> @lonewolfnsp It could be a location issue. Now that it's created successfully can it be selected from model builder?

I created a ML workspace in Azure specifying East US as region and from model builder in VS, I was able to specify it and used it for training. couple of things I noticed:
1. FAST! very fast! same dataset on my PC with i7-3770K took nearly 4 hrs, on Azure ML using GPU took only 32 mins.. AMAZING!
2. training locally, I don't see any onnx file generated after training, but Azure training will generate the onnx and jspn mapping file. Also, in terms of nugetr package required, local training uses tensorflow transformer wheras Azure GPU training requires onnx runtime and onnx transformer. 
3. I was not able to delete the resource group created by VS for those failed model builder runs. I deleted all resources used by the group manually, but when I tried to delete the empty resource griup, it won't allow me to. funny thing is, even after I manually add in a resource such as VM, and tried to delete the now "non empty" resource group, it would delete the newly added resources but not the group. group remains empty and cannot be deleted. 
So, in view of this, I guess, it's just an issue with the model builder and not region. 
any way I can help to improve it?

**Comment by TomJamesAtDataSummit** [comment]
I am having the same problem for model builder (object detection). If I try to "Create new workspace" via Visual Studio 
I receive an error message:

> Long running operation failed with status 'Failed'. Additional Info: 'At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.'

If I try to create this resource directly in Azure, the "Workspace Edition" drop down is no longer visible, so it's not possible this way either.
![image](https://user-images.githubusercontent.com/52748031/94588486-de600600-027b-11eb-848e-6ba6ed0436b1.png)

**Error Log File**
[8c590497-0a2d-4aa1-988a-027a9be6e492.txt](https://github.com/dotnet/machinelearning-modelbuilder/files/5300658/8c590497-0a2d-4aa1-988a-027a9be6e492.txt)

**Comment by beccamc** [comment]
@TomJamesAtDataSummit Thanks for the details! This looks like the same issue tracked here #1104.  We're working on a fix. Creating the resource directly in Azure should work, you can ignore the "Workspace Edition" field. Azure removed the option and makes everything an enterprise workspace. 

@lonewolfnsp I've seen more issues come in similar to this. I assume this was the first ML workspace you were creating in your subscription?

**Comment by beccamc** [comment]
I think this is the same problem as issue #1104. Creation of the first ML workspace fails for some users. There is a bug in the Azure templates we use for creation flow. If you go to the portal and create a workspace it should work. Visit https://ml.azure.com/ and it should guide you through creating a new workspace. 

Please look to 1104 for updates on fixing this issue. Thanks!
