### ISSUE TITLE
Error in Azure Training

### ISSUE THREAD

**Issue by justinormont** [dotnet/machinelearning-modelbuilder#803]
**System Information (please complete the following information):**
 - Model Builder Version: _(unknown, where is this?)_ Updated extension yesterday.
 - Visual Studio Version: Microsoft Visual Studio Enterprise 2019 Preview Version 16.6.0 Preview 2.1

**Describe the bug**
```
Object reference not set to an instance of an object.

at AzureML.AutoMLRunnerImages.<RunAutoMLAsync>d__27.MoveNext() in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/RemoteAutoML/AutoMLRunnerImages.cs:line 231
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ML.ModelBuilder.AutoMLService.Experiments.AzureImageClassificationExperiment.<ExecuteAsync>d__13.MoveNext() in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/Experiments/AzureImageClassificationExperiment.cs:line 69
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ML.ModelBuilder.AutoMLEngine.<StartTrainingAsync>d__30.MoveNext() in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/AutoMLEngineService/AutoMLEngine.cs:line 147

Please include run id AutoML_939342c2-984d-4669-b729-b3129c9a0e1c in the report
```

End of the training output is:
```
...
Running AutoML pipeline sweep...
Running AutoML pipeline sweep...
Child run status:Completed: 1, Canceled: 1

Running AutoML pipeline sweep...

Child run status:Completed: 1, Canceled: 1
Completed a training run
Downloading best model to C:\Users\jormont\AppData\Local\Temp\MLVSTools\Redacted_DatasetML\Redacted_DatasetML.Model\bestModel.onnx..
Object reference not set to an instance of an object.
```

Clicking the "Monitor current run in Azure portal", redirect to an error page:
![image](https://user-images.githubusercontent.com/4080826/83942212-6d658180-a7a6-11ea-8c6f-69e8e3c5d199.png)

This says the resource group wasn't found; the model training was successful as the output indicates, so I'm unsure why the same resource group couldn't be found.

**Comment by beccamc** [comment]
This is very old, and I don't think we have a repro anymore. closing.
