### ISSUE TITLE
ONNX fails in CodeGen for Azure Connected Mode

### ISSUE THREAD

**Issue by justinormont** [dotnet/machinelearning-modelbuilder#806]
**System Information (please complete the following information):**
 - Model Builder Version: _(Where do I find this?)_ Extension updated two days ago.
 - Visual Studio Version: Microsoft Visual Studio Enterprise 2019 Preview Version 16.6.0 Preview 2.1

**Describe the bug**
After training a multiclass image model on Azure, the generated project fails to run.

Error:
`DllNotFoundException: Unable to load DLL 'onnxruntime' or one of its dependencies: The specified module could not be found. (0x8007007E)`

Error details:
```
System.Reflection.TargetInvocationException
  HResult=0x80131604
  Message=Exception has been thrown by the target of an invocation.
  Source=System.Private.CoreLib
  StackTrace:
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at Microsoft.ML.Runtime.ComponentCatalog.LoadableClassInfo.CreateInstanceCore(Object[] ctorArgs)
   at Microsoft.ML.Runtime.ComponentCatalog.LoadableClassInfo.CreateInstance(IHostEnvironment env, Object args, Object[] extra)
   at Microsoft.ML.Runtime.ComponentCatalog.TryCreateInstance[TRes](IHostEnvironment env, Type signatureType, TRes& result, String name, String options, Object[] extra)
   at Microsoft.ML.Runtime.ComponentCatalog.TryCreateInstance[TRes,TSig](IHostEnvironment env, TRes& result, String name, String options, Object[] extra)
   at Microsoft.ML.ModelLoadContext.TryLoadModelCore[TRes,TSig](IHostEnvironment env, TRes& result, Object[] extra)
   at Microsoft.ML.ModelLoadContext.TryLoadModel[TRes,TSig](IHostEnvironment env, TRes& result, RepositoryReader rep, Entry ent, String dir, Object[] extra)
   at Microsoft.ML.ModelLoadContext.LoadModel[TRes,TSig](IHostEnvironment env, TRes& result, RepositoryReader rep, Entry ent, String dir, Object[] extra)
   at Microsoft.ML.ModelLoadContext.LoadModelOrNull[TRes,TSig](IHostEnvironment env, TRes& result, RepositoryReader rep, String dir, Object[] extra)
   at Microsoft.ML.ModelLoadContext.LoadModel[TRes,TSig](IHostEnvironment env, TRes& result, RepositoryReader rep, String dir, Object[] extra)
   at Microsoft.ML.ModelOperationsCatalog.Load(Stream stream, DataViewSchema& inputSchema)
   at Microsoft.ML.ModelOperationsCatalog.Load(String filePath, DataViewSchema& inputSchema)
   at RedactedDatasetModelBuilderML.Model.ConsumeModel.CreatePredictionEngine() in C:\Users\jormont\source\repos\RedactedDatasetModelBuilder\RedactedDatasetModelBuilderML.Model\ConsumeModel.cs:line 37
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
Inner Exception 1:
TargetInvocationException: Exception has been thrown by the target of an invocation.
Inner Exception 2:
TypeInitializationException: The type initializer for 'Microsoft.ML.OnnxRuntime.NativeMethods' threw an exception.
Inner Exception 3:
DllNotFoundException: Unable to load DLL 'onnxruntime' or one of its dependencies: The specified module could not be found. (0x8007007E)
```

**Mitigation**
Adding a few lines to both `.csproj` files seems to fix it: _(should verify)_
```diff
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
+    <Platforms>x64</Platforms>
+    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
  </PropertyGroup>
  
  <ItemGroup>
    <PackageReference Include="Microsoft.ML" Version="1.5.0-preview2" />
    <PackageReference Include="Microsoft.ML.ImageAnalytics" Version="1.5.0-preview2" />
    <PackageReference Include="Microsoft.ML.OnnxTransformer" Version="1.5.0-preview2" />
+    <PackageReference Include="Microsoft.ML.OnnxRuntime" Version="1.3.0" />
  </ItemGroup>

```

**To Reproduce**
Train a multiclass classification model using the Azure Connected Mode. Run project.

**Comment by JakeRadMSFT** [comment]
Reproduced and just OnnxRuntime was enough for me:

<PackageReference Include="Microsoft.ML.OnnxRuntime" Version="1.3.0" />
