### ISSUE TITLE
Training failed with the exception: System.InvalidOperationException: Metadata KeyValues does not exist

### ISSUE THREAD

**Issue by IvoNijssen** [dotnet/machinelearning-modelbuilder#825]
**System Information (please complete the following information):**
 - Model Builder Version: 
![image](https://user-images.githubusercontent.com/29116996/84488696-dbc3ab80-aca0-11ea-8437-9cac7ee12c90.png)
[91f2da1d-aac0-46ef-a72d-67f4a7a375d4.txt](https://github.com/dotnet/machinelearning-modelbuilder/files/4769966/91f2da1d-aac0-46ef-a72d-67f4a7a375d4.txt)

Microsoft Visual Studio Professional 2019
Version 16.6.2

**Describe the bug**
Training failed with the exception: System.InvalidOperationException: Metadata KeyValues does not exist
   at Microsoft.ML.Transforms.KeyToValueMappingTransformer.Mapper.ComputeKvMaps(DataViewSchema schema, DataViewType[]& types, KeyToValueMap[]& kvMaps)
   at Microsoft.ML.Transforms.KeyToValueMappingTransformer.Mapper..ctor(KeyToValueMappingTransformer parent, DataViewSchema inputSchema)
   at Microsoft.ML.Transforms.KeyToValueMappingTransformer.MakeRowMapper(DataViewSchema inputSchema)
   at Microsoft.ML.Data.RowToRowTransformerBase.GetOutputSchema(DataViewSchema inputSchema)
   at Microsoft.ML.Data.TrivialEstimator`1.Fit(IDataView input)
   at Microsoft.ML.Data.EstimatorChain`1.Fit(IDataView input)
   at Microsoft.ML.AutoML.RunnerUtil.TrainAndScorePipeline[TMetrics](MLContext context, SuggestedPipeline pipeline, IDataView trainData, IDataView validData, String labelColumn, IMetricsAgent`1 metricsAgent, ITransformer preprocessorTransform, FileInfo modelFileInfo, DataViewSchema modelInputSchema, IChannel logger)

**To Reproduce**
4th step Train model.

**Expected behavior**
To get to step 5.

**Additional context**
Trying to do a text classification scenario

**Comment by LittleLittleCloud** [comment]
The error message isn't really helpful here, based on the log, the training aborts because training set has 0 instances, which means when splitting training-test-validate set, the training set has 0 piece of data.

This usually happens when your dataset is too small, how many rows do you have in your dataset.


This usually happens when your dataset is too small, how many rows do you have for your dataset?

**Comment by IvoNijssen** [comment]
Thanks for you reply, issue is solved.
