### ISSUE TITLE
Model Builder throws error "Could not find input column ..." on Predict (Evaluate tab)

### ISSUE THREAD

**Issue by OliaG** [dotnet/machinelearning-modelbuilder#856]
**System Information (please complete the following information):**
 - Visual Studio Version 16 .7.0 Preview 3.0 [30208.133.master]

**Describe the bug**

**To Reproduce**
1. Choose "Text Classification" template
2. Environment: local
3. Data: 
[adult.zip](https://github.com/dotnet/machinelearning-modelbuilder/files/4840984/adult.zip)
4. Column to predict: salary, choose all columns as features
5. Train 10 seconds
6. On Evaluate page leave everything as pre-populated, click Predict

**Expected behavior**
No error.

**Actual behavior**
Error
![image](https://user-images.githubusercontent.com/31997351/85928137-aea9f800-b85f-11ea-9ef7-05405e3d951a.png)

Log file: 
[f5837c28-bc78-469c-82e1-76a71e51b63e.txt](https://github.com/dotnet/machinelearning-modelbuilder/files/4840978/f5837c28-bc78-469c-82e1-76a71e51b63e.txt)

Error:
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at StreamJsonRpc.JsonRpc.<InvokeCoreAsync>d__94`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ML.ModelBuilder.AutoMLServiceFactory.AutoMLServiceProxy.<PredictMultiClassClassificationAsync>d__16.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ML.ModelBuilder.TrainSession.<PredictMultiClassClassificationAsync>d__51.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.ML.ModelBuilder.ToolWindows.EvaluateTabDataContext.<MulticlassficationAsync>d__93.MoveNext()

**Comment by JakeRadMSFT** [comment]
Related to  #890 ?

**Comment by beccamc** [comment]
Yes, the problem here is the "-" in some of the column labels. Some of our code is stripping the "-" out, and some is leaving it in, meaning we can't find "marital-status" as it's been replaced with "maritialstatus".  

Removing the "-" char will unblock you. I've a PR up to fix - https://github.com/dotnet/machinelearning-tools/pull/731

**Comment by KeithT** [comment]
Had a similar issue, but on reading this got it working for now, by removing space between words in column names.
