### ISSUE TITLE
Specified label column 'Label' was not found.

### ISSUE THREAD

**Issue by MichaelMeyer1** [dotnet/machinelearning-modelbuilder#858]
Model Builder Version:  16.1.0.2027905
Visual Studio Version:  16.6.30225.117  (Visual Studio Community 2019)

Model Builder Error
Specified label column 'Label' was not found.

   at Microsoft.ML.AutoML.ColumnTypeInference.GetAndValidateLabelColumn(Arguments args, IntermediateColumn[] cols)
   at Microsoft.ML.AutoML.ColumnTypeInference.InferTextFileColumnTypesCore(MLContext context, IMultiStreamSource fileSource, Arguments args)
   at Microsoft.ML.AutoML.ColumnInferenceApi.InferColumnTypes(MLContext context, TextFileSample sample, ColumnSplitResult splitInference, Boolean hasHeader, Nullable`1 labelColumnIndex, String label)
   at Microsoft.ML.AutoML.ColumnInferenceApi.InferColumns(MLContext context, String path, ColumnInformation columnInfo, Nullable`1 separatorChar, Nullable`1 allowQuotedStrings, Nullable`1 supportSparse, Boolean trimWhitespace, Boolean groupColumns, Boolean hasHeader)
   at Microsoft.ML.ModelBuilder.AutoMLEngine.InferColumns(MLContext context, AutoMLServiceParamater config, ColumnInformation columnInformation)
   at Microsoft.ML.ModelBuilder.AutoMLEngine.<StartTrainingAsync>d__30.MoveNext() in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/AutoMLEngineService/AutoMLEngine.cs:line 112

Steps to Reproduce
1. Select the Image Classification Scenario
2. Select image folder
3. Start Training
![image](https://user-images.githubusercontent.com/13951445/85961021-dc2c9980-b964-11ea-9153-df75aa768100.png)

**Comment by LittleLittleCloud** [comment]
Can you kill servicehub.x64 in process explorer, and retrain to see if problem gone?

**Comment by MichaelMeyer1** [comment]
@LittleLittleCloud that didnt seem to help. the problem is still there.

**Comment by LittleLittleCloud** [comment]
@MichaelMeyer1  your model builder doesn't look like the latest version. Can you upgrade to the latest version and try again? In the latest version, if the problem still exists, there will be a URL link to log file in the exception window, which is of great help to debug, and could you upload that log to this thread?

**Comment by MichaelMeyer1** [comment]
@LittleLittleCloud I updated to the latest version in Manage extensions in visual studio to 16.1.0.2027905.  If there's a newer version what's the best way to get it?
![image](https://user-images.githubusercontent.com/13951445/86625752-d21d2300-bf82-11ea-9bbd-f79e40c6ffda.png)

**Comment by qcmiao1998** [comment]
Same problem

**Comment by qcmiao1998** [comment]
I solve the problem by reinstall the model builder.

**Comment by MichaelMeyer1** [comment]
Im still having the problem even if I reinstall the model builder.

**Comment by qcmiao1998** [comment]
> @LittleLittleCloud I'm still having the problem even if I reinstall the model builder. Is it a problem with VS community and the builder?

I install the model builder long long ago, it seems a bug after update. I uninstall the model builder in `Visual Studio Installer` and run `vsixinstaller /u:FE96D051-645F-4309-AE99-107A776B0DA2` to uninstall it again, after that install it again, it works.

I found that only to uninstall it twice, the old version can be cleaned totally.

**Comment by LittleLittleCloud** [comment]
> @LittleLittleCloud I'm still having the problem even if I reinstall the model builder. Is it a problem with VS community and the builder?

Hi @MichaelMeyer1 , sorry for the late reply.
First, 2027905 is the latest version. If you still have that error, then it should be a bug in ModelBuilder and I will take a look.

To help debug, could you upload the error log to this thread? You should be able to find a link to log file which located to the next of the 'report issue' link. Thanks

**Comment by LittleLittleCloud** [comment]
close due to no responses, feel free to reopen it if you have any questions

**Comment by marc40000** [comment]
I have this exact same issue as well. I have not been able to fix it yet. Just wanted to tell that it's pretty confusing to have the model build in Modify Visual Studio which you get to by Tools->Get Tools and Features as well as though Manage Extentions which you reach by Extensions->Manage Extensions.

Personally I installed the Model Builder like described on the website through Modify Visual Studio. Then I got this error. A few seconds later Visual Studio poped up a Notification that there is an update and it updated it through extensions. I still got this error.

Then I googled and found this thread. Here you suggest to uninstall it, but I'm not able to. Whatever I do, it still is accessible by Solution right click->Add->Machine Learning while it is deselected in Modify Visual Studio.

**Comment by marc40000** [comment]
Ok I got it working now. Here is what I did in case someone else needs another idea how to fix the issue for her/him:

I uninstalled the Model Builder by calling all uninstallers and reverting several times until it actually was removed. This was ugly and chaotic so I can't recall the actual order I used.

I then just installed it from Extensions and then it just worked. The Model Builder looks completey different to the one installed from the Visual Studio installer. It has 4 Scenarios and 4 Examples in two rows insteas of 5 Scenarios in one row. Also there is an Environment Categorie which sounds like you might be able to choose between cpu and gpu at some time. The visual studio installer version also does not have that. So you can visually distinguish between the two.

So, at least for me, the way to install Model Builder described here https://dotnet.microsoft.com/learn/ml-dotnet/get-started-tutorial/install is not working for me atm.

After that, I still had some issues.
- For some reason, if you have an csv file with data and 2+ labels, you have to select the Text classification scenario. No idea why it's called like that, but it lets you choose a csv file or sql db and colums like you'ld expect.
- It still complained about my csv file. I figured out it doesn't like empty colums. Compared to the Visual Studio version where the empty colums had not name in the comboboxes, this version gives them name liuke Column9. So there was work done on this, but it still does not work. Removing the empty columns made it work.
- If you get an error when loading your csv file and you modify it and want to try it again, it will give you errors again and again. If you modify your csv file, close the model builder and start again with solution->right click->Add->Machine Learning. Just selecting the modified file again always complained about something.
- After finishing training and adding the model to the project, it didn't compile. It said to do nuget package restore. But that says there are no packages tob e restored. However this worked: Tools > NuGet Package Manager > Package Manager Console, then enter dotnet restore. I found that here https://stackoverflow.com/questions/48440223/assets-file-project-assets-json-not-found-run-a-nuget-package-restore

I hope this helps someone a bit.

**Comment by KeithT** [comment]
@marc40000 Thanks for posting as I had the same problem so also tried to get rid of ML.NET, which is mildly challenging as it refuses to die. 
Steps: 
1. Tried to revert it from installed extensions in VS. It reported the reversion failed.
2. Removed it from VS installer - showed as removed i.e. unticked in the list of installed individual components.
3. On opening VS it was still available through the solution explorer - Add and in Manage extensions, but now revert had been replaced by Uninstall and the version had dropped down to: 16.1.2003.302
4. Tried to uninstalled it, which worked as was no longer available in solution explorer or in extensions.
5. Reinstalled from extensions.
6. Tested and had a completely different interface which on using solved the issue.

So it seems that the autoupdate, which was on, is not updating.

**Comment by andrerav** [comment]
Having the same problem here. 

`2020-11-05 23:39:07.6954 DEBUG Set log file path to C:\Users\Andreas\AppData\Local\Temp\MLVSTools\logs\7b651856-d7ec-4f28-bb41-a4511771c8f2.txt (Microsoft.ML.ModelBuilder.Utils.Logger.Debug)
2020-11-05 23:39:21.5846 DEBUG C:\Users\Andreas\source\repos\ConsoleApp7\ConsoleApp1\21801V72158&68557V444232_hour_20181105T0000_20201106T0000.csv (Microsoft.ML.ModelBuilder.Utils.Logger.Debug)
2020-11-05 23:40:02.6429 DEBUG Disposing TrainSession (Microsoft.ML.ModelBuilder.Utils.Logger.Debug)
2020-11-05 23:40:03.7232 WARN GPU Service not found. Falling back to CPU AutoML Service. (Microsoft.ML.ModelBuilder.Utils.Logger.Warn)
2020-11-05 23:40:05.4626 DEBUG Specified label column '_5_6m' was not found.
   at Microsoft.ML.AutoML.ColumnTypeInference.GetAndValidateLabelColumn(Arguments args, IntermediateColumn[] cols)
   at Microsoft.ML.AutoML.ColumnTypeInference.InferTextFileColumnTypesCore(MLContext context, IMultiStreamSource fileSource, Arguments args)
   at Microsoft.ML.AutoML.ColumnInferenceApi.InferColumnTypes(MLContext context, TextFileSample sample, ColumnSplitResult splitInference, Boolean hasHeader, Nullable`1 labelColumnIndex, String label)
   at Microsoft.ML.AutoML.ColumnInferenceApi.InferColumns(MLContext context, String path, ColumnInformation columnInfo, Nullable`1 separatorChar, Nullable`1 allowQuotedStrings, Nullable`1 supportSparse, Boolean trimWhitespace, Boolean groupColumns, Boolean hasHeader)
   at Microsoft.ML.ModelBuilder.AutoMLEngine.InferColumns(MLContext context, AutoMLServiceParamater config, ColumnInformation columnInformation)
   at Microsoft.ML.ModelBuilder.AutoMLEngine.<StartTrainingAsync>d__30.MoveNext() in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/AutoMLEngineService/AutoMLEngine.cs:line 112 (Microsoft.ML.ModelBuilder.Utils.Logger.Debug)
2020-11-05 23:42:55.5569 DEBUG Disposing TrainSession (Microsoft.ML.ModelBuilder.Utils.Logger.Debug)
2020-11-05 23:42:55.5569 DEBUG Disposing AutoMLService Client (Microsoft.ML.ModelBuilder.Utils.Logger.Debug)
2020-11-05 23:42:55.5589 DEBUG Disposing TrainSession (Microsoft.ML.ModelBuilder.Utils.Logger.Debug)
2020-11-05 23:42:55.9710 DEBUG Specified label column '_5_6m' was not found.
   at Microsoft.ML.AutoML.ColumnTypeInference.GetAndValidateLabelColumn(Arguments args, IntermediateColumn[] cols)
   at Microsoft.ML.AutoML.ColumnTypeInference.InferTextFileColumnTypesCore(MLContext context, IMultiStreamSource fileSource, Arguments args)
   at Microsoft.ML.AutoML.ColumnInferenceApi.InferColumnTypes(MLContext context, TextFileSample sample, ColumnSplitResult splitInference, Boolean hasHeader, Nullable`1 labelColumnIndex, String label)
   at Microsoft.ML.AutoML.ColumnInferenceApi.InferColumns(MLContext context, String path, ColumnInformation columnInfo, Nullable`1 separatorChar, Nullable`1 allowQuotedStrings, Nullable`1 supportSparse, Boolean trimWhitespace, Boolean groupColumns, Boolean hasHeader)
   at Microsoft.ML.ModelBuilder.AutoMLEngine.InferColumns(MLContext context, AutoMLServiceParamater config, ColumnInformation columnInformation)
   at Microsoft.ML.ModelBuilder.AutoMLEngine.<StartTrainingAsync>d__30.MoveNext() in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/AutoMLEngineService/AutoMLEngine.cs:line 112 (Microsoft.ML.ModelBuilder.Utils.Logger.Debug)
2020-11-05 23:42:57.6643 DEBUG Open Log FileC:\Users\Andreas\AppData\Local\Temp\MLVSTools\logs\7b651856-d7ec-4f28-bb41-a4511771c8f2.txt (Microsoft.ML.ModelBuilder.Utils.Logger.Debug)
2020-11-05 23:43:03.3916 DEBUG Open Log FileC:\Users\Andreas\AppData\Local\Temp\MLVSTools\logs\7b651856-d7ec-4f28-bb41-a4511771c8f2.txt (Microsoft.ML.ModelBuilder.Utils.Logger.Debug)`

The data file can be downloaded from here: https://www.vegvesen.no/trafikkdata/start/eksport?datatype=HOUR&from=2018-11-05&lat=63.435649166124996&lon=10.408562140878322&to=2020-11-06&trafikanttype=vehicle&trpids=21801V72158%2C68557V444232&zoom=13

**Comment by Wvader** [comment]
```
   at Microsoft.ML.AutoML.ColumnTypeInference.GetAndValidateLabelColumn(Arguments args, IntermediateColumn[] cols)
   at Microsoft.ML.AutoML.ColumnTypeInference.InferTextFileColumnTypesCore(MLContext context, IMultiStreamSource fileSource, Arguments args)
   at Microsoft.ML.AutoML.ColumnInferenceApi.InferColumnTypes(MLContext context, TextFileSample sample, ColumnSplitResult splitInference, Boolean hasHeader, Nullable`1 labelColumnIndex, String label)
   at Microsoft.ML.AutoML.ColumnInferenceApi.InferColumns(MLContext context, String path, ColumnInformation columnInfo, Nullable`1 separatorChar, Nullable`1 allowQuotedStrings, Nullable`1 supportSparse, Boolean trimWhitespace, Boolean groupColumns, Boolean hasHeader)
   at Microsoft.ML.ModelBuilder.AutoMLEngine.InferColumns(MLContext context, AutoMLServiceParamater config, ColumnInformation columnInformation)
   at Microsoft.ML.ModelBuilder.AutoMLEngine.<StartTrainingAsync>d__30.MoveNext() in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/AutoMLEngineService/AutoMLEngine.cs:line 112
   ````
With the following dataset: https://archive.ics.uci.edu/ml/machine-learning-databases/00601/

The MS tutorial: https://youtu.be/sBHRd6e5ZBY
