### ISSUE TITLE
Issue encountered on: Problem encountered on https://dotnet.microsoft.com/learn/ml-dotnet/get-started-tutorial/consume

### ISSUE THREAD

**Issue by gtfMasterJohn** [dotnet/machinelearning-modelbuilder#902]
Problem encountered on https://dotnet.microsoft.com/learn/ml-dotnet/get-started-tutorial/consume
Operating System: windows

is giving me this error: 
System.TypeInitializationException
  HResult=0x80131534
  Message=The type initializer for 'ConsoleDiplomadoAIML.Model.ConsumeModel' threw an exception.
  Source=ConsoleDiplomadoAIML.Model
  StackTrace:
   at ConsoleDiplomadoAIML.Model.ConsumeModel.Predict(ModelInput input) in C:\Users\[user]\source\repos\ConsoleDiplomadoAI\ConsoleDiplomadoAIML.Model\ConsumeModel.cs:line 22
   at myMLApp.Program.Main(String[] args) in C:\Users\[user]\source\repos\ConsoleDiplomadoAI\ConsoleDiplomadoAI\Program.cs:line 15

Inner Exception 1:
FileNotFoundException: Could not load file or assembly 'Microsoft.ML.Data, Version=1.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The system cannot find the file specified.

when running this line: 
            // Load model and predict output of sample data
            ModelOutput result = ConsumeModel.Predict(input);

Please help i am new with ML.
Thanks

**Comment by beccamc** [comment]
Sorry you ran into this problem @gtfMasterJohn! I'm guessing your project uses .NET Full Framework?

This is a bug in the .NET Full Framework non-SDK-style project format. We are pursing a permanent fix with the .NET team. 
 
To get unblocked, you can upgrade your .NET Framework project to use the [SDK-style](https://docs.microsoft.com/en-us/dotnet/standard/frameworks), or start a new project using .NET Core. Checkout this [blog ](https://www.hanselman.com/blog/UpgradingAnExistingNETProjectFilesToTheLeanNewCSPROJFormatFromNETCore.aspx) by Scott Hanselman for more help.
 
If you can't upgrade to the SDK-style, use the following to get unblocked with the non-SDK-style project format..

1. Set the target platform to x64
`<PlatformTarget>x64</PlatformTarget>`
 
2. Add a package reference to your project for [Microsoft.ML](https://www.nuget.org/packages/Microsoft.ML) (latest version) 
`<PackageReference Include="Microsoft.ML" Version="1.5.1" />`

**Comment by beccamc** [comment]
@gtfMasterJohn Any luck with the above solution?

**Comment by beccamc** [comment]
Closing this due to inactivity - ping me or reopen if you need additional help!
