### ISSUE TITLE
Can't load text data

### ISSUE THREAD

**Issue by RachamimYaakobov** [dotnet/machinelearning-modelbuilder#946]
**System Information**
 - Model Builder Version: 16.1.0.2041102
 - Visual Studio Version: 16.6.5

**The bag**

My data looks like:
```
#@ TextLoader{
#@   header+
#@   sep=tab
#@   col=Signal:TX:0
#@   col=Features:R4:1-13
#@ }
Signal	13	0:""
A	5.18318939	7.15346956	-2.17563128	-0.73105526	-5.266888	1.53642082	-2.5065968	0.673678041	-2.15960288	-0.59014225	-0.0943836346	0.799055755	1.63462913
A	5.498637	9.607026	-0.5584643	-0.0328068	-3.16750336	2.07753539	-1.43945122	0.4845428	-1.4946686	-0.169637516	0.7250544	2.36166024	0.497059882
A	3.996713	11.7442684	1.47274029	0.0203783289	-2.41468763	3.58536744	-3.14649081	2.43419576	-0.339808732	0.72464025	-0.0729868561	0.8280493	-0.120707527
A	2.67490387	12.8288279	-0.206502244	1.45496285	1.17160869	-1.95037043	-3.38032174	1.82436979	0.610646546	-1.488981	-0.06361399	0.788708448	0.351375878
A	5.30536747	8.270027	-2.740677	1.41013825	-2.654548	2.299344	-1.65489733	0.7302742	-2.18515658	-1.39530623	0.8179908	1.97329521	-0.116933838
A	0.579052746	9.369362	-0.340619415	1.0491215	-3.72689939	3.48625636	-0.710082	1.97451723	0.0125530474	0.270270258	-1.08870339	1.16362035	0.6432678
A	2.17444062	12.5961065	0.21108067	2.12631655	0.877906144	-0.401404172	-1.015385	1.27959609	-0.4173578	-0.781255066	0.304535717	2.30834246	-0.202794492
A	3.30898833	13.313899	-1.68393946	1.661705	-1.33209419	1.2256918	-3.991646	1.98770607	-4.016889	0.935438037	0.00443459675	1.95483315	0.629864335
A	2.96511436	12.5907974	0.514994	1.14698339	0.400934458	-0.478516728	-0.53402257	1.267731	-0.721033454	-0.7496938	0.2800758	0.567380369	-1.0322051
```

And when I try to load it I get error:
```
Data ErrorInput array is longer than the number of columns in this table.
   at System.Data.DataTable.NewRecordFromArray(Object[] value)
   at System.Data.DataRowCollection.Add(Object[] values)
   at Microsoft.ML.ModelBuilder.ToolWindows.DataTabDataContext.<>c__DisplayClass140_0.<<CreateDataTable>b__0>d.MoveNext()
```
The text file was created with `mlContext.Data.SaveAsText(dataView, fs);`

**Comment by JakeRadMSFT** [comment]
Thanks for reporting! We don't support that format yet in Model Builder.

Related to #212

**Comment by JakeRadMSFT** [comment]
How was the dataset created? Do you have an original CSV or TSV you could use?

**Comment by RachamimYaakobov** [comment]
dataset created from Xml, and my `features` is an `float[13]`, so I not heve any idea how to load it to Model Builder.

**Comment by JakeRadMSFT** [comment]
How did you get it from XML to the SaveAsText format? Sorry for all the questions just trying to understand the full path you took. 

We'll look into supporting this format.

**Comment by RachamimYaakobov** [comment]
I have a list of example objects in XML, so I uploaded the list with `XmlSerializer`, and I did:

```
var dataView = mlContext.Data.LoadFromEnumerable(examples);
```
Then I did:
```
using (var fs = File.Create ("examples.txt"))
{
   mlContext.Data.SaveAsText (dataView, fs);
}
```

**Comment by zewditu** [comment]
The current model builder file loader does not support Ml.NET formatted files. ML.Net formed files schema is not in the way the model builder expected. Hence we need to convert Ml.Net formatted files into IdataView to inspect the scheme information the files.
