### ISSUE TITLE
Model Builder error after selecting table from Database

### ISSUE THREAD

**Issue by MuhammadZeshan382** [dotnet/machinelearning-modelbuilder#982]
at Microsoft.ML.ModelBuilder.ToolWindows.DataTabDataContext.GetFileDataPropertiesFromSql()
   at Microsoft.ML.ModelBuilder.ToolWindows.BaseViewModel.<>c__DisplayClass5_2.<.ctor>b__3(Object sender, PropertyChangedEventArgs e)
[logfile.txt](https://github.com/dotnet/machinelearning-modelbuilder/files/5149735/logfile.txt)

**Comment by LittleLittleCloud** [comment]
Looks like a dup of #970
