### ISSUE TITLE
Cannot generate model form SQL Server database

### ISSUE THREAD

**Issue by ddemland** [dotnet/machinelearning-modelbuilder#988]
**System Information (please complete the following information):**
 - Model Builder Version: Date Installed: 9/1/2020 Version: 16.1.0.2027905
 - Visual Studio Version: Microsoft Visual Studio Professional 2019 Version 16.7.2

I have a training table that is defined as:

CREATE TABLE [dbo].[banknote_train](
	[variance] [real] NULL,
	[skewness] [real] NULL,
	[curtosis] [real] NULL,
	[entropy] [real] NULL,
	[class] [smallint] NULL
) ON [PRIMARY]

I add a machine learning Select Value prediction. I select Data as shown below:

![image](https://user-images.githubusercontent.com/67738/92153262-d45ffa00-edd8-11ea-885d-832f2327765d.png)

I select SQL Server and fill out all the requirement fields and test the connection successfully. I am able to select the table and the column for prediction and the rest is filled in automatically as shown below:

![image](https://user-images.githubusercontent.com/67738/92153299-e2ae1600-edd8-11ea-944f-dd95d3bb1df9.png)

When I select Train I get the following:

![image](https://user-images.githubusercontent.com/67738/92153332-f22d5f00-edd8-11ea-9e06-fea1a1df35ee.png)

The Log has the following messages:

2020-09-03 09:34:50.1267 DEBUG Set log file path to C:\Users\DDemland\AppData\Local\Temp\MLVSTools\logs\ae8fcb8e-9263-4d57-98bc-4f17f5f1f23c.txt (Microsoft.ML.ModelBuilder.Utils.Logger.Debug)
2020-09-03 09:40:40.7234 DEBUG Disposing TrainSession (Microsoft.ML.ModelBuilder.Utils.Logger.Debug)
2020-09-03 09:40:41.6258 WARN GPU Service not found. Falling back to CPU AutoML Service. (Microsoft.ML.ModelBuilder.Utils.Logger.Warn)
2020-09-03 09:40:43.8141 INFO |     Trainer                             RSquared Absolute-loss Squared-loss RMS-loss  Duration #Iteration      | (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2020-09-03 09:40:44.1315 DEBUG Provided label column 'class' was of type String, but only type Single is allowed.
   at Microsoft.ML.AutoML.UserInputValidationUtil.ValidateTrainDataColumn(IDataView trainData, String columnName, String columnPurpose, IEnumerable`1 allowedTypes)
   at Microsoft.ML.AutoML.UserInputValidationUtil.ValidateColumnInformation(IDataView trainData, ColumnInformation columnInformation, TaskKind task)
   at Microsoft.ML.AutoML.ExperimentBase`2.ExecuteCrossValSummary(IDataView[] trainDatasets, ColumnInformation columnInfo, IDataView[] validationDatasets, IEstimator`1 preFeaturizer, IProgress`1 progressHandler)
   at Microsoft.ML.AutoML.ExperimentBase`2.Execute(IDataView trainData, ColumnInformation columnInformation, IEstimator`1 preFeaturizer, IProgress`1 progressHandler)
   at Microsoft.ML.ModelBuilder.AutoMLService.Experiments.AutoMLExperiment`3.<>c__DisplayClass21_0.<ExecuteAsync>b__5() in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/Experiments/AutoMLExperiment.cs:line 81
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ML.ModelBuilder.AutoMLService.Experiments.AutoMLExperiment`3.<ExecuteAsync>d__21.MoveNext() in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/Experiments/AutoMLExperiment.cs:line 108
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ML.ModelBuilder.AutoMLEngine.<StartTrainingAsync>d__30.MoveNext() in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/AutoMLEngineService/AutoMLEngine.cs:line 147 (Microsoft.ML.ModelBuilder.Utils.Logger.Debug)
2020-09-03 09:40:59.6554 DEBUG Open Log FileC:\Users\DDemland\AppData\Local\Temp\MLVSTools\logs\ae8fcb8e-9263-4d57-98bc-4f17f5f1f23c.txt (Microsoft.ML.ModelBuilder.Utils.Logger.Debug)

How do I generate a model from SQL Server?

**Comment by beccamc** [comment]
@ddemland Sorry you ran into this problem and thanks for the detailed steps. Can you try this again and choose "Text classification" as your scenario? If you chose value prediction, ML.Net is expected to predict a single (like price, miles travelled, etc). Your class label looks like binary or category data and should be classified using "Text Classification". 

cc: @briacht

**Comment by ddemland** [comment]
Thank you that worked. It took a couple of days because I did an update to VS 2019 and in that process, I was unaware that VS updated model builder and it started not working. I reported this in issue 970. Once I figured this out, I did a revert and it now works. Thank you.
