### ISSUE TITLE
Model Builder error on Azure Training

### ISSUE THREAD

**Issue by elbruno** [dotnet/machinelearning-modelbuilder#991]
**System Information (please complete the following information):**
 - Model Builder Version: 16.1.1.2041102
 - Visual Studio Version: Visual Studio 2019 Preview, 16.8.0 Preview 2.1

**Describe the bug**
Complete step by step to train an Image Recognition scenario using Azure Environment. 

**To Reproduce**
1. Add Machine Learning to C# Project
2. Select Image Classification scenario
3. Select Azure as Training Environment
4. Select training image folder
5. Start Training

**Expected behavior**
After uploading all the training images, Model Builder raises this exception

   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at Azure.MachineLearning.Services.Compute.ComputeTargetPageFetcher.FetchNextPage() in /_/src/Microsoft.ML.AzureMLClient/Compute/ComputeTargetPageFetcher.cs:line 35
   at Azure.MachineLearning.Services.LazyEnumerator`1.<GetEnumerator>d__9.MoveNext() in /_/src/Microsoft.ML.AzureMLClient/LazyEnumerator.cs:line 26
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source)
   at AzureML.AutoMLRunnerImages.<RunAutoMLAsync>d__27.MoveNext() in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/RemoteAutoML/AutoMLRunnerImages.cs:line 233
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ML.ModelBuilder.AutoMLService.Experiments.AzureImageClassificationExperiment.<ExecuteAsync>d__13.MoveNext() in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/Experiments/AzureImageClassificationExperiment.cs:line 69
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ML.ModelBuilder.AutoMLEngine.<StartTrainingAsync>d__26.MoveNext() in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/AutoMLEngineService/AutoMLEngine.cs:line 134

![image](https://user-images.githubusercontent.com/3533489/92646226-1941d000-f2b4-11ea-812b-184d6e59802b.png)

**Additional context**
Attached the full runtime log.
[b6e7c212-c030-45b8-8c31-a8c125ae1115.txt](https://github.com/dotnet/machinelearning-modelbuilder/files/5197670/b6e7c212-c030-45b8-8c31-a8c125ae1115.txt)

**Comment by LittleLittleCloud** [comment]
Seems that AzClient can't get computer info, can you go to azure portal and check if selected compute is created succesfully?

**Comment by arafattehsin** [comment]
This is exactly my [issue](https://github.com/dotnet/machinelearning/issues/5396). And to answer you, @LittleLittleCloud - my compute is successfully created. 

![image](https://user-images.githubusercontent.com/16351038/93065284-dcaf1380-f6bb-11ea-8a36-6c4385ff83d8.png)

**Comment by elbruno** [comment]
I also tested with the latest version:  16.2.0.2046002
the one with includes object detection and I still have the same error

![image](https://user-images.githubusercontent.com/3533489/93090720-2c192380-f66b-11ea-93bd-a344a1b974fb.png)

**Comment by LittleLittleCloud** [comment]
Thanks for the feedback @elbruno @arafattehsin  We are taking a look at it

**Comment by beccamc** [comment]
Thanks for reporting @elbruno and @arafattehsin. This aggregate exception message isn't helpful (need to fix that!) I'd like to know if the run was started and ran into a problem. Can you check the ML portal (https://ml.azure.com) and see if the run has any information?

If the run can't access the compute for some reason the experiment error should tell us the problem. Thanks for your patience while we figure this out! 

If you're not familiar with the ML portal... 

- Click Experiments on the left nav. 
- Click on your experiment name (probably "ImageClassification" or "ObjectDetection"). You should see a run from when you were testing. It's probably failed or cancelled. 

![image](https://user-images.githubusercontent.com/9122518/93125858-4cf46f80-f691-11ea-8caa-8a7cbf4555d4.png)


- Go into that run. It might show some information on the error at the top, or the problem might be in a child run. 

![image](https://user-images.githubusercontent.com/9122518/93125490-d3f51800-f690-11ea-8849-696e5f95e579.png)

- Check the child run for any helpful info. Sometimes it's inside a warning message at the top. You'll need to expand that to see the inner exception info. 
![image](https://user-images.githubusercontent.com/9122518/93125726-29312980-f691-11ea-8cd1-ea9678e6b2a8.png)

**Comment by arafattehsin** [comment]
Hi @beccamc - Thank you for this detailed explanation. Unfortunately, I can't even see any experiments being executed. My experiment is created but I don't see any run.

![image](https://user-images.githubusercontent.com/16351038/93156883-6a3a4400-f74c-11ea-97be-a148feb8e346.png)

**Comment by LittleLittleCloud** [comment]
@arafattehsin This is so strange... It looks like the training fail at fetching compute step so experiemnt won't even have a chance to create.

T'm trying to reproduce the error, could you tell me how do you create compute, did you use the UI in model builder? or through Azure portal. And could you share your compute's property, and which configuration did you use to create compute.

**Comment by arafattehsin** [comment]
@LittleLittleCloud  I created it using the UI in Model Builder

![image](https://user-images.githubusercontent.com/16351038/93270001-7decb580-f7f3-11ea-8d51-7c04ef2a735f.png)

If you can tell you a way which worked for you, please do so as I can try the exact same way to make it work.

**Comment by LittleLittleCloud** [comment]
@arafattehsin  I didn't do anything specifically.. Could you try creating compute in azure portal, this is the configuration I use
![image](https://user-images.githubusercontent.com/16876986/93302862-786d7c00-f7af-11ea-9e0c-f6652e078c0f.png)

**Comment by LittleLittleCloud** [comment]
Use dedicated machine solves the problem, better error message when launch training on low-priority machine fails is needed
